#!/usr/bin/env python3
"""Batch translate Chinese fragments to English in .tex files."""
import re, sys, os

# Comprehensive Chinese→English mapping for the pidgin text in these files
# Format: (chinese_pattern, english_replacement) — longer patterns first
TRANSLATIONS = [
    # === Multi-character compounds (longer first) ===
    ("存在性", "existence"),
    ("收敛性", "convergence"),
    ("连续性", "continuity"),
    ("一致性", "consistency"),
    ("单调性", "monotonicity"),
    ("对称性", "symmetry"),
    ("周期性", "periodicity"),
    ("有效性", "effectiveness"),
    ("紧致性", "tightness"),
    ("光滑性", "smoothness"),
    ("不可区分性", "indistinguishability"),
    ("可检测性", "detectability"),
    ("等变性", "equivariance"),
    ("不变性", "invariance"),
    ("可区分性", "distinguishability"),
    ("不可辨识性", "unidentifiability"),
    ("可辨识性", "identifiability"),
    ("归一化", "normalization"),
    ("初始化", "initialization"),
    ("形式化", "formalization"),
    ("参数化", "parameterization"),
    ("启发式", "heuristic"),
    ("对抗性", "adversarial"),
    ("必要性", "necessity"),
    ("充分性", "sufficiency"),
    ("完备性", "completeness"),
    ("交换性", "commutativity"),
    ("局部性", "locality"),
    
    ("马尔可夫链", "Markov chain"),
    ("信息论", "information-theoretic"),
    ("李群同态", "Lie group homomorphism"),
    ("贝叶斯最优", "Bayes-optimal"),
    ("黎曼", "Riemann"),
    ("柯西", "Cauchy"),
    ("切比雪夫", "Chebyshev"),
    ("霍夫丁", "Hoeffding"),
    ("法诺", "Fano"),
    
    ("退化", "degenerate"),
    ("收敛", "converge"),
    ("发散", "diverge"),
    ("衰减", "decay"),
    ("松弛", "relaxation"),
    ("截止", "cutoff"),
    ("逼近", "approximate"),
    ("估计", "estimate"),
    ("评估", "evaluate"),
    ("假设", "assumption"),
    ("定理", "theorem"),
    ("引理", "lemma"),
    ("推论", "corollary"),
    ("定义", "definition"),
    ("证明", "proof"),
    ("构造", "construction"),
    ("陈述", "statement"),
    ("结论", "conclusion"),
    ("总结", "summary"),
    ("摘要", "abstract"),
    ("推荐", "recommendation"),
    ("描述", "description"),
    ("解释", "explanation"),
    ("说明", "note"),
    ("标注", "label"),
    ("标记", "mark"),
    ("推导", "derivation"),
    ("验证", "verification"),
    ("检查", "check"),
    ("审查", "audit"),
    ("审计", "audit"),
    ("攻击", "attack"),
    ("防御", "defense"),
    ("保护", "protection"),
    ("保证", "guarantee"),
    ("约束", "constraint"),
    ("限制", "restriction"),
    ("条件", "condition"),
    ("假设", "assumption"),
    ("要求", "requirement"),
    ("选择", "select"),
    ("选取", "choose"),
    ("排除", "exclude"),
    ("包括", "include"),
    ("包含", "contain"),
    ("排除", "exclude"),
    ("忽略", "ignore"),
    ("考虑", "consider"),
    ("观察", "observe"),
    ("注意", "note"),
    ("承认", "admit"),
    ("主张", "claim"),
    ("宣称", "assert"),
    ("声明", "declare"),
    ("强调", "emphasize"),
    ("指出", "point out"),
    ("表明", "indicate"),
    ("显示", "show"),
    ("展现", "display"),
    ("呈现", "present"),
    ("体现", "embody"),
    ("反映", "reflect"),
    ("对应", "correspond"),
    ("匹配", "match"),
    ("连接", "connect"),
    ("耦合", "couple"),
    ("解耦", "decouple"),
    ("折叠", "fold"),
    ("展开", "expand"),
    ("投影", "project"),
    ("映射", "map"),
    ("嵌入", "embed"),
    ("编码", "encode"),
    ("解码", "decode"),
    ("压缩", "compress"),
    ("扩展", "extend"),
    ("推广", "generalize"),
    ("简化", "simplify"),
    ("优化", "optimize"),
    ("最小化", "minimize"),
    ("最大化", "maximize"),
    ("归一化", "normalize"),
    ("标准化", "standardize"),
    ("正则化", "regularize"),
    ("离散化", "discretize"),
    ("量化", "quantize"),
    ("采样", "sample"),
    ("插值", "interpolate"),
    ("外推", "extrapolate"),
    ("内插", "interpolate"),
    ("平滑", "smooth"),
    ("滤波", "filter"),
    ("去噪", "denoise"),
    ("增强", "enhance"),
    ("减弱", "weaken"),
    ("放大", "amplify"),
    ("缩小", "shrink"),
    ("增加", "increase"),
    ("减少", "decrease"),
    ("提升", "improve"),
    ("降低", "reduce"),
    ("上升", "rise"),
    ("下降", "descend"),
    ("保持", "maintain"),
    ("保留", "preserve"),
    ("保存", "save"),
    ("存储", "store"),
    ("删除", "delete"),
    ("移除", "remove"),
    ("添加", "add"),
    ("插入", "insert"),
    ("替换", "replace"),
    ("交换", "swap"),
    ("排列", "permute"),
    ("旋转", "rotate"),
    ("平移", "translate"),
    ("缩放", "scale"),
    ("剪切", "shear"),
    ("反射", "reflect"),
    ("扭曲", "distort"),
    ("变形", "deform"),
    ("恢复", "restore"),
    ("重建", "reconstruct"),
    ("修复", "fix"),
    ("纠正", "correct"),
    ("补偿", "compensate"),
    ("惩罚", "penalize"),
    ("奖励", "reward"),
    ("探索", "explore"),
    ("利用", "exploit"),
    ("发现", "discover"),
    ("学习", "learn"),
    ("训练", "train"),
    ("测试", "test"),
    ("验证", "validate"),
    ("调优", "tune"),
    ("微调", "fine-tune"),
    ("蒸馏", "distill"),
    ("剪枝", "prune"),
    ("量化", "quantize"),
    ("加速", "accelerate"),
    ("稳定", "stabilize"),
    ("崩溃", "collapse"),
    ("爆炸", "explode"),
    ("消失", "vanish"),
    ("出现", "appear"),
    ("消失", "disappear"),
    ("存在", "exist"),
    ("满足", "satisfy"),
    ("违反", "violate"),
    ("保持", "hold"),
    ("成立", "hold"),
    ("失效", "fail"),
    ("成功", "succeed"),
    ("失败", "fail"),
    ("正确", "correct"),
    ("错误", "incorrect"),
    ("准确", "accurate"),
    ("精确", "precise"),
    ("近似", "approximate"),
    ("严格", "rigorous"),
    ("严谨", "rigorous"),
    ("诚实", "honest"),
    ("实际", "practical"),
    ("理论", "theoretical"),
    ("经验", "empirical"),
    ("数值", "numerical"),
    ("解析", "analytical"),
    ("符号", "symbol"),
    ("概念", "concept"),
    ("记号", "notation"),
    ("框架", "framework"),
    ("体系", "system"),
    ("结构", "structure"),
    ("机制", "mechanism"),
    ("过程", "process"),
    ("流程", "pipeline"),
    ("方法", "method"),
    ("方案", "scheme"),
    ("策略", "strategy"),
    ("算法", "algorithm"),
    ("模型", "model"),
    ("网络", "network"),
    ("系统", "system"),
    ("组件", "component"),
    ("模块", "module"),
    ("单元", "unit"),
    ("层次", "level"),
    ("阶段", "stage"),
    ("步骤", "step"),
    ("路径", "path"),
    ("轨迹", "trajectory"),
    ("轨道", "orbit"),
    ("区域", "region"),
    ("领域", "domain"),
    ("场景", "scenario"),
    ("情况", "case"),
    ("情形", "situation"),
    ("状态", "state"),
    ("模式", "pattern"),
    ("类型", "type"),
    ("类别", "category"),
    ("种类", "kind"),
    ("形式", "form"),
    ("版本", "version"),
    ("变量", "variable"),
    ("参数", "parameter"),
    ("常数", "constant"),
    ("系数", "coefficient"),
    ("因子", "factor"),
    ("维度", "dimension"),
    ("尺度", "scale"),
    ("大小", "size"),
    ("数量", "quantity"),
    ("质量", "quality"),
    ("能量", "energy"),
    ("力度", "intensity"),
    ("速度", "speed"),
    ("速率", "rate"),
    ("频率", "frequency"),
    ("周期", "period"),
    ("波长", "wavelength"),
    ("相位", "phase"),
    ("振幅", "amplitude"),
    ("距离", "distance"),
    ("角度", "angle"),
    ("方向", "direction"),
    ("位置", "position"),
    ("坐标", "coordinate"),
    ("空间", "space"),
    ("时间", "time"),
    ("序列", "sequence"),
    ("集合", "set"),
    ("分布", "distribution"),
    ("概率", "probability"),
    ("期望", "expectation"),
    ("方差", "variance"),
    ("协方差", "covariance"),
    ("标准差", "standard deviation"),
    ("误差", "error"),
    ("偏差", "bias"),
    ("噪声", "noise"),
    ("信号", "signal"),
    ("信息", "information"),
    ("熵", "entropy"),
    ("散度", "divergence"),
    ("互信息", "mutual information"),
    ("梯度", "gradient"),
    ("海森", "Hessian"),
    ("雅可比", "Jacobian"),
    ("拉普拉斯", "Laplacian"),
    ("傅里叶", "Fourier"),
    ("特征值", "eigenvalue"),
    ("特征向量", "eigenvector"),
    ("奇异值", "singular value"),
    ("范数", "norm"),
    ("内积", "inner product"),
    ("外积", "outer product"),
    ("点积", "dot product"),
    ("转置", "transpose"),
    ("逆", "inverse"),
    ("行列式", "determinant"),
    ("迹", "trace"),
    ("秩", "rank"),
    ("谱", "spectrum"),
    ("核", "kernel"),
    ("边界", "boundary"),
    ("临界点", "critical point"),
    ("不动点", "fixed point"),
    ("鞍点", "saddle point"),
    ("极值点", "extremum"),
    ("极小值", "minimum"),
    ("极大值", "maximum"),
    ("全局最优", "global optimum"),
    ("局部最优", "local optimum"),
    ("全局最小", "global minimum"),
    ("局部极小", "local minimum"),
    ("学习率", "learning rate"),
    ("步长", "step size"),
    ("批量", "batch"),
    ("轮次", "epoch"),
    ("迭代", "iteration"),
    ("更新", "update"),
    ("重置", "reset"),
    ("初始化", "initialize"),
    ("预热", "warmup"),
    ("退火", "annealing"),
    ("正则化", "regularization"),
    ("丢弃", "dropout"),
    ("批归一化", "batch normalization"),
    ("层归一化", "layer normalization"),
    ("残差", "residual"),
    ("注意力", "attention"),
    ("多头", "multi-head"),
    ("前馈", "feedforward"),
    ("嵌入", "embedding"),
    ("位置编码", "positional encoding"),
    ("自注意", "self-attention"),
    ("交叉注意", "cross-attention"),
    ("掩码", "mask"),
    ("填充", "padding"),
    ("分词", "tokenize"),
    ("词汇表", "vocabulary"),
    ("语料库", "corpus"),
    ("数据集", "dataset"),
    ("训练集", "training set"),
    ("验证集", "validation set"),
    ("测试集", "test set"),
    ("基准", "baseline"),
    ("基线", "baseline"),
    ("指标", "metric"),
    ("准确率", "accuracy"),
    ("精确率", "precision"),
    ("召回率", "recall"),
    ("F1值", "F1 score"),
    ("AUC", "AUC"),
    ("损失", "loss"),
    ("遗憾", "regret"),
    ("奖励", "reward"),
    ("惩罚", "penalty"),
    ("上界", "upper bound"),
    ("下界", "lower bound"),
    ("边界", "bound"),
    ("最坏情况", "worst case"),
    ("最好情况", "best case"),
    ("平均情况", "average case"),
    ("最优", "optimal"),
    ("次优", "suboptimal"),
    ("近似最优", "near-optimal"),
    ("渐近最优", "asymptotically optimal"),
    ("极小极大", "minimax"),
    ("审稿", "review"),
    ("论文", "paper"),
    ("文献", "literature"),
    ("引用", "citation"),
    ("参考", "reference"),
    ("附录", "appendix"),
    ("致谢", "acknowledgment"),
    ("资金", "funding"),
    ("冲突", "conflict"),
    ("贡献", "contribution"),
    ("创新", "novelty"),
    ("局限", "limitation"),
    ("未来工作", "future work"),
    ("开放问题", "open problem"),
    ("猜想", "conjecture"),
    ("示例", "example"),
    ("反例", "counterexample"),
    ("特例", "special case"),
    ("一般情况", "general case"),
    ("理想情况", "ideal case"),
    ("物理", "physics"),
    ("化学", "chemistry"),
    ("生物", "biology"),
    ("材料", "materials"),
    ("医学", "medical"),
    ("气候", "climate"),
    ("海洋", "ocean"),
    ("蛋白质", "protein"),
    ("氨基酸", "amino acid"),
    ("残基", "residue"),
    ("螺旋", "helix"),
    ("折叠", "folding"),
    ("晶体", "crystal"),
    ("缺陷", "defect"),
    ("空位", "vacancy"),
    ("间隙", "interstitial"),
    ("晶界", "grain boundary"),
    ("表面", "surface"),
    ("体相", "bulk"),
    ("总能", "total energy"),
    ("形成能", "formation energy"),
    ("结合能", "binding energy"),
    ("激活能", "activation energy"),
    ("势垒", "barrier"),
    ("力场", "force field"),
    ("电荷", "charge"),
    ("自旋", "spin"),
    ("轨道", "orbital"),
    ("能级", "energy level"),
    ("能带", "energy band"),
    ("态密度", "density of states"),
    ("费米能级", "Fermi level"),
    ("布里渊区", "Brillouin zone"),
    ("声子", "phonon"),
    ("电子", "electron"),
    ("离子", "ion"),
    ("原子", "atom"),
    ("分子", "molecule"),
    ("超胞", "supercell"),
    ("第一性原理", "first-principles"),
    ("密度泛函理论", "density functional theory"),
    ("分子动力学", "molecular dynamics"),
    ("蒙特卡洛", "Monte Carlo"),
    ("机器学习", "machine learning"),
    ("深度学习", "deep learning"),
    ("强化学习", "reinforcement learning"),
    ("迁移学习", "transfer learning"),
    ("元学习", "meta-learning"),
    ("对比学习", "contrastive learning"),
    ("自监督学习", "self-supervised learning"),
    ("半监督学习", "semi-supervised learning"),
    ("无监督学习", "unsupervised learning"),
    ("主动学习", "active learning"),
    ("在线学习", "online learning"),
    ("持续学习", "continual learning"),
    ("终身学习", "lifelong learning"),
    ("小样本学习", "few-shot learning"),
    ("零样本学习", "zero-shot learning"),
    ("生成模型", "generative model"),
    ("判别模型", "discriminative model"),
    ("扩散模型", "diffusion model"),
    ("流模型", "flow model"),
    ("自编码器", "autoencoder"),
    ("变分自编码器", "variational autoencoder"),
    ("生成对抗网络", "GAN"),
    ("图神经网络", "graph neural network"),
    ("等变网络", "equivariant network"),
    ("变换器", "Transformer"),
    ("卷积神经网络", "convolutional neural network"),
    ("循环神经网络", "recurrent neural network"),
    ("长短期记忆", "LSTM"),
    ("门控循环单元", "GRU"),
    ("注意力机制", "attention mechanism"),
    ("残差连接", "residual connection"),
    ("跳跃连接", "skip connection"),
    ("激活函数", "activation function"),
    ("损失函数", "loss function"),
    ("目标函数", "objective function"),
    ("代价函数", "cost function"),
    ("奖励函数", "reward function"),
    ("值函数", "value function"),
    ("策略函数", "policy function"),
    ("核函数", "kernel function"),
    ("基函数", "basis function"),
    ("格林函数", "Green's function"),
    ("泛函", "functional"),
    ("变分", "variational"),
    ("扰动", "perturbation"),
    ("渐近", "asymptotic"),
    ("解析", "analytic"),
    ("数值", "numerical"),
    ("闭式解", "closed-form solution"),
    ("显式", "explicit"),
    ("隐式", "implicit"),
    ("迭代", "iterative"),
    ("递归", "recursive"),
    ("归纳", "inductive"),
    ("演绎", "deductive"),
    ("推理", "inference"),
    ("归纳", "induction"),
    ("归约", "reduction"),
    ("约化", "reduction"),
    ("分解", "decomposition"),
    ("合成", "composition"),
    ("组合", "combination"),
    ("排列", "permutation"),
    ("分区", "partition"),
    ("聚类", "clustering"),
    ("分类", "classification"),
    ("回归", "regression"),
    ("检测", "detection"),
    ("分割", "segmentation"),
    ("识别", "recognition"),
    ("预测", "prediction"),
    ("生成", "generation"),
    ("重建", "reconstruction"),
    ("增强", "augmentation"),
    ("降噪", "denoising"),
    ("超分辨", "super-resolution"),
    ("风格迁移", "style transfer"),
    ("域适应", "domain adaptation"),
    ("分布偏移", "distribution shift"),
    ("协变量偏移", "covariate shift"),
    ("标签偏移", "label shift"),
    ("概念漂移", "concept drift"),
    ("公平性", "fairness"),
    ("可解释性", "interpretability"),
    ("鲁棒性", "robustness"),
    ("泛化性", "generalization"),
    ("可扩展性", "scalability"),
    ("可复现性", "reproducibility"),
    ("可迁移性", "transferability"),
    ("可组合性", "composability"),
    ("模块化", "modularity"),
    ("解耦性", "decoupling"),
    ("稀疏性", "sparsity"),
    ("低秩性", "low-rankness"),
    ("平滑性", "smoothness"),
    ("凸性", "convexity"),
    ("非凸性", "non-convexity"),
    ("多模态", "multi-modal"),
    ("跨模态", "cross-modal"),
    ("多任务", "multi-task"),
    ("多目标", "multi-objective"),
    ("多尺度", "multi-scale"),
    ("多分辨率", "multi-resolution"),
    ("多视角", "multi-view"),
    ("多语言", "multi-lingual"),
    ("零样本", "zero-shot"),
    ("少样本", "few-shot"),
    ("开放集", "open-set"),
    ("闭集", "closed-set"),
    ("分布外", "out-of-distribution"),
    ("对抗样本", "adversarial example"),
    ("后门攻击", "backdoor attack"),
    ("数据投毒", "data poisoning"),
    ("模型窃取", "model stealing"),
    ("成员推断", "membership inference"),
    ("差分隐私", "differential privacy"),
    ("联邦学习", "federated learning"),
    ("安全多方计算", "secure multi-party computation"),
    ("同态加密", "homomorphic encryption"),
    ("零知识证明", "zero-knowledge proof"),
    ("区块链", "blockchain"),
    ("去中心化", "decentralized"),
    ("分布式", "distributed"),
    ("并行", "parallel"),
    ("异步", "asynchronous"),
    ("同步", "synchronous"),
    
    # === Single characters and very common 2-char ===
    ("即", "i.e."),
    ("例", "e.g."),
    ("等", "etc."),
    ("与", "and"),
    ("或", "or"),
    ("且", "and"),
    ("但", "but"),
    ("若", "if"),
    ("则", "then"),
    ("因", "since"),
    ("故", "thus"),
    ("由", "by"),
    ("从", "from"),
    ("到", "to"),
    ("对", "for"),
    ("向", "toward"),
    ("沿", "along"),
    ("经", "via"),
    ("以", "with"),
    ("用", "using"),
    ("为", "as"),
    ("将", "will"),
    ("被", "by"),
    ("把", "将 → take"),
    ("所", "that which"),
    ("者", "one that"),
    
    # These are structural particles — provide English equivalents
    ("的", "'s"),  # possessive/attributive — but context-dependent
    ("是", "is"),
    ("有", "has"),
    ("在", "in"),
    ("不", "not"),
    ("会", "will"),
    ("能", "can"),
    ("可", "may"),
    ("要", "must"),
    ("应", "should"),
    ("需", "need"),
    ("已", "already"),
    ("未", "not yet"),
    ("正", "currently"),
    ("都", "all"),
    ("也", "also"),
    ("就", "then"),
    ("才", "only then"),
    ("只", "only"),
    ("仅", "merely"),
    ("更", "more"),
    ("最", "most"),
    ("很", "very"),
    ("太", "too"),
    ("极", "extremely"),
    ("较", "relatively"),
    ("稍", "slightly"),
    ("略", "slightly"),
    ("每", "each"),
    ("各", "each"),
    ("某", "some"),
    ("任", "any"),
    ("另", "another"),
    ("同", "same"),
    ("异", "different"),
    ("前", "previous"),
    ("后", "after"),
    ("上", "above"),
    ("下", "below"),
    ("左", "left"),
    ("右", "right"),
    ("中", "middle"),
    ("内", "inner"),
    ("外", "outer"),
    ("大", "large"),
    ("小", "small"),
    ("多", "many"),
    ("少", "few"),
    ("高", "high"),
    ("低", "low"),
    ("长", "long"),
    ("短", "short"),
    ("快", "fast"),
    ("慢", "slow"),
    ("深", "deep"),
    ("浅", "shallow"),
    ("宽", "wide"),
    ("窄", "narrow"),
    ("强", "strong"),
    ("弱", "weak"),
    ("新", "new"),
    ("旧", "old"),
    ("好", "good"),
    ("坏", "bad"),
    ("真", "true"),
    ("假", "false"),
    ("正", "positive"),
    ("负", "negative"),
    ("零", "zero"),
    ("一", "one"),
    ("二", "two"),
    ("三", "three"),
    ("四", "four"),
    ("五", "five"),
    ("六", "six"),
    ("七", "seven"),
    ("八", "eight"),
    ("九", "nine"),
    ("十", "ten"),
    ("百", "hundred"),
    ("千", "thousand"),
    ("万", "ten thousand"),
    ("亿", "hundred million"),
    ("第", "th"),  # ordinal prefix
    
    # Remaining common single chars
    ("其", "its"),
    ("它", "it"),
    ("他", "he"),
    ("她", "she"),
    ("我", "I"),
    ("你", "you"),
    ("们", "(plural)"),
    ("这", "this"),
    ("那", "that"),
    ("哪", "which"),
    ("什", "what"),
    ("怎", "how"),
    ("为", "why"),
    ("何", "what"),
    ("谁", "who"),
    ("吗", "?"),
    ("呢", "(particle)"),
    ("吧", "(particle)"),
    ("啊", "(particle)"),
    ("过", "pass"),
    ("着", "-ing"),
    ("了", "(past)"),
    ("得", "obtain"),
    ("让", "let"),
    ("使", "make"),
    ("给", "give"),
    ("拿", "take"),
    ("放", "put"),
    ("走", "go"),
    ("来", "come"),
    ("去", "go"),
    ("进", "enter"),
    ("出", "exit"),
    ("上", "up"),
    ("下", "down"),
    ("开", "open"),
    ("关", "close"),
    ("合", "combine"),
    ("分", "split"),
    ("加", "add"),
    ("减", "subtract"),
    ("乘", "multiply"),
    ("除", "divide"),
    
    # Math notation characters
    ("∑", "\\sum"),
    ("∏", "\\prod"),
    ("∫", "\\int"),
    ("∂", "\\partial"),
    ("√", "\\sqrt"),
    ("∞", "\\infty"),
    ("→", "\\to"),
    ("⇒", "\\Rightarrow"),
    ("⇔", "\\Leftrightarrow"),
    ("≤", "\\leq"),
    ("≥", "\\geq"),
    ("≠", "\\neq"),
    ("≈", "\\approx"),
    ("∼", "\\sim"),
    ("∈", "\\in"),
    ("∉", "\\notin"),
    ("⊂", "\\subset"),
    ("⊆", "\\subseteq"),
    ("∪", "\\cup"),
    ("∩", "\\cap"),
    ("∅", "\\emptyset"),
    ("∀", "\\forall"),
    ("∃", "\\exists"),
    ("∄", "\\nexists"),
    ("∧", "\\land"),
    ("∨", "\\lor"),
    ("¬", "\\neg"),
    ("⊕", "\\oplus"),
    ("⊗", "\\otimes"),
    ("⊥", "\\perp"),
    ("∥", "\\parallel"),
    ("·", "\\cdot"),
    ("×", "\\times"),
    ("÷", "\\div"),
    ("±", "\\pm"),
    ("∓", "\\mp"),
    ("∝", "\\propto"),
    ("≪", "\\ll"),
    ("≫", "\\gg"),
    ("≃", "\\simeq"),
    ("≅", "\\cong"),
    ("≡", "\\equiv"),
    ("≢", "\\not\\equiv"),
    ("⊤", "\\top"),
    ("⊥", "\\bot"),
]

# Longer patterns MUST be tried first
TRANSLATIONS.sort(key=lambda x: -len(x[0]))

def find_chinese_ranges(text):
    """Find all Chinese character ranges in text."""
    ranges = []
    i = 0
    while i < len(text):
        if '\u4e00' <= text[i] <= '\u9fff' or '\u3400' <= text[i] <= '\u4dbf':
            start = i
            while i < len(text) and ('\u4e00' <= text[i] <= '\u9fff' or '\u3400' <= text[i] <= '\u4dbf'):
                i += 1
            ranges.append((start, i))
        else:
            i += 1
    return ranges

def translate_file(filepath):
    """Translate all Chinese fragments in a file."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Apply translations greedily (longest match first)
    result = content
    for chinese, english in TRANSLATIONS:
        result = result.replace(chinese, english)
    
    # Also handle any remaining single Chinese chars with context-aware translation
    # by replacing Chinese chars that survived with a marker
    remaining = find_chinese_ranges(result)
    if remaining:
        chars = set()
        for start, end in remaining:
            chars.update(result[start:end])
        print(f"  WARNING: {filepath} still has {len(remaining)} Chinese fragments after translation.")
        print(f"  Remaining chars: {''.join(sorted(chars))[:100]}")
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(result)
    
    return len(find_chinese_ranges(content)), len(remaining)

def main():
    files = [
        "theory/self_evolution/final_review_jmlr.tex",
        "theory/self_evolution/final_review_nature.tex",
        "theory/self_evolution/README.tex",
        "theory/self_evolution/situs_final_verification.tex",
        "theory/self_evolution/multi_head_spring_and_positional_encoding_analysis.tex",
        "theory/self_evolution/ppe_rigorous_derivation.tex",
        "theory/self_evolution/situs_physical_validation.tex",
        "theory/self_evolution/spring_convergence_analysis.tex",
        "theory/self_evolution/spring_hostile_review.tex",
        "theory/theorems/01_noise_detection_guarantee.tex",
        "theory/theorems/02_weak_feature_failure.tex",
        "theory/theorems/03_unidentifiability_theorem.tex",
    ]
    
    base = "F:/scx"
    total_before = 0
    total_after = 0
    
    for f in files:
        path = os.path.join(base, f)
        if not os.path.exists(path):
            print(f"MISSING: {path}")
            continue
        before, after = translate_file(path)
        total_before += before
        total_after += after
        print(f"  {f}: {before} → {after} fragments")
    
    print(f"\nTOTAL: {total_before} → {total_after} Chinese fragments remaining")

if __name__ == "__main__":
    main()
