#!/usr/bin/env python3
"""Final Batch C translation - all 14 files."""
import re, os, sys

BASE = r"F:\scx"
cn_re = re.compile(r'[\u4e00-\u9fff]+')

def load_translations():
    """Build comprehensive translation dictionary."""
    t = {}
    
    # === SPRING_NAMING.tex ===
    t['春季算法'] = 'Spring Algorithm'
    t['复苏'] = 'resurrection'
    
    # === THEOREMS_UNIFIED.tex ===
    t['越小，界越宽松'] = 'The smaller it is, the looser the bound'
    t['这反映了检测稀有噪声的内在困难。'] = 'This reflects the inherent difficulty of detecting rare noise.'
    
    # === scx_llm/main.tex ===
    t['雅洁'] = 'Yajie'
    
    # === theory/theorems/README.tex ===
    t['本目录存放'] = 'This directory contains'
    t['框架的核心定理：'] = ' the core theorems of the SCX framework:'
    t['多专家一致性噪声检测保证'] = 'Multi-Expert Consistency Noise Detection Guarantee'
    t['弱特征失效下界'] = 'Weak Feature Failure Lower Bound'
    t['噪声与可学习困难的不可识别性'] = 'Unidentifiability of Noise vs. Learnable Difficulty'
    t['三个定理的逻辑闭环'] = 'Logical Closure of the Three Theorems'
    t['正命题'] = 'Positive Statement'
    t['能检测噪声'] = 'SCX can detect noise'
    t['边界命题'] = 'Boundary Statement'
    t['当特征弱时,'] = 'When features are weak, '
    t['退化为损失基线'] = 'SCX degenerates to the loss baseline'
    t['必要性命题'] = 'Necessity Statement'
    t['噪声与困难根本不可区分'] = 'noise and difficulty are fundamentally indistinguishable'
    t['非任意假设'] = 'A1-A6 are not arbitrary assumptions'
    t['而是打破不可识别性的最小条件'] = 'but rather the minimal conditions that break unidentifiability'
    t['在 A1-A6 下,'] = 'Under A1-A6, '
    t['当特征弱时, SCX'] = 'When features are weak, SCX'
    t['无 A1-A6 时,'] = 'Without A1-A6, '
    
    # === self_evolution/README.tex ===
    t['自我进化理论'] = 'Self-Evolution Theory'
    t['数学形式化'] = 'Mathematical Formalization'
    t['最后更新'] = 'Last Updated'
    t['问题'] = 'Problem'
    t['核心问题'] = 'Core Problem'
    t['困难'] = 'Difficulty'
    t['核心洞察'] = 'Core Insight'
    t['九个核心文件'] = 'Nine Core Files'
    t['核心结果'] = 'Core Result'
    t['核心定理'] = 'Core Theorems'
    t['四种收敛路径'] = 'Four Convergence Paths'
    t['路径'] = 'Path'
    t['特征'] = 'Characteristics'
    t['条件'] = 'Conditions'
    t['经典收敛'] = 'Classical Convergence'
    t['单调改进'] = 'monotonic improvement'
    t['全部满足，充分退火'] = 'all satisfied, sufficient annealing'
    t['极限环'] = 'Limit Cycle'
    t['系统在有限配置间周期振荡'] = 'system oscillates periodically among finite configurations'
    t['退火不充分，耦合过强'] = 'insufficient annealing, excessive coupling'
    t['永动发现'] = 'Perpetual Discovery'
    t['新结构持续发现，'] = 'new structures continuously discovered, '
    t['无限增长'] = 'grows without bound'
    t['开放物理世界，无限探索预算'] = 'open physical world, unlimited exploration budget'
    t['发散崩溃'] = 'Divergent Collapse'
    t['退化，质量下降'] = 'degenerates, quality declines'
    t['反馈回路断裂，'] = 'feedback loop breaks, '
    t['反馈噪声过大'] = 'feedback noise excessive'
    t['的精确分界条件是'] = 'The precise boundary conditions are'
    t['开放问题'] = 'open problems'
    t['见'] = 'see'
    t['与现有理论体系的关系'] = 'Relationship with Existing Theoretical Frameworks'
    t['从属关系'] = 'Subordination Relationships'
    t['提供自进化必要性论证'] = 'provides the necessity argument for self-evolution'
    t['自进化闭环必须存在'] = 'the self-evolution closed loop must exist'
    t['初始化提供保证'] = 'provides initialization guarantees'
    t['的初始条件'] = 'initial conditions'
    t['中心结果'] = 'central result'
    t['闭环渐近收敛到自洽点'] = 'closed loop converges asymptotically to a self-consistent point'
    t['弱特征界'] = 'Weak Feature Bound'
    t['限制改进速度'] = 'limits improvement speed'
    t['最小最大最优'] = 'Minimax Optimality'
    t['提供的渐近最优性'] = 'provides asymptotic optimality'
    t['完备性界'] = 'Completeness Bound'
    t['物理有限性强制有限时间收敛'] = 'physical finiteness enforces finite-time convergence'
    t['新引入假设'] = 'Newly Introduced Assumptions'
    t['至'] = 'to'
    t['新引入，核心假设'] = 'Newly introduced, core assumption'
    t['物理约束（非统计学假设）'] = 'Physical constraint (non-statistical assumption)'
    t['平滑性假设'] = 'Smoothness assumption'
    t['的扩展'] = 'extension'
    t['标准'] = 'Standard '
    t['退火条件'] = 'Annealing condition'
    t['与已知理论的连接摘要'] = 'Summary of Connections to Known Theories'
    t['理论框架'] = 'Theoretical Framework'
    t['核心机制'] = 'Core Mechanism'
    t['自进化的关键差异'] = 'Key Differences from SCX Self-Evolution'
    t['生成合成游戏；'] = 'generates synthetic games; '
    t['依赖真实'] = 'relies on real '
    t['数据'] = 'data'
    t['优化静态黑箱；'] = 'optimizes static black box; '
    t['的目标分布在演化'] = 'target distribution evolves'
    t['即时反馈；'] = 'immediate oracle feedback; '
    t['延迟反馈'] = 'delayed feedback'
    t['不可计算；'] = 'uncomputable; '
    t['限制在有限假设类'] = 'restricted to finite hypothesis class'
    t['详见'] = 'See '
    t['完整对比表。'] = 'for the complete comparison table.'
    t['理论状态评估'] = 'Theoretical Status Assessment'
    t['类别'] = 'Category'
    t['比例'] = 'Proportion'
    t['说明'] = 'Description'
    t['严格理论'] = 'Rigorous Theory'
    t['的有限状态版本'] = 'finite-state version'
    t['贝叶斯鞅收敛'] = 'Bayesian martingale convergence'
    t['标准收敛'] = 'standard convergence'
    t['上界'] = 'upper bound'
    t['形式化猜想'] = 'Formalized Conjectures'
    t['连续状态空间扩展'] = 'continuous state-space extension'
    t['双时间尺度收敛'] = 'two-timescale convergence'
    t['收缩率'] = 'contraction rate'
    t['合理假设'] = 'Reasonable Assumptions'
    t['精确'] = 'Exact '
    t['函数形式'] = 'function form'
    t['极限环条件'] = 'limit cycle conditions'
    t['类比'] = 'analogy'
    t['最优退火策略'] = 'optimal annealing strategy'
    t['优先级排序'] = 'Priority Ordering'
    t['优先级'] = 'Priority'
    t['明确的'] = 'Explicit '
    t['的定义与下降证明'] = 'definition and descent proof'
    t['四种收敛路径的精确定界'] = 'Precise bounding of the four convergence paths'
    t['耦合'] = 'coupled '
    t['系统的紧收敛率'] = 'system tight convergence rate'
    t['最优'] = 'Optimal '
    t['更新频率'] = 'update frequency'
    t['收敛所需的最小记忆库大小'] = 'Minimum memory bank size for convergence'
    t['非渐近（有限时间）保证'] = 'Non-asymptotic (finite-time) guarantees'
    t['分布偏移下的鲁棒性刻画'] = 'Robustness under distribution shift'
    t['的严格化'] = 'rigorization'
    t['文件结构'] = 'File Structure'
    t['本文件'] = 'This file'
    t['符号系统与问题设定'] = 'Symbol System and Problem Setup'
    t['离散动力系统形式化'] = 'Discrete Dynamical System Formalization'
    t['在线学习'] = 'Online Learning'
    t['分析'] = 'Analysis'
    t['贝叶斯更新解释'] = 'Bayesian Update Interpretation'
    t['随机逼近分析'] = 'Stochastic Approximation Analysis'
    t['不动点与收敛定理（中心）'] = 'Fixed Point and Convergence Theorem (Center)'
    t['完备性分析'] = 'Completeness Analysis'
    t['与已知理论的连接'] = 'Connections to Known Theories'
    t['验证报告'] = 'Verification Report'
    t['跨领域适用'] = 'Cross-Domain Applicability'
    t['领域'] = 'Domain'
    t['角色'] = 'Role'
    t['判断'] = 'Judge '
    t['标签正确性'] = 'label correctness'
    t['势能面模型'] = 'potential energy surface model'
    t['累积的'] = 'Accumulated '
    t['计算轨迹'] = 'computation trajectories'
    t['医学图像'] = 'Medical Imaging'
    t['判断诊断标签质量'] = 'judge diagnostic label quality'
    t['辅助诊断模型'] = 'auxiliary diagnostic model'
    t['累积的专家复核记录'] = 'accumulated expert review records'
    t['自动驾驶'] = 'Autonomous Driving'
    t['判断检测框'] = 'judge detection box'
    t['标注质量'] = 'annotation quality'
    t['感知模型'] = 'perception model'
    t['累积的路测验证数据'] = 'accumulated road-test validation data'
    t['判断标注'] = 'judge annotation'
    t['生成质量'] = 'generation quality'
    t['下游任务模型'] = 'downstream task model'
    t['累积的人工审核日志'] = 'accumulated human review logs'
    t['参考文献（新增）'] = 'References (Newly Added)'
    t['学生'] = 'student '
    t['构成耦合动力系统'] = 'form a coupled dynamical system'
    t['的选择决定了'] = 'determines '
    t['的训练分布，而'] = 'the training distribution, and '
    t['的输出提供反馈给'] = 'output provides feedback to '
    t['将 SCX 的自我进化闭环（judge'] = 'Formalize the SCX self-evolution closed loop (judge'
    t['\\ldots）形式化为严格的数学理论，并与已知理论框架建立连接。'] = '...) as a rigorous mathematical theory, and establish connections with known theoretical frameworks.'
    t['SCX 系统在运行中形成以下闭环：'] = 'The SCX system forms the following closed loop during operation:'
    t['：这个闭环是否收敛？收敛到何处？收敛速率如何？在何种条件下发散？'] = ': Does this closed loop converge? To what? At what rate? Under what conditions does it diverge?'
    t['SCX 自我进化的正确数学对象是耦合动力系统 (S_t,'] = 'The correct mathematical object for SCX self-evolution is the coupled dynamical system (S_t,'
    t['，其全局行为由 Lyapunov 函数 V(S,'] = ', whose global behavior is governed by the monotonic descent property of the Lyapunov function V(S,'
    t[') 的单调下降性质主导。'] = ').'
    t['Judge (S_t'] = 'Judge (S_t scoring)'
    t['评分)'] = ' scoring)'
    t['记忆库)'] = ' memory bank)'
    t['更新评分)'] = ' update scoring)'
    t['学生更新)'] = ' student update)'
    
    # More README translations
    t['文件'] = 'File'
    t['内容'] = 'Content'
    t['状态'] = 'Status'
    t['完整'] = 'Complete'
    
    # === situs_final_verification.tex (key headings only) ===
    t['Situs 理论最终验证报告'] = 'Situs Theory Final Verification Report'
    t['验证日期'] = 'Verification Date'
    t['验证文件'] = 'Verification Files'
    t['行'] = 'lines'
    t['逐项检查'] = 'Item-by-Item Check'
    t['定理'] = 'Theorem'
    t['常数是否已修正为'] = 'Has the Lipschitz constant been corrected to'
    t['位置'] = 'Location'
    t['公式'] = 'Formula'
    t['结论'] = 'Conclusion'
    t['通过。'] = 'Pass.'
    t['归一化因子是否已加入？'] = 'Has the normalization factor been added?'
    t['框内公式是否已去掉'] = 'Has the boxed formula dropped its'
    t['依赖'] = '-dependence'
    t['依赖？'] = '-dependence?'
    t['无'] = 'None'
    t['定理编号是否统一为'] = 'Have theorem numbers been unified to'
    t['指的是'] = 'This refers to'
    t['学习型'] = 'learnable '
    t['破坏'] = 'breaking '
    t['的精确条件'] = 'precise conditions'
    t['这个定理。'] = '.'
    t['两文件统一使用'] = 'Both files uniformly use'
    t['。同时命题'] = '. Meanwhile Proposition'
    t['固定'] = 'fixed '
    t['保持不可区分性'] = 'preserves unidentifiability'
    t['的编号也一致。'] = 'numbering is also consistent.'
    t['是否修正为'] = 'Has d_min been corrected to'
    t['推导'] = 'Derivation'
    t['推导链完整，'] = 'Derivation chain complete; '
    t['条件已正确引用（覆盖整个序列区间需'] = 'Nyquist condition correctly cited (covering full sequence interval requires'
    t['是否已降级为启发式估计？'] = 'Has it been downgraded to a heuristic estimate?'
    t['关键变化'] = 'Key Change'
    t['从'] = 'From '
    t['（下界）'] = '(lower bound)'
    t['（启发式估计------非严格下界）'] = '(heuristic estimate --- not a rigorous lower bound)'
    t['环境类型'] = 'Environment Type'
    t['诚实标记'] = 'Honesty Label'
    t['明确声明'] = 'Explicit Declaration'
    t['此表达式'] = 'This expression'
    t['不是'] = 'is NOT '
    t['严格的数学下界'] = 'a rigorous mathematical lower bound'
    t['逻辑错误标注'] = 'Logical Error Annotation'
    t['从两个'] = 'From two '
    t['下界不能逻辑地推出差的下界'] = 'lower bounds one cannot logically derive a lower bound on the difference'
    t['等号误用说明'] = 'Equality Misuse Note'
    t['若'] = 'If '
    t['若假设'] = 'If one assumes the '
    t['两文件对齐良好。'] = 'Both files are well-aligned.'
    t['步骤'] = 'Step'
    t['是否已限定为贝叶斯最优？'] = 'Has it been qualified as Bayes-optimal?'
    t['层面'] = 'Aspect'
    t['定理标题'] = 'Theorem Title'
    t['充分条件'] = 'Sufficient Condition'
    t['结论陈述'] = 'Conclusion Statement'
    t['贝叶斯最优分类器'] = 'Bayes-optimal classifier'
    t['在增广特征下的检测边际变化满足'] = 'under augmented features satisfies'
    t['标记'] = 'Marked'
    t['猜想'] = 'Conjecture'
    t['局限声明'] = 'Limitation Statement'
    t['退化声明'] = 'Degradation Statement'
    t['若步骤'] = 'If Step'
    t['破坏方向是否已改为开放问题？'] = 'Has the breaking direction been changed to an open problem?'
    t['陈述内'] = 'Within Statement'
    t['若前提'] = 'If premise'
    t['不成立'] = 'does not hold'
    t['不可区分性是否被破坏目前是一个'] = 'whether unidentifiability is broken is currently an'
    t['最小示例重评'] = 'Minimal Example Re-assessment'
    t['此示例实际上证明了'] = 'This example actually proves'
    t['的鲁棒性，而非其脆弱性'] = 'robustness, not its fragility'
    t['此最小示例实际上证明了'] = 'This minimal example actually proves'
    t['诚实度表'] = 'Honesty Table'
    t['条目'] = 'Entry'
    t['破坏方向无构造性证明'] = 'No constructive proof for the breaking direction'
    t['前提成立时'] = 'holds under premises'
    t['前提不成立时'] = 'open problem when premises do not hold'
    t['原声称的'] = 'The originally claimed'
    t['构造性示例证明破坏方向'] = 'constructive example proving the breaking direction'
    t['已被重评为'] = 'has been reassessed as'
    t['构造性示例反而展示了定理的鲁棒性'] = 'the constructive example instead demonstrates the theorem robustness'
    t['符合预期。'] = 'as expected.'
    t['两份文件之间是否还有符号不一致？'] = 'Are there any remaining notation inconsistencies?'
    t['一致的项目'] = 'Consistent Items'
    t['符号'] = 'Symbol/Concept'
    t['概念'] = ''
    t['预期差异（非问题）'] = 'Expected Differences (Non-Issues)'
    t['差异'] = 'Difference'
    t['原因'] = 'Reason'
    t['判定'] = 'Assessment'
    t['使用框架名'] = 'uses framework name'
    t['使用缩写'] = 'uses abbreviation'
    t['上标约定不同'] = 'superscript convention differs'
    t['章节编号偏移'] = 'section number offset'
    t['有'] = 'has '
    t['引言'] = 'Introduction'
    t['无引言直接从编码定义开始'] = 'has no introduction, starts from encoding definition'
    t['环境形式'] = 'Environment form'
    t['格式差异'] = 'Format difference'
    t['残余不一致（需关注）'] = 'Residual Inconsistencies (Need Attention)'
    t['中的'] = ' in the '
    t['过度声称'] = 'Overclaim'
    t['摘要'] = 'Abstract'
    t['证明了'] = 'proves'
    t['充要条件'] = 'necessary and sufficient condition'
    t['为'] = 'is '
    t['（定理'] = '(Theorem '
    t['）'] = ')'
    t['标题'] = 'title'
    t['必要性条件'] = 'Necessary Condition'
    t['总结'] = 'Summary'
    t['摘要称定理'] = 'The abstract claims that Theorem'
    t['给出了'] = 'provides'
    t['但实际上定理'] = 'but actually Theorem'
    t['仅证'] = 'only proves'
    t['独立的'] = 'independent '
    t['另外给出（且允许非信息论机制）。此外，充分条件包含步骤'] = 'separately (allowing non-information-theoretic mechanisms). Moreover, the sufficient condition includes Step'
    t['的启发式推广（从贝叶斯最优到实际专家），而非纯粹严格证明。'] = 'heuristic generalization (from Bayes-optimal to actual experts), not a purely rigorous proof.'
    t['建议'] = 'Recommendation'
    t['摘要中'] = 'In the abstract, '
    t['应改为'] = 'should be changed to'
    t['）与必要条件（命题'] = ') and necessary condition (Proposition '
    t['），或至少将归属从单独的'] = '), or at least correct the attribution from'
    t['修正为'] = 'to '
    t['的双重陈述'] = 'Dual Statement'
    t['粗略形式：'] = 'Rough form: '
    t['修正项'] = 'correction term'
    t['精确形式：'] = 'Precise form: '
    t['仅有精确形式'] = 'Only the precise form'
    t['先给出一个较粗略的形式，再给出精确形式。两个版本的第二项不同（'] = 'first gives a rougher form, then a precise form. The second terms differ between the two versions ('
    t['使用了概念上不同的'] = 'uses the conceptually different'
    t['而精确版使用'] = 'while the precise version uses'
    t['。这可能导致读者困惑------两个形式不等价。'] = '. This may confuse readers --- the two forms are not equivalent.'
    t['编号'] = 'Number'
    t['标签'] = 'Label'
    
    # ====== Common math/LaTeX words ======
    t['证明'] = 'Proof'
    t['证毕'] = 'QED'
    t['引理'] = 'Lemma'
    t['推论'] = 'Corollary'
    t['命题'] = 'Proposition'
    t['定义'] = 'Definition'
    t['注记'] = 'Note'
    t['注'] = 'Note'
    t['文档状态'] = 'Document Status'
    t['完整分析'] = 'Complete Analysis'
    t['严格数学推导'] = 'Rigorous Mathematical Derivation'
    t['诚实暴击'] = 'Honest Critique'
    t['不委婉'] = 'Unsparing'
    t['前置阅读'] = 'Prerequisites'
    t['审计报告'] = 'Audit Report'
    t['方法论'] = 'Methodology'
    t['严格形式推导'] = 'Rigorous Formal Derivation'
    t['诚实暴击（不委婉）'] = 'Honest Critique (Unsparing)'
    t['符号约定与框架重构'] = 'Notation Convention and Framework Reconstruction'
    t['符号约定与先备知识'] = 'Notation Convention and Prerequisites'
    t['符号约定'] = 'Notation Convention'
    t['符号与设定'] = 'Notation and Setup'
    t['含义'] = 'Meaning'
    t['目录'] = 'Table of Contents'
    t['定义：弱特征'] = 'Definition: Weak Features'
    t['定理陈述'] = 'Theorem Statement'
    t['关键引理'] = 'Key Lemmas'
    t['均值分离'] = 'Mean Separation'
    t['主定理'] = 'Main Theorem'
    t['主结果'] = 'Main Result'
    t['证明技术'] = 'Proof Technique'
    t['证明路径'] = 'Proof Path'
    t['证明思路'] = 'Proof Idea'
    t['证明构造'] = 'Proof Construction'
    t['关联实验'] = 'Related Experiments'
    t['关联代码'] = 'Related Code'
    t['关联概念'] = 'Related Concepts'
    t['实用解读'] = 'Practical Interpretation'
    t['数据生成'] = 'Data Generation'
    t['取值空间'] = 'Value Space'
    t['输入空间'] = 'Input Space'
    t['标签空间'] = 'Label Space'
    t['数据分布'] = 'Data Distribution'
    t['状态空间'] = 'State Space'
    t['观测空间'] = 'Observation Space'
    t['潜在变量模型'] = 'Latent Variable Model'
    t['不可观测'] = 'unobservable'
    t['形式化陈述'] = 'Formal Statement'
    t['形式化定义'] = 'Formal Definition'
    t['解读'] = 'Interpretation'
    t['构造框架'] = 'Construction Framework'
    t['世界等价性验证'] = 'World Equivalence Verification'
    t['算法不可区分性'] = 'Algorithm Unidentifiability'
    t['扩展'] = 'Extension'
    t['假设'] = 'Assumptions'
    t['设定'] = 'Setup'
    t['修正记录'] = 'Revision History'
    t['初版完成'] = 'First version complete'
    t['核心主张'] = 'Core Claim'
    t['检测边际'] = 'Detection Margin'
    t['一致性计数与阈值'] = 'Consistency Count and Threshold'
    t['基础'] = 'Foundation'
    
    return t

def translate_file(path, translations):
    with open(path, 'r', encoding='utf-8') as f:
        c = f.read()
    before = len(cn_re.findall(c))
    for cn, en in sorted(translations.items(), key=lambda x: -len(x[0])):
        if cn in c:
            c = c.replace(cn, en)
    after = len(cn_re.findall(c))
    with open(path, 'w', encoding='utf-8') as f:
        f.write(c)
    return before, after

# Main
translations = load_translations()
all_files = [
    'theory/self_evolution/SPRING_NAMING.tex',
    'theory/THEOREMS_UNIFIED.tex',
    'paper/archive/scx_llm/main.tex',
    'theory/theorems/README.tex',
    'theory/self_evolution/README.tex',
    'theory/self_evolution/situs_final_verification.tex',
    'theory/self_evolution/multi_head_spring_and_positional_encoding_analysis.tex',
    'theory/self_evolution/ppe_rigorous_derivation.tex',
    'theory/self_evolution/situs_physical_validation.tex',
    'theory/self_evolution/spring_convergence_analysis.tex',
    'theory/self_evolution/spring_hostile_review.tex',
    'theory/theorems/01_noise_detection_guarantee.tex',
    'theory/theorems/02_weak_feature_failure.tex',
    'theory/theorems/03_unidentifiability_theorem.tex',
]

total_before, total_after = 0, 0
for f in all_files:
    path = os.path.join(BASE, f)
    if os.path.exists(path):
        b, a = translate_file(path, translations)
        total_before += b
        total_after += a
        print(f"  {os.path.basename(f)}: {b} -> {a} ({b-a} translated)")
    else:
        print(f"  MISSING: {f}")

print(f"\nTotal: {total_before} -> {total_after} ({total_before-total_after} Chinese chars translated)")
