#!/usr/bin/env python3
"""Step 4: Large-scale Chinese->English translation for 8 remaining files."""
import re, os
BASE = r"F:\scx"

UNIVERSAL = {
    # Common document structure words
    '文档状态': 'Document Status',
    '完整分析': 'Complete Analysis',
    '严格数学推导': 'Rigorous Mathematical Derivation',
    '诚实暴击': 'Honest Critique',
    '不委婉': 'Unsparing',
    '前置阅读': 'Prerequisites',
    '审计报告': 'Audit Report',
    '方法论': 'Methodology',
    '严格形式推导': 'Rigorous Formal Derivation',
    '诚实暴击（不委婉）': 'Honest Critique (Unsparing)',
    '依赖': 'Dependencies',
    '核心问题': 'Core Problem',
    '核心洞察': 'Core Insight',
    '核心定理': 'Core Theorem',
    '核心结果': 'Core Result',
    '核心判据': 'Core Criterion',
    '核心主张': 'Core Claim',
    '核心机制': 'Core Mechanism',
    # Common section/heading words
    '符号约定与框架重构': 'Notation Convention and Framework Reconstruction',
    '符号约定与先备知识': 'Notation Convention and Prerequisites',
    '符号约定': 'Notation Convention',
    '符号与设定': 'Notation and Setup',
    '符号': 'Symbol',
    '含义': 'Meaning',
    '文件': 'File',
    '目录': 'Table of Contents',
    '定义：弱特征': 'Definition: Weak Features',
    '定理陈述': 'Theorem Statement',
    '关键引理': 'Key Lemmas',
    '均值分离': 'Mean Separation',
    '主定理': 'Main Theorem',
    '主结果': 'Main Result',
    '证明': 'Proof',
    '证明技术': 'Proof Technique',
    '证明路径': 'Proof Path',
    '证明思路': 'Proof Idea',
    '证明构造': 'Proof Construction',
    '关联实验': 'Related Experiments',
    '关联代码': 'Related Code',
    '关联概念': 'Related Concepts',
    '实用解读': 'Practical Interpretation',
    '数据生成': 'Data Generation',
    '取值空间': 'Value Space',
    '输入空间': 'Input Space',
    '标签空间': 'Label Space',
    '数据分布': 'Data Distribution',
    '状态空间': 'State Space',
    '观测空间': 'Observation Space',
    '潜在变量模型': 'Latent Variable Model',
    '不可观测': 'unobservable',
    '形式化陈述': 'Formal Statement',
    '形式化定义': 'Formal Definition',
    '解读': 'Interpretation',
    '构造框架': 'Construction Framework',
    '世界等价性验证': 'World Equivalence Verification',
    '算法不可区分性': 'Algorithm Unidentifiability',
    '扩展': 'Extension',
    # Section headings
    '假设': 'Assumptions',
    '设定': 'Setup',
    '完整': 'Complete',
    '修正记录': 'Revision History',
    '初版完成': 'First version complete',
    '状态': 'Status',
    '内容': 'Content',
    '位置': 'Location',
    '公式': 'Formula',
    '结论': 'Conclusion',
    '问题': 'Problem',
    '困难': 'Difficulty',
    '条件': 'Conditions',
    # Math/theorem words
    '定理': 'Theorem',
    '引理': 'Lemma',
    '推论': 'Corollary',
    '命题': 'Proposition',
    '定义': 'Definition',
    '注记': 'Note',
    '注': 'Note',
    '检查': 'Check',
    # Common connecting words
    '其中': 'where',
    '设': 'Let',
    '当': 'When',
    '若': 'If',
    '则': 'then',
    '且': 'and',
    '或': 'or',
    '即': 'i.e.',
    '与': 'and',
    '对': 'for',
    '由': 'by',
    '为': 'is',
    '的': '',
    '在': 'in',
    '和': 'and',
    '上': 'on',
    '中': 'in',
    '有': 'has',
    '是': 'is',
    '均': 'all',
    '均来自验证报告': 'all from the verification report',
    '均已修正': 'all fixed',
    '两个': 'Two',
    '三个': 'Three',
    '以下': 'below',
    '以上': 'above',
    '因此': 'Therefore',
    '从而': 'thus',
    '此外': 'Moreover',
    '特别地': 'In particular',
    '具体地': 'Specifically',
    '形式化地': 'Formally',
    '等价地': 'Equivalently',
    '即：': 'i.e.:',
    '例如：': 'e.g.:',
    '包括': 'including',
    '但不': 'but not',
    '然而': 'However',
    '因为': 'because',
    '所以': 'so',
    '如果': 'If',
    '那么': 'then',
    '或者': 'or',
    '证明：': 'Proof: ',
    '证毕': 'QED',
    '成立': 'holds',
    '满足': 'satisfies',
    '存在': 'there exists',
    '使得': 'such that',
    '任意': 'any',
    '所有': 'all',
    '每个': 'each',
    '给定': 'given',
    '关于': 'with respect to',
    '根据': 'according to',
    '通过': 'via',
    '利用': 'using',
    '定义': 'define',
    '计算': 'compute',
    '获得': 'obtain',
    '得到': 'yields',
    '给出': 'gives',
    '提供': 'provides',
    '保证': 'guarantees',
    '确保': 'ensures',
    '需要': 'requires',
    '必须': 'must',
    '可以': 'can',
    '可能': 'may',
    '应该': 'should',
    '能够': 'can',
    '不能': 'cannot',
    '不会': 'will not',
    '不同': 'different',
    '相同': 'same',
    '一致': 'consistent',
    '独立': 'independent',
    '依赖': 'dependent',
    '相关': 'correlated',
    '无关': 'irrelevant',
    '重要': 'important',
    '关键': 'key',
    '主要': 'main',
    '基本': 'basic',
    '一般': 'general',
    '特殊': 'special',
    '具体': 'specific',
    '实际': 'actual',
    '理论': 'theoretical',
    '实验': 'experimental',
    '数值': 'numerical',
    '结果': 'result',
    '方法': 'method',
    '过程': 'process',
    '步骤': 'step',
    '阶段': 'stage',
    '部分': 'part',
    '方面': 'aspect',
    '情况': 'case',
    '情形': 'case',
    '例子': 'example',
    '示例': 'example',
    '反例': 'counterexample',
    '构造': 'construction',
    '集合': 'set',
    '函数': 'function',
    '常数': 'constant',
    '变量': 'variable',
    '参数': 'parameter',
    '分布': 'distribution',
    '概率': 'probability',
    '期望': 'expectation',
    '方差': 'variance',
    '误差': 'error',
    '损失': 'loss',
    '样本': 'sample',
    '数据': 'data',
    '模型': 'model',
    '特征': 'feature',
    '标签': 'label',
    '类别': 'class',
    '分类': 'classification',
    '回归': 'regression',
    '训练': 'training',
    '测试': 'testing',
    '验证': 'validation',
    '评估': 'evaluation',
    '检测': 'detection',
    '识别': 'recognition',
    '预测': 'prediction',
    '估计': 'estimation',
    '推断': 'inference',
    '优化': 'optimization',
    '收敛': 'convergence',
    '发散': 'divergence',
    '稳定': 'stable',
    '平衡': 'balanced',
    '对称': 'symmetric',
    '非对称': 'asymmetric',
    '均匀': 'uniform',
    '非均匀': 'non-uniform',
    '线性': 'linear',
    '非线性': 'nonlinear',
    '凸': 'convex',
    '非凸': 'non-convex',
    '光滑': 'smooth',
    '连续': 'continuous',
    '离散': 'discrete',
    '有限': 'finite',
    '无限': 'infinite',
    '局部': 'local',
    '全局': 'global',
    '上界': 'Upper Bound',
    '下界': 'Lower Bound',
    '紧界': 'Tight Bound',
    '速率': 'rate',
    '效率': 'efficiency',
    '质量': 'quality',
    '数量': 'quantity',
    '大小': 'size',
    '维度': 'dimension',
    '尺度': 'scale',
    '顺序': 'order',
    '排序': 'ordering',
    '最大': 'maximum',
    '最小': 'minimum',
    '最优': 'optimal',
    '次优': 'suboptimal',
    '有效': 'effective',
    '无效': 'ineffective',
    '可行': 'feasible',
    '不可行': 'infeasible',
    '可计算': 'computable',
    '不可计算': 'uncomputable',
    '可观测': 'observable',
    '未观测': 'unobserved',
    '已知': 'known',
    '未知': 'unknown',
    '确定': 'deterministic',
    '随机': 'random',
    '噪声': 'noise',
    '干净': 'clean',
    '清洁': 'clean',
    '困难': 'hard',
    '简单': 'easy',
    '真实': 'true',
    '虚假': 'false',
    '正确': 'correct',
    '错误': 'incorrect',
    '准确': 'accurate',
    '精确': 'exact',
    '近似': 'approximate',
    '严格': 'rigorous',
    '宽松': 'loose',
    '保守': 'conservative',
    '激进': 'aggressive',
    '安全': 'safe',
    '危险': 'dangerous',
    '高': 'high',
    '低': 'low',
    '大': 'large',
    '小': 'small',
    '多': 'many',
    '少': 'few',
    '快': 'fast',
    '慢': 'slow',
    '好': 'good',
    '坏': 'bad',
    '新': 'new',
    '旧': 'old',
    '强': 'strong',
    '弱': 'weak',
    '首次': 'first',
    '最后': 'last',
    '现在': 'now',
    '之前': 'before',
    '之后': 'after',
    '同时': 'simultaneously',
    '已经': 'already',
    '尚未': 'not yet',
    '仍然': 'still',
    '总是': 'always',
    '从不': 'never',
    '经常': 'often',
    '很少': 'rarely',
    '至少': 'at least',
    '至多': 'at most',
    '超过': 'exceed',
    '低于': 'below',
    '等于': 'equal',
    '不等于': 'not equal',
    '大于': 'greater than',
    '小于': 'less than',
    '之间': 'between',
    '之内': 'within',
    '之外': 'outside',
    '除了': 'except',
    '包括': 'including',
    '不包括': 'excluding',
    '关于': 'regarding',
    '对于': 'for',
    '针对': 'targeting',
    '基于': 'based on',
    '通过': 'through',
    '根据': 'according to',
    '按照': 'following',
    '随着': 'as',
    '随着时间': 'over time',
    '在这种情况下': 'in this case',
    '一般来说': 'generally speaking',
    '换句话说': 'in other words',
    '也就是说': 'that is to say',
    '这意味着': 'this means',
    '这表明': 'this indicates',
    '这导致': 'this leads to',
    '这保证': 'this guarantees',
    '这要求': 'this requires',
    '这允许': 'this allows',
    '这防止': 'this prevents',
    '这解释': 'this explains',
    '这反映': 'this reflects',
    '这暗示': 'this suggests',
    '这与': 'this is',
    '一致': 'consistent with',
    '不一致': 'inconsistent',
    '矛盾': 'contradicts',
    '对应': 'corresponds',
    '相当于': 'equivalent to',
    '不同于': 'different from',
    '类似于': 'similar to',
    '优于': 'superior to',
    '劣于': 'inferior to',
    '依赖于': 'depends on',
    '基于': 'based on',
    # Common punctuation/phrases
    '。': '.',
    '，': ', ',
    '：': ': ',
    '；': '; ',
    '？': '?',
    '！': '!',
    '、': ', ',
    '------': ' --- ',
    '----': ' -- ',
    # Remove empty quotes
    '「': '"',
    '」': '"',
    '『': '"',
    '』': '"',
    '（': ' (',
    '）': ') ',
    '【': '[',
    '】': '] ',
    '《': '"',
    '》': '"',
    # Additional common two-char
    '没有': 'without',
    '不是': 'is not',
    '不会': 'will not',
    '不能': 'cannot',
    '不可': 'not',
    '不足': 'insufficient',
    '不够': 'insufficient',
    '不变': 'unchanged',
    '不再': 'no longer',
    '不仅': 'not only',
    '不论': 'regardless',
    '不如': 'inferior to',
    '不同': 'different',
    '不行': 'not feasible',
    '不许': 'not allowed',
    '不要': 'do not',
    '不该': 'should not',
    '超过': 'exceeds',
    '超出': 'beyond',
    '充分': 'sufficient',
    '充足': 'adequate',
    '充满': 'full of',
    '除非': 'unless',
    '处理': 'handle',
    '处于': 'in',
    '存在': 'exists',
    '达到': 'achieve',
    '打破': 'break',
    '打开': 'open',
    '代表': 'represent',
    '代替': 'replace',
    '但是': 'but',
    '导致': 'lead to',
    '得到': 'obtain',
    '等待': 'wait',
    '等于': 'equals',
    '抵消': 'cancel',
    '定义': 'define',
    '度量': 'metric',
    '对于': 'for',
    '对应': 'correspond',
    '而非': 'rather than',
    '发生': 'occur',
    '发现': 'discover',
    '发展': 'develop',
    '反对': 'oppose',
    '反映': 'reflect',
    '方法': 'method',
    '方面': 'aspect',
    '方式': 'way',
    '方向': 'direction',
    '防止': 'prevent',
    '放大': 'amplify',
    '放弃': 'abandon',
    '非常': 'very',
    '分布': 'distribution',
    '分解': 'decomposition',
    '分类': 'classification',
    '分析': 'analysis',
    '否则': 'otherwise',
    '符合': 'consistent with',
    '复杂': 'complex',
    '改变': 'change',
    '改进': 'improve',
    '概括': 'summarize',
    '概念': 'concept',
    '干扰': 'interfere',
    '感到': 'feel',
    '感谢': 'thank',
    '刚刚': 'just',
    '高度': 'highly',
    '告诉': 'tell',
    '根据': 'according to',
    '更加': 'more',
    '更新': 'update',
    '工作': 'work',
    '功能': 'function',
    '贡献': 'contribution',
    '构造': 'construct',
    '估计': 'estimate',
    '鼓励': 'encourage',
    '固定': 'fixed',
    '关键': 'key',
    '关系': 'relationship',
    '关于': 'regarding',
    '观察': 'observe',
    '观点': 'viewpoint',
    '管理': 'manage',
    '过程': 'process',
    '还是': 'or',
    '含义': 'meaning',
    '合理': 'reasonable',
    '合适': 'suitable',
    '合作': 'collaborate',
    '很多': 'many',
    '很少': 'few',
    '后来': 'later',
    '后续': 'subsequent',
    '忽略': 'ignore',
    '互相': 'mutually',
    '划分': 'partition',
    '环境': 'environment',
    '回答': 'answer',
    '回归': 'regression',
    '获得': 'obtain',
    '基本': 'basic',
    '基础': 'foundation',
    '基于': 'based on',
    '极大': 'extremely',
    '极其': 'extremely',
    '集合': 'set',
    '几乎': 'almost',
    '计算': 'compute',
    '记录': 'record',
    '技术': 'technique',
    '继续': 'continue',
    '加快': 'accelerate',
    '加入': 'join',
    '假设': 'assumption',
    '价值': 'value',
    '简单': 'simple',
    '简化': 'simplify',
    '建立': 'establish',
    '建议': 'suggest',
    '降低': 'reduce',
    '交流': 'communicate',
    '接近': 'approach',
    '接受': 'accept',
    '结果': 'result',
    '结束': 'end',
    '结论': 'conclusion',
    '解决': 'solve',
    '解释': 'explain',
    '介绍': 'introduce',
    '进行': 'conduct',
    '经过': 'after',
    '经验': 'experience',
    '精确': 'precise',
    '具有': 'possess',
    '决定': 'determine',
    '绝对': 'absolute',
    '均方': 'mean square',
    '开发': 'develop',
    '开始': 'start',
    '考虑': 'consider',
    '可能': 'possible',
    '可以': 'can',
    '肯定': 'certainly',
    '控制': 'control',
    '困难': 'difficult',
    '扩大': 'expand',
    '来自': 'from',
    '类型': 'type',
    '理解': 'understand',
    '理论': 'theory',
    '理想': 'ideal',
    '理由': 'reason',
    '利用': 'utilize',
    '例子': 'example',
    '连接': 'connect',
    '连续': 'continuous',
    '联合': 'joint',
    '联系': 'connection',
    '两者': 'both',
    '另外': 'additionally',
    '另一种': 'another',
    '满足': 'satisfy',
    '没有': 'without',
    '每个': 'each',
    '描述': 'describe',
    '明显': 'obvious',
    '命令': 'command',
    '某处': 'somewhere',
    '目标': 'goal',
    '目前': 'currently',
    '哪些': 'which',
    '内部': 'internal',
    '内容': 'content',
    '能够': 'can',
    '能力': 'ability',
    '能量': 'energy',
    '判断': 'judge',
    '配置': 'configuration',
    '匹配': 'match',
    '偏差': 'bias',
    '偏离': 'deviate',
    '平衡': 'balance',
    '平均': 'average',
    '评估': 'evaluate',
    '评论': 'comment',
    '破坏': 'break',
    '普遍': 'general',
    '期望': 'expectation',
    '其他': 'other',
    '其中': 'where',
    '奇怪': 'strange',
    '启动': 'start',
    '前面': 'earlier',
    '强烈': 'strongly',
    '情况': 'situation',
    '求解': 'solve',
    '区别': 'distinguish',
    '趋势': 'trend',
    '全部': 'all',
    '确保': 'ensure',
    '确定': 'determine',
    '确认': 'confirm',
    '然后': 'then',
    '然而': 'however',
    '认为': 'consider',
    '任何': 'any',
    '任务': 'task',
    '仍然': 'still',
    '容易': 'easy',
    '如果': 'if',
    '如何': 'how',
    '如今': 'nowadays',
    '若干': 'several',
    '删除': 'delete',
    '设计': 'design',
    '设置': 'set',
    '涉及': 'involve',
    '生成': 'generate',
    '声明': 'declare',
    '省略': 'omit',
    '失败': 'fail',
    '失去': 'lose',
    '时间': 'time',
    '实际': 'actual',
    '实践': 'practice',
    '实现': 'implement',
    '实验': 'experiment',
    '使得': 'such that',
    '使用': 'use',
    '示例': 'example',
    '事件': 'event',
    '事实': 'fact',
    '是否': 'whether',
    '适合': 'suitable',
    '适用': 'applicable',
    '收到': 'receive',
    '受到': 'subject to',
    '输出': 'output',
    '输入': 'input',
    '属于': 'belong to',
    '数据': 'data',
    '数量': 'quantity',
    '数学': 'mathematics',
    '数值': 'numerical',
    '双重': 'dual',
    '水平': 'level',
    '顺序': 'order',
    '说明': 'explain',
    '思考': 'think',
    '似乎': 'seems',
    '搜索': 'search',
    '虽然': 'although',
    '随着': 'as',
    '损失': 'loss',
    '所有': 'all',
    '它们': 'they',
    '他方': 'other',
    '讨论': 'discuss',
    '特别': 'especially',
    '特点': 'characteristic',
    '特殊': 'special',
    '特征': 'feature',
    '提出': 'propose',
    '提供': 'provide',
    '提升': 'improve',
    '提醒': 'remind',
    '题目': 'title',
    '替换': 'replace',
    '条件': 'condition',
    '通过': 'through',
    '通常': 'usually',
    '同时': 'simultaneously',
    '同样': 'similarly',
    '同意': 'agree',
    '统一': 'unify',
    '统计': 'statistical',
    '投入': 'invest',
    '图像': 'image',
    '推广': 'generalize',
    '推理': 'inference',
    '推论': 'corollary',
    '退化': 'degenerate',
    '外部': 'external',
    '完成': 'complete',
    '完全': 'completely',
    '完整': 'complete',
    '网络': 'network',
    '往往': 'often',
    '忘记': 'forget',
    '危险': 'dangerous',
    '唯一': 'unique',
    '维护': 'maintain',
    '未来': 'future',
    '位置': 'location',
    '为了': 'in order to',
    '为什么': 'why',
    '问题': 'problem',
    '我们': 'we',
    '无法': 'cannot',
    '无论': 'regardless',
    '系统': 'system',
    '细节': 'detail',
    '下降': 'decrease',
    '下面': 'below',
    '显示': 'show',
    '显著': 'significant',
    '限制': 'restrict',
    '线性': 'linear',
    '相比': 'compared to',
    '相当': 'quite',
    '相反': 'on the contrary',
    '相关': 'related',
    '相互': 'mutual',
    '相似': 'similar',
    '相同': 'identical',
    '详细': 'detailed',
    '响应': 'response',
    '想要': 'want',
    '项目': 'project',
    '像': 'like',
    '消除': 'eliminate',
    '消耗': 'consume',
    '消息': 'message',
    '效果': 'effect',
    '效率': 'efficiency',
    '新的': 'new',
    '信号': 'signal',
    '信息': 'information',
    '形成': 'form',
    '形式': 'form',
    '性能': 'performance',
    '性质': 'property',
    '修改': 'modify',
    '需求': 'requirement',
    '需要': 'need',
    '许多': 'many',
    '序列': 'sequence',
    '选择': 'choose',
    '学习': 'learn',
    '训练': 'train',
    '压力': 'pressure',
    '严重': 'severe',
    '研究': 'research',
    '演化': 'evolve',
    '验证': 'verify',
    '样本': 'sample',
    '要求': 'require',
    '要么': 'either',
    '一般': 'general',
    '一次': 'once',
    '一定': 'certainly',
    '一个': 'one',
    '一类': 'one type',
    '一切': 'all',
    '一些': 'some',
    '一样': 'same',
    '一种': 'a kind of',
    '一致': 'consistent',
    '依然': 'still',
    '移动': 'move',
    '已经': 'already',
    '以及': 'and',
    '以来': 'since',
    '以前': 'before',
    '以上': 'above',
    '以下': 'following',
    '以为': 'think',
    '因此': 'therefore',
    '因素': 'factor',
    '因为': 'because',
    '引入': 'introduce',
    '隐藏': 'hidden',
    '应当': 'should',
    '应该': 'should',
    '应用': 'apply',
    '影响': 'affect',
    '永远': 'forever',
    '用于': 'used for',
    '优点': 'advantage',
    '优先': 'priority',
    '尤其': 'especially',
    '由于': 'due to',
    '有关': 'related',
    '有时': 'sometimes',
    '有效': 'effective',
    '有些': 'some',
    '有用': 'useful',
    '右边': 'right',
    '预测': 'predict',
    '预期': 'expect',
    '遇到': 'encounter',
    '原本': 'originally',
    '原理': 'principle',
    '原因': 'reason',
    '允许': 'allow',
    '运动': 'motion',
    '运算': 'operation',
    '运行': 'run',
    '再次': 'again',
    '在于': 'lies in',
    '暂时': 'temporarily',
    '早期': 'early',
    '增加': 'increase',
    '增长': 'growth',
    '展示': 'demonstrate',
    '找到': 'find',
    '真实': 'real',
    '真正': 'truly',
    '整个': 'entire',
    '整理': 'organize',
    '正常': 'normal',
    '正确': 'correct',
    '正式': 'formal',
    '正在': 'currently',
    '证据': 'evidence',
    '证明': 'proof',
    '支持': 'support',
    '知道': 'know',
    '知识': 'knowledge',
    '执行': 'execute',
    '直接': 'directly',
    '值得': 'worth',
    '指出': 'point out',
    '指导': 'guide',
    '至今': 'so far',
    '至少': 'at least',
    '制定': 'formulate',
    '制造': 'produce',
    '质量': 'quality',
    '智能': 'intelligence',
    '滞后': 'lag',
    '中间': 'middle',
    '中心': 'center',
    '种类': 'type',
    '重要': 'important',
    '周期': 'period',
    '逐渐': 'gradually',
    '主动': 'active',
    '主要': 'main',
    '注意': 'note',
    '专门': 'specialized',
    '状态': 'state',
    '准确': 'accurate',
    '准则': 'criterion',
    '资料': 'material',
    '资源': 'resource',
    '自动': 'automatic',
    '自己': 'self',
    '自然': 'natural',
    '自我': 'self',
    '自由': 'free',
    '综合': 'comprehensive',
    '总结': 'summary',
    '总是': 'always',
    '总体': 'overall',
    '足够': 'sufficient',
    '最大': 'maximum',
    '最好': 'best',
    '最后': 'last',
    '最近': 'recent',
    '最差': 'worst',
    '最初': 'initial',
    '最终': 'final',
    '左右': 'around',
    '作用': 'role',
    '做出': 'make',
    '做到': 'achieve',
    '作者': 'author',
    '研究': 'study',
    '发现': 'found',
    '表明': 'shows',
    '表现': 'performance',
    '表示': 'denote',
    '表达': 'express',
    '表格': 'table',
    '波动': 'fluctuation',
    '补充': 'supplement',
    '捕获': 'capture',
    '测量': 'measure',
    '测试': 'test',
    '策略': 'strategy',
    '产出': 'output',
    '产生': 'produce',
    '场景': 'scenario',
    '称为': 'called',
    '成为': 'becomes',
    '成长': 'growth',
    '程度': 'degree',
    '惩罚': 'penalty',
    '持续': 'continuous',
    '尺度': 'scale',
    '充分': 'sufficient',
    '充满': 'full of',
    '重复': 'repeat',
    '重新': 're-',
    '抽象': 'abstract',
    '出现': 'appear',
    '初始': 'initial',
    '除了': 'except',
    '处理': 'process',
    '传递': 'transfer',
    '传统': 'traditional',
    '创新': 'innovation',
    '创造': 'create',
    '纯粹': 'pure',
    '从而': 'thereby',
    '存在': 'exist',
    '错误': 'error',
    '达成': 'achieve',
    '达到': 'reach',
    '大量': 'large amount',
    '代替': 'replace',
    '带来': 'bring',
    '单位': 'unit',
    '但是': 'but',
    '导致': 'lead to',
    '导向': 'guide',
    '得到': 'obtain',
    '等待': 'wait',
    '等于': 'equal',
    '抵消': 'cancel',
    '地点': 'location',
    '地位': 'position',
    '第二': 'second',
    '第三': 'third',
    '第一': 'first',
    '典型': 'typical',
    '调查': 'investigate',
    '调整': 'adjust',
    '迭代': 'iteration',
    '定义': 'definition',
    '独立': 'independent',
    '度量': 'metric',
    '断裂': 'fracture',
    '对比': 'contrast',
    '对称': 'symmetric',
    '对话': 'dialogue',
    '对于': 'for',
    '对应': 'correspond',
    '多种': 'multiple',
    '额外': 'additional',
    '恶劣': 'bad',
    '发挥': 'exert',
    '发现': 'discover',
    '发展': 'develop',
    '法则': 'law',
    '翻译': 'translate',
    '反馈': 'feedback',
    '反应': 'reaction',
    '范围': 'range',
    '方案': 'scheme',
    '方法': 'method',
    '方面': 'aspect',
    '方式': 'manner',
    '放弃': 'abandon',
    '放置': 'place',
    '非常': 'very',
    '分布': 'distribution',
    '分割': 'partition',
    '分解': 'decompose',
    '分类': 'classification',
    '分配': 'assign',
    '分析': 'analysis',
    '份额': 'share',
    '风险': 'risk',
    '否定': 'deny',
    '幅度': 'magnitude',
    '符合': 'consistent with',
    '辅助': 'auxiliary',
    '复杂': 'complex',
    '覆盖': 'cover',
    '概率': 'probability',
    '概念': 'concept',
    '改善': 'improve',
    '感觉': 'feel',
    '高度': 'highly',
    '各个': 'each',
    '根本': 'fundamental',
    '更紧': 'tighter',
    '更加': 'more',
    '更新': 'update',
    '构造': 'construct',
    '估计': 'estimate',
    '固定': 'fixed',
    '观察': 'observation',
    '观点': 'view',
    '管理': 'manage',
    '广泛': 'widely',
    '归纳': 'induction',
    '过程': 'process',
    '过度': 'excessive',
    '过去': 'past',
    '含义': 'meaning',
    '合作': 'collaborate',
    '核心': 'core',
    '衡量': 'measure',
    '忽略': 'ignore',
    '互动': 'interact',
    '划分': 'partition',
    '话题': 'topic',
    '环境': 'environment',
    '缓慢': 'slow',
    '回答': 'answer',
    '混合': 'mixture',
    '活动': 'activity',
    '获得': 'obtain',
    '机会': 'opportunity',
    '机制': 'mechanism',
    '积极': 'active',
    '基本': 'basic',
    '基础': 'foundation',
    '基因': 'gene',
    '基于': 'based on',
    '极端': 'extreme',
    '极限': 'limit',
    '集合': 'set',
    '几乎': 'almost',
    '技术': 'technique',
    '计划': 'plan',
    '计算': 'computation',
    '记录': 'record',
    '技能': 'skill',
    '继续': 'continue',
    '加速': 'accelerate',
    '加入': 'join',
    '假设': 'assumption',
    '价值': 'value',
    '坚持': 'insist',
    '间接': 'indirect',
    '兼容': 'compatible',
    '检测': 'detection',
    '简单': 'simple',
    '简化': 'simplify',
    '建立': 'establish',
    '建议': 'suggestion',
    '建筑': 'architecture',
    '健康': 'health',
    '将来': 'future',
    '降低': 'reduce',
    '交叉': 'cross',
    '交流': 'communicate',
    '交易': 'transaction',
    '角色': 'role',
    '教育': 'education',
    '接近': 'approach',
    '接受': 'accept',
    '结构': 'structure',
    '结果': 'result',
    '结合': 'combine',
    '结论': 'conclusion',
    '结束': 'end',
    '解决': 'solve',
    '解释': 'explain',
    '介绍': 'introduce',
    '进行': 'proceed',
    '经常': 'often',
    '经典': 'classical',
    '经历': 'experience',
    '经验': 'experience',
    '精确': 'precise',
    '竞争': 'compete',
    '具有': 'have',
    '决定': 'decide',
    '绝对': 'absolute',
    '开发': 'develop',
    '开放': 'open',
    '开始': 'begin',
    '科学': 'science',
    '可能': 'possible',
    '可以': 'can',
    '肯定': 'certain',
    '空间': 'space',
    '控制': 'control',
    '框架': 'framework',
    '困难': 'difficult',
    '扩展': 'extend',
    '来源': 'source',
    '劳动': 'labor',
    '理解': 'understand',
    '理论': 'theory',
    '理想': 'ideal',
    '力量': 'strength',
    '历史': 'history',
    '利用': 'utilize',
    '例子': 'example',
    '连接': 'connect',
    '连续': 'continuous',
    '联合': 'joint',
    '联系': 'connection',
    '两者': 'both',
    '领域': 'domain',
    '流程': 'pipeline',
    '路径': 'path',
    '逻辑': 'logic',
    '满足': 'satisfy',
    '没有': 'without',
    '每个': 'each',
    '描述': 'describe',
    '明确': 'explicit',
    '模式': 'pattern',
    '目标': 'goal',
    '某些': 'certain',
    '目前': 'currently',
    '难以': 'difficult to',
    '能力': 'ability',
    '评估': 'evaluate',
    '破坏': 'break',
    '普遍': 'general',
    '启动': 'launch',
    '起源': 'origin',
    '强化': 'strengthen',
    '情况': 'situation',
    '区域': 'region',
    '趋势': 'trend',
    '全部': 'all',
    '全球': 'global',
    '确认': 'confirm',
    '然后': 'then',
    '然而': 'however',
    '任务': 'task',
    '仍然': 'still',
    '容易': 'easy',
    '融合': 'fuse',
    '如果': 'if',
    '如何': 'how',
    '若干': 'several',
    '筛选': 'filter',
    '删除': 'delete',
    '设计': 'design',
    '社会': 'society',
    '涉及': 'involve',
    '深度': 'depth',
    '生成': 'generate',
    '声明': 'declare',
    '省略': 'omit',
    '失败': 'fail',
    '时间': 'time',
    '实际': 'actual',
    '实践': 'practice',
    '实现': 'implement',
    '实验': 'experiment',
    '使得': 'such that',
    '使用': 'use',
    '示例': 'example',
    '事件': 'event',
    '事实': 'fact',
    '事物': 'thing',
    '是否': 'whether',
    '适用': 'applicable',
    '收到': 'receive',
    '受到': 'subject to',
    '输出': 'output',
    '输入': 'input',
    '熟悉': 'familiar',
    '属于': 'belong to',
    '数据': 'data',
    '数量': 'quantity',
    '数学': 'mathematical',
    '数值': 'numerical',
    '水平': 'level',
    '顺序': 'order',
    '说明': 'explain',
    '思想': 'thought',
    '速度': 'speed',
    '虽然': 'although',
    '随着': 'as',
    '损失': 'loss',
    '缩短': 'shorten',
    '所有': 'all',
    '它们': 'they',
    '讨论': 'discuss',
    '特别': 'especially',
    '特点': 'characteristic',
    '特殊': 'special',
    '特征': 'feature',
    '提出': 'propose',
    '提供': 'provide',
    '提升': 'improve',
    '体系': 'system',
    '体验': 'experience',
    '替换': 'replace',
    '条件': 'condition',
    '停止': 'stop',
    '通过': 'through',
    '通常': 'usually',
    '同时': 'simultaneously',
    '同样': 'similarly',
    '同意': 'agree',
    '统一': 'unify',
    '统计': 'statistical',
    '投入': 'invest',
    '投资': 'invest',
    '突破': 'breakthrough',
    '推广': 'generalize',
    '推荐': 'recommend',
    '推论': 'corollary',
    '退化': 'degenerate',
    '完成': 'complete',
    '完全': 'completely',
    '完整': 'complete',
    '网络': 'network',
    '往往': 'often',
    '忘记': 'forget',
    '危险': 'dangerous',
    '唯一': 'unique',
    '维持': 'maintain',
    '未来': 'future',
    '位置': 'location',
    '我们': 'we',
    '物理': 'physical',
    '物质': 'matter',
    '吸收': 'absorb',
    '希望': 'hope',
    '系统': 'system',
    '细节': 'detail',
    '下降': 'decrease',
    '下面': 'below',
    '显示': 'show',
    '显著': 'significant',
    '限制': 'restrict',
    '线性': 'linear',
    '相当': 'quite',
    '相关': 'related',
    '相互': 'mutual',
    '相似': 'similar',
    '相同': 'identical',
    '相信': 'believe',
    '详细': 'detailed',
    '响应': 'response',
    '想要': 'want',
    '项目': 'project',
    '消除': 'eliminate',
    '消耗': 'consume',
    '消息': 'message',
    '小组': 'group',
    '效果': 'effect',
    '效率': 'efficiency',
    '协议': 'protocol',
    '新的': 'new',
    '信号': 'signal',
    '信息': 'information',
    '信心': 'confidence',
    '形成': 'form',
    '形式': 'form',
    '性能': 'performance',
    '性质': 'property',
    '修改': 'modify',
    '需要': 'need',
    '许多': 'many',
    '宣布': 'announce',
    '选择': 'select',
    '学习': 'learn',
    '训练': 'train',
    '研究': 'research',
    '验证': 'verify',
    '样本': 'sample',
    '要求': 'require',
    '一次': 'once',
    '一定': 'certainly',
    '一共': 'in total',
    '一类': 'a type of',
    '一切': 'all',
    '一些': 'some',
    '一样': 'same',
    '一种': 'a kind of',
    '一致': 'consistent',
    '移动': 'move',
    '已经': 'already',
    '以及': 'and',
    '以来': 'since',
    '以前': 'previously',
    '以上': 'above',
    '以下': 'below',
    '以为': 'assume',
    '因此': 'therefore',
    '因为': 'because',
    '引入': 'introduce',
    '隐藏': 'hidden',
    '应当': 'should',
    '应该': 'should',
    '应用': 'apply',
    '影响': 'affect',
    '永远': 'forever',
    '用于': 'used for',
    '优化': 'optimize',
    '优势': 'advantage',
    '优先': 'priority',
    '尤其': 'especially',
    '由于': 'due to',
    '有关': 'related',
    '有效': 'effective',
    '有用': 'useful',
    '预测': 'predict',
    '预期': 'expect',
    '遇到': 'encounter',
    '原本': 'originally',
    '原理': 'principle',
    '原因': 'reason',
    '允许': 'allow',
    '运行': 'run',
    '再次': 'again',
    '在于': 'lies in',
    '增加': 'increase',
    '展示': 'demonstrate',
    '找到': 'find',
    '真实': 'real',
    '真正': 'truly',
    '整个': 'entire',
    '整体': 'overall',
    '正常': 'normal',
    '正确': 'correct',
    '正式': 'formal',
    '证明': 'proof',
    '支持': 'support',
    '知道': 'know',
    '知识': 'knowledge',
    '执行': 'execute',
    '直接': 'directly',
    '值得': 'worth',
    '指出': 'point out',
    '指导': 'guide',
    '至今': 'so far',
    '至少': 'at least',
    '制造': 'produce',
    '质量': 'quality',
    '滞后': 'lag',
    '中心': 'center',
    '重要': 'important',
    '逐渐': 'gradually',
    '主动': 'active',
    '主要': 'main',
    '注意': 'note',
    '状态': 'state',
    '准确': 'accurate',
    '准则': 'criterion',
    '资源': 'resource',
    '自动': 'automatically',
    '自己': 'itself',
    '自然': 'natural',
    '自我': 'self',
    '自由': 'free',
    '综合': 'synthesize',
    '总结': 'summary',
    '总是': 'always',
    '总体': 'overall',
    '足够': 'sufficient',
    '最大': 'maximum',
    '最好': 'best',
    '最后': 'last',
    '最近': 'recent',
    '最差': 'worst',
    '最初': 'initial',
    '最终': 'final',
    '作用': 'role',
    '做出': 'make',
    '做到': 'achieve',
    '作者': 'author',
    '选择': 'choose',
    '差异': 'difference',
    '判定': 'assessment',
    '编号': 'number',
    '标签': 'label',
    '层面': 'aspect',
    '建议': 'recommendation',
    '通过': 'pass',
    '说明': 'description',
}
