#!/usr/bin/env python3
"""Step 2: Translate theory/theorems/README.tex and theory/self_evolution/README.tex"""
import re, os
BASE = r"F:\scx"

def replace_all(path, mapping):
    with open(path, 'r', encoding='utf-8') as f:
        c = f.read()
    for cn, en in sorted(mapping.items(), key=lambda x: -len(x[0])):
        if cn in c:
            c = c.replace(cn, en)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(c)
    rem = len(re.findall(r'[\u4e00-\u9fff]+', c))
    return rem

# File: theory/theorems/README.tex
r = replace_all(os.path.join(BASE, 'theory/theorems/README.tex'), {
    '本目录存放': 'This directory contains',
    '框架的核心定理：': ' the core theorems of the SCX framework:',
    '多专家一致性噪声检测保证': 'Multi-Expert Consistency Noise Detection Guarantee',
    '弱特征失效下界': 'Weak Feature Failure Lower Bound',
    '噪声与可学习困难的不可识别性': 'Unidentifiability of Noise vs. Learnable Difficulty',
    '三个定理的逻辑闭环': 'Logical Closure of the Three Theorems',
    '正命题': 'Positive Statement',
    '能检测噪声': ' SCX can detect noise',
    '边界命题': 'Boundary Statement',
    '当特征弱时': ' When features are weak, ',
    '退化为损失基线': ' SCX degenerates to the loss baseline',
    '必要性命题': 'Necessity Statement',
    '噪声与困难根本不可区分': ' noise and difficulty are fundamentally indistinguishable',
    '非任意假设': ' A1-A6 are not arbitrary assumptions',
    '而是打破不可识别性的最小条件': ' but rather the minimal conditions that break unidentifiability',
    '完整': 'Complete',
    '文件': 'File',
    '内容': 'Content',
    '状态': 'Status',
})
print(f"theorems/README.tex: {r} remaining")

# File: theory/self_evolution/README.tex
r = replace_all(os.path.join(BASE, 'theory/self_evolution/README.tex'), {
    '自我进化理论': 'Self-Evolution Theory',
    '数学形式化': 'Mathematical Formalization',
    '最后更新': 'Last Updated',
    '问题': 'Problem',
    '核心问题': 'Core Problem',
    '困难': 'Difficulty',
    '核心洞察': 'Core Insight',
    '九个核心文件': 'Nine Core Files',
    '核心结果': 'Core Result',
    '核心定理': 'Core Theorems',
    '四种收敛路径': 'Four Convergence Paths',
    '路径': 'Path',
    '特征': 'Characteristics',
    '条件': 'Conditions',
    '经典收敛': 'Classical Convergence',
    '单调改进': ' monotonic improvement',
    '全部满足，充分退火': ' all satisfied, sufficient annealing',
    '极限环': 'Limit Cycle',
    '系统在有限配置间周期振荡': ' system oscillates periodically among finite configurations',
    '退火不充分，耦合过强': ' insufficient annealing, excessive coupling',
    '永动发现': 'Perpetual Discovery',
    '新结构持续发现，': ' new structures continuously discovered, ',
    '无限增长': ' grows without bound',
    '开放物理世界，无限探索预算': ' open physical world, unlimited exploration budget',
    '发散崩溃': 'Divergent Collapse',
    '退化，质量下降': ' degenerates, quality declines',
    '反馈回路断裂，': ' feedback loop breaks, ',
    '反馈噪声过大': ' feedback noise excessive',
    '的精确分界条件是': 'The precise boundary conditions are',
    '开放问题': 'open problems',
    '见': ' see ',
    '与现有理论体系的关系': 'Relationship with Existing Theoretical Frameworks',
    '从属关系': 'Subordination Relationships',
    '提供自进化必要性论证': ' provides the necessity argument for self-evolution',
    '自进化闭环必须存在': ' the self-evolution closed loop must exist',
    '初始化提供保证': ' provides initialization guarantees',
    '的初始条件': ' initial conditions',
    '中心结果': ' central result',
    '闭环渐近收敛到自洽点': ' closed loop converges asymptotically to a self-consistent point',
    '弱特征界': ' Weak Feature Bound',
    '限制改进速度': ' limits improvement speed',
    '最小最大最优': ' Minimax Optimality',
    '提供的渐近最优性': ' provides asymptotic optimality',
    '完备性界': ' Completeness Bound',
    '物理有限性强制有限时间收敛': ' physical finiteness enforces finite-time convergence',
    '新引入假设': 'Newly Introduced Assumptions',
    '至': ' to ',
    '新引入，核心假设': ' Newly introduced, core assumption',
    '物理约束（非统计学假设）': ' Physical constraint (non-statistical assumption)',
    '平滑性假设': ' Smoothness assumption',
    '的扩展': ' extension',
    '标准': ' Standard ',
    '退火条件': ' Annealing condition',
    '与已知理论的连接摘要': 'Summary of Connections to Known Theories',
    '理论框架': 'Theoretical Framework',
    '核心机制': 'Core Mechanism',
    '自进化的关键差异': 'Key Differences from SCX Self-Evolution',
    '生成合成游戏；': ' generates synthetic games; ',
    '依赖真实': ' relies on real ',
    '数据': ' data',
    '优化静态黑箱；': ' optimizes static black box; ',
    '的目标分布在演化': ' target distribution evolves',
    '即时反馈；': ' immediate oracle feedback; ',
    '延迟反馈': ' delayed feedback',
    '不可计算；': ' uncomputable; ',
    '限制在有限假设类': ' restricted to finite hypothesis class',
    '详见': 'See ',
    '完整对比表。': ' for the complete comparison table.',
    '理论状态评估': 'Theoretical Status Assessment',
    '类别': 'Category',
    '比例': 'Proportion',
    '说明': 'Description',
    '严格理论': 'Rigorous Theory',
    '的有限状态版本': ' finite-state version',
    '贝叶斯鞅收敛': ' Bayesian martingale convergence',
    '标准收敛': ' standard convergence',
    '上界': ' upper bound',
    '形式化猜想': 'Formalized Conjectures',
    '连续状态空间扩展': ' continuous state-space extension',
    '双时间尺度收敛': ' two-timescale convergence',
    '收缩率': ' contraction rate',
    '合理假设': 'Reasonable Assumptions',
    '精确': 'Exact ',
    '函数形式': ' function form',
    '极限环条件': ' limit cycle conditions',
    '类比': ' analogy',
    '最优退火策略': ' optimal annealing strategy',
    '优先级排序': 'Priority Ordering',
    '优先级': 'Priority',
    '明确的': 'Explicit ',
    '的定义与下降证明': ' definition and descent proof',
    '四种收敛路径的精确定界': 'Precise bounding of the four convergence paths',
    '耦合': ' coupled ',
    '系统的紧收敛率': ' system tight convergence rate',
    '最优': 'Optimal ',
    '更新频率': ' update frequency',
    '收敛所需的最小记忆库大小': 'Minimum memory bank size for convergence',
    '非渐近（有限时间）保证': 'Non-asymptotic (finite-time) guarantees',
    '分布偏移下的鲁棒性刻画': 'Robustness under distribution shift',
    '的严格化': ' rigorization',
    '文件结构': 'File Structure',
    '本文件': 'This file',
    '符号系统与问题设定': 'Symbol System and Problem Setup',
    '离散动力系统形式化': 'Discrete Dynamical System Formalization',
    '在线学习': 'Online Learning',
    '分析': ' Analysis',
    '贝叶斯更新解释': 'Bayesian Update Interpretation',
    '随机逼近分析': 'Stochastic Approximation Analysis',
    '不动点与收敛定理（中心）': 'Fixed Point and Convergence Theorem (Center)',
    '完备性分析': 'Completeness Analysis',
    '与已知理论的连接': 'Connections to Known Theories',
    '验证报告': 'Verification Report',
    '跨领域适用': 'Cross-Domain Applicability',
    '领域': 'Domain',
    '角色': 'Role',
    '判断': 'Judge ',
    '标签正确性': ' label correctness',
    '势能面模型': ' potential energy surface model',
    '累积的': 'Accumulated ',
    '计算轨迹': ' computation trajectories',
    '医学图像': 'Medical Imaging',
    '判断诊断标签质量': ' judge diagnostic label quality',
    '辅助诊断模型': ' auxiliary diagnostic model',
    '累积的专家复核记录': ' accumulated expert review records',
    '自动驾驶': 'Autonomous Driving',
    '判断检测框': ' judge detection box',
    '标注质量': ' annotation quality',
    '感知模型': ' perception model',
    '累积的路测验证数据': ' accumulated road-test validation data',
    '判断标注': ' judge annotation',
    '生成质量': ' generation quality',
    '下游任务模型': ' downstream task model',
    '累积的人工审核日志': ' accumulated human review logs',
    '参考文献（新增）': 'References (Newly Added)',
    '学生': ' student ',
    '构成耦合动力系统': ' form a coupled dynamical system',
    '的选择决定了': ' determines ',
    '的训练分布，而': ' the training distribution, and ',
    '的输出提供反馈给': ' output provides feedback to ',
    # specific long phrases
    '将 SCX 的自我进化闭环（judge → store → update → re-judge → re-update →': 'Formalize the SCX self-evolution closed loop (judge -> store -> update -> re-judge -> re-update ->',
    '\\ldots）形式化为严格的数学理论，并与已知理论框架建立连接。': '...) as a rigorous mathematical theory, and establish connections with known theoretical frameworks.',
    'SCX 系统在运行中形成以下闭环：': 'The SCX system forms the following closed loop during operation:',
    '：这个闭环是否收敛？收敛到何处？收敛速率如何？在何种条件下发散？': ': Does this closed loop converge? To what? At what rate? Under what conditions does it diverge?',
    'SCX 自我进化的正确数学对象是耦合动力系统 (S_t, θ_t, M_t)，': 'The correct mathematical object for SCX self-evolution is the coupled dynamical system (S_t, theta_t, M_t),',
    '其全局行为由 Lyapunov 函数 V(S, θ) 的单调下降性质主导。': 'whose global behavior is governed by the monotonic descent property of the Lyapunov function V(S, theta).',
    'Gatekeeper': 'Gatekeeper',
    # Table headers  
    '文件': 'File',
    '内容': 'Content',
    '状态': 'Status',
})
print(f"self_evolution/README.tex: {r} remaining")
print("Step 2 complete")
