#!/usr/bin/env python3
"""Step 3: Handle situs_final_verification.tex (324 segments)"""
import re, os
BASE = r"F:\scx"

def replace_all(path, mapping):
    with open(path, 'r', encoding='utf-8') as f:
        c = f.read()
    for cn, en in sorted(mapping.items(), key=lambda x: -len(x[0])):
        if cn in c:
            c = c.replace(cn, en)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(c)
    rem = len(re.findall(r'[\u4e00-\u9fff]+', c))
    return rem

m = {
    'Situs 理论最终验证报告': 'Situs Theory Final Verification Report',
    '验证日期': 'Verification Date',
    '验证文件': 'Verification Files',
    '行': ' lines',
    '逐项检查': 'Item-by-Item Check',
    '定理': 'Theorem',
    '常数是否已修正为': 'Has the Lipschitz constant been corrected to',
    '文件': 'File',
    '位置': 'Location',
    '公式': 'Formula',
    '状态': 'Status',
    '结论': 'Conclusion',
    '两文件一致，常数已修正。归一化因子': 'Both files are consistent; constant corrected. Normalization factor',
    '已被纳入证明推导，最终': 'has been incorporated into the proof derivation; the final',
    '常数通过': 'Lipschitz constant, via',
    '的平方根求和得到系数': 'square-root summation, yields coefficient',
    '。推论': '. Corollary',
    '的渐近行为': 'asymptotic behavior of',
    '也因此从': 'has therefore been reduced from',
    '降为': 'to',
    '通过。': 'Pass.',
    '归一化因子是否已加入？': 'Has the normalization factor been added?',
    '框内公式是否已去掉': 'Has the boxed formula dropped its',
    '依赖': '-dependence',
    '依赖？': '-dependence?',
    '无': 'None',
    '定理编号是否统一为': 'Have theorem numbers been unified to',
    '指的是': 'This refers to',
    '学习型': ' learnable ',
    '破坏': ' breaking ',
    '的精确条件': ' precise conditions',
    '这个定理。': '.',
    '两文件统一使用': 'Both files uniformly use',
    '。同时命题': '. Meanwhile Proposition',
    '固定': ' fixed ',
    '保持不可区分性': ' preserves unidentifiability',
    '的编号也一致。': ' numbering is also consistent.',
    '是否修正为': 'Has d_min been corrected to',
    '推导': 'Derivation',
    '推导链完整，': 'Derivation chain complete; ',
    '条件已正确引用（覆盖整个序列区间需': 'Nyquist condition correctly cited (covering full sequence interval requires',
    '是否已降级为启发式估计？': 'Has it been downgraded to a heuristic estimate?',
    '关键变化': 'Key Change',
    '从': 'From ',
    '（下界）': ' (lower bound)',
    '（启发式估计------非严格下界）': ' (heuristic estimate --- not a rigorous lower bound)',
    '特征': 'Characteristics',
    '环境类型': 'Environment Type',
    '诚实标记': 'Honesty Label',
    '明确声明': 'Explicit Declaration',
    '此表达式': 'This expression',
    '不是': ' is NOT ',
    '严格的数学下界': ' a rigorous mathematical lower bound',
    '逻辑错误标注': 'Logical Error Annotation',
    '从两个': 'From two ',
    '下界不能逻辑地推出差的下界': ' lower bounds one cannot logically derive a lower bound on the difference',
    '等号误用说明': 'Equality Misuse Note',
    '若': 'If ',
    '不等式在两个世界均达到等号（这在一般情况下不成立）': ' inequality attains equality in both worlds (which generally does not hold)',
    '若假设': 'If one assumes the ',
    '不等式在两个世界均达到等号（需特定分布条件）': ' inequality attains equality in both worlds (requires specific distributional conditions)',
    '两文件对齐良好。': 'Both files are well-aligned.',
    '步骤': 'Step',
    '是否已限定为贝叶斯最优？': 'Has it been qualified as Bayes-optimal?',
    '层面': 'Aspect',
    '定理标题': 'Theorem Title',
    '充分条件': 'Sufficient Condition',
    '信息论形式（贝叶斯最优限定）': 'Information-Theoretic Form (Bayes-Optimal Qualified)',
    '信息论形式，贝叶斯最优限定': 'Information-Theoretic Form, Bayes-Optimal Qualified',
    '结论陈述': 'Conclusion Statement',
    '贝叶斯最优分类器': 'Bayes-optimal classifier',
    '在增广特征下的检测边际变化满足': 'under augmented features satisfies',
    '标记': 'Marked',
    '猜想': 'Conjecture',
    '局限声明': 'Limitation Statement',
    '为严格信息论推导（结论对贝叶斯最优分类器成立）': 'are rigorous information-theoretic derivations (conclusion holds for the Bayes-optimal classifier)',
    '证明了贝叶斯最优分类器可以从位置信息中受益': 'proved that the Bayes-optimal classifier can benefit from positional information',
    '退化声明': 'Degradation Statement',
    '若步骤': 'If Step',
    '的推广不成立，定理退化为经典结论------平凡的': ' generalization does not hold, the theorem degenerates to a classical result --- trivial',
    '的推广不成立，定理': ' generalization does not hold, Theorem',
    '退化为一个经典结论------平凡的': ' degenerates to a classical result --- trivial',
    '破坏方向是否已改为开放问题？': 'Has the breaking direction been changed to an open problem?',
    '陈述内': 'Within Statement',
    '若前提': 'If premise',
    '不成立': ' does not hold',
    '不可区分性是否被破坏目前是一个': 'whether unidentifiability is broken is currently an',
    '开放问题': 'Open Problem',
    '最小示例重评': 'Minimal Example Re-assessment',
    '此示例实际上证明了': 'This example actually proves',
    '的鲁棒性，而非其脆弱性': ' robustness, not its fragility',
    '此最小示例实际上证明了': 'This minimal example actually proves',
    '诚实度表': 'Honesty Table',
    '条目': 'Entry',
    '破坏方向无构造性证明': 'No constructive proof for the breaking direction',
    '前提成立时': 'holds under premises',
    '前提不成立时': 'open problem when premises do not hold',
    '原声称的': 'The originally claimed',
    '构造性示例证明破坏方向': 'constructive example proving the breaking direction',
    '已被重评为': 'has been reassessed as',
    '构造性示例反而展示了定理的鲁棒性': 'the constructive example instead demonstrates the theorem robustness',
    '符合预期。': 'as expected.',
    '两份文件之间是否还有符号不一致？': 'Are there any remaining notation inconsistencies?',
    '一致的项目': 'Consistent Items',
    '符号': 'Symbol/Concept',
    '概念': '',
    '预期差异（非问题）': 'Expected Differences (Non-Issues)',
    '差异': 'Difference',
    '原因': 'Reason',
    '判定': 'Assessment',
    '使用框架名': 'uses framework name',
    '使用缩写': 'uses abbreviation',
    '上标约定不同': 'superscript convention differs',
    '章节编号偏移': 'section number offset',
    '有': ' has ',
    '引言': 'Introduction',
    '无引言直接从编码定义开始': 'has no introduction, starts from encoding definition',
    '环境形式': 'Environment form',
    '格式差异': 'Format difference',
    '残余不一致（需关注）': 'Residual Inconsistencies (Need Attention)',
    '中的': ' in the ',
    '过度声称': 'Overclaim',
    '摘要': 'Abstract',
    '证明了': 'proves',
    '充要条件': 'necessary and sufficient condition',
    '为': ' is ',
    '（定理': ' (Theorem ',
    '）': ')',
    '标题': ' title',
    '必要性条件': 'Necessary Condition',
    '总结': 'Summary',
    '问题': 'Problem',
    '摘要称定理': 'The abstract claims that Theorem',
    '给出了': ' provides',
    '但实际上定理': 'but actually Theorem',
    '仅证': 'only proves',
    '（且限定在贝叶斯最优分类器），必要条件由': ' (qualified to Bayes-optimal classifier), and the necessary condition is separately given by',
    '独立的': ' independent ',
    '另外给出（且允许非信息论机制）。此外，充分条件包含步骤': ' separately (allowing non-information-theoretic mechanisms). Moreover, the sufficient condition includes Step',
    '的启发式推广（从贝叶斯最优到实际专家），而非纯粹严格证明。': ' heuristic generalization (from Bayes-optimal to actual experts), not a purely rigorous proof.',
    '建议': 'Recommendation',
    '摘要中': 'In the abstract, ',
    '应改为': 'should be changed to',
    '）与必要条件（命题': ') and necessary condition (Proposition ',
    '），或至少将归属从单独的': '), or at least correct the attribution from',
    '修正为': ' to ',
    '的双重陈述': 'Dual Statement',
    '粗略形式：': 'Rough form: ',
    '修正项': ' correction term',
    '精确形式：': 'Precise form: ',
    '仅有精确形式': 'Only the precise form',
    '先给出一个较粗略的形式，再给出精确形式。两个版本的第二项不同（': 'first gives a rougher form, then a precise form. The second terms differ between the two versions (',
    '使用了概念上不同的': 'uses the conceptually different',
    '而精确版使用': 'while the precise version uses',
    '。这可能导致读者困惑------两个形式不等价。': '. This may confuse readers --- the two forms are not equivalent.',
    '内容': 'Content',
    '编号': 'Number',
    '标签': 'Label',
}

r = replace_all(os.path.join(BASE, 'theory/self_evolution/situs_final_verification.tex'), m)
print(f"situs_final_verification.tex: {r} remaining")
print("Step 3 complete")
