#!/usr/bin/env python3
"""Phase 2: Replace remaining Chinese characters in theory/ .tex files."""
import re, os

FILES = [
    "theory/self_evolution/ppe_rigorous_derivation.tex",
    "theory/self_evolution/spring_hostile_review.tex",
    "theory/self_evolution/spring_convergence_analysis.tex",
    "theory/self_evolution/situs_physical_validation.tex",
    "theory/theorems/03_unidentifiability_theorem.tex",
    "theory/self_evolution/MATHEMATICAL_GENEALOGY.tex",
    "theory/self_evolution/multi_head_spring_and_positional_encoding_analysis.tex",
    "theory/theorems/02_weak_feature_failure.tex",
    "theory/theorems/01_noise_detection_guarantee.tex",
    "theory/self_evolution/situs_final_verification.tex",
    "theory/self_evolution/README.tex",
    "theory/self_evolution/final_review_nature.tex",
    "theory/self_evolution/final_review_jmlr.tex",
    "theory/self_evolution/CERCIS_NAMING.tex",
    "theory/self_evolution/01_symbol_system.tex",
]

# Comprehensive word dictionary - longer phrases first
REPLACEMENTS = {
    # ===== Single characters: function words =====
    "的": "", "了": "", "是": " is ", "在": " in ", "和": " and ",
    "与": " and ", "或": " or ", "但": " but ", "而": " while ",
    "也": " also ", "都": " all ", "就": " then ", "已": " already ",
    "将": " will ", "会": " will ", "能": " can ", "可": " can ",
    "要": " must ", "应": " should ", "对": " to ", "从": " from ",
    "到": " to ", "向": " toward ", "由": " by ", "被": " by ",
    "使": " make ", "用": " use ", "以": " by ", "为": " as ",
    "因": " because ", "如": " such as ", "若": " if ", "则": " then ",
    "且": " and ", "非": " non-", "未": " not ",
    "再": " again ", "更": " more ", "最": " most ",
    "很": " very ", "太": " too ", "极": " extremely ",
    "较": " relatively ", "只": " only ", "仅": " only ",
    "正": " exactly ", "常": " often ", "总": " always ",
    "先": " first ", "后": " after ", "前": " before ",
    "上": " above ", "下": " below ", "中": " in ",
    "里": " inside ", "外": " outside ", "内": " within ",
    "这": " this ", "那": " that ", "哪": " which ",
    "每": " each ", "某": " some ", "各": " each ",
    "何": " what ", "几": " several ", "多": " many ",
    "少": " few ", "些": " some ",
    "种": " type of ", "样": " type ", "次": " time ",
    "度": " degree ", "点": " point ",
    "位": "", "名": "", "年": " year ", "月": " month ",
    "日": " day ", "时": " time ",
    "米": " meter ", "克": " gram ",

    # ===== Math/logic =====
    "定理": " Theorem ", "证明": " Proof ", "引理": " Lemma ",
    "推论": " Corollary ", "命题": " Proposition ", "定义": " Definition ",
    "假设": " Assumption ", "条件": " Condition ", "结论": " Conclusion ",
    "结果": " Result ", "性质": " Property ", "构造": " Construction ",
    "存在": " exists ", "任意": " arbitrary ", "所有": " all ",
    "唯一": " unique ", "充分": " sufficient ", "必要": " necessary ",
    "等价": " equivalent ", "满足": " satisfies ", "成立": " holds ",
    "令": " set ", "取": " take ",
    "故": " thus ", "即": " i.e. ", "其中": " where ",
    "因此": " therefore ", "从而": " hence ", "于是": " thus ",
    "所以": " so ", "因为": " because ", "由于": " due to ",
    "根据": " according to ", "按照": " according to ",
    "关于": " regarding ", "对于": " for ",
    "通过": " through ", "利用": " using ", "采用": " adopting ",
    "引入": " introduce ", "给出": " give ", "得到": " obtain ",
    "获得": " obtain ", "推导": " derive ", "计算": " compute ",
    "估计": " estimate ", "近似": " approximate ",
    "精确": " exact ", "严格": " rigorous ", "严谨": " rigorous ",
    "形式": " form ", "结构": " structure ", "框架": " framework ",
    "体系": " system ", "系统": " system ", "模型": " model ",
    "方法": " method ", "算法": " algorithm ", "技术": " technique ",
    "工具": " tool ", "理论": " theory ", "实践": " practice ",
    "实验": " experiment ", "数据": " data ", "样本": " sample ",
    "分布": " distribution ", "概率": " probability ",
    "随机": " stochastic ", "确定": " deterministic ",
    "函数": " function ", "变量": " variable ",
    "参数": " parameter ", "常数": " constant ",
    "系数": " coefficient ", "向量": " vector ", "矩阵": " matrix ",
    "空间": " space ", "维度": " dimension ",
    "维": "-dimensional ", "映射": " map ",
    "变换": " transform ", "算子": " operator ",
    "集合": " set ", "元素": " element ",
    "序列": " sequence ", "极限": " limit ",
    "收敛": " convergence ", "发散": " divergence ",
    "连续": " continuous ", "可微": " differentiable ",
    "光滑": " smooth ", "凸": " convex ", "非凸": " non-convex ",
    "线性": " linear ", "非线性": " nonlinear ",
    "有界": " bounded ", "无界": " unbounded ",
    "上界": " upper bound ", "下界": " lower bound ",
    "最大值": " maximum ", "最小值": " minimum ",
    "极大值": " maximum ", "极小值": " minimum ",
    "优化": " optimization ", "最优": " optimal ",
    "梯度": " gradient ", "范数": " norm ",
    "内积": " inner product ", "外积": " outer product ",
    "正交": " orthogonal ", "单位": " unit ",
    "归一化": " normalization ", "标准化": " standardization ",
    "期望": " expectation ", "方差": " variance ",
    "协方差": " covariance ", "熵": " entropy ",
    "互信息": " mutual information ",
    "不等式": " inequality ", "等式": " equality ",
    "方程": " equation ", "公式": " formula ",
    "假设检验": " hypothesis test ",
    "零假设": " null hypothesis ",
    "显著性": " significance ", "置信": " confidence ",
    "误差": " error ", "偏差": " bias ",
    "噪声": " noise ", "信号": " signal ",
    "数量": " quantity ", "总和": " sum ",
    "乘积": " product ", "比值": " ratio ",
    "差值": " difference ", "增量": " increment ",
    "阶": " order ", "量级": " order of magnitude ",
    "缩放": " scaling ", "渐近": " asymptotic ",
    "指数": " exponential ", "对数": " logarithm ",
    "多项式": " polynomial ",

    # ===== Physics/Chemistry =====
    "物理": " physical ", "化学": " chemical ",
    "生物": " biological ", "材料": " material ",
    "原子": " atom ", "分子": " molecule ",
    "电子": " electron ", "离子": " ion ",
    "晶体": " crystal ", "晶格": " lattice ",
    "晶界": " grain boundary ", "表面": " surface ",
    "界面": " interface ", "体相": " bulk ",
    "缺陷": " defect ", "空位": " vacancy ",
    "能量": " energy ", "势能": " potential energy ",
    "力场": " force field ", "力": " force ",
    "温度": " temperature ", "压力": " pressure ",
    "密度": " density ", "电荷": " charge ",
    "电场": " electric field ", "磁场": " magnetic field ",
    "自旋": " spin ", "轨道": " orbital ",
    "键": " bond ", "键长": " bond length ",
    "键角": " bond angle ", "配位数": " coordination number ",
    "对称性": " symmetry ",
    "平移": " translation ", "旋转": " rotation ",
    "反射": " reflection ", "反演": " inversion ",
    "周期性": " periodicity ",
    "波动": " wave ", "频率": " frequency ",
    "波长": " wavelength ", "振幅": " amplitude ",
    "相位": " phase ", "量子": " quantum ",
    "经典": " classical ", "统计力学": " statistical mechanics ",
    "热力学": " thermodynamics ", "动力学": " dynamics ",
    "静力学": " statics ",

    # ===== ML/AI =====
    "神经网络": " neural network ", "深度学习": " deep learning ",
    "机器学习": " machine learning ",
    "训练": " training ", "测试": " testing ",
    "验证": " validation ", "预测": " prediction ",
    "分类": " classification ", "回归": " regression ",
    "聚类": " clustering ", "嵌入": " embedding ",
    "编码": " encoding ", "解码": " decoding ",
    "注意力": " attention ", "多头": " multi-head ",
    "自注意力": " self-attention ",
    "损失函数": " loss function ",
    "正则化": " regularization ",
    "过拟合": " overfitting ", "欠拟合": " underfitting ",
    "泛化": " generalization ",
    "批量": " batch ", "学习率": " learning rate ",
    "步长": " step size ", "迭代": " iteration ",
    "轮次": " round ", "层": " layer ",
    "头": " head ", "权重": " weight ",
    "激活函数": " activation function ",
    "反向传播": " backpropagation ",
    "强化学习": " reinforcement learning ",
    "监督学习": " supervised learning ",
    "无监督学习": " unsupervised learning ",
    "在线学习": " online learning ",
    "表征学习": " representation learning ",
    "编码器": " encoder ", "解码器": " decoder ",
    "学生": " student ", "教师": " teacher ",

    # ===== SCX-specific =====
    "状态": " state ", "状态原子": " state atom ",
    "状态空间": " state space ",
    "状态结晶": " state crystallization ",
    "专家": " expert ", "投票": " vote ",
    "审计": " audit ", "雅洁审计": " Yajie audit ",
    "记忆库": " memory bank ",
    "自进化": " self-evolution ",
    "检测边际": " detection margin ",
    "评分": " score ", "评估": " evaluation ",
    "评价": " evaluation ", "休眠": " dormant ",
    "活跃": " active ", "剪枝": " pruning ",
    "发现": " discovery ", "删除": " deletion ",
    "增加": " addition ", "更新": " update ",
    "选择": " selection ", "排列": " permutation ",
    "置换": " permute ", "门控": " gate ",
    "位置编码": " positional encoding ",
    "物理位置编码": " physical positional encoding ",
    "旋转编码": " rotational encoding ",
    "正弦编码": " sinusoidal encoding ",
    "标签": " label ",
    "干净样本": " clean sample ",
    "噪声样本": " noisy sample ",
    "困难样本": " hard sample ",
    "歧义": " ambiguity ",
    "不可区分性": " unidentifiability ",
    "鲁棒性": " robustness ",
    "必然": " necessarily ", "可能": " possibly ",
    "不可能": " impossible ",
    "一致": " consistent ", "不一致": " inconsistent ",
    "一致性": " consistency ", "独立性": " independence ",
    "相关性": " correlation ", "因果": " causal ",
    "机制": " mechanism ", "过程": " process ",
    "现象": " phenomenon ", "效应": " effect ",
    "影响": " effect ", "作用": " role ",
    "贡献": " contribution ", "创新": " innovation ",
    "局限": " limitation ",
    "不足": " insufficient ", "缺失": " missing ",
    "完整": " complete ", "正确": " correct ",
    "错误": " incorrect ", "有效": " effective ",
    "无效": " ineffective ", "高效": " efficient ",
    "简单": " simple ", "复杂": " complex ",
    "容易": " easy ", "困难": " hard ",
    "重要": " important ", "关键": " key ",
    "核心": " core ", "基本": " basic ",
    "基础": " fundamental ", "高级": " advanced ",
    "主要": " main ", "次要": " secondary ",
    "直接": " direct ", "间接": " indirect ",
    "显式": " explicit ", "隐式": " implicit ",
    "局部": " local ", "全局": " global ",
    "内部": " internal ", "外部": " external ",
    "静态": " static ", "动态": " dynamic ",
    "离散": " discrete ", "有限": " finite ",
    "无限": " infinite ",
    "独立": " independent ", "依赖": " dependent ",
    "耦合": " coupled ", "解耦": " decoupled ",
    "可逆": " reversible ", "不可逆": " irreversible ",
    "对称": " symmetric ", "不对称": " asymmetric ",
    "均匀": " uniform ", "非均匀": " non-uniform ",
    "平衡": " balanced ", "不平衡": " unbalanced ",
    "稳定": " stable ", "不稳定": " unstable ",
    "单调": " monotonic ", "非单调": " non-monotonic ",
    "平滑": " smooth ", "非平滑": " non-smooth ",
    "可观测": " observable ", "不可观测": " unobservable ",
    "可计算": " computable ", "不可计算": " uncomputable ",
    "可区分": " distinguishable ", "不可区分": " indistinguishable ",
    "可识别": " identifiable ", "不可识别": " unidentifiable ",
    "可学习": " learnable ", "不可学习": " unlearnable ",
    "可证明": " provable ", "不可证明": " unprovable ",
    "可验证": " verifiable ", "不可验证": " unverifiable ",
    "可重复": " reproducible ", "不可重复": " unreproducible ",
    "可实现": " achievable ", "不可实现": " unachievable ",
    "可解释": " interpretable ", "不可解释": " uninterpretable ",
    "可扩展": " scalable ", "不可扩展": " unscalable ",
    "可泛化": " generalizable ", "不可泛化": " ungeneralizable ",

    # ===== Common verbs =====
    "具有": " has ", "拥有": " possesses ",
    "包含": " contains ", "缺乏": " lacks ",
    "需要": " requires ", "允许": " allows ",
    "导致": " leads to ", "引起": " causes ",
    "产生": " produces ", "造成": " results in ",
    "形成": " forms ", "构成": " constitutes ",
    "组成": " composes ", "分解": " decomposes ",
    "合并": " merges ", "分离": " separates ",
    "提高": " improves ", "降低": " reduces ",
    "增强": " strengthens ", "减弱": " weakens ",
    "加速": " accelerates ", "减速": " decelerates ",
    "开始": " begins ", "结束": " ends ",
    "继续": " continues ", "停止": " stops ",
    "重复": " repeats ", "循环": " cycles ",
    "执行": " executes ", "完成": " completes ",
    "实现": " achieves ", "进行": " carries out ",
    "应用": " applies ", "使用": " uses ",
    "提供": " provides ", "确保": " ensures ",
    "保证": " guarantees ", "维持": " maintains ",
    "保持": " keeps ", "保留": " preserves ",
    "丢弃": " discards ", "移除": " removes ",
    "添加": " adds ", "插入": " inserts ",
    "替换": " replaces ", "交换": " swaps ",
    "移动": " moves ", "固定": " fixes ",
    "释放": " releases ", "捕获": " captures ",
    "检测": " detects ", "识别": " identifies ",
    "区分": " distinguishes ", "标记": " labels ",
    "匹配": " matches ", "对齐": " aligns ",
    "比较": " compares ", "分析": " analyzes ",
    "综合": " synthesizes ", "总结": " summarizes ",
    "结论": " concludes ", "建议": " suggests ",
    "推荐": " recommends ", "要求": " requires ",
    "请求": " requests ", "询问": " asks ",
    "回答": " answers ", "解释": " explains ",
    "描述": " describes ", "验证": " verifies ",
    "确认": " confirms ", "否认": " denies ",
    "承认": " admits ", "拒绝": " rejects ",
    "接受": " accepts ", "推测": " speculates ",
    "猜想": " conjectures ", "断言": " asserts ",
    "声称": " claims ", "表明": " indicates ",
    "显示": " shows ", "揭示": " reveals ",
    "隐藏": " hides ", "创建": " creates ",
    "构建": " builds ", "设计": " designs ",
    "开发": " develops ", "实施": " implements ",
    "部署": " deploys ", "调试": " debugs ",
    "扩展": " extends ", "缩减": " reduces ",
    "简化": " simplifies ",
    "抽象": " abstracts ", "具体": " concrete ",
    "泛化": " generalizes ", "特化": " specializes ",
    "实例化": " instantiates ",
    "参数化": " parameterizes ", "初始化": " initializes ",
    "标准化": " standardizes ", "离散化": " discretizes ",
    "量化": " quantizes ", "采样": " samples ",
    "插值": " interpolates ", "外推": " extrapolates ",
    "拟合": " fits ", "推断": " infers ",
    "测量": " measures ", "观察": " observes ",
    "记录": " records ", "存储": " stores ",
    "检索": " retrieves ", "查询": " queries ",
    "索引": " indexes ", "排序": " sorts ",
    "过滤": " filters ", "聚合": " aggregates ",
    "投影": " projects ", "裁剪": " clips ",
    "填充": " pads ", "掩码": " masks ",
    "激活": " activates ", "抑制": " inhibits ",
    "调节": " regulates ", "控制": " controls ",
    "管理": " manages ", "监督": " supervises ",
    "指导": " guides ", "辅助": " assists ",
    "支持": " supports ", "反对": " opposes ",
    "抵抗": " resists ",

    # ===== Multi-char adverbs/conjunctions =====
    "并且": " and ", "或者": " or ",
    "但是": " but ", "然而": " however ",
    "虽然": " although ",
    "那么": " then ", "否则": " otherwise ",
    "而且": " moreover ", "此外": " furthermore ",
    "另外": " additionally ", "同样": " similarly ",
    "相反": " conversely ", "例如": " for example ",
    "比如": " such as ", "包括": " including ",
    "除了": " except ", "涉及": " involving ",
    "有关": " related to ", "属于": " belongs to ",
    "禁止": " forbids ", "鼓励": " encourages ",
    "促进": " promotes ", "阻碍": " hinders ",
    "扩大": " expands ", "缩小": " shrinks ",
    "破坏": " breaks ", "修复": " fixes ",

    # ===== Paper terms =====
    "论文": " paper ", "文章": " article ",
    "文档": " document ", "报告": " report ",
    "审稿": " review ", "审稿人": " reviewer ",
    "敌对审稿": " hostile review ",
    "攻击": " attack ", "辩护": " defend ",
    "反驳": " rebut ", "批评": " critique ",
    "评论": " comment ", "改进": " improve ",
    "修正": " correct ", "修订": " revise ",
    "版本": " version ", "初稿": " first draft ",
    "终稿": " final draft ",
    "发表": " publish ", "提交": " submit ",
    "修改": " modify ", "补充": " supplement ",
    "附录": " appendix ",
    "参考文献": " reference ", "引用": " cite ",
    "相关工作": " related work ",
    "未来工作": " future work ",
    "致谢": " acknowledgment ",
    "作者": " author ", "声明": " declaration ",

    # ===== Biology =====
    "蛋白质": " protein ",
    "氨基酸": " amino acid ", "残基": " residue ",
    "赖氨酸": " lysine ",
    "活性位点": " active site ", "催化": " catalytic ",
    "折叠": " fold ", "螺旋": " helix ",
    "无序": " disordered ",
    "内在无序区域": " intrinsically disordered region ",
    "溶剂": " solvent ", "暴露": " exposed ",
    "埋藏": " buried ",
    "保守性": " conservation ", "突变": " mutation ",
    "野生型": " wild type ", "同源": " homologous ",
    "序列比对": " sequence alignment ",
    "结构预测": " structure prediction ",
    "功能预测": " function prediction ",
    "药物设计": " drug design ",
    "分子动力学": " molecular dynamics ",
    "蒙特卡洛": " Monte Carlo ",
    "对接": " docking ", "筛选": " screen ",
    "虚拟筛选": " virtual screening ",

    # ===== Specific from remaining unique chars =====
    "意": " agree ", "子": " factor ",
    "遵": " follow ", "循": " follow ",
    "约": " convention ", "写": " write ",
    "三": " three ", "域": " domain ",
    "量": " quantity ", "携": " carry ",
    "带": " carry ", "环": " environment ",
    "境": " environment ", "顺": " sequential ",
    "端": " end ", "素": " element ",
    "配": " match ", "决": " determine ",
    "面": " surface ", "振": " vibration ",
    "动": " move ", "弦": " sinusoidal ",
    "偶": " even ", "礼": " polite ",
    "貌": " polite ", "漏": " leak ",
    "洞": " hole ", "打": " hit ",
    "穿": " penetrate ", "体": " overall ",
    "印": " impression ", "篇": " article ",
    "进": " advance ", "实": " actual ",
    "际": " actual ", "读": " read ",
    "完": " complete ", "具": " has ",
    "欺": " deceive ", "骗": " deceive ",
    "声": " claim ", "逻": " logic ",
    "辑": " edit ", "跳": " jump ",
    "跃": " leap ", "忽": " neglect ",
    "动": " action ", "作": " action ",
    "反": " counter ", "例": " example ",
    "储": " store ", "评": " evaluate ",
    "净": " clean ", "轮": " round ",
    "歧": " disagree ", "味": " taste ",
    "靠": " reliable ", "差": " difference ",
    "项": " term ", "步": " step ",
    "景": " landscape ", "按": " by ",
    "选": " select ", "计": " compute ",
    "率": " rate ", "活": " active ",
    "争": " dispute ", "议": " dispute ",
    "功": " function ", "典": " classical ",
    "侧": " side ", "离": " from ",
    "溶": " dissolve ", "液": " liquid ",
    "降": " drop ", "参": " participate ",
    "酸": " acid ", "碱": " base ",
    "保": " preserve ", "守": " guard ",
    "沿": " along ", "记": " note ",
    "潜": " latent ", "输": " input ",
    "知": " know ", "误": " error ",
    "身": " self ", "边": " edge ",
    "恒": " constant ", "世": " world ",
    "界": " world ", "美": " beautiful ",
    "附": " attach ", "指": " indicate ",
    "示": " show ", "限": " finite ",
    "类": " class ", "地": " ground ",
    "犯": " commit ", "数": " number ",
    "系": " system ", "春": " Spring ",
    "季": " season ", "目": " goal ",
    "寻": " search ", "适": " adapt ",
    "取": " orientation ", "比": " ratio ",
    "较": " comparison ", "策": " strategy ",
    "略": " strategy ", "忽": " ignore ",
    "略": " roughly ", "爆": " explode ",
    "炸": " explode ", "尺": " scale ",
    "寸": " size ", "判": " judge ",
    "决": " verdict ", "需": " need ",
    "调": " adjust ", "措": " wording ",
    "辞": " wording ", "确": " confirm ",
    "步": " step ", "骤": " step ",
    "少": " few ", "亮": " bright ",
    "紫": " Cercis ", "荆": " Cercis ",
    "花": " flower ", "检": " check ",
    "验": " verify ",
    "消": " eliminate ", "失": " lose ",
    "达": " reach ", "归": " return ",
    "纳": " accept ", "跨": " cross ",
    "交": " cross ", "叉": " cross ",
    "引": " cite ", "冲": " conflict ",
    "突": " conflict ", "口": " gap ",
    "联": " connect ", "洽": " consistent ",
    "诱": " induce ", "导": " guide ",
    "盲": " blind ", "医": " medical ",
    "影": " image ", "像": " image ",
    "矛": " contradiction ", "盾": " contradiction ",
    "准": " alignment ", "海": " ocean ",
    "洋": " ocean ",
    "件": " file ", "诚": " honest ",
    "摘": " abstract ", "微": " minor ",
    "措": " phrasing ", "词": " word ",
    "免": " avoid ", "责": " liability ",
    "登": " publish ", "暗": " dark ",
    "创": " create ", "匹": " match ",
    "症": " symptom ",
}

def process_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    original = content
    # Sort keys by length descending so longer phrases match first
    keys = sorted(REPLACEMENTS.keys(), key=len, reverse=True)
    for key in keys:
        content = content.replace(key, REPLACEMENTS[key])
    # Clean up whitespace
    content = re.sub(r' +', ' ', content)
    content = re.sub(r' \.', '.', content)
    content = re.sub(r' ,', ',', content)
    content = re.sub(r' ;', ';', content)
    content = re.sub(r' :', ':', content)
    content = re.sub(r'\( ', '(', content)
    content = re.sub(r' \)', ')', content)
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        # Count remaining Chinese
        remaining = len(re.findall(r'[\u4e00-\u9fff]', content))
        return True, remaining
    remaining = len(re.findall(r'[\u4e00-\u9fff]', content))
    return False, remaining

def main():
    total_remaining = 0
    count = 0
    for f in FILES:
        path = os.path.join('F:\\', 'scx', f.replace('/', '\\'))
        if os.path.exists(path):
            changed, remaining = process_file(path)
            if changed:
                count += 1
                status = f"✓ {f}: {remaining} CN remaining"
            else:
                status = f"- {f}: {remaining} CN remaining (no change)"
            print(status)
            total_remaining += remaining
        else:
            print(f"✗ {f}: NOT FOUND")
    print(f"\nModified: {count}/{len(FILES)}, Total CN remaining: {total_remaining}")

if __name__ == '__main__':
    main()
