#!/usr/bin/env python3
"""
Translate Chinese text in LaTeX theory files to English.
Handles the re-cleaning of theory/ Batch 3 files.
"""
import re, os

def translate_line(line):
    """Translate Chinese text in a line to English."""
    # Skip lines that are purely math/LaTeX commands
    if not re.search(r'[\u4e00-\u9fff]', line):
        return line
    
    # Translation dictionary for common Chinese phrases
    translations = [
        # === MATHEMATICAL_GENEALOGY ===
        ('Spring 自进化算法 ---', 'Spring Self-Evolution Algorithm ---'),
        ('数学谱系学', 'Mathematical Genealogy'),
        ('Spring (春季)', 'Spring'),
        ('地位', 'Status'),
        ('目标) 的核心算法', 'target) core algorithm'),
        ('文档类型', 'Document Type'),
        ('理论根源追溯 ---', 'Theoretical Genealogy ---'),
        ('数学领域归属、关键思想来源、历史发展脉络、与前人工作的对比', 'Mathematical domain classification, key idea origins, historical development timeline, and comparison with prior work'),
        ('日期', 'Date'),
        ('目录', 'Table of Contents'),
        ('数学领域归属', 'Mathematical Domain Classification'),
        ('关键思想与证明工具', 'Key Ideas and Proof Tools'),
        ('历史发展时间线', 'Historical Development Timeline'),
        ('与前人的对比表', 'Comparison with Prior Work'),
        ('Spring 独有的贡献', "Spring's Unique Contributions"),
        ('自进化算法并非属于单一数学领域，而是跨越七个经典数学领域，在它们的交汇处合成全新结构。', 'The Spring self-evolution algorithm does not belong to a single mathematical domain, but spans seven classical mathematical domains, synthesizing a completely new structure at their intersection.'),
        ('随机逼近 (Stochastic', 'Stochastic Approximation (Stochastic'),
        ('根源', 'Origin'),
        ('Spring 中的角色', 'Role in Spring'),
        ('在线更新遵循', 'online update follows'),
        ('递归：', 'recursion:'),
        ('其中学习率', 'where the learning rate'),
        ('满足标准 RM', 'satisfies the standard RM'),
        ('条件：', 'conditions:'),
        ('Spring 将标准 RM 推广到', 'Spring generalizes the standard RM to'),
        ('耦合双时间尺度', 'coupled two-timescale'),
        ('快时间尺度', 'Fast timescale'),
        ('慢时间尺度', 'Slow timescale'),
        ('在学生准稳态下以速率', 'under the student quasi-steady-state at rate'),
        ('这对应于 Borkar (2008) 的双时间尺度随机逼近框架，条件 C6\'', 'This corresponds to Borkar (2008)\'s two-timescale stochastic approximation framework, where condition C6\''),
        ('是关键创新------它同时保证学生局部收敛与累积分布偏移有限。', 'is the key innovation---it simultaneously guarantees local convergence of the student and bounded cumulative distribution shift.'),
        ('参考文献', 'References'),
        ('动力系统 / Lyapunov', 'Dynamical Systems / Lyapunov'),
        ('稳定性', 'Stability'),
        
        # === MULTI-HEAD SPRING ===
        ('Multi-Head Spring 与 Physical Positional Encoding', 'Multi-Head Spring and Physical Positional Encoding'),
        ('的严格数学分析', ': A Rigorous Mathematical Analysis'),
        ('对 SCX', 'On the SCX'),
        ('框架定理基础的诚实审查', 'Framework Theorem Foundations: An Honest Audit'),
        ('文档状态', 'Document Status'),
        ('完整分析', 'Complete Analysis'),
        ('依赖', 'Dependencies'),
        ('方法论', 'Methodology'),
        ('严格形式推导 + 诚实暴击（不委婉）', 'Rigorous Formal Derivation + Honest Critique (No Euphemisms)'),
        ('符号约定与框架重构', 'Notation Conventions and Framework Reconstruction'),
        ('在进入分析之前，我们先精确地重构 SCX 框架的数学基础。以下所有定义均从', 'Before entering the analysis, we first precisely reconstruct the mathematical foundations of the SCX framework. All definitions below are rigorously formalized from the'),
        ('中的定理描述严格形式化。', 'theorem descriptions.'),
        ('状态结晶（State', 'State Crystallization (State'),
        ('设原始物理观测空间为', 'Let the raw physical observation space be'),
        ('连续物理量：PBE', 'continuous physical quantities: PBE'),
        ('能量面、力场、电子密度等）。State Crystallization 是一个映射：', 'energy surfaces, force fields, electron densities, etc.). State Crystallization is a mapping:'),
        ('其中每个', 'where each'),
        ('是一个', 'is a'),
        ('离散状态原子', 'discrete state atom'),
        ('的向量表示。与 BPE', '\'s vector representation. Unlike BPE'),
        ('的统计驱动不同，', 'which is statistically driven,'),
        ('是物理驱动的：它根据 PBE', 'is physically driven: it clusters according to the natural curvature boundaries of the PBE'),
        ('能量面的自然曲率边界进行聚类。形式上有：', 'energy surface. Formally:'),
        ('其中', 'where'),
        ('雅洁审计（Yajie', 'Yajie Audit (Yajie'),
        ('设有', 'Let there be'),
        ('对于状态原子', 'For a state atom'),
        ('及其标签', 'and its label'),
        ('，定义：', ', define:'),
        ('专家 m 不同意给定标签', 'expert m disagrees with the given label'),
        ('一致性计数：', 'Consistency count:'),
        ('是专家', 'is the probability that experts'),
        ('不同意', 'disagree with'),
        ('标签的概率。对于干净样本，', 'the label. For clean samples,'), 
        ('对于噪声样本，', 'For noisy samples,'),
        ('其中', 'where'),
        ('是基础质量分（基于多专家一致性），', 'is the base quality score (based on multi-expert consistency),'),
        ('是新奇性奖励，', 'is the novelty bonus,'), 
        ('是时间衰减探索权重。', 'is the time-decaying exploration weight.'),
        ('自进化动力学', 'Self-Evolution Dynamics'),
        ('状态转移：', 'State transition:'),
        
        # === Common table headers ===
        ('文件', 'File'),
        ('内容', 'Content'),
        ('核心结果', 'Core Result'),
        ('状态', 'Status'),
        ('完整', 'Complete'),
        ('位置', 'Location'),
        ('公式', 'Formula'),
        ('结论', 'Conclusion'),
        ('符号', 'Symbol'),
        ('含义', 'Meaning'),
        ('算法 / 框架', 'Algorithm / Framework'),
        ('自进化?', 'Self-Evolving?'),
        ('收敛证明?', 'Convergence Proof?'),
        ('记忆?', 'Memory?'),
        ('领域', 'Domain'),
        ('维度', 'Dimension'),
        ('问题', 'Problem'),
        ('核心问题', 'Core Question'),
        ('困难', 'Difficulty'),
        ('核心洞察', 'Core Insight'),
        
        # === More common terms ===
        ('九个核心文件', 'Nine Core Files'),
        ('核心定理', 'Core Theorems'),
        ('四种收敛路径', 'Four Convergence Paths'),
        ('路径', 'Path'),
        ('特征', 'Characteristics'),
        ('条件', 'Conditions'),
        ('与现有理论体系的关系', 'Relationship to Existing Theoretical Frameworks'),
        ('从属关系', 'Dependency Graph'),
        ('新引入假设', 'Newly Introduced Assumptions'),
        ('与已知理论的连接摘要', 'Connection Summary with Known Theories'),
        ('理论框架', 'Framework'),
        ('核心机制', 'Core Mechanism'),
        ('与 SCX 自进化的关键差异', 'Key Differences from SCX Self-Evolution'),
        ('理论状态评估', 'Theoretical Status Assessment'),
        ('类别', 'Category'),
        ('比例', 'Proportion'),
        ('说明', 'Explanation'),
        ('严格理论', 'Rigorous Theory'),
        ('形式化猜想', 'Formalized Conjecture'),
        ('合理假设', 'Reasonable Hypothesis'),
        ('开放问题（优先级排序）', 'Open Problems (Priority-Sorted)'),
        ('优先级', 'Priority'),
        ('文件结构', 'File Structure'),
        ('跨领域适用', 'Cross-Domain Applicability'),
        ('角色', 'Role'),
        ('参考文献（新增）', 'References (Newly Added)'),
        ('总结', 'Summary'),
        
        # === situs_final_verification ===
        ('理论最终验证报告', 'Theory Final Verification Report'),
        ('验证日期', 'Verification Date'),
        ('验证文件', 'Verified Files'),
        ('逐项检查', 'Item-by-Item Check'),
        ('定理 1.2.3 Lipschitz 常数是否已修正为', 'Theorem 1.2.3 Lipschitz Constant Corrected to'),
        ('两文件一致，常数已修正。归一化因子', 'Both files are consistent; the constant has been corrected. The normalization factor'),
        ('已被纳入证明推导，最终 Lipschitz 常数通过', 'has been incorporated into the proof derivation; the final Lipschitz constant is obtained via'),
        ('的平方根求和得到系数', 'sum of squares root, yielding coefficient'),
        ('的渐近行为', 'asymptotic behavior'),
        ('也因此从', 'thus also changes from'),
        ('降为', 'to'),
        ('通过。', 'Pass.'),
        ('定理 1.2.1 归一化因子是否已加入？md 框内公式是否已去掉', 'Theorem 1.2.1 Normalization Factor Added? Boxed Formula L-Dependence Removed?'),
        ('依赖？', 'Dependence?'),
        ('归一化因子 √(2/d)', 'Normalization Factor √(2/d)'),
        ('两文件均包含归一化因子，且均解释了其作用：保证', 'Both files include the normalization factor and explain its purpose: ensuring'),
        ('以及编码核在', 'and the encoding kernel at'),
        ('时收敛到目标核', 'converges to the target kernel'),
        ('而非发散至', 'rather than diverging to'),
        ('框内公式是否去掉 L 依赖', 'Boxed Formula L-Dependence Removal'),
        ('定理编号是否统一为', 'Theorem Numbering Unified to'),
        ('两文件统一使用', 'Both files consistently use'),
        ('同时命题', 'Meanwhile Proposition'),
        ('的编号也一致。', 'numbering is also consistent.'),
        ('是否修正为', 'Corrected to'),
        ('推导链完整，Nyquist 条件已正确引用（覆盖整个序列区间需', 'The derivation chain is complete; the Nyquist condition is correctly cited (covering the entire sequence interval requires'),
        ('定理 2.4.1', 'Theorem 2.4.1'),
        ('是否已降级为启发式估计？', 'Downgraded to Heuristic Estimate?'),
        ('关键变化', 'Key Change'),
        ('从', 'From'),
        ('定理（下界）', 'Theorem (Lower Bound)'),
        ('命题（启发式估计------非严格下界）', 'Proposition (Heuristic Estimate---Not a Rigorous Lower Bound)'),
        ('定理 2.2.1 步骤 4', 'Theorem 2.2.1 Step 4'),
        ('是否已限定为贝叶斯最优？', 'Restricted to Bayes Optimal?'),
        ('Theorem 3\'', 'Theorem 3\''),
        ('破坏方向是否已改为开放问题？', 'Destruction Direction Changed to Open Problem?'),
        ('两份文件之间是否还有符号不一致？', 'Residual Symbol Inconsistencies Between the Two Files?'),
        ('一致的项目', 'Consistent Items'),
        ('符号/概念', 'Symbol/Concept'),
        ('预期差异（非问题）', 'Expected Differences (Non-Issues)'),
        ('差异', 'Difference'),
        ('原因', 'Reason'),
        ('判定', 'Judgment'),
        ('残余不一致（需关注）', 'Residual Inconsistencies (Require Attention)'),
        ('总体评估', 'Overall Assessment'),
        ('检查项', 'Check Item'),
        ('项完全通过。核心修正（Lipschitz', 'items fully passed. Core corrections (Lipschitz'),
        ('项残余问题为 minor 级别', 'residual issues are minor-level'),
        ('措辞过于绝对，以及', 'wording too absolute, and'),
        ('文档内的双重定理陈述', 'dual theorem statement in the document'),
        ('均不影响数学正确性，可在下一轮编辑中修正。', 'do not affect mathematical correctness and can be corrected in the next editing round.'),
        
        # === situs_physical_validation ===
        ('物理真实性验证与适用场景分析', 'Physical Realism Validation and Applicability Scenario Analysis'),
        ('诚实暴击 --- 不委婉', 'Honest Critique --- No Euphemisms'),
        ('前置阅读', 'Prerequisite Reading'),
        ('严密数学推导），', 'Rigorous Mathematical Derivation),'),
        ('审计报告）', 'Audit Report)'),
        ('真实物理数据 + 数学定理的物理对应 + 逐一场景论证', 'Real Physical Data + Physical Correspondence of Mathematical Theorems + Scenario-by-Scenario Argumentation'),
        ('核心判据', 'Core Criterion'),
        ('即物理位置在给定状态原子条件下必须携带关于标签的额外信息', 'i.e., physical position must carry additional information about the label given the state atom'),
        ('部分：物理真实性检查', 'Part: Physical Realism Check'),
        ('蛋白质序列位置编码', 'Protein Sequence Positional Encoding'),
        ('相同氨基酸，不同位置：Lys-37（活性位点）vs', 'Same Amino Acid, Different Positions: Lys-37 (Active Site) vs'),
        ('表面', 'Surface'),
        ('生物学事实（无可争议）', 'Biological Facts (Indisputable)'),
        ('同一个赖氨酸残基在蛋白质不同位置具有完全不同的功能角色：', 'The same lysine residue at different positions in a protein has completely different functional roles:'),
        ('物理判断', 'Physical Judgment'),
        ('物理量', 'Physical Quantity'),
        ('活性位点', 'Active Site'),
        ('差异来源', 'Source of Difference'),
        ('根本问题', 'Fundamental Problem'),
        ('诚实结论', 'Honest Conclusion'),
        ('材料 3D', 'Materials 3D'),
        ('结构位置编码', 'Structure Positional Encoding'),
        ('物理事实', 'Physical Facts'),
        ('总修正', 'Total Correction'),
        ('原子总数 N：32 vs 256 超胞的 DFT', 'Total Atom Count N: 32 vs 256 Supercell DFT'),
        ('精度', 'Accuracy'),
        
        # === spring_convergence_analysis ===
        ('自进化动力学的严密收敛分析', 'Rigorous Convergence Analysis of Self-Evolution Dynamics'),
        ('诚实度标签', 'Honesty Labels'),
        ('符号约定与先备知识', 'Notation Conventions and Prerequisites'),
        ('状态空间', 'State Space'),
        ('Spring 自进化动力学的完整状态为三元组：', 'The complete state of the Spring self-evolution dynamics is a triple:'),
        ('参数维度：', 'Parameter dimensionality:'),
        ('雅洁审计与检测边际', 'Yajie Audit and Detection Margin'),
        ('随机梯度下降', 'Stochastic Gradient Descent'),
        
        # === spring_hostile_review ===
        ('自进化收敛分析的敌对审稿报告', 'Hostile Review Report of the Self-Evolution Convergence Analysis'),
        ('审稿定位', 'Reviewer Positioning'),
        ('审稿日期', 'Review Date'),
        ('审稿对象', 'Review Target'),
        ('审查方法', 'Review Method'),
        ('审稿标准', 'Review Standard'),
        ('总体印象', 'Overall Impression'),
        
        # === Theorem files ===
        ('核心主张', 'Core Claim'),
        ('修正记录', 'Revision Record'),
        ('定理陈述', 'Theorem Statement'),
        ('符号与设定', 'Notation and Setup'),
        ('设以下对象：', 'Define the following objects:'),
        ('输入空间，可测', 'Input space, measurable'),
        ('标签空间，', 'Label space,'),
        ('分类）或', 'classification) or'),
        ('回归）', 'regression)'),
        ('数据分布，', 'Data distribution,'),
        ('真实标注函数（未知 Oracle）', 'True labeling function (unknown Oracle)'),
        ('个专家模型，', 'expert models,'),
        ('状态划分，', 'State partition,'),
        ('的可测分割', 'measurable partition of'),
        ('有界损失函数', 'Bounded loss function'),
        ('专家错误的阈值', 'Expert error threshold'),
        ('噪声检测阈值', 'Noise detection threshold'),
        ('标签噪声模型', 'Label Noise Model'),
        ('为真实标签），观察到的标签', 'is the true label), the observed label'),
        ('生成如下：', 'is generated as follows:'),
        ('以概率', 'with probability'),
        ('其中', 'where'),
        ('为全局噪声率，噪声事件与', 'is the global noise rate, and noise events are independent of'),
        ('和所有训练数据独立。', 'and all training data.'),
        ('一致性得分', 'Consistency Score'),
        ('检测规则', 'Detection Rule'),
        ('被标记为噪声当且仅当', 'is flagged as noise if and only if'),
        ('假设', 'Assumptions'),
        ('不相交训练集', 'Disjoint Training Sets'),
        ('清洁数据上的条件独立', 'Conditional Independence on Clean Data'),
        ('合理性说明与局限', 'Justification and Limitations'),
        ('结构性假设', 'Structural Assumption'),
        ('有界损失', 'Bounded Loss'),
        ('均匀独立噪声', 'Uniform Independent Noise'),
        ('状态同质性', 'State Homogeneity'),
        ('状态划分充分性', 'State Partition Sufficiency'),
        ('平衡误差分布', 'Balanced Error Distribution'),
        ('关键引理', 'Key Lemma'),
        ('均值分离', 'Mean Separation'),
        ('主定理', 'Main Result'),
        ('关键推论', 'Key Corollary'),
        ('证明', 'Proof'),
        ('清洁数据的假阳性率', 'False Positive Rate on Clean Data'),
        ('噪声数据的真阳性率', 'True Positive Rate on Noisy Data'),
        ('新增假设', 'New Assumption'),
        ('合理性', 'Justification'),
        ('注记', 'Remark'),
        ('推论', 'Corollaries'),
        ('对称专家', 'Symmetric Experts'),
        ('最优阈值选择', 'Optimal Threshold Selection'),
        ('一致可检测的充分条件', 'Sufficient Condition for Uniform Detectability'),
        
        # Common words/phrases
        ('清洁', 'Clean'),
        ('噪声', 'Noise'),
        ('干净', 'Clean'),
        ('错误', 'Error'),
        ('正确', 'Correct'),
        ('检测', 'Detection'),
        ('保证', 'Guarantee'),
        ('算法', 'Algorithm'),
        ('模型', 'Model'),
        ('数据', 'Data'),
        ('训练', 'Training'),
        ('测试', 'Test'),
        ('评估', 'Evaluation'),
        ('结果', 'Result'),
        ('分析', 'Analysis'),
        ('方法', 'Method'),
        ('系统', 'System'),
        ('结构', 'Structure'),
        ('函数', 'Function'),
        ('参数', 'Parameter'),
        ('分布', 'Distribution'),
        ('样本', 'Sample'),
        ('学习', 'Learning'),
        ('更新', 'Update'),
        ('选择', 'Selection'),
        ('进化', 'Evolution'),
        ('收敛', 'Convergence'),
        ('最优', 'Optimal'),
        ('下界', 'Lower Bound'),
        ('上界', 'Upper Bound'),
        ('速率', 'Rate'),
        ('实验', 'Experiment'),
        ('理论', 'Theory'),
        ('原创', 'Original'),
        ('自然', 'Nature'),
        ('科学', 'Science'),
        ('计算', 'Computation'),
        ('物理', 'Physics'),
        ('化学', 'Chemistry'),
        ('生物', 'Biology'),
        ('材料', 'Materials'),
        ('论文', 'Paper'),
        ('第', 'Part'),
        ('关联实验', 'Related Experiments'),
        ('关联代码', 'Related Code'),
        ('关联概念', 'Related Concepts'),
        ('弱特征失效', 'Weak Feature Failure'),
        
        # single character fixes
        ('行', 'lines'),
        ('无', 'None'),
        ('是', 'Yes'),
        ('否', 'No'),
    ]
    
    result = line
    for cn, en in translations:
        result = result.replace(cn, en)
    
    return result

def process_file(fpath):
    with open(fpath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    lines = content.split('\n')
    new_lines = []
    changed = 0
    for line in lines:
        new_line = translate_line(line)
        if new_line != line:
            changed += 1
        new_lines.append(new_line)
    
    new_content = '\n'.join(new_lines)
    
    with open(fpath, 'w', encoding='utf-8') as f:
        f.write(new_content)
    
    # Count remaining Chinese chars
    remaining = len(re.findall(r'[\u4e00-\u9fff]', new_content))
    print(f"  {fpath}: {changed} lines changed, {remaining} Chinese chars remaining")

# Process all files
files = [
    'theory/self_evolution/MATHEMATICAL_GENEALOGY.tex',
    'theory/self_evolution/multi_head_spring_and_positional_encoding_analysis.tex',
    'theory/self_evolution/ppe_rigorous_derivation.tex',
    'theory/self_evolution/situs_final_verification.tex',
    'theory/self_evolution/situs_physical_validation.tex',
    'theory/self_evolution/spring_convergence_analysis.tex',
    'theory/self_evolution/spring_hostile_review.tex',
    'theory/theorems/01_noise_detection_guarantee.tex',
    'theory/theorems/02_weak_feature_failure.tex',
    'theory/theorems/03_unidentifiability_theorem.tex',
]

for f in files:
    if os.path.exists(f):
        process_file(f)
    else:
        print(f"  NOT FOUND: {f}")
