#!/usr/bin/env python3
"""Replace Chinese fragments in theory/ .tex files with English translations."""
import re, os, sys

FILES = [
    "theory/self_evolution/ppe_rigorous_derivation.tex",
    "theory/self_evolution/spring_hostile_review.tex",
    "theory/self_evolution/spring_convergence_analysis.tex",
    "theory/self_evolution/situs_physical_validation.tex",
    "theory/theorems/03_unidentifiability_theorem.tex",
    "theory/self_evolution/MATHEMATICAL_GENEALOGY.tex",
    "theory/self_evolution/multi_head_spring_and_positional_encoding_analysis.tex",
    "theory/self_evolution/hostile_review.tex",
    "theory/SCX_Undiscovered_Theorems.tex",
    "theory/theorems/02_weak_feature_failure.tex",
    "theory/theorems/01_noise_detection_guarantee.tex",
    "theory/self_evolution/situs_final_verification.tex",
    "theory/self_evolution/README.tex",
    "theory/self_evolution/final_review_nature.tex",
    "theory/self_evolution/final_review_jmlr.tex",
    "theory/self_evolution/CERCIS_NAMING.tex",
    "theory/self_evolution/01_symbol_system.tex",
]

# Word/Phrase-level replacements (longer patterns first)
PHRASES = [
    # === Common function words and particles ===
    ("的", ""),  # possessive particle - often redundant in English
    ("了", ""),  # completion particle
    ("是", " is "),
    ("在", " in "),
    ("和", " and "),
    ("与", " and "),
    ("或", " or "),
    ("但", " but "),
    ("而", " and "),
    ("也", " also "),
    ("都", " all "),
    ("就", " then "),
    ("才", " only then "),
    ("已", " already "),
    ("将", " will "),
    ("会", " will "),
    ("能", " can "),
    ("可", " can "),
    ("要", " must "),
    ("应", " should "),
    ("该", " should "),
    ("对", " for "),
    ("从", " from "),
    ("到", " to "),
    ("向", " toward "),
    ("由", " by "),
    ("被", " by "),
    ("把", ""),
    ("让", " let "),
    ("使", " make "),
    ("用", " use "),
    ("以", " by "),
    ("为", " as "),
    ("因", " because "),
    ("为", " for "),
    ("如", " such as "),
    ("若", " if "),
    ("则", " then "),
    ("且", " and "),
    ("并", " and "),
    ("或", " or "),
    ("非", " non-"),
    ("未", " not yet "),
    ("已", " already "),
    ("再", " again "),
    ("又", " again "),
    ("还", " still "),
    ("更", " more "),
    ("最", " most "),
    ("很", " very "),
    ("太", " too "),
    ("极", " extremely "),
    ("较", " relatively "),
    ("稍", " slightly "),
    ("略", " slightly "),
    ("只", " only "),
    ("仅", " only "),
    ("刚", " just "),
    ("正", " exactly "),
    ("常", " often "),
    ("总", " always "),
    ("永", " forever "),
    ("先", " first "),
    ("后", " after "),
    ("前", " before "),
    ("上", " above "),
    ("下", " below "),
    ("中", " in "),
    ("里", " inside "),
    ("外", " outside "),
    ("内", " within "),
    ("旁", " beside "),
    ("左", " left "),
    ("右", " right "),
    ("东", " east "),
    ("西", " west "),
    ("南", " south "),
    ("北", " north "),
    ("这", " this "),
    ("那", " that "),
    ("哪", " which "),
    ("每", " each "),
    ("某", " some "),
    ("各", " each "),
    ("任", " any "),
    ("何", " what "),
    ("几", " several "),
    ("多", " many "),
    ("少", " few "),
    ("些", " some "),
    ("个", ""),
    ("种", " kind of "),
    ("样", " type "),
    ("次", " time "),
    ("回", " time "),
    ("遍", " time "),
    ("度", " degree "),
    ("点", " point "),
    ("条", ""),
    ("张", ""),
    ("本", ""),
    ("支", ""),
    ("块", ""),
    ("首", ""),
    ("位", ""),
    ("名", ""),
    ("岁", " years "),
    ("年", " year "),
    ("月", " month "),
    ("日", " day "),
    ("时", " time "),
    ("分", " minute "),
    ("秒", " second "),
    ("元", " dollar "),
    ("角", ""),
    ("分", " cent "),
    ("米", " meter "),
    ("克", " gram "),
    ("升", " liter "),

    # === Mathematics/Logic ===
    ("定理", "Theorem"),
    ("证明", "Proof"),
    ("引理", "Lemma"),
    ("推论", "Corollary"),
    ("命题", "Proposition"),
    ("定义", "Definition"),
    ("假设", "Assumption"),
    ("条件", "Condition"),
    ("结论", "Conclusion"),
    ("结果", "Result"),
    ("性质", "Property"),
    ("构造", "Construction"),
    ("存在", "exists"),
    ("任意", "arbitrary"),
    ("所有", "all"),
    ("唯一", "unique"),
    ("充分", "sufficient"),
    ("必要", "necessary"),
    ("当且仅当", "iff"),
    ("等价", "equivalent"),
    ("满足", "satisfies"),
    ("成立", "holds"),
    ("不成立", "does not hold"),
    ("设", "let"),
    ("令", "set"),
    ("取", "take"),
    ("则", "then"),
    ("故", "thus"),
    ("即", "i.e."),
    ("其中", "where"),
    ("因此", "therefore"),
    ("从而", "hence"),
    ("由此", "from this"),
    ("于是", "thus"),
    ("所以", "so"),
    ("因为", "because"),
    ("由于", "due to"),
    ("根据", "according to"),
    ("按照", "according to"),
    ("关于", "regarding"),
    ("对于", "for"),
    ("通过", "through"),
    ("利用", "using"),
    ("采用", "adopting"),
    ("引入", "introduce"),
    ("给出", "give"),
    ("得到", "obtain"),
    ("获得", "obtain"),
    ("推导", "derive"),
    ("计算", "compute"),
    ("估计", "estimate"),
    ("近似", "approximate"),
    ("精确", "exact"),
    ("严格", "rigorous"),
    ("严谨", "rigorous"),
    ("正式", "formal"),
    ("形式", "form"),
    ("结构", "structure"),
    ("框架", "framework"),
    ("体系", "system"),
    ("系统", "system"),
    ("模型", "model"),
    ("方法", "method"),
    ("算法", "algorithm"),
    ("技术", "technique"),
    ("工具", "tool"),
    ("理论", "theory"),
    ("实践", "practice"),
    ("实验", "experiment"),
    ("数据", "data"),
    ("样本", "sample"),
    ("分布", "distribution"),
    ("概率", "probability"),
    ("随机", "random"),
    ("确定", "determine"),
    ("确定性的", "deterministic"),
    ("不确定性", "uncertainty"),
    ("函数", "function"),
    ("变量", "variable"),
    ("参数", "parameter"),
    ("常数", "constant"),
    ("系数", "coefficient"),
    ("向量", "vector"),
    ("矩阵", "matrix"),
    ("空间", "space"),
    ("维度", "dimension"),
    ("维", "dimensional"),
    ("映射", "map"),
    ("变换", "transform"),
    ("算子", "operator"),
    ("泛函", "functional"),
    ("集合", "set"),
    ("元素", "element"),
    ("序列", "sequence"),
    ("极限", "limit"),
    ("收敛", "convergence"),
    ("发散", "divergence"),
    ("连续", "continuous"),
    ("可微", "differentiable"),
    ("光滑", "smooth"),
    ("凸", "convex"),
    ("非凸", "non-convex"),
    ("线性", "linear"),
    ("非线性", "nonlinear"),
    ("有界", "bounded"),
    ("无界", "unbounded"),
    ("上界", "upper bound"),
    ("下界", "lower bound"),
    ("最大值", "maximum"),
    ("最小值", "minimum"),
    ("极大值", "maximum"),
    ("极小值", "minimum"),
    ("优化", "optimize"),
    ("最优", "optimal"),
    ("次优", "suboptimal"),
    ("梯度", "gradient"),
    ("黑塞", "Hessian"),
    ("雅可比", "Jacobian"),
    ("特征值", "eigenvalue"),
    ("特征向量", "eigenvector"),
    ("谱", "spectrum"),
    ("范数", "norm"),
    ("内积", "inner product"),
    ("外积", "outer product"),
    ("正交", "orthogonal"),
    ("单位", "unit"),
    ("归一化", "normalized"),
    ("标准化", "standardized"),
    ("期望", "expectation"),
    ("方差", "variance"),
    ("协方差", "covariance"),
    ("熵", "entropy"),
    ("互信息", "mutual information"),
    ("KL散度", "KL divergence"),
    ("信息论", "information theory"),
    ("不等式", "inequality"),
    ("等式", "equality"),
    ("方程", "equation"),
    ("公式", "formula"),
    ("假设检验", "hypothesis test"),
    ("零假设", "null hypothesis"),
    ("备择假设", "alternative hypothesis"),
    ("显著性", "significance"),
    ("置信", "confidence"),
    ("误差", "error"),
    ("偏差", "bias"),
    ("噪声", "noise"),
    ("信号", "signal"),
    ("数量", "quantity"),
    ("总和", "sum"),
    ("乘积", "product"),
    ("比值", "ratio"),
    ("差值", "difference"),
    ("增量", "increment"),
    ("减量", "decrement"),
    ("阶", "order"),
    ("量级", "order of magnitude"),
    ("缩放", "scale"),
    ("渐近", "asymptotic"),
    ("指数", "exponential"),
    ("对数", "logarithm"),
    ("多项式", "polynomial"),

    # === Physics/Chemistry/Materials ===
    ("物理", "physical"),
    ("化学", "chemical"),
    ("生物", "biological"),
    ("材料", "material"),
    ("原子", "atom"),
    ("分子", "molecule"),
    ("电子", "electron"),
    ("离子", "ion"),
    ("晶体", "crystal"),
    ("晶格", "lattice"),
    ("晶界", "grain boundary"),
    ("表面", "surface"),
    ("界面", "interface"),
    ("体相", "bulk"),
    ("缺陷", "defect"),
    ("空位", "vacancy"),
    ("间隙", "interstitial"),
    ("位错", "dislocation"),
    ("能量", "energy"),
    ("势能", "potential energy"),
    ("力场", "force field"),
    ("力", "force"),
    ("温度", "temperature"),
    ("压力", "pressure"),
    ("密度", "density"),
    ("电荷", "charge"),
    ("电场", "electric field"),
    ("磁场", "magnetic field"),
    ("自旋", "spin"),
    ("轨道", "orbital"),
    ("键", "bond"),
    ("键长", "bond length"),
    ("键角", "bond angle"),
    ("配位数", "coordination number"),
    ("对称性", "symmetry"),
    ("平移", "translation"),
    ("旋转", "rotation"),
    ("反射", "reflection"),
    ("反演", "inversion"),
    ("周期性", "periodicity"),
    ("波动", "wave"),
    ("频率", "frequency"),
    ("波长", "wavelength"),
    ("振幅", "amplitude"),
    ("相位", "phase"),
    ("量子", "quantum"),
    ("经典", "classical"),
    ("相对论", "relativity"),
    ("统计力学", "statistical mechanics"),
    ("热力学", "thermodynamics"),
    ("动力学", "dynamics"),
    ("运动学", "kinematics"),
    ("静力学", "statics"),

    # === Machine Learning / AI ===
    ("神经网络", "neural network"),
    ("深度学习", "deep learning"),
    ("机器学习", "machine learning"),
    ("训练", "train"),
    ("测试", "test"),
    ("验证", "validate"),
    ("预测", "predict"),
    ("分类", "classify"),
    ("回归", "regression"),
    ("聚类", "cluster"),
    ("嵌入", "embedding"),
    ("编码", "encoding"),
    ("解码", "decoding"),
    ("注意力", "attention"),
    ("多头", "multi-head"),
    ("自注意力", "self-attention"),
    ("交叉注意力", "cross-attention"),
    ("变换器", "Transformer"),
    ("损失函数", "loss function"),
    ("正则化", "regularization"),
    ("过拟合", "overfitting"),
    ("欠拟合", "underfitting"),
    ("泛化", "generalize"),
    ("批量", "batch"),
    ("学习率", "learning rate"),
    ("步长", "step size"),
    ("迭代", "iteration"),
    ("轮次", "round"),
    ("层", "layer"),
    ("头", "head"),
    ("权重", "weight"),
    ("偏置", "bias"),
    ("激活函数", "activation function"),
    ("反向传播", "backpropagation"),
    ("自动微分", "automatic differentiation"),
    ("强化学习", "reinforcement learning"),
    ("监督学习", "supervised learning"),
    ("无监督学习", "unsupervised learning"),
    ("半监督学习", "semi-supervised learning"),
    ("自监督学习", "self-supervised learning"),
    ("迁移学习", "transfer learning"),
    ("元学习", "meta-learning"),
    ("在线学习", "online learning"),
    ("离线学习", "offline learning"),
    ("表征学习", "representation learning"),
    ("对比学习", "contrastive learning"),
    ("生成模型", "generative model"),
    ("判别模型", "discriminative model"),
    ("编码器", "encoder"),
    ("解码器", "decoder"),
    ("学生", "student"),
    ("教师", "teacher"),
    ("蒸馏", "distillation"),

    # === SCX-specific terms ===
    ("状态", "state"),
    ("状态原子", "state atom"),
    ("状态空间", "state space"),
    ("状态结晶", "state crystallization"),
    ("专家", "expert"),
    ("投票", "vote"),
    ("审计", "audit"),
    ("雅洁审计", "Yajie audit"),
    ("记忆库", "memory bank"),
    ("自进化", "self-evolution"),
    ("自演进", "self-evolution"),
    ("检测边际", "detection margin"),
    ("评分", "score"),
    ("评估", "evaluate"),
    ("评价", "evaluate"),
    ("休眠", "dormant"),
    ("活跃", "active"),
    ("剪枝", "prune"),
    ("发现", "discover"),
    ("删除", "delete"),
    ("增加", "add"),
    ("更新", "update"),
    ("选择", "select"),
    ("排序", "sort"),
    ("排列", "permutation"),
    ("置换", "permute"),
    ("门控", "gate"),
    ("看门人", "gatekeeper"),
    ("学生参数", "student parameter"),
    ("位置编码", "positional encoding"),
    ("物理位置编码", "physical positional encoding"),
    ("旋转编码", "rotational encoding"),
    ("正弦编码", "sinusoidal encoding"),
    ("标签", "label"),
    ("干净样本", "clean sample"),
    ("噪声样本", "noisy sample"),
    ("困难样本", "hard sample"),
    ("歧义", "ambiguity"),
    ("不可区分性", "unidentifiability"),
    ("鲁棒性", "robustness"),
    ("脆弱性", "fragility"),
    ("必然", "necessarily"),
    ("可能", "possibly"),
    ("不可能", "impossible"),
    ("一致", "consistent"),
    ("不一致", "inconsistent"),
    ("一致性", "consistency"),
    ("独立性", "independence"),
    ("相关性", "correlation"),
    ("因果", "causal"),
    ("机制", "mechanism"),
    ("过程", "process"),
    ("现象", "phenomenon"),
    ("效应", "effect"),
    ("影响", "affect"),
    ("作用", "role"),
    ("贡献", "contribution"),
    ("创新", "innovation"),
    ("突破", "breakthrough"),
    ("局限", "limitation"),
    ("缺陷", "defect"),
    ("不足", "insufficient"),
    ("缺失", "missing"),
    ("完整", "complete"),
    ("不完整", "incomplete"),
    ("正确", "correct"),
    ("错误", "incorrect"),
    ("有效", "effective"),
    ("无效", "ineffective"),
    ("高效", "efficient"),
    ("低效", "inefficient"),
    ("简单", "simple"),
    ("复杂", "complex"),
    ("容易", "easy"),
    ("困难", "hard"),
    ("重要", "important"),
    ("关键", "key"),
    ("核心", "core"),
    ("基本", "basic"),
    ("基础", "fundamental"),
    ("高级", "advanced"),
    ("初级", "elementary"),
    ("主要", "main"),
    ("次要", "secondary"),
    ("直接", "direct"),
    ("间接", "indirect"),
    ("显式", "explicit"),
    ("隐式", "implicit"),
    ("局部", "local"),
    ("全局", "global"),
    ("内部", "internal"),
    ("外部", "external"),
    ("静态", "static"),
    ("动态", "dynamic"),
    ("离散", "discrete"),
    ("连续", "continuous"),
    ("有限", "finite"),
    ("无限", "infinite"),
    ("确定", "deterministic"),
    ("随机", "stochastic"),
    ("独立", "independent"),
    ("依赖", "dependent"),
    ("耦合", "coupled"),
    ("解耦", "decoupled"),
    ("可逆", "reversible"),
    ("不可逆", "irreversible"),
    ("对称", "symmetric"),
    ("不对称", "asymmetric"),
    ("各向同性", "isotropic"),
    ("各向异性", "anisotropic"),
    ("均匀", "uniform"),
    ("非均匀", "non-uniform"),
    ("平衡", "balanced"),
    ("不平衡", "unbalanced"),
    ("稳定", "stable"),
    ("不稳定", "unstable"),
    ("收敛", "convergent"),
    ("发散", "divergent"),
    ("单调", "monotonic"),
    ("非单调", "non-monotonic"),
    ("线性", "linear"),
    ("非线性", "nonlinear"),
    ("凸", "convex"),
    ("非凸", "non-convex"),
    ("平滑", "smooth"),
    ("非平滑", "non-smooth"),
    ("可微", "differentiable"),
    ("不可微", "non-differentiable"),
    ("可逆", "invertible"),
    ("不可逆", "non-invertible"),
    ("可观测", "observable"),
    ("不可观测", "unobservable"),
    ("可计算", "computable"),
    ("不可计算", "uncomputable"),
    ("可实现", "achievable"),
    ("不可实现", "unachievable"),
    ("可区分", "distinguishable"),
    ("不可区分", "indistinguishable"),
    ("可识别", "identifiable"),
    ("不可识别", "unidentifiable"),
    ("可学习", "learnable"),
    ("不可学习", "unlearnable"),
    ("可解释", "interpretable"),
    ("不可解释", "uninterpretable"),
    ("可扩展", "scalable"),
    ("不可扩展", "unscalable"),
    ("可泛化", "generalizable"),
    ("不可泛化", "ungeneralizable"),
    ("可证明", "provable"),
    ("不可证明", "unprovable"),
    ("可验证", "verifiable"),
    ("不可验证", "unverifiable"),
    ("可重复", "reproducible"),
    ("不可重复", "unreproducible"),
    ("可逆", "reversible"),
    ("不可逆", "irreversible"),

    # === Research paper terms ===
    ("论文", "paper"),
    ("文章", "article"),
    ("文档", "document"),
    ("报告", "report"),
    ("审稿", "review"),
    ("审稿人", "reviewer"),
    ("敌对审稿", "hostile review"),
    ("攻击", "attack"),
    ("辩护", "defend"),
    ("反驳", "rebut"),
    ("批评", "critique"),
    ("评论", "comment"),
    ("建议", "suggestion"),
    ("改进", "improve"),
    ("修正", "correct"),
    ("修订", "revise"),
    ("版本", "version"),
    ("初稿", "first draft"),
    ("终稿", "final draft"),
    ("发表", "publish"),
    ("提交", "submit"),
    ("接受", "accept"),
    ("拒绝", "reject"),
    ("修改", "modify"),
    ("补充", "supplement"),
    ("附录", "appendix"),
    ("参考文献", "reference"),
    ("引用", "cite"),
    ("相关工作", "related work"),
    ("未来工作", "future work"),
    ("致谢", "acknowledgment"),
    ("作者", "author"),
    ("贡献", "contribution"),
    ("声明", "declaration"),

    # === Biology / Protein specific ===
    ("蛋白质", "protein"),
    ("蛋", ""),
    ("白", ""),
    ("质", ""),
    ("氨基酸", "amino acid"),
    ("残基", "residue"),
    ("赖氨酸", "lysine"),
    ("活性位点", "active site"),
    ("催化", "catalytic"),
    ("折叠", "fold"),
    ("螺旋", "helix"),
    ("折叠", "sheet"),
    ("无序", "disordered"),
    ("内在无序区域", "intrinsically disordered region"),
    ("溶剂", "solvent"),
    ("暴露", "exposed"),
    ("埋藏", "buried"),
    ("保守性", "conservation"),
    ("突变", "mutation"),
    ("野生型", "wild type"),
    ("同源", "homologous"),
    ("序列比对", "sequence alignment"),
    ("结构预测", "structure prediction"),
    ("功能预测", "function prediction"),
    ("药物设计", "drug design"),
    ("分子动力学", "molecular dynamics"),
    ("蒙特卡洛", "Monte Carlo"),
    ("对接", "docking"),
    ("筛选", "screen"),
    ("虚拟筛选", "virtual screening"),

    # === Specific common multi-char patterns from files ===
    ("并且", "and"),
    ("或者", "or"),
    ("但是", "but"),
    ("然而", "however"),
    ("虽然", "although"),
    ("因为", "because"),
    ("所以", "therefore"),
    ("如果", "if"),
    ("那么", "then"),
    ("否则", "otherwise"),
    ("而且", "moreover"),
    ("此外", "furthermore"),
    ("另外", "additionally"),
    ("同样", "similarly"),
    ("相反", "conversely"),
    ("例如", "for example"),
    ("比如", "such as"),
    ("包括", "including"),
    ("除了", "except"),
    ("关于", "regarding"),
    ("根据", "according to"),
    ("通过", "through"),
    ("利用", "using"),
    ("对于", "for"),
    ("针对", "targeting"),
    ("涉及", "involving"),
    ("有关", "related to"),
    ("属于", "belongs to"),
    ("具有", "has"),
    ("拥有", "possesses"),
    ("存在", "exists"),
    ("包含", "contains"),
    ("缺乏", "lacks"),
    ("需要", "requires"),
    ("允许", "allows"),
    ("禁止", "forbids"),
    ("鼓励", "encourages"),
    ("抑制", "suppresses"),
    ("促进", "promotes"),
    ("阻碍", "hinders"),
    ("导致", "leads to"),
    ("引起", "causes"),
    ("产生", "produces"),
    ("造成", "results in"),
    ("形成", "forms"),
    ("构成", "constitutes"),
    ("组成", "composes"),
    ("分解", "decomposes"),
    ("合并", "merges"),
    ("分离", "separates"),
    ("增加", "increases"),
    ("减少", "decreases"),
    ("扩大", "expands"),
    ("缩小", "shrinks"),
    ("提高", "improves"),
    ("降低", "reduces"),
    ("增强", "strengthens"),
    ("减弱", "weakens"),
    ("加速", "accelerates"),
    ("减速", "decelerates"),
    ("开始", "begins"),
    ("结束", "ends"),
    ("继续", "continues"),
    ("停止", "stops"),
    ("重复", "repeats"),
    ("循环", "cycles"),
    ("执行", "executes"),
    ("完成", "completes"),
    ("实现", "achieves"),
    ("进行", "carries out"),
    ("应用", "applies"),
    ("使用", "uses"),
    ("提供", "provides"),
    ("确保", "ensures"),
    ("保证", "guarantees"),
    ("维持", "maintains"),
    ("保持", "keeps"),
    ("保留", "preserves"),
    ("丢弃", "discards"),
    ("移除", "removes"),
    ("添加", "adds"),
    ("插入", "inserts"),
    ("删除", "deletes"),
    ("替换", "replaces"),
    ("交换", "swaps"),
    ("移动", "moves"),
    ("固定", "fixes"),
    ("释放", "releases"),
    ("捕获", "captures"),
    ("检测", "detects"),
    ("识别", "identifies"),
    ("区分", "distinguishes"),
    ("分类", "classifies"),
    ("标记", "labels"),
    ("匹配", "matches"),
    ("对齐", "aligns"),
    ("比较", "compares"),
    ("分析", "analyzes"),
    ("综合", "synthesizes"),
    ("总结", "summarizes"),
    ("结论", "concludes"),
    ("建议", "suggests"),
    ("推荐", "recommends"),
    ("要求", "requires"),
    ("请求", "requests"),
    ("询问", "asks"),
    ("回答", "answers"),
    ("解释", "explains"),
    ("描述", "describes"),
    ("定义", "defines"),
    ("证明", "proves"),
    ("验证", "verifies"),
    ("确认", "confirms"),
    ("否认", "denies"),
    ("承认", "admits"),
    ("拒绝", "rejects"),
    ("接受", "accepts"),
    ("假设", "assumes"),
    ("推测", "speculates"),
    ("猜想", "conjectures"),
    ("断言", "asserts"),
    ("声称", "claims"),
    ("表明", "indicates"),
    ("显示", "shows"),
    ("揭示", "reveals"),
    ("隐藏", "hides"),
    ("发现", "discovers"),
    ("发明", "invents"),
    ("创建", "creates"),
    ("构建", "builds"),
    ("设计", "designs"),
    ("开发", "develops"),
    ("实施", "implements"),
    ("部署", "deploys"),
    ("测试", "tests"),
    ("调试", "debugs"),
    ("优化", "optimizes"),
    ("改进", "improves"),
    ("增强", "enhances"),
    ("扩展", "extends"),
    ("缩减", "reduces"),
    ("简化", "simplifies"),
    ("复杂化", "complicates"),
    ("抽象", "abstracts"),
    ("具体", "concrete"),
    ("泛化", "generalizes"),
    ("特化", "specializes"),
    ("实例化", "instantiates"),
    ("参数化", "parameterizes"),
    ("初始化", "initializes"),
    ("归一化", "normalizes"),
    ("标准化", "standardizes"),
    ("正则化", "regularizes"),
    ("离散化", "discretizes"),
    ("连续化", "continualizes"),
    ("量化", "quantizes"),
    ("采样", "samples"),
    ("插值", "interpolates"),
    ("外推", "extrapolates"),
    ("拟合", "fits"),
    ("预测", "predicts"),
    ("推断", "infers"),
    ("估计", "estimates"),
    ("计算", "computes"),
    ("评估", "evaluates"),
    ("测量", "measures"),
    ("观察", "observes"),
    ("记录", "records"),
    ("存储", "stores"),
    ("检索", "retrieves"),
    ("查询", "queries"),
    ("索引", "indexes"),
    ("排序", "sorts"),
    ("过滤", "filters"),
    ("聚合", "aggregates"),
    ("分解", "decomposes"),
    ("变换", "transforms"),
    ("投影", "projects"),
    ("旋转", "rotates"),
    ("平移", "translates"),
    ("缩放", "scales"),
    ("裁剪", "clips"),
    ("填充", "pads"),
    ("掩码", "masks"),
    ("激活", "activates"),
    ("抑制", "inhibits"),
    ("调节", "regulates"),
    ("控制", "controls"),
    ("管理", "manages"),
    ("监督", "supervises"),
    ("指导", "guides"),
    ("辅助", "assists"),
    ("支持", "supports"),
    ("反对", "opposes"),
    ("抵抗", "resists"),

    # === File-specific long phrases ===
    # From ppe_rigorous_derivation.tex - broken mixed text fixes
    ("is maintainsconsistent", "We maintain consistency"),
    ("thisthis paper adoptsusing", "this paper adopts"),
    ("primarySymbol/Concept", "primary notation"),
    ("atrequiretimeheavynewExact Definition", "while providing precise definitions where needed"),
    ("Status-专家system", "State-Expert System"),
    ("专家投票", "Expert Voting"),
    ("toeach 样this", "For each sample"),
    ("输出is", "output is"),
    ("专家same意todetermineLabel", "expert agrees with the assigned label"),
    ("专家is different意todetermineLabel", "expert disagrees with the assigned label"),
    ("atdry净samplelower (Labelcorrect)", "For clean samples (label correct)"),
    ("atnoisesamplelower (Labelincorrect)", "For noisy samples (label incorrect)"),
    ("thisand CC report的", "This is consistent with the CC report's"),
    ("决策threshold", "Decision threshold"),
    ("Markedis noise", "Marked as noise"),
    ("Chernoff-Hoeffding Foundation", "Chernoff-Hoeffding Foundation"),
    ("Hoeffding inequality: to i.i.d. Bernoulli random variable", "Hoeffding inequality: for i.i.d. Bernoulli random variables"),
    ("meanis", "with mean"),
    ("applied tonoise detection", "Applied to noise detection"),
    ("false positive (Type I)", "False positive (Type I error)"),
    ("false negative (Type II)", "False negative (Type II error)"),
    ("取", "Setting"),
    ("twooneuniform", "both are uniformly bounded by"),
    ("Note: CC Audit Report使using", "Note: The CC Audit Report uses"),
    ("thisindicateits", "This indicates their"),
    ("Definitionmayis different", "definition may differ"),
    ("maymany了一 1/2 because子", "possibly by a factor of 1/2 in the exponent"),
    ("this文atmaintainsmathematicalExact nessfront提lower", "This document maintains mathematical rigor by"),
    ("遵循 CC report的约determine", "following the CC report's convention"),
    ("heavynew校准", "recalibrate"),
    ("使 bound 写is", "so that the bound is written as"),
    ("thismutualwhenatDefinition", "This means if we define"),
    ("at原始reportmiddle记is", "in the original report it is denoted"),
    ("back续Analysismiddle", "In the subsequent analysis"),
    ("Exact 常数because子does not affectDerivationstructure", "the exact constant factor does not affect the derivation structure"),

    # Section headers
    ("第 1 part: encodingfunction的rigorousMathematical Formalization", "Part 1: Rigorous Mathematical Formalization of the Encoding Function"),
    ("三kindphysicalLocation域的Definition", "Definition of Three Physical Location Domains"),
    ("Definition 1.1.1 (mark量Location域------蛋white质序列)", "Definition 1.1.1 (Scalar Location Domain --- Protein Sequence)"),
    ("where L is sequence length. tocontinuousapproximate, 嵌入is", "where L is the sequence length. For continuous approximation, we embed"),
    ("physicalMeaning", "Physical meaning"),
    ("残基索引携带localchemical环境的一维顺序information (N 端→C 端)", "the residue index carries one-dimensional sequential information about the local chemical environment (N-terminus to C-terminus)"),
    ("Definition 1.1.2 (3D to量Location域------atom坐mark)", "Definition 1.1.2 (3D Vector Location Domain --- Atomic Coordinates)"),
    ("元素", "Elements"),
    ("is atomatreal space in the 笛卡尔坐mark", "are atomic coordinates in real Cartesian space"),
    ("atom的三维spaceLocation携带键long、键angle、配位数等几何information", "the three-dimensional spatial positions of atoms carry geometric information such as bond lengths, bond angles, and coordination numbers"),
    ("thisis **mostabundance of的**physicalLocation域", "This is the **most informative** physical location domain"),
    ("Definition 1.1.3 (mark量total数域------atom数)", "Definition 1.1.3 (Scalar Count Domain --- Atom Count)"),
    ("system的totalatom数", "the total number of atoms in the system"),
    ("systemsize决determine了energy面的dimension、may的振动模式数、defectconcentrateddegree等", "the system size determines the dimensionality of the energy landscape, the number of possible vibrational modes, defect concentration, etc."),
    ("tosmallsystem特别important (has 限尺寸effect)", "particularly important for small systems (finite-size effects)"),

    # From hostile_review.tex
    ("敌对审稿报告", "Hostile Review Report"),
    ("审稿人身份", "Reviewer Identity"),
    ("最苛刻的审稿人", "the most demanding reviewer"),
    ("审稿日期", "Review Date"),
    ("审稿对象", "Review Target"),
    ("审稿标准", "Review Standard"),
    ("不礼貌。不妥协。只要有一个漏洞就不放过。", "Impolite. Uncompromising. Any single flaw will be exploited."),
    ("总体印象", "Overall Impression"),
    ("这篇论文声称", "This paper claims"),
    ("实际读完后的结论是", "The conclusion after actually reading is"),
    ("这篇文章在多个核心定理的证明上存在根本性错误或无法修复的逻辑跳跃", "This article contains fundamental errors or irreparable logical gaps in the proofs of multiple core theorems"),
    ("以下逐条分解", "The following provides a point-by-point breakdown"),
    ("符号一致性", "Notation Consistency"),
    ("定理编号不一致", "Theorem Numbering Inconsistency"),
    ("位置", "Location"),
    ("差异", "Difference"),
    ("编号差1", "Offset by 1"),
    ("一致", "Consistent"),
    ("攻击", "Attack"),
    ("这", "This"),
    ("不是笔误", "is not a typo"),
    ("逻辑链条断裂", "a break in the logical chain"),
    ("符号命名体系的双重人格", "Dual Personality of the Notation System"),
    ("论文正文使用", "The main paper uses"),
    ("论文声称这些编号与", "The paper claims these numbers are"),
    ("保持一致", "consistent with"),
    ("双重人格", "split personality"),
    ("两个版本", "Two Versions"),
    ("论文版", "Paper version"),
    ("md版", "Markdown version"),
    ("同一个上界", "the same upper bound"),
    ("假设检验", "Hypothesis Testing"),
    ("还成立吗", "Do They Still Hold"),
    ("原始状态", "Original State"),
    ("加入Situs后", "After Adding Situs"),
    ("被削弱", "is weakened"),
    ("攻击严重度", "Attack Severity"),
    ("中", "Medium"),
    ("低", "Low"),
    ("高", "High"),
    ("致命", "Fatal"),

    # From spring_convergence_analysis.tex
    ("Spring self-evolution rigorous convergence of dynamicsAnalysis", "Spring Self-Evolution: Rigorous Convergence Analysis of Dynamics"),
    ("Document Status", "Document Status"),
    ("Rigorous Mathematical Derivation + Honest Critique", "Rigorous Mathematical Derivation + Honest Critique"),
    ("Methodology", "Methodology"),
    ("non-convex optimizationtheory", "Non-convex optimization theory"),
    ("Online Learning", "Online Learning"),
    ("stochastic process", "Stochastic process"),
    ("each resultmarkNote", "each result is labeled"),
    ("反例构造", "Counterexample Construction"),
    ("Notation Convention and Prerequisites", "Notation Convention and Prerequisites"),
    ("Spring State Space", "Spring State Space"),
    ("三元组", "triple"),
    ("Memory bank update", "Memory Bank Update"),
    ("Yajie审计andDetection Margin", "Yajie Audit and Detection Margin"),
    ("core量", "core quantity"),
    ("Problem 1: non-凸 Robbins-Monro convergence率", "Problem 1: Non-convex Robbins-Monro Convergence Rate"),
    ("ProblemExact 陈述", "Precise Problem Statement"),
    ("loss景观的排列to称nessstructure", "Permutation Symmetry Structure of the Loss Landscape"),
    ("商space构造", "Quotient Space Construction"),
    ("排列商space", "Permutation Quotient Space"),
    ("等价relationship", "equivalence relation"),
    ("saddle point逃逸Analysis", "Saddle Point Escape Analysis"),
    ("rigoroussaddle pointness质", "Rigorous Saddle Point Properties"),
    ("严格鞍点", "strict saddle point"),
    ("convergence率upper bound", "Convergence Rate Upper Bound"),
    ("一般non-凸情形的convergence", "Convergence in the General Non-convex Case"),
    ("gradient范数meaninglower", "in terms of gradient norm"),
    ("一般non-凸情形", "general non-convex case"),
    ("Honest Critique", "Honest Critique"),
    ("convergence率lower bound", "Convergence Rate Lower Bound"),
    ("排列to称nesscauses的lower bound", "Lower Bound Induced by Permutation Symmetry"),
    ("排列to称stationary pointbetween的距离lower bound", "Lower Bound on Distance Between Permutation-Symmetric Stationary Points"),
    ("排列to称nesscurrently面利用", "Positive Exploitation of Permutation Symmetry"),
    ("to称ness简化Analysis", "Symmetry Simplifies Analysis"),
    ("实用value", "Practical Value"),
    ("Problem 1 Summary", "Problem 1 Summary"),
    ("coreConclusion", "Core Conclusion"),
    ("Problem 2: memory bankregret bound", "Problem 2: Memory Bank Regret Bound"),
    ("Online Learningform化", "Online Learning Formalization"),
    ("动作spaceand奖励", "Action Space and Reward"),
    ("memory bankupdate", "Memory Bank Update"),
    ("comparison基准: Optimal fixed strategy", "Comparison Baseline: Optimal Fixed Strategy"),
    ("动作spacesize变化", "Variable Action Space Size"),

    # Situser
    ("Situs (Physical Positional Encoding) physical realism verificationandapplicable scenarioAnalysis",
     "Situs (Physical Positional Encoding): Physical Realism Verification and Applicable Scenario Analysis"),
    ("Document Status: Honest Critique --- Unsparing", "Document Status: Honest Critique --- Unsparing"),
    ("第 1 part: physical realismcheck", "Part 1: Physical Realism Check"),
    ("蛋white质序列Locationencoding", "Protein Sequence Position Encoding"),
    ("相同氨基酸, 不同位置", "Same Amino Acid, Different Positions"),
    ("生物学事实", "Biological Fact"),
    ("物理判断", "Physical Judgment"),
    ("物理量", "Physical Quantity"),
    ("差异来源", "Source of Difference"),
    ("关键限制", "Key Limitation"),
    ("但是", "However"),
    ("根", "root"),
    ("缺陷", "flaw"),
    ("诚实结论", "Honest Conclusion"),
    ("α-螺旋 3.6 残基/圈periodicity", "Alpha-Helix 3.6 Residues per Turn Periodicity"),
    ("物理事实", "Physical Fact"),
    ("正弦编码能否捕获", "Can Sinusoidal Encoding Capture This"),
    ("但是标准Transformer编码做不到", "But Standard Transformer Encoding Cannot"),
    ("物理最优谱能否解决", "Can the Physically Optimal Spectrum Solve This"),
    ("根本问题", "Fundamental Problem"),
    ("内在无序区域中Situs的退化", "Degradation of Situs in Intrinsically Disordered Regions"),
    ("Situs在IDR上的行为", "Behavior of Situs on IDRs"),
    ("Situs退化为维度为d的加性噪声", "Situs degenerates to additive noise in d dimensions"),
    ("最坏场景", "Worst-Case Scenario"),
    ("材料3D结构位置编码", "Material 3D Structure Position Encoding"),
    ("V_N 空位形成能", "V_N Vacancy Formation Energy"),
    ("晶界 vs 体相 vs 表面", "Grain Boundary vs. Bulk vs. Surface"),
    ("物理事实 (DFT计算数据)", "Physical Facts (DFT Computational Data)"),
    ("形成能", "Formation Energy"),
    ("物理原因", "Physical Reason"),
    ("完整四面体配位", "Complete tetrahedral coordination"),
    ("断开", "Breaking"),
    ("表面弛豫释放应变能", "Surface relaxation releases strain energy"),
    ("晶界本征应力场", "Grain boundary intrinsic stress field"),
    ("多余体积", "excess volume"),
    ("悬挂键预存在", "pre-existing dangling bonds"),
    ("差异幅度", "Difference Magnitude"),
    ("决定性影响", "decisive impact"),
    ("物理因果链", "Physical Causal Chain"),
    ("清晰的因果箭头", "clear causal arrow"),
    ("自变量", "independent variable"),
    ("因变量", "dependent variable"),
    ("原因侧", "cause side"),
    ("信息论意义上严格且量大", "rigorous in the information-theoretic sense and substantial in magnitude"),
    ("可观", "substantial"),
    ("检测边际增益", "Detection Margin Gain"),
    ("收紧", "tightens"),
    ("物理上最有价值的应用场景", "physically most valuable application scenario"),
    ("主场", "home turf"),
    ("旋转编码的物理对称性检查", "Physical Symmetry Check of Rotational Encoding"),
    ("检验1: 平移不变性", "Check 1: Translation Invariance"),
    ("严格成立", "holds rigorously"),
    ("晶体的基本要求", "basic requirement of crystallography"),
    ("完美晶体", "perfect crystal"),
    ("检验2: 旋转等变性", "Check 2: Rotation Equivariance"),
    ("不成立", "does not hold"),
    ("全局旋转", "global rotation"),
    ("坐标轴", "coordinate axis"),
    ("分配", "assign"),
    ("不相交的维度对", "disjoint dimension pairs"),
    ("物理旋转混合了", "physical rotation mixes"),
    ("编码空间中没有对应的混合机制", "there is no corresponding mixing mechanism in the encoding space"),
    ("破坏后果", "Consequences of the Failure"),
    ("致命的", "fatal"),
    ("多晶/晶界系统", "polycrystal/grain boundary systems"),
    ("取向不同", "different orientations"),
    ("粒子动力学轨迹", "particle dynamics trajectories"),
    ("整体旋转", "overall rotation"),
    ("表面slab计算", "surface slab calculations"),
    ("不同切面", "different terminations"),
    ("可以修复吗", "Can It Be Fixed"),
    ("理论上可以", "theoretically possible"),
    ("替代方案", "Alternative approach"),
    ("球谐函数编码", "Spherical harmonic encoding"),
    ("代价", "Cost"),
    ("严格缺陷", "serious flaw"),
    ("受控场景", "controlled scenarios"),
    ("单晶", "single crystal"),
    ("固定取向", "fixed orientation"),
    ("取向已对齐", "orientations are aligned"),

    # MATHEMATICAL_GENEALOGY.tex
    ("Spring 自进化算法 --- 数学谱系学", "Spring Self-Evolution Algorithm --- Mathematical Genealogy"),
    ("地位", "Status"),
    ("文档类型", "Document Type"),
    ("数学领域归属、关键思想来源、历史发展脉络、与前人工作的对比", 
     "Mathematical Domain Attribution, Key Idea Sources, Historical Development Context, Comparison with Prior Work"),
    ("日期", "Date"),
    ("目录", "Table of Contents"),
    ("数学领域归属", "Mathematical Domain Attribution"),
    ("关键思想与证明工具", "Key Ideas and Proof Tools"),
    ("历史发展时间线", "Historical Development Timeline"),
    ("与前人的对比表", "Comparison Table with Prior Work"),
    ("独有的贡献", "Unique Contributions"),
    ("并非属于单一数学领域", "does not belong to a single mathematical domain"),
    ("而是跨越七个经典数学领域", "but rather spans seven classical mathematical domains"),
    ("在它们的交汇处合成全新结构", "synthesizing an entirely new structure at their intersection"),
    ("随机逼近", "Stochastic Approximation"),
    ("根源", "Origin"),
    ("角色", "Role"),
    ("在线更新遵循", "online update follows"),
    ("递归", "recursion"),
    ("其中学习率满足标准条件", "where the learning rate satisfies the standard conditions"),
    ("推广到", "generalized to"),
    ("耦合双时间尺度", "coupled two-time-scale"),
    ("快时间尺度", "Fast time scale"),
    ("慢时间尺度", "Slow time scale"),
    ("固定", "fixed"),
    ("更新", "updated"),
    ("速率", "rate"),
    ("准稳态", "quasi-steady state"),
    ("关键创新", "key innovation"),
    ("同时保证", "simultaneously ensures"),
    ("局部收敛", "local convergence"),
    ("累积分布偏移", "cumulative distribution shift"),
    ("动力系统 / Lyapunov 稳定性", "Dynamical Systems / Lyapunov Stability"),
    ("离散动力系统", "discrete dynamical system"),
    ("演化状态空间", "evolution state space"),
    ("候选", "candidate"),
    ("下降性质", "descent property"),
    ("完整证明", "fully proved"),
    ("不动点", "fixed point"),
    ("满足", "satisfies"),
    ("自洽耦合方程", "self-consistent coupling equations"),
    ("极限集为单点", "omega-limit set is a singleton"),
    ("工具链", "tool chain"),
    ("吸引子", "attractor"),
    ("盆地", "basin"),
    ("相图", "phase diagram"),
    ("四种收敛机制", "four convergence mechanisms"),

    # multi_head analysis
    ("Multi-Head Spring and Physical Positional Encoding rigorous mathematicalAnalysis",
     "Multi-Head Spring and Physical Positional Encoding: Rigorous Mathematical Analysis"),
    ("to SCX frameworkTheoremFoundation honest audit",
     "Honest Audit of the SCX Framework Theorem Foundation"),
    ("Notation Convention and Framework Reconstruction",
     "Notation Convention and Framework Reconstruction"),
    ("atentersAnalysis'sfront", "Before entering the analysis"),
    ("we firstExact reconstruct", "we first precisely reconstruct"),
    ("mathematicalFoundation", "mathematical foundations"),
    ("with lower has DefinitionuniformFrom prompt in the Theoremdescriberigorousform化",
     "Below we formalize all definitions from the theorem descriptions rigorously"),
    ("State Crystallization", "State Crystallization"),
    ("Status结晶", "State Crystallization"),
    ("setup原始physicalObservation Spaceis", "Let the raw physical observation space be"),
    ("continuousphysical quantity", "continuous physical quantities"),
    ("PBE energy面、力场、电子densedegree等", "PBE energy surfaces, force fields, electron density, etc."),
    ("State Crystallization is一 映射", "State Crystallization is a mapping"),
    ("where each s_i is一 discreteStatusatom的toward量representation",
     "where each s_i is a vector representation of a discrete state atom"),
    ("and BPE的统计驱动is different", "Unlike BPE's statistical driving"),
    ("isphysics-driven的", "it is physics-driven"),
    ("itaccording to PBE energy面的self-however曲率boundary进lines聚类",
     "it performs clustering based on the intrinsic curvature boundaries of the PBE energy surface"),
    ("formupperhas", "Formally"),
    ("Yajie Audit", "Yajie Audit"),
    ("Yajie审计", "Yajie Audit"),
    ("setuphas M independent专家model", "Let there be M independent expert models"),
    ("及itsLabel", "and its label"),
    ("consistentness计数", "Consistency count"),
    ("where p_s_i is专家''is different意''Label的probability",
     "where p_{s_i} is the probability that an expert disagrees with the label"),
    ("fordry净sample", "For clean samples"),
    ("fornoisesample", "For noisy samples"),
    ("Cercis Score", "Cercis Score"),
    ("where Q(s_i) isFoundationqualityseparate", "where Q(s_i) is the fundamental quality score"),
    ("N(s_i) isnew奇ness奖励", "N(s_i) is the novelty reward"),
    ("η(t) istimebetween衰subtract探索weight", "η(t) is the temporally decaying exploration weight"),
    ("Spring self-evolutiondynamics", "Spring Self-Evolution Dynamics"),
    ("Status转移", "State Transition"),
    ("Spring self-Note意力form", "Spring Self-Attention Form"),
    ("Core Theorems的Exact Theorem Statement", "Precise Theorem Statements of Core Theorems"),
    ("Theorem 1 (multi-expertconsistentnessnoise detection)", "Theorem 1 (Multi-Expert Consistency Noise Detection)"),
    ("Theorem 2 (weakCharacteristics必however失效)", "Theorem 2 (Necessary Failure of Weak Features)"),
    ("Theorem 3 (noise andDifficultysample的indistinguishability)", "Theorem 3 (Indistinguishability of Noise and Hard Samples)"),
    ("Theorem 4 (Exact 常数 Minimax Optimal )", "Theorem 4 (Exact Constant Minimax Optimality)"),

    # SCX_Undiscovered_Theorems
    ("SCX Framework: Undiscovered New Theoretical Directions",
     "SCX Framework: Undiscovered New Theoretical Directions"),
    ("Deep Deduction by Theoretical Architect", "Deep Deduction by Theoretical Architect"),
    ("深究是否还有未被发现的理论盲点", "Deep investigation into whether undiscovered theoretical blind spots remain"),
    ("量子SCX定理", "Quantum SCX Theorem"),
    ("量子传感下的远程审计", "Remote Audit under Quantum Sensing"),
    ("至今完全建立在经典信息论基础上", "has so far been built entirely on classical information theory foundations"),
    ("一个根本问题浮现", "a fundamental question arises"),
    ("量子不可克隆定理", "Quantum No-Cloning Theorem"),
    ("量子纠缠和Bell不等式", "Quantum Entanglement and Bell Inequalities"),
    ("更深层次", "At a deeper level"),
    ("量子推广是什么", "What is the quantum generalization"),
    ("变成了一个Hermitian算符", "becomes a Hermitian operator"),

    # theorems/01
    ("Theorem 1: Multi-Expert Consistency Guarantees for Label Noise Detection",
     "Theorem 1: Multi-Expert Consistency Guarantees for Label Noise Detection"),
    ("Core Claim", "Core Claim"),
    ("Revision History", "Revision History"),
    ("Lemma 3 Proofreconstruction", "Lemma 3 Proof Reconstruction"),
    ("Chernoff appendix KL directioncorrection", "Chernoff appendix KL direction correction"),
    ("two bug uniformfromVerification Report", "two bugs fixed per Verification Report"),
    ("Notation and Setup", "Notation and Setup"),
    ("setupwithlowerto象", "Set up the following objects"),

    # theorems/02
    ("Theorem 2: Weak Feature Failure", "Theorem 2: Weak Feature Failure"),
    ("Theorem 3: Unidentifiability", "Theorem 3: Unidentifiability"),
    ("沿using Theorem 1 Symbol/Concept体系", "Following the notation system of Theorem 1"),
    ("补充withlower记号", "supplemented with the following notation"),
    ("trueLabel (潜atvariable, **unobservable**)", "True label (latent variable, **unobservable**)"),
    ("observationLabel", "Observed label"),
    ("输入-dependence的noise率", "Input-dependent noise rate"),
    ("Latent Variable Model", "Latent Variable Model"),
    ("Data Generationbywithlower潜atprocess决determine", "Data generation is determined by the following latent process"),
    ("trueLabel y* by x throughnot知 Oracle f* generate", "True label y* is generated from x through the unknown oracle f*"),
    ("observationLabel y cancanbecausenoisebias离 y*", "Observed label y may deviate from y* due to noise"),
    ("专家prediction is x andtrainingdata的function", "Expert predictions are functions of x and training data"),
    ("Status s(x) is X to S 映射, describe输入的intrinsicCharacteristics", "State s(x) is a mapping from X to S, describing the intrinsic characteristics of the input"),
    ("Observation Space", "Observation Space"),
    ("研究oneonlycan访问", "The researcher can only access"),
    ("Nonemethod直接observation y*、s(x) ornoise指示variable", "Cannot directly observe y*, s(x), or the noise indicator variable"),
    ("Formal Statement", "Formal Statement"),
    ("Theorem 3 (Noise-Difficulty Unidentifiability)", "Theorem 3 (Noise-Difficulty Unidentifiability)"),
    ("构造ness反例method", "Constructive counterexample method"),
    ("Proof", "Proof"),
    ("Construction Framework", "Construction Framework"),
    ("世界 A: noise驱动 (Noise-Driven)", "World A: Noise-Driven"),
    ("世界 B: 难degree驱动 (Difficulty-Driven)", "World B: Difficulty-Driven"),
    ("清洁易懂", "clean and easy"),
    ("占比", "proportion"),
    ("概率", "probability"),
    ("翻转", "flipped"),
    ("准确率", "accuracy"),
    ("普遍困难", "generally difficult"),

    # situs_final_verification
    ("Situs theoretical finalVerification Report", "Situs Theoretical Final Verification Report"),
    ("Verification Date", "Verification Date"),
    ("Verification Files", "Verification Files"),
    ("Item-by-Item Check", "Item-by-Item Check"),
    ("两个文件都包含", "Both files contain"),
    ("都解释了", "both explain"),
    ("作用", "their role"),
    ("保证", "guarantee"),
    ("收敛到", "converges to"),
    ("非发散到", "does not diverge to"),
    ("L 是否已被去掉", "Has L been removed"),
    ("去掉了", "removed"),
    ("没有", "No"),
    ("通过", "through"),
    ("间接引入", "indirectly introduced"),
    ("没有出现在编码本身的框内公式中", "does not appear in the boxed formula of the encoding itself"),
    ("定理编号", "Theorem Number"),
    ("统一", "unified"),
    ("是否统一为", "unified to"),
    ("两者均", "Both"),
    ("使用", "use"),
    ("同时", "Meanwhile"),
    ("编号也一致", "numbering is also consistent"),
    ("是否修正为", "corrected to"),
    ("推导链完整", "Derivation chain is complete"),
    ("正确引用", "correctly cited"),
    ("覆盖整个序列区间需满足", "covering the full sequence interval requires"),
    ("关键变化", "Key Change"),
    ("从", "From"),
    ("变成了", "changed to"),
    ("特性", "Characteristic"),
    ("诚实标签", "Honesty Label"),
    ("警告框", "warning box"),
    ("明确声明", "Explicit Declaration"),
    ("逻辑错误注释", "Logical Error Annotation"),
    ("错误使用", "Incorrect Usage"),
    ("注释", "Note"),
    ("两个文件都很好地对齐", "Both files are well-aligned"),
    ("限制", "restricted"),
    ("到", "to"),
    ("各方面", "Aspect"),
    ("步骤标记", "Step Marked"),
    ("限制声明", "Limitation Statement"),
    ("退化声明", "Degradation Statement"),
    ("破坏方向", "Breaking Direction"),
    ("是否改为", "Changed to"),
    ("开放问题", "Open Problem"),
    ("定理陈述内", "Within Theorem Statement"),
    ("最小示例重新评估", "Minimal Example Re-Evaluation"),
    ("诚实度表", "Honesty Table"),
    ("符号不一致", "Notation Inconsistencies"),
    ("一致的项目", "Consistent Items"),
    ("状态", "Status"),
    ("预期差异（非问题）", "Expected Differences (Non-Issues)"),
    ("原因", "Reason"),
    ("评估", "Assessment"),
    ("格式差异", "Format difference"),
    ("残留不一致（需要关注）", "Residual Inconsistencies (Need Attention)"),
    ("摘要中的必要充分条件过度宣称", "Overclaim of Necessary and Sufficient Condition in Abstract"),
    ("问题", "Problem"),
    ("建议", "Recommendation"),
    ("双重陈述", "Dual Statement"),
    ("粗略形式", "Rough form"),
    ("精确形式", "Precise form"),
    ("混淆读者", "confuse readers"),
    ("两个形式不等价", "the two forms are not equivalent"),
]

# Additional single-character replacements (only process after multi-char)
# These are handled by the main replacement loop

def process_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original = content
    
    # Apply phrase replacements (longer patterns first - already sorted by length in our list)
    for old, new in PHRASES:
        content = content.replace(old, new)
    
    # Clean up whitespace artifacts
    content = re.sub(r' {2,}', ' ', content)
    content = re.sub(r' \.', '.', content)
    content = re.sub(r' ,', ',', content)
    content = re.sub(r' ;', ';', content)
    content = re.sub(r' :', ':', content)
    
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False

def main():
    count = 0
    for f in FILES:
        full = os.path.join(os.path.dirname(__file__) or '.', f)
        full = os.path.normpath(full)
        if not os.path.exists(full):
            full = os.path.join('F:', 'scx', f.replace('/', '\\'))
            full = os.path.normpath(full)
        if os.path.exists(full):
            changed = process_file(full)
            if changed:
                count += 1
                print(f"✓ {f}")
            else:
                print(f"- {f} (no changes)")
        else:
            print(f"✗ {f} NOT FOUND at {full}")
    print(f"\nTotal files modified: {count}/{len(FILES)}")

if __name__ == '__main__':
    main()
