#!/usr/bin/env python3
"""Batch translate Chinese -> English in theory/ .tex files."""

import re, os, sys

BASE = 'theory'

# ── Translation map: all Chinese→English replacements per file ──
# Format: {filepath: [(old_cn_string, new_en_string), ...]}
# Ordered longest-first within each file to avoid partial matches.

TRANSLATIONS = {}

# ────────────────────────────────────────────────────────────────
# 01_state_conditioned_risk.tex
# ────────────────────────────────────────────────────────────────
TRANSLATIONS['definitions/01_state_conditioned_risk.tex'] = [
    ('SCX 框架的核心数学对象定义文档。定义状态、状态条件专家风险、SCX 可靠性、数据价值等基本概念。',
     'Core mathematical object definitions for the SCX framework. Defines states, state-conditioned expert risk, SCX reliability, data value, and other fundamental concepts.'),
    ('状态 \\(s\\) 是输入空间 \\(\\mathcal{X}\\) 的一个可测子集。状态划分',
     'A state \\(s\\) is a measurable subset of the input space \\(\\mathcal{X}\\). The state partition'),
    ('即 \\(\\phi(X)\\) 是 \\(Y\\) 关于 \\(X\\) 的\\textbf{近似充分统计量}。',
     'That is, \\(\\phi(X)\\) is an \\textbf{approximate sufficient statistic} for \\(Y\\) given \\(X\\).'),
    ('软状态赋值函数 \\(\\gamma: \\mathcal{X} \\times \\mathcal{S} \\to [0,1]\\)\n满足：',
     'The soft state assignment function \\(\\gamma: \\mathcal{X} \\times \\mathcal{S} \\to [0,1]\\)\nsatisfies:'),
    ('常见实现方式：', 'Common implementations:'),
    ('后验概率', 'Posterior probability'),
    ('加权', 'Weighting'),
    ('专家 \\(f_m\\) 在输入 \\(x\\) 处的点态风险：',
     'The pointwise risk of expert \\(f_m\\) at input \\(x\\) is:'),
    ('其中 \\(\\ell: \\mathcal{Y} \\times \\mathcal{Y} \\to \\mathbb{R}_{\\ge 0}\\)\n为损失函数，\\(f^*: \\mathcal{X} \\to \\mathcal{Y}\\) 为真实标注函数。',
     'where \\(\\ell: \\mathcal{Y} \\times \\mathcal{Y} \\to \\mathbb{R}_{\\ge 0}\\)\nis the loss function, and \\(f^*: \\mathcal{X} \\to \\mathcal{Y}\\) is the true labeling function.'),
    ('这是 Kolmogorov 意义下的条件期望。由 Radon-Nikodym 定理保证存在性：',
     'This is the conditional expectation in the sense of Kolmogorov. Existence is guaranteed by the Radon-Nikodym theorem:'),
    ('当 \\(P(X \\in s) = 0\\) 时，\\(R_m(s)\\) 可定义为',
     'When \\(P(X \\in s) = 0\\), \\(R_m(s)\\) can be defined as'),
    ('的 \\(\\epsilon\\)-邻域。', 'the \\(\\epsilon\\)-neighborhood of \\(s\\).'),
    ('专家风险 \\(R_m(s)\\) 衡量专家 \\(f_m\\) 相对于\\textbf{不可知最优} \\(f^*\\)\n的表现，而非相对于 \\(R^*(s)\\)。',
     'The expert risk \\(R_m(s)\\) measures the performance of expert \\(f_m\\) relative to the \\textbf{unknowable optimum} \\(f^*\\),\nrather than relative to \\(R^*(s)\\).'),
    ('对于平方损失 \\(\\ell(\\hat{y}, y) = (\\hat{y} - y)^2\\)，令回归函数',
     'For squared loss \\(\\ell(\\hat{y}, y) = (\\hat{y} - y)^2\\), let the regression function be'),
    ('近似误差', 'Approximation error'),
    ('目标噪声', 'Target noise'),
    ('在 \\(f^* = r\\) 的特殊情况下得到\\textbf{条件偏差-方差分解}：',
     'In the special case \\(f^* = r\\), we obtain the \\textbf{conditional bias-variance decomposition}:'),
    ('其中 \\(\\tau > 0\\) 为可靠性阈值。经验估计为：',
     'where \\(\\tau > 0\\) is the reliability threshold. The empirical estimate is:'),
    ('SCX 的 \\(SCX_m(s)\\) 可以映射到 Rasch 模型：',
     'The SCX \\(SCX_m(s)\\) can be mapped to the Rasch model:'),
    ('其中 \\(\\theta_s\\) 是状态 \\(s\\) 的\'\'可处理性\'\'参数，\\(b_m\\) 是专家 \\(m\\)\n的能力阈值。',
     'where \\(\\theta_s\\) is the \'\'tractability\'\' parameter of state \\(s\\), and \\(b_m\\) is the ability threshold of expert \\(m\\).'),
    ('各因子含义：', 'Meaning of each factor:'),
    ('因子', 'Factor'),
    ('符号', 'Symbol'),
    ('含义', 'Meaning'),
    ('范围', 'Range'),
    ('平均残差', 'Average residual'),
    ('状态 \\(s\\) 的当前平均预测误差', 'Current average prediction error of state \\(s\\)'),
    ('状态概率', 'State probability'),
    ('状态 \\(s\\) 的出现概率 \\(P(x \\in s)\\)', 'Occurrence probability \\(P(x \\in s)\\) of state \\(s\\)'),
    ('可学习性', 'Learnability'),
    ('状态 \\(s\\) 的性能可改善程度', 'Degree to which performance in state \\(s\\) can be improved'),
    ('多样性惩罚', 'Diversity penalty'),
    ('状态 \\(s\\) 的未饱和程度（\\(D\\)=冗余度）', 'Degree of unsaturation of state \\(s\\) (\\(D\\) = redundancy)'),
    ('专家覆盖', 'Expert coverage'),
    ('最佳专家在状态 \\(s\\) 上的可靠性', 'Reliability of the best expert on state \\(s\\)'),
    ('SCX 的 \\(V(s)\\) 是一个\\textbf{代理 Shapley 值}，它将数据点级别的 Shapley\n值计算分解为： - 先聚合成状态 \\(s\\)（复杂度 \\(O(2^{|S|})\\)，其中\n\\(|S| \\ll N\\)） - 再使用乘法分解（五个可解释因子的乘积）',
     'SCX\'s \\(V(s)\\) is a \\textbf{proxy Shapley value} that decomposes the per-data-point Shapley\nvalue computation into: first aggregating into states \\(s\\) (complexity \\(O(2^{|S|})\\), where\n\\(|S| \\ll N\\)), then using a multiplicative decomposition (product of five interpretable factors).'),
    ('其中 \\(C(s)\\) 为状态 \\(s\\) 的内部一致性：',
     'where \\(C(s)\\) is the internal consistency of state \\(s\\):'),
    ('其中\n\\(R(f|s) = \\mathbb{E}[\\ell(f(X), Y) | X \\in s]\\)，\\(R^*(s) = \\inf_f R(f|s)\\)\n是贝叶斯风险。\\(L(s) \\to 0\\) 表示状态在现有函数类 \\(\\mathcal{F}\\)\n下不可学习。',
     'where\n\\(R(f|s) = \\mathbb{E}[\\ell(f(X), Y) | X \\in s]\\), and \\(R^*(s) = \\inf_f R(f|s)\\)\nis the Bayes risk. \\(L(s) \\to 0\\) indicates that the state is unlearnable under the current function class \\(\\mathcal{F}\\).'),
    ('状态冗余度估计：', 'State redundancy estimate:'),
    ('其中 \\(\\text{Sim}(s)\\) 为状态内部相似度，\\(\\text{Boundary}(s)\\)\n为边界样本比例。',
     'where \\(\\text{Sim}(s)\\) is the intra-state similarity, and \\(\\text{Boundary}(s)\\)\nis the proportion of boundary samples.'),
    ('归一化保证 \\(\\sum_{m=1}^M w_m(x) = 1\\)，\\(\\alpha > 0\\) 为逆温度参数。',
     'Normalization ensures \\(\\sum_{m=1}^M w_m(x) = 1\\), with \\(\\alpha > 0\\) as the inverse temperature parameter.'),
    ('设 \\(\\ell \\in [0, L_{\\max}]\\)，状态 \\(s\\) 有 \\(n_s\\) 个样本。对任意\n\\(\\delta > 0\\)，以概率至少 \\(1 - \\delta\\)：',
     'Let \\(\\ell \\in [0, L_{\\max}]\\) and let state \\(s\\) have \\(n_s\\) samples. For any\n\\(\\delta > 0\\), with probability at least \\(1 - \\delta\\):'),
    ('存在分布使得任意估计器 \\(\\hat{R}_m(s)\\) 满足：',
     'There exists a distribution such that any estimator \\(\\hat{R}_m(s)\\) satisfies:'),
    ('其中 \\(\\sigma^2(s) = \\text{Var}(\\ell(f_m(X), f^*(X)) \\mid X \\in s)\\)。',
     'where \\(\\sigma^2(s) = \\text{Var}(\\ell(f_m(X), f^*(X)) \\mid X \\in s)\\).'),
    ('符号表', 'Notation Table'),
    ('输入空间', 'Input space'),
    ('度量空间', 'Metric space'),
    ('标签空间', 'Label space'),
    ('真实标注函数', 'True labeling function'),
    ('未知 oracle', 'Unknown oracle'),
    ('第 \\(m\\) 个专家模型', 'The \\(m\\)-th expert model'),
    ('可计算函数', 'Computable function'),
    ('专家总数', 'Total number of experts'),
    ('状态空间', 'State space'),
    ('单个状态', 'A single state'),
    ('的可测子集', 'measurable subset of'),
    ('状态软赋值', 'State soft assignment'),
    ('损失函数', 'Loss function'),
    ('可靠性阈值', 'Reliability threshold'),
    ('状态条件专家风险', 'State-conditioned expert risk'),
    ('SCX 可靠性指标', 'SCX reliability metric'),
    ('状态数据价值', 'State data value'),
    ('状态平均残差', 'State average residual'),
    ('内部一致性', 'Internal consistency'),
    ('噪声比例', 'Noise proportion'),
    ('冗余度', 'Redundancy'),
    ('嵌入映射', 'Embedding mapping'),
    ('逆温度参数', 'Inverse temperature parameter'),
    ('回归函数 \\(\\mathbb{E}[Y \\mid X=x]\\)', 'Regression function \\(\\mathbb{E}[Y \\mid X=x]\\)'),
    ('条件贝叶斯风险', 'Conditional Bayes risk'),
    ('SCX 核心框架数学分析', 'SCX Core Framework Mathematical Analysis'),
    ('SCX 数学基础与证明建构', 'SCX Mathematical Foundations and Proof Construction'),
    ('参考文献', 'References'),
    ('状态条件的数学本质是找到一个映射', 'The mathematical essence of the state partition is finding a mapping'),
    ('Borel \\(\\sigma\\)-代数中的可测集', 'Borel \\(\\sigma\\)-algebra'),
    ('与 IRT 的关系', 'Relationship to IRT'),
    ('与 Shapley 值的关系', 'Relationship to Shapley Values'),
    ('与 UCB bandit 的联系', 'Connection to UCB Bandit'),
    ('收敛性质', 'Convergence Properties'),
    ('经验风险估计的集中性', 'Concentration of Empirical Risk Estimates'),
    ('最小最大下界', 'Minimax Lower Bound'),
]

# ────────────────────────────────────────────────────────────────
# a2_correlation_analysis.tex
# ────────────────────────────────────────────────────────────────
TRANSLATIONS['explorations/a2_correlation_analysis.tex'] = [
    ('\\textbf{触发}: Hostile review 指出 A2 ``几乎肯定为假，是整个框架的\nAchilles 之踵\'\' \\textbf{结论}:\n诊断正确，但可以修复。替换为弱相关集中不等式，降价退化速率。',
     '\\textbf{Trigger}: Hostile review points out that A2 is ``almost certainly false, the Achilles heel of the entire framework.\'\' \\textbf{Conclusion}:\nThe diagnosis is correct, but it can be repaired. Replace with weakly-correlated concentration inequality, which degrades the rate gracefully.'),
    ('问题确诊', 'Problem Diagnosis'),
    ('条件独立', 'Conditional independence'),
    ('如果专家错误之间存在条件相关 \\(\\rho > 0\\)（给定状态 \\(s\\)）: - CNN:\n所有专家在模糊图像上一起错 - MLIP: 所有专家在过渡态构型上一起错 -\n有效独立专家数: \\(M_{\\text{eff}} \\approx M / (1 + (M-1)\\rho)\\)',
     'If expert errors are conditionally correlated \\(\\rho > 0\\) (given state \\(s\\)): - CNN:\nAll experts err together on blurry images - MLIP: All experts err together on transition-state configurations -\nEffective number of independent experts: \\(M_{\\text{eff}} \\approx M / (1 + (M-1)\\rho)\\)'),
    ('指数增益几乎消失。', 'the exponential gain nearly vanishes.'),
    ('\\textbf{CIFAR-10 实验证据}: 理论下界 F1≥0.976（假定的独立情况），实测\nF1=0.617。差距无法仅用 \\(\\mu_s\\) 估计误差解释。',
     '\\textbf{CIFAR-10 experimental evidence}: Theoretical lower bound F1≥0.976 (under assumed independence), empirical\nF1=0.617. The gap cannot be explained solely by \\(\\mu_s\\) estimation error.'),
    ('\\textbf{AlN 实验证据}: 全局界 F1≥0.87 匹配经验值。但仅当\n\\(\\rho \\lesssim 0.02\\) 时才成立------这是一个极弱的假设，需要验证。',
     '\\textbf{AlN experimental evidence}: Global bound F1≥0.87 matches empirical value. But this holds only when\n\\(\\rho \\lesssim 0.02\\) --- this is an extremely weak assumption that needs verification.'),
    ('修复方案', 'Repair Strategy'),
    ('诚实化 A2', 'Honestifying A2'),
    ('\\textbf{旧 A2}: 给定 \\(x\\) 下，专家错误 \\(\\{e_m\\}\\) 条件独立。',
     '\\textbf{Old A2}: Given \\(x\\), expert errors \\(\\{e_m\\}\\) are conditionally independent.'),
    ('\\textbf{新 A2\'}: 给定状态 \\(s\\) 下，专家错误 \\(\\{e_m\\}\\)\n的条件相关系数有界:',
     '\\textbf{New A2\'}: Given state \\(s\\), the conditional correlation coefficients of expert errors \\(\\{e_m\\}\\)\nare bounded:'),
    ('当 \\(\\bar{\\rho} = 0\\) 时恢复旧 A2。', 'When \\(\\bar{\\rho} = 0\\), the old A2 is recovered.'),
    ('弱相关集中不等式', 'Weakly-Correlated Concentration Inequality'),
    ('\\textbf{Lemma 2\' (弱相关 Hoeffding)}. 设 \\(\\{e_m\\}_{m=1}^M\\) 为\n\\([0,1]\\)-值随机变量，满足 \\(\\mathbb{E}[e_m \\mid s] \\leq \\mu_s\\)，且\n\\(\\text{Cov}(e_m, e_{m\'} \\mid s) \\leq \\rho \\cdot \\sqrt{\\text{Var}(e_m) \\text{Var}(e_{m\'})}\\)，其中\n\\(\\rho \\in [0, 1)\\)。则:',
     '\\textbf{Lemma 2\' (Weakly-Correlated Hoeffding)}. Let \\(\\{e_m\\}_{m=1}^M\\) be\n\\([0,1]\\)-valued random variables satisfying \\(\\mathbb{E}[e_m \\mid s] \\leq \\mu_s\\), with\n\\(\\text{Cov}(e_m, e_{m\'} \\mid s) \\leq \\rho \\cdot \\sqrt{\\text{Var}(e_m) \\text{Var}(e_{m\'})}\\), where\n\\(\\rho \\in [0, 1)\\). Then:'),
    ('\\textbf{证明}:\n对相关随机变量，\\(\\text{Var}(\\sum_m e_m \\mid s) = \\sum_m \\text{Var}(e_m) + \\sum_{m \\neq m\'} \\text{Cov}(e_m, e_{m\'}) \\leq M\\sigma^2(1 + (M-1)\\rho)\\)，其中\n\\(\\sigma^2 = \\max_m \\text{Var}(e_m) \\leq 1/4\\)。应用 Bentkus (2004) 或\nvan de Geer \\& Lederer (2013) 的弱相关 Hoeffding 界。\\(\\square\\)',
     '\\textbf{Proof}:\nFor correlated random variables, \\(\\text{Var}(\\sum_m e_m \\mid s) = \\sum_m \\text{Var}(e_m) + \\sum_{m \\neq m\'} \\text{Cov}(e_m, e_{m\'}) \\leq M\\sigma^2(1 + (M-1)\\rho)\\), where\n\\(\\sigma^2 = \\max_m \\text{Var}(e_m) \\leq 1/4\\). Apply the weakly-correlated Hoeffding bound of Bentkus (2004) or\nvan de Geer \\& Lederer (2013). \\(\\square\\)'),
    ('修正后的 Theorem 1', 'Corrected Theorem 1'),
    ('是状态 \\(s\\) 内的\\textbf{最大专家错误相关系数}。', 'is the \\textbf{maximum expert error correlation coefficient} within state \\(s\\).'),
    ('退化速率', 'Degradation rate'),
    ('原界', 'Original bound'),
    ('轻微', 'Mild'),
    ('中度', 'Moderate'),
    ('显著', 'Significant'),
    ('严重', 'Severe'),
    ('指数增益消失', 'Exponential gain vanishes'),
    ('\\textbf{关键推论}: 即使 \\(\\bar{\\rho}_s = 0.05\\)（轻微相关），\\(M=12\\)\n仍然相当于 7.7 个独立专家------指数收敛依然成立，只是常数稍大。',
     '\\textbf{Key Corollary}: Even with \\(\\bar{\\rho}_s = 0.05\\) (mild correlation), \\(M=12\\)\nstill corresponds to 7.7 independent experts --- exponential convergence still holds, just with a slightly larger constant.'),
    ('的可检验性', 'Testability of'),
    ('与旧 A2 不同，A2\' 是\\textbf{可检验的}: 1. 对每个状态\n\\(s\\)，计算专家错误矩阵 \\(E_s \\in \\{0,1\\}^{n_s \\times M}\\) 2.\n估计成对相关系数 \\(\\hat{\\rho}_{mm\'}^{(s)}\\) 3. 取\n\\(\\hat{\\bar{\\rho}}_s = \\max_{m \\neq m\'} \\hat{\\rho}_{mm\'}^{(s)}\\) 4. 如果\n\\(\\hat{\\bar{\\rho}}_s \\geq 0.5\\)，发出 A2\' 违反警告',
     'Unlike old A2, A2\' is \\textbf{testable}: 1. For each state\n\\(s\\), compute the expert error matrix \\(E_s \\in \\{0,1\\}^{n_s \\times M}\\) 2.\nEstimate pairwise correlation coefficients \\(\\hat{\\rho}_{mm\'}^{(s)}\\) 3. Take\n\\(\\hat{\\bar{\\rho}}_s = \\max_{m \\neq m\'} \\hat{\\rho}_{mm\'}^{(s)}\\) 4. If\n\\(\\hat{\\bar{\\rho}}_s \\geq 0.5\\), issue an A2\' violation warning'),
    ('\\textbf{AlN v3 估计}: 在 8 个状态上估计\n\\(\\hat{\\bar{\\rho}}_s\\)（待实验验证），预期在 thermal 状态上\n\\(\\hat{\\bar{\\rho}} \\lesssim 0.05\\)（因为每个专家在不同子集上训练）。',
     '\\textbf{AlN v3 Estimate}: Estimate\n\\(\\hat{\\bar{\\rho}}_s\\) over 8 states (pending experimental verification), expecting\n\\(\\hat{\\bar{\\rho}} \\lesssim 0.05\\) on thermal states (since each expert is trained on a different subset).'),
    ('对 Theorem 4\' (Exact Constant Minimax) 的影响', 'Impact on Theorem 4\' (Exact Constant Minimax)'),
    ('问题', 'Problem'),
    ('Theorem 4\' 使用 Bahadur-Rao 精确渐近，要求 i.i.d. Bernoulli\n专家错误。如果存在相关:',
     'Theorem 4\' uses Bahadur-Rao exact asymptotics, requiring i.i.d. Bernoulli\nexpert errors. If correlation exists:'),
    ('Bahadur-Rao 的渐近展开需要修正: 实际方差被放大 \\((1+(M-1)\\rho)\\) 倍。',
     'The Bahadur-Rao asymptotic expansion needs correction: the actual variance is amplified by a factor of \\((1+(M-1)\\rho)\\).'),
    ('修正', 'Correction'),
    ('\\textbf{修正的 Bahadur-Rao} (相关 Bernoulli):',
     '\\textbf{Corrected Bahadur-Rao} (Correlated Bernoulli):'),
    ('相关使有效样本量减少，但\\textbf{指数速率 \\(\\kappa\\) 不变}（Chernoff\n信息只依赖于边际分布，不依赖相关性）。',
     'Correlation reduces the effective sample size, but \\textbf{the exponential rate \\(\\kappa\\) is unchanged} (Chernoff\ninformation depends only on marginal distributions, not on correlation).'),
    ('\\textbf{关键结论}: 精确常数 \\(C_{\\min}\\) 需要乘以 \\(\\sqrt{1+(M-1)\\rho}\\)\n的修正因子------但这不影响\\textbf{速率最优性}（liminf\n的指数不变）和\\textbf{常数最优性}（只要修正后的常数对所有算法都适用）。',
     '\\textbf{Key Conclusion}: The exact constant \\(C_{\\min}\\) needs to be multiplied by a correction factor \\(\\sqrt{1+(M-1)\\rho}\\)\n--- but this does not affect \\textbf{rate optimality} (the liminf\nexponent is unchanged) nor \\textbf{constant optimality} (as long as the corrected constant applies to all algorithms).'),
    ('对 Theorem 2 的影响', 'Impact on Theorem 2'),
    ('Theorem 2 的 Fano-Pinsker-TV 链\\textbf{不依赖 A2}------只依赖特征\n\\(\\phi\\) 和状态 \\(S\\) 之间的互信息。专家相关不影响这个 bound。',
     'Theorem 2\'s Fano-Pinsker-TV chain \\textbf{does not depend on A2} --- it only depends on the mutual information between features\n\\(\\phi\\) and states \\(S\\). Expert correlation does not affect this bound.'),
    ('对 Theorem 3 的影响', 'Impact on Theorem 3'),
    ('Theorem 3 的构造（世界 A vs 世界 B）\\textbf{在 A2\'\n下仍然成立}------两个世界都可以容纳相关专家。不可识别性结论不受影响。',
     'Theorem 3\'s construction (World A vs World B) \\textbf{still holds under A2\'}\n--- both worlds can accommodate correlated experts. The unidentifiability conclusion is unaffected.'),
    ('诚实结论', 'Honest Conclusions'),
    ('定理', 'Theorem'),
    ('A2 依赖程度', 'A2 Dependence'),
    ('关联影响', 'Correlation Impact'),
    ('修正难度', 'Repair Difficulty'),
    ('高', 'High'),
    ('无', 'None'),
    ('无需修正', 'No correction needed'),
    ('中等（替换 Hoeffding）', 'Moderate (replace Hoeffding)'),
    ('精确常数修正 \\(\\sqrt{1+(M-1)\\rho}\\)', 'Exact constant correction \\(\\sqrt{1+(M-1)\\rho}\\)'),
    ('中等（Bahadur-Rao 相关版本）', 'Moderate (correlated Bahadur-Rao version)'),
    ('\\textbf{总体}: A2 是框架最脆弱的假设，但可以修复为\nA2\'（弱相关）而不改变核心结论的方向。指数速率仍然成立，只是有效专家数从\n\\(M\\) 降为\n\\(M_{\\text{eff}}\\)。在实践中，两层状态发现\\textbf{降低}了专家相关（因为状态内特征同质），但不能\\textbf{消除}它。',
     '\\textbf{Overall}: A2 is the framework\'s most fragile assumption, but can be repaired to\nA2\' (weak correlation) without changing the direction of core conclusions. The exponential rate still holds; only the effective number of experts drops from\n\\(M\\) to\n\\(M_{\\text{eff}}\\). In practice, two-layer state discovery \\textbf{reduces} expert correlation (because intra-state features are homogeneous), but cannot \\textbf{eliminate} it.'),
    ('\\textbf{向审稿人的诚实回应}: ``We acknowledge that A2 (conditional\nindependence) is the strongest and least verifiable assumption in the\nframework. We relax it to A2\' (bounded correlation) and provide the\ndegraded bound. Under A2\', the exponential rate is preserved but with\neffective expert count \\(M_{\\text{eff}} = M/(1+(M-1)\\bar{\\rho})\\). We\nprovide a procedure for estimating \\(\\bar{\\rho}\\) from data.\'\'',
     '\\textbf{Honest Response to Reviewer}: ``We acknowledge that A2 (conditional\nindependence) is the strongest and least verifiable assumption in the\nframework. We relax it to A2\' (bounded correlation) and provide the\ndegraded bound. Under A2\', the exponential rate is preserved but with\neffective expert count \\(M_{\\text{eff}} = M/(1+(M-1)\\bar{\\rho})\\). We\nprovide a procedure for estimating \\(\\bar{\\rho}\\) from data.\'\''),
    ('数值验证：AlN 数据的相关性', 'Numerical Verification: Correlation in AlN Data'),
    ('（待跑实验。预期：两层状态发现后，每个状态内专家错误的相关性应该很低------因为专家在不同子集上训练，且状态内样本分布同质。如果\nthermal 状态的 \\(\\hat{\\bar{\\rho}} \\gtrsim 0.1\\)，则当前 \\(M=12\\)\n不够，需要增加到 \\(M \\approx 20\\)。）',
     '(Experiments pending. Expectation: after two-layer state discovery, the correlation of expert errors within each state should be low --- because experts are trained on different subsets and intra-state sample distributions are homogeneous. If\nthe thermal state has \\(\\hat{\\bar{\\rho}} \\gtrsim 0.1\\), then the current \\(M=12\\)\nis insufficient and should be increased to \\(M \\approx 20\\).)'),
    ('关联', 'Related'),
]

# ────────────────────────────────────────────────────────────────
# a2_rigorous_analysis.tex
# ────────────────────────────────────────────────────────────────
TRANSLATIONS['explorations/a2_rigorous_analysis.tex'] = [
    ('触发: hostile review 指出 \\(\\exp(-2M\\Delta^2/(1+(M-1)\\rho))\\)\n不是严格定理 结论: 正确。方差膨胀代入 Hoeffding\n是指启发式，不是严格界。但 A2 本身有更强的论证。',
     'Trigger: hostile review points out that \\(\\exp(-2M\\Delta^2/(1+(M-1)\\rho))\\)\nis not a rigorous theorem. Conclusion: correct. Plugging variance inflation into Hoeffding\nis a heuristic, not a rigorous bound. But A2 itself has stronger justification.'),
    ('的严格数学分析', '--- Rigorous Mathematical Analysis'),
    ('是不是严格定理？', '--- Is It a Rigorous Theorem?'),
    ('\\textbf{不是。}', '\\textbf{No.}'),
    ('Hoeffding 不等式的证明依赖:', 'The proof of Hoeffding\'s inequality depends on:'),
    ('这个\\textbf{因式分解}要求 \\(\\{X_i\\}\\) 独立。如果 \\(X_i\\) 相关，MGF\n不能因式分解，你不能简单地把 \\(M\\) 替换成 \\(M/(1+(M-1)\\rho)\\)\n就得到严格指数界。',
     'This \\textbf{factorization} requires \\(\\{X_i\\}\\) to be independent. If \\(X_i\\) are correlated, the MGF\ncannot be factorized, and you cannot simply substitute \\(M/(1+(M-1)\\rho)\\) for \\(M\\)\nto obtain a rigorous exponential bound.'),
    ('方差膨胀 \\((1+(M-1)\\rho)\\) 对 \\textbf{\\(\\text{Var}(\\sum X_i)\\)}\n是正确的，但对 \\textbf{指数集中} 不正确。方差只给 Chebyshev\n界（多项式速率 \\(1/t^2\\)），不是指数界。',
     'Variance inflation \\((1+(M-1)\\rho)\\) is correct for \\textbf{\\(\\text{Var}(\\sum X_i)\\)}\nbut not for \\textbf{exponential concentration}. Variance only gives a Chebyshev\nbound (polynomial rate \\(1/t^2\\)), not an exponential bound.'),
    ('\\textbf{结论}: 方差膨胀 Hoeffding\n是启发式（heuristic），在调查抽样和群组随机试验中广泛使用，但不是数学定理。把它写进\nSI 会被审稿人抓。',
     '\\textbf{Conclusion}: The variance-inflated Hoeffding\nis a heuristic, widely used in survey sampling and cluster randomized trials, but it is not a mathematical theorem. Writing it into the\nSI will get caught by reviewers.'),
    ('那 A2 本身到底站不站得住？', 'So Does A2 Itself Hold Up or Not?'),
    ('更强的论证: A1 蕴含 A2', 'A Stronger Argument: A1 Implies A2'),
    ('A1 说: \\(M\\) 个专家在\\textbf{不相交的独立同分布子集}上训练。',
     'A1 states: \\(M\\) experts are trained on \\textbf{disjoint i.i.d. subsets}.'),
    ('每个 \\(f_m = \\mathcal{A}(D_m)\\) 是训练算法 \\(\\mathcal{A}\\)\n作用于数据子集 \\(D_m\\) 的\\textbf{确定函数}。',
     'Each \\(f_m = \\mathcal{A}(D_m)\\) is a \\textbf{deterministic function} of training algorithm \\(\\mathcal{A}\\)\napplied to data subset \\(D_m\\).'),
    ('因为 \\(D_1, \\dots, D_M\\) 是独立随机变量，\\(f_1, \\dots, f_M\\)\n也是独立的随机函数。',
     'Since \\(D_1, \\dots, D_M\\) are independent random variables, \\(f_1, \\dots, f_M\\)\nare also independent random functions.'),
    ('对任意固定的测试点 \\(x\\):', 'For any fixed test point \\(x\\):'),
    ('\\textbf{A2 不是假设------它是 A1 的推论。}', '\\textbf{A2 is not an assumption --- it is a corollary of A1.}'),
    ('概率空间是什么？', 'What Is the Probability Space?'),
    ('Hoeffding\n界的概率空间是\\textbf{训练数据的随机性}，不是测试数据的随机性。',
     'The probability space of the Hoeffding\nbound is the \\textbf{randomness of training data}, not the randomness of test data.'),
    ('意思是: 如果你随机划分训练数据 \\(M\\) 次、独立训练 \\(M\\)\n个专家，得到的专家集以高概率具有好的噪声检测性质。',
     'Meaning: if you randomly partition training data \\(M\\) times and independently train \\(M\\)\nexperts, the resulting expert ensemble has good noise-detection properties with high probability.'),
    ('\\textbf{训练完成后}，你有一组固定的专家。对于给定的测试样本\n\\(x\\)，\\(C(x)\\) 是一个确定性的数。Hoeffding 不适用。',
     '\\textbf{After training}, you have a fixed set of experts. For a given test sample\n\\(x\\), \\(C(x)\\) is a deterministic number. Hoeffding does not apply.'),
    ('但这不削弱定理------所有的泛化界都有这个性质。定理告诉你\'\'这个\\textbf{方法}是好的\'\'，不是\'\'这组\\textbf{特定专家}是好的\'\'。',
     'But this does not weaken the theorem --- all generalization bounds have this property. The theorem tells you ``this \\textbf{method} is good,\'\' not ``this \\textbf{specific ensemble} is good.\'\''),
    ('Hostile reviewer 的反驳为什么不对', 'Why the Hostile Reviewer\'s Objection Is Wrong'),
    ('这是在说: \\textbf{给定已经训练好的\nCNN}，它们在模糊图像上的确定行为是一致的。',
     'This is saying: \\textbf{given already-trained\nCNNs}, their deterministic behavior on blurry images is consistent.'),
    ('但 Hoeffding 问的是:\n\\textbf{在训练之前}，随机划分数据并独立训练后，你有多大把握得到一组能检测噪声的专家？',
     'But what Hoeffding asks is:\n\\textbf{before training}, after randomly partitioning data and independently training, how confident are you of obtaining an ensemble that can detect noise?'),
    ('两者不在同一个概率空间里。Hostile reviewer\n混淆了\\textbf{训练后确定性行为}和\\textbf{训练前概率保证}。',
     'These two are not in the same probability space. The hostile reviewer\nconfuses \\textbf{post-training deterministic behavior} with \\textbf{pre-training probabilistic guarantee}.'),
    ('但仍有一个残留问题', 'But There Remains a Residual Issue'),
    ('即使 A2 严格成立（作为 A1 的推论），\\textbf{估计} \\(\\mu_s\\)\n仍然需要清洁标签。在有限样本下，\\(\\hat{\\mu}_s\\) 的误差会转化为\n\\(\\hat{\\Delta}_s\\)\n的误差。这是\\textbf{有限样本估计问题}，不是\\textbf{独立性假设问题}。推论\n4（有限样本校正）已经用保守上界处理了这个问题。',
     'Even if A2 holds rigorously (as a corollary of A1), \\textbf{estimating} \\(\\mu_s\\)\nstill requires clean labels. In finite samples, errors in \\(\\hat{\\mu}_s\\) translate into\nerrors in \\(\\hat{\\Delta}_s\\).\nThis is a \\textbf{finite-sample estimation problem}, not an \\textbf{independence assumption problem}. Corollary\n4 (finite-sample correction) already handles this with a conservative upper bound.'),
    ('诚实的修改建议', 'Honest Revision Suggestions'),
    ('不要引入 A2\'', 'Do Not Introduce A2\''),
    ('方差膨胀 Hoeffding 是启发式，不够格写进定理陈述。保持原有的\nA2，但\\textbf{在正文和 SI 中诚实讨论}。',
     'The variance-inflated Hoeffding is a heuristic and is not qualified for theorem statements. Keep the original\nA2, but \\textbf{discuss it honestly in the main text and SI}.'),
    ('在 SI 中加一节 ``On the Role of Assumption A2\'\'', 'Add a Section ``On the Role of Assumption A2\'\' in the SI,'),
    ('内容: 1. A2 实际上是 A1 的推论（不相交训练集 → 独立专家 → 独立错误） 2.\n概率空间是训练随机性，不是测试行为 3. 有限样本下 \\(\\mu_s\\)\n的估计误差有独立处理（推论 4） 4.\n在实践中，专家错误可能表现出表面相关（同一张模糊图），但这反映的是特征相似性导致相似的\n\\(\\mu_s\\)，而非统计相关性 5. 对 A2 的经验诊断:\n在验证集上估计专家错误的条件相关系数；如果显著偏离零，检查训练集是否真的不相交',
     'Contents: 1. A2 is actually a corollary of A1 (disjoint training sets → independent experts → independent errors) 2.\nThe probability space is training randomness, not test behavior 3. The estimation error of \\(\\mu_s\\)\nin finite samples is handled separately (Corollary 4) 4.\nIn practice, expert errors may exhibit superficial correlation (same blurry image), but this reflects similar \\(\\mu_s\\) values due to feature similarity, not statistical dependence 5. Empirical diagnosis of A2:\nEstimate conditional correlation coefficients of expert errors on a validation set; if they deviate significantly from zero, check whether training sets were truly disjoint'),
    ('在正文中诚实措辞', 'Honest Wording in the Main Text'),
    ('把 ``conditional independence\'\' 改为: \\textgreater{} ``conditional\nindependence of expert errors, which follows from training on disjoint\ndata subsets (Assumption A1)\'\'',
     'Change ``conditional independence\'\' to: \\textgreater{} ``conditional\nindependence of expert errors, which follows from training on disjoint\ndata subsets (Assumption A1)\'\''),
    ('这样把 A2 从\'\'假设\'\'降级为\'\'A1 的逻辑结果\'\'，同时指出它依赖于 A1\n的正确执行。',
     'This downgrades A2 from ``assumption\'\' to ``logical consequence of A1,\'\' while noting that it depends on the correct execution of A1.'),
    ('最终判断', 'Final Judgment'),
    ('状态', 'Status'),
    ('A2 是否站得住？', 'Does A2 hold up?'),
    ('\\textbf{是} --- A1 蕴含 A2（训练集不相交 → 专家独立）', '\\textbf{Yes} --- A1 implies A2 (disjoint training sets → independent experts)'),
    ('在实践中是否违反？', 'Is it violated in practice?'),
    ('\\textbf{取决于 A1 的执行} --- 如果训练集真的不相交，A2 成立', '\\textbf{Depends on A1 execution} --- if training sets are truly disjoint, A2 holds'),
    ('\\(\\exp(-2M\\Delta^2/(1+(M-1)\\rho))\\) 是否严格？', 'Is \\(\\exp(-2M\\Delta^2/(1+(M-1)\\rho))\\) rigorous?'),
    ('\\textbf{否} --- 这是启发式，不应写进定理', '\\textbf{No} --- this is a heuristic and should not appear in theorems'),
    ('应该如何修改？', 'How should it be revised?'),
    ('澄清 A2 是 A1 的推论；在 SI 中加入诚实讨论；不要引入虚假的 A2\'', 'Clarify that A2 is a corollary of A1; add honest discussion in the SI; do not introduce a fake A2\''),
    ('对论文的影响程度', 'Impact on the paper'),
    ('\\textbf{低} --- 不需要改定理陈述，只需要加一段诚实讨论', '\\textbf{Low} --- no need to change theorem statements, just add a paragraph of honest discussion'),
    ('对 hostile review 其他批评的回应', 'Response to Other Criticisms from the Hostile Review'),
    ('``CIFAR F1=0.617, 理论下界 F1≥0.976\'\'', '``CIFAR F1=0.617, theoretical lower bound F1≥0.976\'\''),
    ('这已经在 §4.3（紧致性讨论）中诚实处理了: \\(\\mu_s\\) 在 CIFAR 实验中约为\n0.45（3-epoch CPU 训练后），而非假定的 0.20。代入正确的 \\(\\mu_s\\)\n后下界为 F1≥0.18，与经验值 0.617 一致。',
     'This has already been honestly addressed in §4.3 (tightness discussion): \\(\\mu_s\\) in the CIFAR experiment is approximately\n0.45 (after 3-epoch CPU training), not the assumed 0.20. Plugging in the correct \\(\\mu_s\\)\ngives a lower bound of F1≥0.18, consistent with the empirical value 0.617.'),
    ('``\\(\\mu_s\\) 需要清洁标签 → 鸡生蛋\'\'', '``\\(\\mu_s\\) requires clean labels → chicken-and-egg\'\''),
    ('冷启动协议需要少量锚点样本（推论 1），这是理论上的必要成本（Thm 3\n证明了没有锚点时不可识别）。这不是循环定义------是对不可识别性定理的工程回应。',
     'The cold-start protocol requires a small number of anchor samples (Corollary 1), which is a theoretically necessary cost (Thm 3\nproves unidentifiability without anchors). This is not a circular definition --- it is an engineering response to the unidentifiability theorem.'),
    ('``Bootstrap 诊断的 τ=0.7 是拍脑袋\'\'', '``Bootstrap diagnostic τ=0.7 is arbitrary\'\''),
    ('承认。\\(\\tau=0.7\\) 是初始校准值，应在具体领域中根据已知噪声标签校准。SI\n中应明确标注为\'\'建议初始值，需领域校准\'\'。',
     'Acknowledged. \\(\\tau=0.7\\) is an initial calibration value that should be calibrated against known noisy labels in specific domains. The SI\nshould explicitly label it as ``suggested initial value, requires domain calibration.\'\''),
]

# ────────────────────────────────────────────────────────────────
# exact_constant_minimax.tex  (has 487 CN segments)
# ────────────────────────────────────────────────────────────────
TRANSLATIONS['explorations/exact_constant_minimax.tex'] = [
    ('\\textbf{目标}: 不仅证明指数 \\(2M\\Delta^2\\) 是 minimax\n最优（速率最优，已有），而且证明\\textbf{指数前面的常数因子}也是最优的。\n\\textbf{工具链}: Chernoff-Stein Lemma → Cramér\'s Theorem → Bahadur-Rao\nTheorem → Exact Asymptotic Minimax Constant \\textbf{期刊价值}: 速率最优\n= IEEE IT 级别。精确常数最优 = Annals of Statistics 级别。',
     '\\textbf{Goal}: Not only prove that the exponent \\(2M\\Delta^2\\) is minimax\noptimal (rate optimal, already done), but also prove that \\textbf{the constant factor in front of the exponent} is optimal.\n\\textbf{Tool chain}: Chernoff-Stein Lemma → Cramér\'s Theorem → Bahadur-Rao\nTheorem → Exact Asymptotic Minimax Constant. \\textbf{Journal value}: Rate optimality\n= IEEE IT level. Exact constant optimality = Annals of Statistics level.'),
    ('回顾：当前状态', 'Review: Current Status'),
    ('已有 (Thm 1 + Thm 4 v2)', 'Existing (Thm 1 + Thm 4 v2)'),
    ('\\textbf{上界} (Thm 1): F1 ≥ 1 − (1/η)exp(−2MΔ²) --- Hoeffding 界',
     '\\textbf{Upper bound} (Thm 1): F1 ≥ 1 − (1/η)exp(−2MΔ²) --- Hoeffding bound'),
    ('\\textbf{上界} (Chernoff 附录): F1 ≥ 1 −\n  (1/η)exp(−M·KL(θ\\textbar\\textbar μ)) --- KL 界，比 Hoeffding 紧 2-5×',
     '\\textbf{Upper bound} (Chernoff Appendix): F1 ≥ 1 −\n  (1/η)exp(−M·KL(θ\\textbar\\textbar μ)) --- KL bound, 2-5× tighter than Hoeffding'),
    ('\\textbf{下界} (Thm 4 v2): liminf\\_\\{M→∞\\} (−1/M) log(1−F1) ≥ 2Δ² ---\n  速率最优',
     '\\textbf{Lower bound} (Thm 4 v2): liminf\\_\\{M→∞\\} (−1/M) log(1−F1) ≥ 2Δ² ---\n  rate optimal'),
    ('\\textbf{下界} (Thm 4 v2, Bretagnolle-Huber): liminf\\_\\{M→∞\\} (−1/M)\n  log(1−F1) ≥ −log(1−H²) --- Hellinger 版本',
     '\\textbf{Lower bound} (Thm 4 v2, Bretagnolle-Huber): liminf\\_\\{M→∞\\} (−1/M)\n  log(1−F1) ≥ −log(1−H²) --- Hellinger version'),
    ('\\textbf{差距}: 上下界的\\textbf{指数}匹配了（都是 \\(e^{-cM}\\)\n形式），但\\textbf{指数前面的常数因子}未匹配。上界前面是\n\\(1/\\eta\\)，下界前面没有明确常数。',
     '\\textbf{Gap}: The upper and lower bound \\textbf{exponents} match (both are of the form \\(e^{-cM}\\)),\nbut the \\textbf{constant factor in front of the exponent} does not match. The upper bound has\n\\(1/\\eta\\) in front; the lower bound has no explicit constant.'),
    ('我们要的 (Thm 4\')', 'What We Want (Thm 4\')'),
    ('其中 \\(\\kappa = \\text{KL}(\\theta^* \\| \\mu)\\) 是 Chernoff\n信息，\\(C_{\\text{SCX}}\\) 是显式常数。且对\\textbf{任意算法}\n\\(\\mathcal{A}\\)：',
     'where \\(\\kappa = \\text{KL}(\\theta^* \\| \\mu)\\) is the Chernoff\ninformation, and \\(C_{\\text{SCX}}\\) is an explicit constant. And for \\textbf{any algorithm}\n\\(\\mathcal{A}\\):'),
    ('若 \\(C_{\\text{SCX}} = C_{\\text{min}}\\)（或比值有界），则 SCX\n是精确常数最优的。',
     'If \\(C_{\\text{SCX}} = C_{\\text{min}}\\) (or the ratio is bounded), then SCX\nis exact-constant optimal.'),
    ('证明架构', 'Proof Architecture'),
    ('Step 1: 精确大偏差 (Cramér + Bahadur-Rao)', 'Step 1: Exact Large Deviations (Cramér + Bahadur-Rao)'),
    ('Step 2: Bernoulli 阈值检验的精确渐近常数', 'Step 2: Exact Asymptotic Constant for Bernoulli Threshold Test'),
    ('Step 3: 从检验误差到 F1 的精确渐近', 'Step 3: Exact Asymptotics from Test Error to F1'),
    ('Step 4: 下界 — 任意检验的最优常数 (Chernoff-Stein + 第二阶渐近)', 'Step 4: Lower Bound — Optimal Constant for Any Test (Chernoff-Stein + Second-Order Asymptotics)'),
    ('Step 5: 匹配 → 常数最优性结论', 'Step 5: Matching → Constant Optimality Conclusion'),
    ('精确大偏差渐近 (Bahadur-Rao)', 'Exact Large Deviation Asymptotics (Bahadur-Rao)'),
    ('设定', 'Setup'),
    ('\\(M\\) 个独立专家。对样本 \\(x\\)，定义', '\\(M\\) independent experts. For sample \\(x\\), define'),
    ('\\textbf{H₀ (清洁)}:', '\\textbf{H₀ (clean)}:'),
    ('（状态 \\(s\\) 内清洁错误率）', '(\\(\\mu_s\\) is the clean error rate within state \\(s\\))'),
    ('\\textbf{H₁ (噪声)}:', '\\textbf{H₁ (noise)}:'),
    ('一致性得分:', 'Consistency score:'),
    ('决策规则: 标记噪声 ⇔ \\(C_M > \\theta\\)，\\(\\theta \\in (p_0, p_1)\\)', 'Decision rule: flag as noisy ⇔ \\(C_M > \\theta\\), \\(\\theta \\in (p_0, p_1)\\)'),
    ('率函数', 'Rate Function'),
    ('对 Bern(p)，对数矩母函数:', 'For Bern(p), the log moment generating function is:'),
    ('大偏差率函数 (Cramér 变换):', 'Large deviation rate function (Cramér transform):'),
    ('对 Bern(p)，有闭式解:', 'For Bern(p), there is a closed-form solution:'),
    ('Cramér 定理 (速率层)', 'Cramér\'s Theorem (Rate Level)'),
    ('对 i.i.d. Bern(p) 样本:', 'For i.i.d. Bern(p) samples:'),
    ('这是\\textbf{大偏差原理 (LDP)}------给出了精确的指数衰减速率。',
     'This is the \\textbf{Large Deviation Principle (LDP)} --- it gives the exact exponential decay rate.'),
    ('\\textbf{从速率最优到 KL 最优的升级}: 我们的旧界用 Hoeffding 的\n\\(2(\\theta-p)^2\\)，新界用精确的 KL。\\(\\text{KL}(\\theta\\|p)\\)\n是精确的大偏差速率函数------Cramér 定理保证它是渐近紧的，而 Hoeffding 界\n\\(2(\\theta-p)^2\\) 仅是它的二次下界（由 Pinsker 型不等式\n\\(\\text{KL}(\\theta\\|p) \\geq 2(\\theta-p)^2\\)）。\\textbf{使用 KL 替代\nHoeffding 不会改变速率的值（\\(\\kappa < 2\\Delta^2\\)\n对典型参数），但使界是渐近精确的}------这是从\'\'松弛界\'\'到\'\'精确渐近\'\'的升级，而非从\'\'慢速率\'\'到\'\'快速率\'\'。',
     '\\textbf{Upgrade from rate optimal to KL optimal}: Our old bound uses Hoeffding\'s\n\\(2(\\theta-p)^2\\), while the new bound uses the exact KL. \\(\\text{KL}(\\theta\\|p)\\)\nis the exact large deviation rate function --- Cramér\'s theorem guarantees it is asymptotically tight, while the Hoeffding bound\n\\(2(\\theta-p)^2\\) is merely its quadratic lower bound (by the Pinsker-type inequality\n\\(\\text{KL}(\\theta\\|p) \\geq 2(\\theta-p)^2\\)). \\textbf{Using KL instead of\nHoeffding does not change the rate value (\\(\\kappa < 2\\Delta^2\\)\nfor typical parameters), but makes the bound asymptotically exact} --- this is an upgrade from ``relaxed bound\'\' to ``exact asymptotics,\'\' not from ``slow rate\'\' to ``fast rate.\'\''),
    ('Bahadur-Rao 定理 (常数层) ★★★', 'Bahadur-Rao Theorem (Constant Level) ★★★'),
    ('\\textbf{定理 (Bahadur-Rao, 1960)}: 设\n\\(X_1, \\dots, X_M \\sim \\text{Bern}(p)\\) i.i.d.，\\(\\theta > p\\)。则：',
     '\\textbf{Theorem (Bahadur-Rao, 1960)}: Let\n\\(X_1, \\dots, X_M \\sim \\text{Bern}(p)\\) i.i.d., \\(\\theta > p\\). Then:'),
    ('其中： - \\(\\lambda^*(\\theta) = \\log\\frac{\\theta(1-p)}{p(1-\\theta)}\\) 是\nCramér 变换中达到上确界的 \\(\\lambda\\) -\n\\(\\sigma^2(\\theta) = \\theta(1-\\theta)\\) 是倾斜分布\n\\(\\text{Bern}(\\theta)\\) 的方差 - \\(\\sim\\) 表示比值 \\(\\to 1\\)（当\n\\(M \\to \\infty\\)）',
     'where: - \\(\\lambda^*(\\theta) = \\log\\frac{\\theta(1-p)}{p(1-\\theta)}\\) is\nthe \\(\\lambda\\) that achieves the supremum in the Cramér transform -\n\\(\\sigma^2(\\theta) = \\theta(1-\\theta)\\) is the variance of the tilted distribution\n\\(\\text{Bern}(\\theta)\\) - \\(\\sim\\) denotes ratio \\(\\to 1\\) (as\n\\(M \\to \\infty\\))'),
    ('\\textbf{推导}: 对 Bern(p)，倾斜测度下的分布为\n\\(\\text{Bern}(\\theta)\\)，因为\n\\(\\mathbb{E}_{\\theta}[X] = \\psi\'_p(\\lambda^*) = \\theta\\)。这个性质的验证：',
     '\\textbf{Derivation}: For Bern(p), the distribution under the tilted measure is\n\\(\\text{Bern}(\\theta)\\), since\n\\(\\mathbb{E}_{\\theta}[X] = \\psi\'_p(\\lambda^*) = \\theta\\). Verification of this property:'),
    ('解 \\(\\psi\'_p(\\lambda^*) = \\theta\\):', 'Solving \\(\\psi\'_p(\\lambda^*) = \\theta\\):'),
    ('即 \\(\\lambda^* = \\log\\frac{\\theta(1-p)}{p(1-\\theta)}\\)。✓',
     'i.e., \\(\\lambda^* = \\log\\frac{\\theta(1-p)}{p(1-\\theta)}\\). ✓'),
    ('倾斜二阶矩:', 'Tilted second moment:'),
    ('处：', 'At:'),
    ('因此', 'Therefore'),
    ('所以倾斜方差 \\(\\sigma^2(\\theta) = \\theta(1-\\theta)\\)。✓',
     'Thus the tilted variance \\(\\sigma^2(\\theta) = \\theta(1-\\theta)\\). ✓'),
    ('应用到 FPR 和 FNR', 'Application to FPR and FNR'),
    ('\\textbf{假阳性率 (FPR)} --- 清洁样本被误标:',
     '\\textbf{False Positive Rate (FPR)} --- clean sample mislabeled:'),
    ('其中 \\(\\lambda_0^* = \\log\\frac{\\theta(1-p_0)}{p_0(1-\\theta)} > 0\\)（因为\n\\(\\theta > p_0\\)）。',
     'where \\(\\lambda_0^* = \\log\\frac{\\theta(1-p_0)}{p_0(1-\\theta)} > 0\\) (since\n\\(\\theta > p_0\\)).'),
    ('\\textbf{假阴性率 (FNR)} --- 噪声样本被漏检:',
     '\\textbf{False Negative Rate (FNR)} --- noisy sample missed:'),
    ('其中 \\(\\lambda_1^* = \\log\\frac{\\theta(1-p_1)}{p_1(1-\\theta)} < 0\\)（因为\n\\(\\theta < p_1\\)），\\(|\\lambda_1^*| = \\log\\frac{p_1(1-\\theta)}{\\theta(1-p_1)}\\)。',
     'where \\(\\lambda_1^* = \\log\\frac{\\theta(1-p_1)}{p_1(1-\\theta)} < 0\\) (since\n\\(\\theta < p_1\\)), and \\(|\\lambda_1^*| = \\log\\frac{p_1(1-\\theta)}{\\theta(1-p_1)}\\).'),
    ('\\textbf{注意}: FNR\n公式用了对称性：\\(C_M \\leq \\theta \\iff 1-C_M \\geq 1-\\theta\\)，而\n\\(1-e_m \\sim \\text{Bern}(1-p_1)\\)。因此\n\\(\\text{KL}(\\theta \\| p_1) = \\text{KL}(1-\\theta \\| 1-p_1)\\)。',
     '\\textbf{Note}: The FNR\nformula uses symmetry: \\(C_M \\leq \\theta \\iff 1-C_M \\geq 1-\\theta\\), and\n\\(1-e_m \\sim \\text{Bern}(1-p_1)\\). Hence\n\\(\\text{KL}(\\theta \\| p_1) = \\text{KL}(1-\\theta \\| 1-p_1)\\).'),
    ('Step 2: F1 的精确渐近', 'Step 2: Exact Asymptotics of F1'),
    ('F1 的展开', 'Expansion of F1'),
    ('回忆:', 'Recall:'),
    ('当\n\\(M\\) 很大时，\\(\\text{FPR}_M\\) 和 \\(\\text{FNR}_M\\) 都 \\(\\to 0\\) 指数快。',
     'When\n\\(M\\) is large, both \\(\\text{FPR}_M\\) and \\(\\text{FNR}_M\\) approach \\(\\to 0\\) exponentially fast.'),
    ('展开到主导阶:', 'Expanding to leading order:'),
    ('代入 Bahadur-Rao 渐近', 'Substituting Bahadur-Rao Asymptotics'),
    ('代入 Step 1 的结果:', 'Substituting the results of Step 1:'),
    ('最优阈值选择', 'Optimal Threshold Selection'),
    ('两个指数项分别以速率 \\(\\text{KL}(\\theta \\| p_0)\\) 和\n\\(\\text{KL}(\\theta \\| p_1)\\) 衰减。为平衡两者，选择 \\(\\theta^*\\) 使得:',
     'The two exponential terms decay at rates \\(\\text{KL}(\\theta \\| p_0)\\) and\n\\(\\text{KL}(\\theta \\| p_1)\\), respectively. To balance them, choose \\(\\theta^*\\) such that:'),
    ('这个 \\(\\kappa\\) 就是 \\textbf{Chernoff 信息}\n\\(C(\\text{Bern}(p_0), \\text{Bern}(p_1))\\)。',
     'This \\(\\kappa\\) is the \\textbf{Chernoff information}\n\\(C(\\text{Bern}(p_0), \\text{Bern}(p_1))\\).'),
    ('\\textbf{性质}: \\(\\kappa\\) 是唯一满足上述等式的值，且当 \\(p_0 < p_1\\)\n时，\\(\\theta^* \\in (p_0, p_1)\\)。由 KL 散度的严格凸性保证唯一性。',
     '\\textbf{Property}: \\(\\kappa\\) is the unique value satisfying the above equality, and when \\(p_0 < p_1\\),\n\\(\\theta^* \\in (p_0, p_1)\\). Uniqueness is guaranteed by the strict convexity of KL divergence.'),
    ('SCX 的精确渐近常数', 'Exact Asymptotic Constant of SCX'),
    ('\\textbf{注意}: \\(\\max\\)\n取的是渐近主导项。若两指数完全相等，两阶项均需保留（它们的和）；若不完全相等但差值在\n\\(O(1/\\sqrt{M})\\) 内，则两个项都贡献到常数中。此处写的是最坏情况常数。',
     '\\textbf{Note}: The \\(\\max\\)\ntakes the asymptotically dominant term. If the two exponents are exactly equal, both terms must be retained (their sum); if they are not exactly equal but the difference is within\n\\(O(1/\\sqrt{M})\\), both terms contribute to the constant. What is written here is the worst-case constant.'),
    ('更精确地，在 \\(\\theta^*\\) 处两个指数严格相等，因此:',
     'More precisely, at \\(\\theta^*\\) the two exponents are strictly equal, therefore:'),
    ('Step 3: 下界 --- 任意算法的最优常数', 'Step 3: Lower Bound --- Optimal Constant for Any Algorithm'),
    ('问题归约', 'Problem Reduction'),
    ('任意噪声检测算法 \\(\\mathcal{A}\\) 在状态 \\(s\\)\n内可被归约为一个假设检验：接受或拒绝对每个样本的 H₀。对于 i.i.d.\n专家错误 \\(e_1, \\dots, e_M\\)，这是一个复合假设检验问题（参数 \\(p\\) 在 H₀\n下为 \\(p_0\\)，在 H₁ 下为 \\(p_1\\)）。',
     'Any noise detection algorithm \\(\\mathcal{A}\\) within state \\(s\\)\ncan be reduced to a hypothesis test: accept or reject H₀ for each sample. For i.i.d.\nexpert errors \\(e_1, \\dots, e_M\\), this is a composite hypothesis testing problem (parameter \\(p\\) is\n\\(p_0\\) under H₀, \\(p_1\\) under H₁).'),
    ('Chernoff-Stein Lemma (误差指数层)', 'Chernoff-Stein Lemma (Error Exponent Level)'),
    ('\\textbf{Stein 引理}: 对于检验 \\(M\\) 个 i.i.d. Bern(p₀) vs Bern(p₁): 固定\n\\(\\text{FPR} \\leq \\alpha \\in (0,1)\\)，最优可达到的 FNR 满足:',
     '\\textbf{Stein\'s Lemma}: For testing \\(M\\) i.i.d. Bern(p₀) vs Bern(p₁): fixing\n\\(\\text{FPR} \\leq \\alpha \\in (0,1)\\), the optimal achievable FNR satisfies:'),
    ('类似地，固定 \\(\\text{FNR} \\leq \\beta\\)，最优 FPR 的指数为\n\\(\\text{KL}(p_1 \\| p_0)\\)。',
     'Similarly, fixing \\(\\text{FNR} \\leq \\beta\\), the optimal FPR exponent is\n\\(\\text{KL}(p_1 \\| p_0)\\).'),
    ('\\textbf{意义}: KL 散度（不是 Hoeffding 的\n\\(2\\Delta^2\\)）是精确的误差指数。SCX 的阈值检验（Chernoff 附录形式）以\nKL 速率达到此界------\\textbf{证明 KL 指数是最优的}。',
     '\\textbf{Significance}: KL divergence (not Hoeffding\'s\n\\(2\\Delta^2\\)) is the exact error exponent. SCX\'s threshold test (in Chernoff Appendix form) achieves this bound at\nthe KL rate --- \\textbf{proving that the KL exponent is optimal}.'),
    ('第二阶渐近 (Hoeffding-Anscombe → Exact Constant)', 'Second-Order Asymptotics (Hoeffding-Anscombe → Exact Constant)'),
    ('这是最难的部分。需要从\'\'误差指数\'\'升级到\'\'误差精确常数\'\'。关键工具:',
     'This is the hardest part. It requires upgrading from ``error exponent\'\' to ``exact error constant.\'\' Key tools:'),
    ('\\textbf{Hoeffding 逼近 (1965)}: 对任意检验 \\(\\phi_M\\):',
     '\\textbf{Hoeffding Approximation (1965)}: For any test \\(\\phi_M\\):'),
    ('其中 \\(K\\) 是与 \\(\\theta^*\\) 和 Fisher 信息相关的显式常数。',
     'where \\(K\\) is an explicit constant related to \\(\\theta^*\\) and the Fisher information.'),
    ('\\textbf{论证路线}: 使用 \\textbf{Le Cam 第三引理} + \\textbf{局部渐近正态\n(LAN)} + \\textbf{Bahadur-Rao 精确下界}。',
     '\\textbf{Argument route}: Use \\textbf{Le Cam\'s Third Lemma} + \\textbf{Local Asymptotic Normality\n(LAN)} + \\textbf{Bahadur-Rao exact lower bound}.'),
    ('具体地: 1. 由 Bahadur-Rao, 任何基于 \\(C_M\\)\n的检验的误差满足精确渐近（不仅是速率） 2. 由 \\textbf{充分性原理}\n(Neyman-Pearson), 基于 \\(C_M\\)\n的检验构成\\textbf{本质完全类}------任何检验的误差界不低于最优 NP 检验 3.\n最优 NP 检验在 \\(\\theta^*\\) 处的 Bahadur-Rao 渐近给出下界常数',
     'Specifically: 1. By Bahadur-Rao, errors of any test based on \\(C_M\\)\nsatisfy exact asymptotics (not just the rate) 2. By the \\textbf{sufficiency principle}\n(Neyman-Pearson), tests based on \\(C_M\\)\nconstitute an \\textbf{essentially complete class} --- no test has error lower than the optimal NP test 3.\nThe Bahadur-Rao asymptotics of the optimal NP test at \\(\\theta^*\\) give the lower-bound constant'),
    ('\\textbf{下界定理} (Lemma E, 完整推导):',
     '\\textbf{Lower Bound Theorem} (Lemma E, full derivation):'),
    ('其中规范常数 \\(C_{\\min}\\)（Lemma E, eq. 45）:',
     'where the canonical constant \\(C_{\\min}\\) (Lemma E, eq. 45) is:'),
    ('且 \\(s = |\\lambda_1^*|/D^*\\),\n\\(D^* = \\lambda_0^* + |\\lambda_1^*| = \\log\\frac{p_1(1-p_0)}{p_0(1-p_1)}\\)。',
     'and \\(s = |\\lambda_1^*|/D^*\\),\n\\(D^* = \\lambda_0^* + |\\lambda_1^*| = \\log\\frac{p_1(1-p_0)}{p_0(1-p_1)}\\).'),
    ('\\textbf{推导来源}: 最优 Bayes 检验使用阈值\n\\(\\tau = (1-\\eta)/\\eta\\)。对应的\n\\(\\theta_{\\text{Bayes}} = \\theta^* + \\frac{1}{M}\\frac{\\log((1-\\eta)/\\eta)}{D^*} + O(1/M^2)\\)。O(1/M)\n的阈值偏移通过指数产生 \\(((1-\\eta)/\\eta)^s\\) 的 O(1) 乘性因子，该因子在\nFPR 和 FNR 贡献中\\textbf{同时出现}（因 \\(s = |\\lambda_1^*|/D^*\\) 且\n\\(1-s = \\lambda_0^*/D^*\\)），证明见 Lemma E §3-4。',
     '\\textbf{Derivation source}: The optimal Bayes test uses threshold\n\\(\\tau = (1-\\eta)/\\eta\\). The corresponding\n\\(\\theta_{\\text{Bayes}} = \\theta^* + \\frac{1}{M}\\frac{\\log((1-\\eta)/\\eta)}{D^*} + O(1/M^2)\\). The O(1/M)\nthreshold shift produces an O(1) multiplicative factor \\(((1-\\eta)/\\eta)^s\\) through the exponent, and this factor appears\n\\textbf{simultaneously} in both FPR and FNR contributions (since \\(s = |\\lambda_1^*|/D^*\\) and\n\\(1-s = \\lambda_0^*/D^*\\)); the proof is in Lemma E §3-4.'),
    ('比较：简单阈值 vs 自适应阈值', 'Comparison: Simple Threshold vs Adaptive Threshold'),
    ('\\textbf{简单阈值 \\(\\theta^*\\)}（Chernoff 信息点，不依赖 \\(\\eta\\)）:',
     '\\textbf{Simple threshold \\(\\theta^*\\)} (Chernoff information point, independent of \\(\\eta\\)):'),
    ('\\textbf{自适应阈值 \\(\\theta^\\dagger\\)}（依赖 \\(\\eta\\)，最小化\n\\(1-\\text{F1}\\)）:',
     '\\textbf{Adaptive threshold \\(\\theta^\\dagger\\)} (depends on \\(\\eta\\), minimizes\n\\(1-\\text{F1}\\)):'),
    ('两者的比值:', 'The ratio of the two:'),
    ('当 \\(\\eta = 1/2\\)（对称噪声）: 比值\n\\(= 1\\)（\\(\\theta^\\dagger = \\theta^*\\)，两者等价）',
     'When \\(\\eta = 1/2\\) (symmetric noise): ratio\n\\(= 1\\) (\\(\\theta^\\dagger = \\theta^*\\), both are equivalent)'),
    ('当 \\(\\eta \\to 0\\)（稀疏噪声）: 比值 \\(\\to 1\\)（但\n\\(\\theta^\\dagger \\to p_1\\)，极端保守）',
     'When \\(\\eta \\to 0\\) (sparse noise): ratio \\(\\to 1\\) (but\n\\(\\theta^\\dagger \\to p_1\\), extremely conservative)'),
    ('对于典型值 \\(0.05 \\leq \\eta \\leq 0.40\\): 比值在 \\(0.7\\) 到 \\(1.0\\)\n之间------自适应阈值提供适度但非巨大的改进',
     'For typical values \\(0.05 \\leq \\eta \\leq 0.40\\): ratio is between \\(0.7\\) and \\(1.0\\)\n--- the adaptive threshold provides a moderate but not dramatic improvement'),
    ('\\textbf{结论}: 使用自适应阈值 \\(\\theta^\\dagger\\) 的 SCX 达到\n\\(C_{\\min}\\)，因此是\\textbf{精确常数 minimax 最优}的。使用 \\(\\theta^*\\)\n的简单版本是次优的，但次优比例通常不超过 1.5×。',
     '\\textbf{Conclusion}: SCX with adaptive threshold \\(\\theta^\\dagger\\) achieves\n\\(C_{\\min}\\), and is therefore \\textbf{exact-constant minimax optimal}. The simple version using \\(\\theta^*\\)\nis suboptimal, but the suboptimality ratio typically does not exceed 1.5×.'),
    ('Step 4: 自适应加权 → 真正常数最优', 'Step 4: Adaptive Weighting → True Constant Optimality'),
    ('关键洞察', 'Key Insight'),
    ('\\(\\theta^*\\) 应通过最小化 \\(1 - \\text{F1}\\)（而非平衡 FPR 和\nFNR）来选择:',
     '\\(\\theta^*\\) should be chosen by minimizing \\(1 - \\text{F1}\\) (rather than balancing FPR and\nFNR):'),
    ('当 \\(\\eta \\neq 1/2\\) 时，\\(\\theta_{\\text{opt}} \\neq \\theta^*\\)（Chernoff\n信息点）！',
     'When \\(\\eta \\neq 1/2\\), \\(\\theta_{\\text{opt}} \\neq \\theta^*\\) (the Chernoff\ninformation point)!'),
    ('解出:', 'Solving:'),
    ('当 \\(M \\to \\infty\\) 时，修正项\n\\(\\frac{1}{M}\\log\\frac{1-\\eta}{\\eta} \\to 0\\)，因此\n\\(\\theta_{\\text{opt}} \\to \\theta^*\\)。但常数因子中的比值\n\\(\\frac{1-\\eta}{\\eta}\\) 仍然存在。',
     'As \\(M \\to \\infty\\), the correction term\n\\(\\frac{1}{M}\\log\\frac{1-\\eta}{\\eta} \\to 0\\), therefore\n\\(\\theta_{\\text{opt}} \\to \\theta^*\\). But the ratio\n\\(\\frac{1-\\eta}{\\eta}\\) still appears in the constant factor.'),
    ('似然比检验的精确最优性', 'Exact Optimality of the Likelihood Ratio Test'),
    ('\\textbf{Neyman-Pearson 引理}: 对于检验简单 H₀ vs 简单 H₁，似然比检验\n(LRT) 是\\textbf{最优}的（最小化 FNR 给定 FPR，或反之）。',
     '\\textbf{Neyman-Pearson Lemma}: For testing simple H₀ vs simple H₁, the likelihood ratio test\n(LRT) is \\textbf{optimal} (minimizes FNR given FPR, or vice versa).'),
    ('在 i.i.d. Bern 设定下，LRT 等价于对 \\(C_M\\) 的阈值检验，但阈值依赖于\nFPR/FNR 的相对代价。当目标是最小化\n\\((1-\\eta)\\text{FPR} + \\eta\\text{FNR}\\) 时，最优阈值 \\(\\theta^\\dagger\\)\n满足:',
     'In the i.i.d. Bern setting, LRT is equivalent to a threshold test on \\(C_M\\), but the threshold depends on\nthe relative cost of FPR/FNR. When the goal is to minimize\n\\((1-\\eta)\\text{FPR} + \\eta\\text{FNR}\\), the optimal threshold \\(\\theta^\\dagger\\)\nsatisfies:'),
    ('在 \\(\\theta^\\dagger = \\theta^* + o(1)\\) 的邻域内展开（当\n\\(M\\to\\infty\\)）得到自适应常数。',
     'Expanding in a neighborhood of \\(\\theta^\\dagger = \\theta^* + o(1)\\) (as\n\\(M\\to\\infty\\)) yields the adaptive constant.'),
    ('\\textbf{结论}: 使用自适应阈值 \\(\\theta^\\dagger\\)（而非 \\(\\theta^*\\)）的\nSCX 检验，其精确常数达到理论下界 \\(C_{\\min}\\):',
     '\\textbf{Conclusion}: The SCX test using adaptive threshold \\(\\theta^\\dagger\\) (rather than \\(\\theta^*\\))\nachieves the theoretical lower bound \\(C_{\\min}\\) in its exact constant:'),
    ('且 \\(C_{\\min}\\) 是任意算法能达到的最优常数。', 'and \\(C_{\\min}\\) is the optimal constant achievable by any algorithm.'),
    ('主定理陈述 (Theorem 4\': Exact Constant Minimax Optimality)', 'Main Theorem Statement (Theorem 4\': Exact Constant Minimax Optimality)'),
    ('\\textbf{Theorem 4\' (Exact Constant Minimax Optimality of SCX Noise\nDetection).} 在假设 A1-A6 下，对任意状态 \\(s\\) 满足\n\\(p_0 = \\mu_s < p_1 = 1 - C_{\\text{bal}} \\cdot \\mu_s/(K-1)\\)。令: -\n\\(\\kappa = C(\\text{Bern}(p_0), \\text{Bern}(p_1))\\) 为 Chernoff 信息:\n\\(\\kappa = \\text{KL}(\\theta^* \\| p_0) = \\text{KL}(\\theta^* \\| p_1)\\) -\n\\(\\theta^* \\in (p_0, p_1)\\) 为唯一满足上述等式的值，闭式解:\n\\(\\theta^* = \\frac{\\log\\frac{1-p_0}{1-p_1}}{\\log\\frac{p_1(1-p_0)}{p_0(1-p_1)}}\\)\n- \\(\\lambda_0^* = \\log\\frac{\\theta^*(1-p_0)}{p_0(1-\\theta^*)} > 0\\),\n\\(\\lambda_1^* = \\log\\frac{\\theta^*(1-p_1)}{p_1(1-\\theta^*)} < 0\\) -\n\\(D^* = \\lambda_0^* + |\\lambda_1^*| = \\log\\frac{p_1(1-p_0)}{p_0(1-p_1)} > 0\\)\n- \\(s = |\\lambda_1^*| / D^* \\in (0,1)\\)',
     '\\textbf{Theorem 4\' (Exact Constant Minimax Optimality of SCX Noise\nDetection).} Under Assumptions A1-A6, for any state \\(s\\) satisfying\n\\(p_0 = \\mu_s < p_1 = 1 - C_{\\text{bal}} \\cdot \\mu_s/(K-1)\\). Let: -\n\\(\\kappa = C(\\text{Bern}(p_0), \\text{Bern}(p_1))\\) be the Chernoff information:\n\\(\\kappa = \\text{KL}(\\theta^* \\| p_0) = \\text{KL}(\\theta^* \\| p_1)\\) -\n\\(\\theta^* \\in (p_0, p_1)\\) be the unique value satisfying the above equality, with closed form:\n\\(\\theta^* = \\frac{\\log\\frac{1-p_0}{1-p_1}}{\\log\\frac{p_1(1-p_0)}{p_0(1-p_1)}}\\)\n- \\(\\lambda_0^* = \\log\\frac{\\theta^*(1-p_0)}{p_0(1-\\theta^*)} > 0\\),\n\\(\\lambda_1^* = \\log\\frac{\\theta^*(1-p_1)}{p_1(1-\\theta^*)} < 0\\) -\n\\(D^* = \\lambda_0^* + |\\lambda_1^*| = \\log\\frac{p_1(1-p_0)}{p_0(1-p_1)} > 0\\)\n- \\(s = |\\lambda_1^*| / D^* \\in (0,1)\\)'),
    ('\\textbf{(a) 可达性 (SCX Achievability)}: 使用自适应阈值\n\\(\\theta^\\dagger\\) 的 SCX 噪声检测器满足:',
     '\\textbf{(a) Achievability (SCX Achievability)}: The SCX noise detector with adaptive threshold\n\\(\\theta^\\dagger\\) satisfies:'),
    ('其中规范最优常数（Lemma E, eq. 45）:', 'where the canonical optimal constant (Lemma E, eq. 45) is:'),
    ('\\(\\theta^\\dagger\\) 的构造:', 'Construction of \\(\\theta^\\dagger\\):'),
    ('\\textbf{(b) 下界 (Minimax Lower Bound)}: 对任意噪声检测算法\n\\(\\mathcal{A}\\):',
     '\\textbf{(b) Lower Bound (Minimax Lower Bound)}: For any noise detection algorithm\n\\(\\mathcal{A}\\):'),
    ('\\textbf{(c) 常数最优性}: SCX\n的渐近常数达到理论下界，因此是\\textbf{精确常数 minimax 最优}的。',
     '\\textbf{(c) Constant Optimality}: SCX\'s\nasymptotic constant achieves the theoretical lower bound, therefore it is \\textbf{exact-constant minimax optimal}.'),
    ('\\textbf{(d) 非渐近界} (Lemma A §A.5, Lemma B §B.4): 对有限\n\\(M \\geq M_0(p_0, p_1, \\eta)\\):',
     '\\textbf{(d) Non-asymptotic Bounds} (Lemma A §A.5, Lemma B §B.4): For finite\n\\(M \\geq M_0(p_0, p_1, \\eta)\\):'),
    ('其中 \\(K_1, K_2\\) 是仅依赖 \\(p_0, p_1\\) 的显式常数（由 Lemma A 的\nStirling 误差界和 Lemma B 的二次余项确定）。',
     'where \\(K_1, K_2\\) are explicit constants depending only on \\(p_0, p_1\\) (determined by Lemma A\'s\nStirling error bounds and Lemma B\'s quadratic remainder terms).'),
    ('\\textbf{(e) 多状态推广} (Lemma F): 对全局 F1:',
     '\\textbf{(e) Multi-State Generalization} (Lemma F): For global F1:'),
    ('其中 \\(\\kappa_{\\min} = \\min_s \\kappa_s\\)，只有达到最小 Chernoff\n信息的状态贡献主导常数。',
     'where \\(\\kappa_{\\min} = \\min_s \\kappa_s\\), and only states achieving the minimum Chernoff\ninformation contribute to the dominant constant.'),
    ('证明链依赖关系', 'Proof Chain Dependency'),
    ('需要填充的引理 (Agent 任务)', 'Lemmas to Fill In (Agent Tasks)'),
    ('引理 A: Bahadur-Rao 对于 Bernoulli 的完整推导', 'Lemma A: Complete Derivation of Bahadur-Rao for Bernoulli'),
    ('验证倾斜测度的所有计算', 'Verify all computations of the tilted measure'),
    ('给出 \\(o(1)\\) 项的显式界 (Berry-Esseen 型修正)', 'Provide explicit bounds for the \\(o(1)\\) term (Berry-Esseen-type correction)'),
    ('推广到非 i.i.d. 但仍独立的 Bernoulli（不同 \\(p_m\\)）', 'Generalize to non-i.i.d. but still independent Bernoulli (different \\(p_m\\))'),
    ('引理 B: F1 渐近展开的高阶项', 'Lemma B: Higher-Order Terms in F1 Asymptotic Expansion'),
    ('从\n\\(1-\\text{F1} \\approx \\frac{1}{2}\\text{FNR} + \\frac{1-\\eta}{2\\eta}\\text{FPR}\\)\n到包括 \\(O(e^{-2M\\kappa})\\) 项', 'From\n\\(1-\\text{F1} \\approx \\frac{1}{2}\\text{FNR} + \\frac{1-\\eta}{2\\eta}\\text{FPR}\\)\nto including \\(O(e^{-2M\\kappa})\\) terms'),
    ('验证展开在 \\(\\eta \\to 0\\) 或 \\(\\eta \\to 1\\) 时的有效性', 'Verify validity of the expansion as \\(\\eta \\to 0\\) or \\(\\eta \\to 1\\)'),
    ('引理 C: Chernoff 信息的显式表达', 'Lemma C: Explicit Expression of Chernoff Information'),
    ('\\(C(\\text{Bern}(p_0), \\text{Bern}(p_1))\\) 的闭式解 (不是数值解)', 'Closed-form solution for \\(C(\\text{Bern}(p_0), \\text{Bern}(p_1))\\) (not numerical)'),
    ('与 \\(2(p_1-p_0)^2\\) (Hoeffding) 和\n\\(\\frac{1}{2}(\\sqrt{p_0} - \\sqrt{p_1})^2\\) (Hellinger) 的比较', 'Comparison with \\(2(p_1-p_0)^2\\) (Hoeffding) and\n\\(\\frac{1}{2}(\\sqrt{p_0} - \\sqrt{p_1})^2\\) (Hellinger)'),
    ('引理 D: 自适应阈值的最优性', 'Lemma D: Optimality of Adaptive Threshold'),
    ('证明 \\(\\theta^\\dagger\\) 最小化 \\(1-\\text{F1}\\) 的渐近表达式', 'Prove that \\(\\theta^\\dagger\\) minimizes the asymptotic expression for \\(1-\\text{F1}\\)'),
    ('验证 \\(\\theta^\\dagger = \\theta^* + O(1/M)\\)', 'Verify \\(\\theta^\\dagger = \\theta^* + O(1/M)\\)'),
    ('导出使用 \\(\\theta^\\dagger\\) 的精确常数', 'Derive the exact constant when using \\(\\theta^\\dagger\\)'),
    ('引理 E: 下界 --- 第二阶渐近最优性', 'Lemma E: Lower Bound --- Second-Order Asymptotic Optimality'),
    ('形式化状态 ``任何算法不优于 LRT\'\'', 'Formalize the statement ``no algorithm outperforms LRT\'\''),
    ('Le Cam 第三引理 + LAN 框架下的精确常数', 'Exact constant under Le Cam\'s Third Lemma + LAN framework'),
    ('或者：使用 Ingster-Suslina 的非参数检验下界框架', 'Alternatively: use Ingster-Suslina\'s nonparametric testing lower-bound framework'),
    ('引理 F: 多状态聚合', 'Lemma F: Multi-State Aggregation'),
    ('从单状态常数最优推广到 \\(\\sum_s \\rho_s\\) 加权', 'Generalize from single-state constant optimality to \\(\\sum_s \\rho_s\\) weighting'),
    ('证明全局常数\n\\(C_{\\text{global}} = \\sum_s \\rho_s C_s\\)（受最坏状态支配）', 'Prove that the global constant\n\\(C_{\\text{global}} = \\sum_s \\rho_s C_s\\) (dominated by the worst state)'),
]

print(f"Translation map built: {sum(len(v) for v in TRANSLATIONS.values())} entries across {len(TRANSLATIONS)} files")
