#!/usr/bin/env python3
"""Third pass: more aggressive CJK character removal and context-aware fixes."""
import re, os

# Aggressive per-character-pattern replacements
FIXES = [
    # Fix garbled text from earlier passes
    ('as机逼近', 'Stochastic Approximation'),
    ('as机', 'random'),
    ('双间尺度', 'two-timescale'),
    ('间尺度', 'timescale'),
    ('鞅convergent', 'martingale convergence'),
    ('鞅', 'martingale'),
    ('下界', 'lower bound'),
    ('上界', 'upper bound'),
    ('学习率', 'learning rate'),
    ('递归', 'recursive'),
    ('不动点', 'fixed point'),
    ('相图', 'phase portrait'),
    ('吸引子', 'attractor'),
    ('盆地', 'basin'),
    ('演化', 'evolution'),
    ('自洽', 'self-consistent'),
    ('耦合', 'coupling'),
    ('滤子', 'filtration'),
    ('先验', 'prior'),
    ('后验', 'posterior'),
    ('速率', 'rate'),
    ('上', 'on'),
    ('下', 'under'),
    ('内', 'within'),
    ('外', 'outside'),
    ('前', 'before'),
    ('后', 'after'),
    ('中', 'in'),
    ('等', 'etc.'),
    ('如', 'e.g.,'),
    ('均', 'all'),
    ('仅', 'only'),
    ('需', 'requires'),
    ('可', 'can'),
    ('应', 'should'),
    ('将', 'will'),
    ('已', 'already'),
    ('未', 'not yet'),
    ('被', 'is'),
    ('把', ''),
    ('给', 'to'),
    ('对', 'to'),
    ('从', 'from'),
    ('向', 'toward'),
    ('与', 'and'),
    ('或', 'or'),
    ('但', 'but'),
    ('而', 'while'),
    ('且', 'and'),
    ('则', 'then'),
    ('若', 'if'),
    ('因', 'because'),
    ('故', 'therefore'),
    ('所', 'all'),
    ('每', 'each'),
    ('各', 'each'),
    ('某', 'some'),
    ('该', 'the'),
    ('此', 'this'),
    ('其', 'its'),
    ('它', 'it'),
    ('它们', 'they'),
    ('他', 'he'),
    ('她', 'she'),
    ('作', 'as'),
    ('由', 'by'),
    ('按', 'by'),
    ('据', 'according to'),
    ('关于', 'regarding'),
    ('对于', 'for'),
    ('通过', 'via'),
    ('根据', 'according to'),
    ('经过', 'after'),
    ('由于', 'since'),
    ('为了', 'in order to'),
    ('因此', 'therefore'),
    ('然而', 'however'),
    ('此外', 'moreover'),
    ('同时', 'simultaneously'),
    ('另外', 'additionally'),
    ('特别', 'especially'),
    ('尤其', 'particularly'),
    ('至少', 'at least'),
    ('最多', 'at most'),
    ('大约', 'approximately'),
    ('完全', 'completely'),
    ('部分', 'partially'),
    ('全部', 'entirely'),
    ('几乎', 'almost'),
    ('可能', 'possibly'),
    ('也许', 'perhaps'),
    ('通常', 'typically'),
    ('经常', 'often'),
    ('有时', 'sometimes'),
    ('很少', 'rarely'),
    ('从不', 'never'),
    ('总是', 'always'),
    ('仍然', 'still'),
    ('已经', 'already'),
    ('曾经', 'once'),
    ('正在', 'currently'),
    ('将会', 'will'),
    ('可以', 'can'),
    ('应该', 'should'),
    ('必须', 'must'),
    ('能够', 'able to'),
    ('需要', 'need to'),
    ('希望', 'hope to'),
    ('试图', 'attempt to'),
    ('打算', 'intend to'),
    ('决定', 'decide to'),
    ('开始', 'begin to'),
    ('继续', 'continue to'),
    ('停止', 'stop'),
    ('完成', 'complete'),
    ('结束', 'end'),
    ('使用', 'use'),
    ('利用', 'utilize'),
    ('采用', 'adopt'),
    ('应用', 'apply'),
    ('运用', 'employ'),
    ('计算', 'compute'),
    ('估计', 'estimate'),
    ('预测', 'predict'),
    ('检测', 'detect'),
    ('识别', 'identify'),
    ('分类', 'classify'),
    ('聚类', 'cluster'),
    ('划分', 'partition'),
    ('映射', 'map'),
    ('编码', 'encode'),
    ('解码', 'decode'),
    ('压缩', 'compress'),
    ('解压', 'decompress'),
    ('存储', 'store'),
    ('检索', 'retrieve'),
    ('更新', 'update'),
    ('删除', 'delete'),
    ('插入', 'insert'),
    ('替换', 'replace'),
    ('修改', 'modify'),
    ('创建', 'create'),
    ('销毁', 'destroy'),
    ('生成', 'generate'),
    ('验证', 'verify'),
    ('确认', 'confirm'),
    ('拒绝', 'reject'),
    ('接受', 'accept'),
    ('忽略', 'ignore'),
    ('考虑', 'consider'),
    ('分析', 'analyze'),
    ('综合', 'synthesize'),
    ('比较', 'compare'),
    ('评估', 'evaluate'),
    ('优化', 'optimize'),
    ('改进', 'improve'),
    ('增强', 'enhance'),
    ('削弱', 'weaken'),
    ('扩大', 'expand'),
    ('缩小', 'shrink'),
    ('增加', 'increase'),
    ('减少', 'decrease'),
    ('提高', 'raise'),
    ('降低', 'lower'),
    ('保持', 'maintain'),
    ('改变', 'change'),
    ('转换', 'transform'),
    ('转移', 'transfer'),
    ('传播', 'propagate'),
    ('反馈', 'feedback'),
    ('输入', 'input'),
    ('输出', 'output'),
    ('处理', 'process'),
    ('控制', 'control'),
    ('管理', 'manage'),
    ('组织', 'organize'),
    ('设计', 'design'),
    ('实现', 'implement'),
    ('部署', 'deploy'),
    ('运行', 'run'),
    ('执行', 'execute'),
    ('操作', 'operate'),
    ('维护', 'maintain'),
    ('监控', 'monitor'),
    ('调试', 'debug'),
    ('修复', 'fix'),
    ('改进', 'improve'),
    ('迭代', 'iterate'),
    ('重复', 'repeat'),
    ('循环', 'loop'),
    ('递归', 'recurse'),
    ('分支', 'branch'),
    ('合并', 'merge'),
    ('分割', 'split'),
    ('分配', 'allocate'),
    ('释放', 'release'),
    ('获取', 'acquire'),
    ('提供', 'provide'),
    ('支持', 'support'),
    ('包含', 'include'),
    ('排除', 'exclude'),
    ('涉及', 'involve'),
    ('相关', 'related'),
    ('依赖', 'depend'),
    ('独立', 'independent'),
    ('一致', 'consistent'),
    ('矛盾', 'contradict'),
    ('冲突', 'conflict'),
    ('协调', 'coordinate'),
    ('平衡', 'balance'),
    ('对称', 'symmetric'),
    ('反对称', 'antisymmetric'),
    ('线性', 'linear'),
    ('非线性', 'nonlinear'),
    ('凸', 'convex'),
    ('凹', 'concave'),
    ('连续', 'continuous'),
    ('离散', 'discrete'),
    ('光滑', 'smooth'),
    ('粗糙', 'rough'),
    ('精确', 'exact'),
    ('近似', 'approximate'),
    ('渐近', 'asymptotic'),
    ('有限', 'finite'),
    ('无限', 'infinite'),
    ('有界', 'bounded'),
    ('无界', 'unbounded'),
    ('收敛', 'convergent'),
    ('发散', 'divergent'),
    ('稳定', 'stable'),
    ('不稳定', 'unstable'),
    ('确定', 'deterministic'),
    ('随机', 'stochastic'),
    ('概率', 'probabilistic'),
    ('统计', 'statistical'),
    ('动态', 'dynamic'),
    ('静态', 'static'),
    ('时间', 'time'),
    ('空间', 'space'),
    ('频率', 'frequency'),
    ('能量', 'energy'),
    ('信息', 'information'),
    ('熵', 'entropy'),
    ('噪声', 'noise'),
    ('信号', 'signal'),
    ('数据', 'data'),
    ('样本', 'sample'),
    ('特征', 'feature'),
    ('标签', 'label'),
    ('类别', 'class'),
    ('集群', 'cluster'),
    ('分布', 'distribution'),
    ('密度', 'density'),
    ('距离', 'distance'),
    ('相似', 'similar'),
    ('度量', 'metric'),
    ('矩阵', 'matrix'),
    ('向量', 'vector'),
    ('张量', 'tensor'),
    ('标量', 'scalar'),
    ('参数', 'parameter'),
    ('变量', 'variable'),
    ('常数', 'constant'),
    ('函数', 'function'),
    ('算子', 'operator'),
    ('映射', 'map'),
    ('变换', 'transform'),
    ('梯度', 'gradient'),
    ('散度', 'divergence'),
    ('旋度', 'curl'),
    ('导数', 'derivative'),
    ('积分', 'integral'),
    ('微分', 'differential'),
    ('方程', 'equation'),
    ('系统', 'system'),
    ('模型', 'model'),
    ('网络', 'network'),
    ('结构', 'structure'),
    ('层次', 'hierarchy'),
    ('模块', 'module'),
    ('组件', 'component'),
    ('接口', 'interface'),
    ('协议', 'protocol'),
    ('算法', 'algorithm'),
    ('方法', 'method'),
    ('技术', 'technique'),
    ('工具', 'tool'),
    ('框架', 'framework'),
    ('平台', 'platform'),
    ('环境', 'environment'),
    ('场景', 'scenario'),
    ('应用', 'application'),
    ('领域', 'domain'),
    ('范围', 'scope'),
    ('边界', 'boundary'),
    ('条件', 'condition'),
    ('假设', 'assumption'),
    ('性质', 'property'),
    ('定理', 'theorem'),
    ('引理', 'lemma'),
    ('推论', 'corollary'),
    ('命题', 'proposition'),
    ('定义', 'definition'),
    ('证明', 'proof'),
    ('示例', 'example'),
    ('注释', 'remark'),
    ('问题', 'problem'),
    ('结论', 'conclusion'),
    ('结果', 'result'),
    ('贡献', 'contribution'),
    ('创新', 'innovation'),
    ('改进', 'improvement'),
    ('扩展', 'extension'),
    ('限制', 'limitation'),
    ('挑战', 'challenge'),
    ('机遇', 'opportunity'),
    ('风险', 'risk'),
    ('代价', 'cost'),
    ('收益', 'benefit'),
    ('效率', 'efficiency'),
    ('性能', 'performance'),
    ('精度', 'accuracy'),
    ('速度', 'speed'),
    ('规模', 'scale'),
    ('复杂度', 'complexity'),
    ('简单', 'simple'),
    ('困难', 'difficult'),
    ('容易', 'easy'),
    ('重要', 'important'),
    ('关键', 'critical'),
    ('核心', 'core'),
    ('基础', 'fundamental'),
    ('基本', 'basic'),
    ('主要', 'main'),
    ('次要', 'secondary'),
    ('本质', 'essential'),
    ('表面', 'superficial'),
    ('深层', 'deep'),
    ('浅层', 'shallow'),
]

def fix_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original = content
    for pattern, replacement in FIXES:
        content = content.replace(pattern, replacement)
    
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False

files = [
    'theory/propositions/03_state_conditioned_weighting.tex',
    'theory/propositions/03_state_conditioned_weighting_proof.tex',
    'theory/propositions/04_compression_fidelity.tex',
    'theory/propositions/05_expert_governance_protocol.tex',
    'theory/propositions/06_two_layer_state_discovery.tex',
    'theory/README.tex',
    'theory/scx_8theorems_review.tex',
    'theory/SCX_Next_Theorems.tex',
    'theory/SCX_Undiscovered_Theorems.tex',
    'theory/self_evolution/01_symbol_system.tex',
    'theory/self_evolution/CERCIS_NAMING.tex',
    'theory/self_evolution/final_review_jmlr.tex',
    'theory/self_evolution/final_review_nature.tex',
    'theory/self_evolution/hostile_review.tex',
    'theory/self_evolution/MATHEMATICAL_GENEALOGY.tex',
]

changed = 0
for f in files:
    if os.path.exists(f):
        if fix_file(f):
            changed += 1
            print(f"Fixed: {f}")
        else:
            print(f"Skip: {f}")

print(f"\nChanged: {changed}/{len(files)}")
