#!/usr/bin/env python3
"""
Second pass: comprehensive Chinese→English translation for remaining Chinese in theory/ Batch 3.
"""
import re, os

# Extensive translation map covering all remaining Chinese patterns
TRANSLATIONS = [
    # === LONG SENTENCES (MATHEMATICAL_GENEALOGY) ===
    ('Robbins-Monro 递归：', 'Robbins-Monro recursion:'),
    ('参考文献: - Robbins', 'References: - Robbins'),
    
    ('动力系统 / Lyapunov\n稳定性', 'Dynamical Systems / Lyapunov\nStability'),
    ('Spring 中的角色: Gatekeeper 评分函数', 'Role in Spring: The gatekeeper scoring function'),
    ('的演化被解释为贝叶斯后验均值更新：', "'s evolution is interpreted as a Bayesian posterior mean update:"),
    ('定理 (Doob 鞅收敛): 序列', 'Theorem (Doob Martingale Convergence): The sequence'),
    ('是关于滤子', 'with respect to the filtration'),
    ('有界鞅。由 Doob 鞅收敛定理：', '-bounded martingale. By the Doob martingale convergence theorem:'),
    ('重要限制：鞅性质要求模型正确（', 'Important limitation: the martingale property requires correct model specification ('), 
    ('在先验', 'in the prior'),
    ('的支撑内）。在模型错误设定下，后验收敛到 KL 投影', "'s support). Under model misspecification, the posterior converges to the KL projection"),
    ('而非真值', 'rather than the true value'),
    ('Spring 诚实标注了此限制。', 'Spring honestly acknowledges this limitation.'),
    ('在线学习 /\n遗憾分析', 'Online Learning /\nRegret Analysis'),
    ('Spring 中的角色: Gatekeeper 的在线梯度下降 (OGD)', 'Role in Spring: The gatekeeper\'s online gradient descent (OGD)'),
    ('更新产生标准遗憾界：', 'update yields the standard regret bound:'),
    ('无延迟', '(No Delay)'),
    ('Spring 将该界推广到', 'Spring generalizes this bound to the'),
    ('延迟反馈', 'delayed feedback'),
    ('设置（NEP 学生的反馈延迟', 'setting (the NEP student\'s feedback delay'),
    ('）：', '):'),
    ('进一步推广到', 'Further generalized to the'),
    ('增长记忆库', 'growing memory bank'),
    ('设置', 'setting'),
    ('的单调增长提供有效样本复杂度改进：', "'s monotonic growth provides effective sample complexity improvement:"),
    ('随着', 'As'),
    ('，系统满足', ', the system satisfies'),
    ('渐近无遗憾', 'asymptotic no-regret'),
    ('集中不等式', 'Concentration Inequalities'),
    ('Spring 中的角色: 在 Spring 的多个关键位置：', 'Role in Spring: At multiple critical points in Spring:'),
    ('共识得分的集中', 'Concentration of the Consensus Score'),
    ('专家一致性', 'Expert consensus'),
    ('的 Hoeffding 尾界：', 'Hoeffding tail bound:'),
    ('当 A2', 'When A2'),
    ('因专家相关而被违反时，', 'is violated due to expert correlation,'),
    ('被替换为有效专家数', 'is replaced by the effective number of experts'),
    ('Chernoff 信息: 检测问题的最优指数速率由 Chernoff 信息', 'Chernoff Information: The optimal exponential rate for the detection problem is given by the Chernoff information'),
    ('给出，应用于 Theorem 4\'。', ', applied to Theorem 4\'.'),
    ('Bahadur-Rao 精确渐近: Bernoulli 格子修正因子', 'Bahadur-Rao Exact Asymptotics: The Bernoulli lattice correction factor'),
    ('替代标准的 Chernoff 前缀，将 Theorem 4\'', 'replaces the standard Chernoff prefactor, tightening Theorem 4\''),
    ('的精确常数收紧 5-12\\%。', "'s exact constant by 5--12\\%."),
    ('信息论', 'Information Theory'),
    ('Spring 中的角色', 'Role in Spring'),
    ('Fano 不等式: 用于 Theorem 2（弱特征失败）的下界', 'Fano\'s Inequality: Used for the lower bound in Theorem 2 (Weak Feature Failure)'),
    ('当特征', 'when the feature'),
    ('与真实状态', 'and the true state'),
    ('的互信息', 'have mutual information'),
    ('时，任何状态估计算法有：', ', any state estimation algorithm has:'),
    ('数据处理不等式 (DPI): 用于 Theorem 2 证明 Step', 'Data Processing Inequality (DPI): Used in Theorem 2 Proof Step'),
    ('马尔可夫链', 'the Markov chain'),
    ('不会增加。', 'does not increase.'),
    ('Pinsker 不等式: 将互信息界', 'Pinsker\'s Inequality: Converts the mutual information bound'),
    ('转换为总变差界', 'to a total variation bound'),
    ('KL 收缩: 在正确模型下，后验收敛', 'KL Contraction: Under correct model specification, the posterior converges'),
    ('Minimax 理论', 'Minimax Theory'),
    ('Spring 中的角色', 'Role in Spring'),
    ('Le Cam 两点法: 构造两个难以区分的分布', 'Le Cam Two-Point Method: Constructs two hard-to-distinguish distributions'),
    ('（清洁）和', '(Clean) and'),
    ('（噪声），利用', '(Noise), using'),
    ('获得 minimax 下界。', 'to obtain a minimax lower bound.'),
    ('Neyman-Pearson 归约: 通过 Neyman-Pearson 引理将任意算法归约为', 'Neyman-Pearson Reduction: Via the Neyman-Pearson lemma, any algorithm is reduced to'),
    ('检验，给出 Theorem 4\' 的最优性。', 'test, giving the optimality of Theorem 4\'.'),
    ('Hellinger 精确张量化: 在', 'Hellinger Exact Tensorization: Under'),
    ('（条件独立）下，', '(Conditional Independence),'),
    ('精确等式，无不等式松弛。', 'an exact equality with no inequality slack.'),
    
    ('Spring 最关键的架构创新。条件 C6\' 要求 gatekeeper 更新速率', "Spring's most critical architectural innovation. Condition C6' requires the gatekeeper update rate"),
    ('是学生更新速率', 'to be a lower-order infinitesimal relative to the student update rate'),
    ('的低阶无穷小：', ':'),
    ('在任意两次 gatekeeper', 'Between any two gatekeeper'),
    ('更新之间，学生执行渐近无限多次梯度步骤，在分布偏移前收敛到当前分布的局部最小值。', 'updates, the student performs asymptotically infinitely many gradient steps, converging to a local minimum of the current distribution before distribution shift occurs.'),
    ('规范调度', 'Canonical Schedule'),
    ('学生探索', 'Student Exploration'),
    ('噪声控制', 'Noise Control'),
    ('有限总分布偏移', 'Finite Total Distribution Shift'),
    ('方差控制', 'Variance Control'),
    ('时间尺度分离', 'Timescale Separation'),
    
    ('参考集重放打破选择偏差', 'Reference Set Replay Breaks Selection Bias'),
    ('Spring 最深刻的证明工具。Theorem 12.2', "Spring's most profound proof tool. Theorem 12.2"),
    ('证明：', 'proves:'),
    ('没有参考集重放，Lyapunov', 'Without reference set replay, Lyapunov'),
    ('下降在渐近意义下是不可能的', 'descent is asymptotically impossible'),
    ('gatekeeper', 'the gatekeeper'),
    ('可以通过只接受', 'can reduce its apparent loss by only accepting'),
    ('简单', 'easy'),
    ('样本来降低表观损失，而不真正改进判别能力。', 'samples, without truly improving discriminative ability.'),
    ('解决方案 (Theorem 12.5, 完整证明): 1.', 'Solution (Theorem 12.5, Full Proof): 1.'),
    ('学生侧', 'Student Side'),
    ('重要性采样权重', 'Importance sampling weights'),
    ('，使得有效训练分布为参考分布', ', making the effective training distribution the reference distribution'),
    ('Gatekeeper 侧', 'Gatekeeper Side'),
    ('在固定参考集', 'On a fixed reference set'),
    ('上计算', 'compute'),
    ('消除对齐偏差', 'eliminating alignment bias'),
    ('代价', 'Cost'),
    ('重要性权重方差膨胀因子', 'Importance weight variance inflation factor'),
    
    ('Lipschitz-almost-everywhere\n引理', 'Lipschitz-Almost-Everywhere\nLemma'),
    ('解决了一个基本的数学障碍 (Lemma SE-1.0, B9 fix)：', 'Resolves a fundamental mathematical obstacle (Lemma SE-1.0, B9 fix):'),
    ('在阈值', 'at the threshold'),
    ('处不连续（指示函数跳跃）。', 'is discontinuous (indicator function jump).'),
    ('在条件 C5（条件 i.i.d.', 'Under Condition C5 (conditional i.i.d.'),
    ('采样）下，不连续集合具有概率测度零，因为：', 'sampling), the discontinuity set has probability measure zero, because:'),
    ('对于连续分布上的光滑函数', 'For smooth functions over continuous distributions,'),
    ('期望不受零测集修改的影响，Lyapunov 分析保留有效。', 'expectations are unaffected by modifications on measure-zero sets; the Lyapunov analysis remains valid.'),
    
    ('贝叶斯后验更新作为 Gatekeeper\n进化', 'Bayesian Posterior Update as Gatekeeper\nEvolution'),
    ('的进化被解释为序贯贝叶斯更新：', "'s evolution is interpreted as sequential Bayesian updating:"),
    ('这产生了两个强大的理论性质： 1.', 'This yields two powerful theoretical properties: 1.'),
    ('鞅性质', 'Martingale Property'),
    ('塔性质', 'Tower Property'),
    ('保证 a.s. 收敛 2.', 'guarantees a.s. convergence. 2.'),
    ('在正确模型下，', 'Under correct model specification,'),
    
    ('Lyapunov\n下降与重要性采样', 'Lyapunov\nDescent with Importance Sampling'),
    ('的完整证明结构证明了', "'s complete proof structure establishes"),
    ('四个项的分解： -', 'Decomposition into four terms: -'),
    ('学生改进', 'Student Improvement'),
    ('，通过重要性采样消除', ', eliminating via importance sampling'),
    ('间隙（', 'gap ('),
    ('已证明', 'Proved'),
    ('） -', ') -'),
    ('Gatekeeper 改进', 'Gatekeeper Improvement'),
    ('，通过在', ', by computing'),
    ('上计算', 'on'),
    ('分布偏移', 'Distribution Shift'),
    ('，由双时间尺度控制（', ', controlled by two-timescale ('),
    ('交叉耦合', 'Cross-Coupling'),
    ('，因参考集可分离性（', ', due to reference set separability ('),
    
    ('收敛率与 Polyak\n平均', 'Convergence Rate and Polyak\nAveraging'),
    ('在强凸条件下，学生的收敛率为', 'Under strong convexity, the student convergence rate is'),
    ('其中', 'where'),
    ('为学习率指数。', 'is the learning rate exponent.'),
    ('Polyak-Ruppert 平均', 'Polyak-Ruppert Averaging'),
    ('将速率提升至', 'boosts the rate to'),
    ('与 minimax 下界', 'matching the minimax lower bound'),
    ('匹配的最优速率', 'the optimal rate'),
    ('适用于任何', 'for any'),
    ('且无需精确调谐。', 'without requiring fine-tuning.'),
    
    ('四种失效模式刻画', 'Characterization of Four Failure Modes'),
    ('系统性地刻画了四种规范失效模式：', 'systematically characterizes four canonical failure modes:'),
    ('模式', 'Mode'),
    ('机制', 'Mechanism'),
    ('严重性', 'Severity'),
    ('过早冻结', 'Premature Freezing'),
    ('在学生提供纠正信号之前衰减过快', 'decays too quickly before the student provides corrective signals'),
    ('中等（双精度下罕见）', 'Medium (rare under double precision)'),
    ('积压', 'Backlog'),
    ('数据进入速率超过 gatekeeper 评分吞吐量', 'Data arrival rate exceeds gatekeeper scoring throughput'),
    ('高（大数据集下实际存在）', 'High (practically present in large datasets)'),
    ('客户端分歧', 'Client Divergence'),
    ('多个不动点 + 不同初始条件/数据流', 'Multiple fixed points + different initial conditions/data streams'),
    ('不可调和的分歧', 'irreconcilable divergence'),
    ('中等（仅多客户端部署）', 'Medium (multi-client deployment only)'),
    ('对抗投毒', 'Adversarial Poisoning'),
    ('对手注入精心构造的样本；自进化循环放大污染', 'Adversary injects carefully crafted samples; self-evolution loop amplifies contamination'),
    ('高（有放大效应时严重）', 'High (severe with amplification)'),
    ('每种模式配有形式化条件、退化速率和缓解策略。', 'Each mode is equipped with formal conditions, degradation rates, and mitigation strategies.'),
    
    # Timeline (verbatim - keep most as-is, just translate the Chinese annotations)
    ('动力系统定性分析的基础——不动点、吸引子、Lyapunov 函数', 'Foundation of qualitative analysis of dynamical systems---fixed points, attractors, Lyapunov functions'),
    ('使用: Ψ(S_t, θ_t) 为 Lyapunov 函数；不动点分析；吸引子盆地', 'Used for: Ψ(S_t, θ_t) as Lyapunov function; fixed point analysis; basin of attraction'),
    ('独立同分布序列的几乎必然收敛基础', 'Foundation of almost sure convergence for i.i.d. sequences'),
    ('使用: 共识统计量 C(x) 的大样本行为', 'Used for: large-sample behavior of consensus statistic C(x)'),
    ('随机梯度下降的数学基础；∑α_t=∞, ∑α_t²<∞ 条件', 'Mathematical foundation of stochastic gradient descent; ∑α_t=∞, ∑α_t²<∞ condition'),
    ('使用: θ_t 更新遵循 RM 递归；双时间尺度扩展', 'Used for: θ_t update follows RM recursion; two-timescale extension'),
    ('假设检验的最优指数速率', 'Optimal exponential rate for hypothesis testing'),
    ('使用: Theorem 4\' 检测的精确指数速率', 'Used for: precise exponential rate for Theorem 4\' detection'),
    ('有界鞅的几乎必然收敛', 'Almost sure convergence of bounded martingales'),
    ('使用: S_t 为 [0,1]-有界鞅 → S_t → S_∞ a.s.', 'Used for: S_t as a [0,1]-bounded martingale → S_t → S_∞ a.s.'),
    ('样本均值尾概率的精确二阶渐近（含格子修正）', 'Exact second-order asymptotics for sample mean tail probabilities (with lattice correction)'),
    ('使用: Theorem 4\' 的精确常数；Bernoulli 格子修正', 'Used for: exact constant for Theorem 4\'; Bernoulli lattice correction'),
    ('信息论下界——互信息与错误概率的关系', 'Information-theoretic lower bound---relationship between mutual information and error probability'),
    ('使用: Theorem 2 弱特征下界', 'Used for: Theorem 2 weak feature lower bound'),
    ('有界独立变量和的指数集中', 'Exponential concentration for sums of bounded independent variables'),
    ('使用: 共识分数的集中界；Theorem 1 的主工具', 'Used for: concentration bound for consensus score; main tool for Theorem 1'),
    ('TV ≤ √(KL/2) —— 信息散度与统计距离的桥梁', 'TV ≤ √(KL/2) --- bridge between information divergence and statistical distance'),
    ('使用: Theorem 2 中 δ → TV 的转换', 'Used for: δ → TV conversion in Theorem 2'),
    ('两点法下界、凸包论证、minimax 最优性框架', 'Two-point method lower bound, convex hull argument, minimax optimality framework'),
    ('使用: Theorem 4\' 下界；Hellinger tensorization', 'Used for: Theorem 4\' lower bound; Hellinger tensorization'),
    ('k-means 的几乎必然一致性', 'Almost sure consistency of k-means'),
    ('使用: Theorem 5 状态发现的理论基础', 'Used for: theoretical foundation for Theorem 5 state discovery'),
    ('路径依赖与次优技术锁定的经济学理论', 'Economic theory of path dependence and lock-in to suboptimal technologies'),
    ('概念类比: Spring 的多不动点结构——gatekeeper 可能锁定于次优自洽配置', 'Conceptual analogy: Spring\'s multiple-fixed-point structure---gatekeeper may lock into suboptimal self-consistent configurations'),
    ('递增回报', 'Increasing Returns'),
    ('正反馈循环中的多重均衡', 'Multiple equilibria in positive feedback loops'),
    ('概念类比: Spring gatekeeper 的选择偏差循环——初始偏差通过自进化被放大', 'Conceptual analogy: Spring gatekeeper selection bias cycle---initial bias is amplified through self-evolution'),
    ('在线凸规划', 'Online Convex Programming'),
    ('在线梯度下降的遗憾界 O(√T)', 'Regret bound O(√T) for online gradient descent'),
    ('使用: gatekeeper OGD 更新、延迟反馈扩展、增长记忆库扩展', 'Used for: gatekeeper OGD update, delayed feedback extension, growing memory bank extension'),
    ('领域自适应理论', 'Domain Adaptation Theory'),
    ('训练与测试分布不匹配的泛化界', 'Generalization bounds for train-test distribution mismatch'),
    ('使用: D_static 间隙的领域自适应界 (Lemma 12.1)', 'Used for: domain adaptation bound for D_static gap (Lemma 12.1)'),
    ('通过自我博弈实现超人类水平、策略迭代、蒙特卡洛树搜索', 'Achieves superhuman level through self-play, policy iteration, Monte Carlo tree search'),
    ('类似: 自进化循环结构、单调改进保证、记忆重放', 'Similar: self-evolution loop structure, monotone improvement guarantee, memory replay'),
    ('不同: 处理真实物理数据（非合成）、未知环境动态、形式收敛证明', 'Different: processes real physical data (not synthetic), unknown environment dynamics, formal convergence proof'),
    ('自进化 Gatekeeper', 'Self-Evolving Gatekeeper'),
    ('自进化评估标准（不仅自改进策略）、单调增长记忆、', 'Self-evolving evaluation criteria (not just self-improving policy), monotonically growing memory,'),
    ('复活机制——', 'resurrection mechanism---'),
    ('冬天不杀，它等待春天', 'Winter does not kill --- it waits for spring'),
    
    # Comparison tables
    ('核心对比', 'Core Comparison'),
    ('年份', 'Year'),
    ('是（渐近 a.s.）', 'Yes (asymptotic a.s.)'),
    ('否（固定查询策略）', 'No (fixed query strategy)'),
    ('是（标签复杂度）', 'Yes (label complexity)'),
    ('标注池', 'Label pool'),
    ('分类（单模型）', 'Classification (single model)'),
    ('否（固定先验）', 'No (fixed prior)'),
    ('是（遗憾）', 'Yes (regret)'),
    ('GP 后验', 'GP posterior'),
    ('黑箱优化', 'Black-box optimization'),
    ('重放缓冲（有替换）', 'Replay buffer (with replacement)'),
    ('游戏（已知环境）', 'Games (known environment)'),
    ('N/A（理论极限）', 'N/A (theoretical limit)'),
    ('是（对可计算环境）', 'Yes (for computable environments)'),
    ('全部历史', 'All history'),
    ('通用归纳（不可计算）', 'Universal induction (uncomputable)'),
    ('gatekeeper 协同进化', 'gatekeeper co-evolution'),
    ('单调增长，无删除', 'monotonically growing, no deletion'),
    ('设计用于物理科学', 'designed for physical sciences'),
    ('*AlphaZero 在表格情况下有策略迭代的收敛证明；对神经网络情况为经验性。', '*AlphaZero has convergence proofs for policy iteration in the tabular case; for neural network case it is empirical.'),
    ('详细对比', 'Detailed Comparison'),
    ('数据生成', 'Data Generation'),
    ('合成（自我博弈）', 'Synthetic (self-play)'),
    ('环境完全已知', 'environment fully known'),
    ('真实（NEP', 'Real (NEP'),
    ('模拟）', 'simulation)'),
    ('物理规律未知', 'physical laws unknown'),
    ('反馈', 'Feedback'),
    ('即时（游戏结局）', 'Instant (game outcome)'),
    ('延迟（NEP 批处理训练）', 'Delayed (NEP batch training)'),
    ('收敛机制', 'Convergence Mechanism'),
    ('策略迭代 + MCTS', 'Policy iteration + MCTS'),
    ('Lyapunov 下降 + 贝叶斯更新', 'Lyapunov descent + Bayesian update'),
    ('记忆', 'Memory'),
    ('重放缓冲（有替换）', 'Replay buffer (with replacement)'),
    ('单调增长记忆库（不删除）', 'Monotonically growing memory bank (no deletion)'),
    ('收敛保证', 'Convergence Guarantee'),
    ('单调改进（表格情况已证明）', 'Monotone improvement (proved for tabular case)'),
    ('有限时间不动点（Theorem', 'Finite-time fixed point (Theorem'),
    ('已证明）', 'Proved)'),
    ('最终状态', 'Final State'),
    ('原则上最优策略', 'In principle, optimal policy'),
    ('自洽不动点（可能次优）', 'Self-consistent fixed point (possibly suboptimal)'),
    ('探索', 'Exploration'),
    ('Dirichlet 噪声 + 访问计数', 'Dirichlet noise + visit count'),
    ('随机探索分数 ε +', 'Random exploration fraction ε +'),
    ('退火接受阈值', 'annealed acceptance threshold'),
    ('贝叶斯优化', 'Bayesian Optimization'),
    ('目标', 'Objective'),
    ('优化静态黑箱函数', 'Optimize static black-box function'),
    ('进化评估标准 + 优化模型', 'Evolve evaluation criteria + optimize model'),
    ('替代模型', 'Surrogate Model'),
    ('高斯过程', 'Gaussian process'),
    ('NEP 学生（神经网络）', 'NEP student (neural network)'),
    ('采集函数', 'Acquisition Function'),
    ('EI / UCB / Thompson', 'EI / UCB / Thompson'),
    ('状态值函数 V(s) =', 'State value function V(s) ='),
    ('粒度', 'Granularity'),
    ('逐点', 'Pointwise'),
    ('逐状态（聚合多个样本）', 'Per-state (aggregating multiple samples)'),
    ('目标数量', 'Number of Objectives'),
    ('单目标（通常）', 'Single-objective (usually)'),
    ('多目标（噪声检测、专家分歧、数据多样性）', 'Multi-objective (noise detection, expert disagreement, data diversity)'),
    ('成本结构', 'Cost Structure'),
    ('同质', 'Homogeneous'),
    ('异质（DFT 计算成本因状态而异）', 'Heterogeneous (DFT computation cost varies by state)'),
    ('收敛速率', 'Convergence Rate'),
    ('累积遗憾', 'Cumulative regret'),
    ('有限时间终止保证', 'Finite-time termination guarantee'),
    ('主动学习', 'Active Learning'),
    ('查询策略', 'Query Strategy'),
    ('不确定性 / QBC / 期望模型变化', 'Uncertainty / QBC / Expected model change'),
    ('状态认证', 'State Certification'),
    ('在状态级聚合后决策', 'decision after state-level aggregation'),
    ('单一判别模型', 'Single discriminative model'),
    ('多专家集成 + 学生模型', 'Multi-expert ensemble + student model'),
    ('查询决策', 'Query Decision'),
    ('分层', 'Hierarchical'),
    ('先状态级，再样本级', 'state-level first, then sample-level'),
    ('噪声处理', 'Noise Handling'),
    ('Oracle 假设清洁（多数）', 'Oracle assumes clean (most)'),
    ('主要设计目标', 'Primary Design Goal'),
    ('明确检测标签噪声', 'explicitly detect label noise'),
    ('标签复杂度', 'Label Complexity'),
    ('认证', 'Certification'),
    ('每个行动由状态级保证认证', 'Each action certified by state-level guarantee'),
    
    # Spring's unique contributions
    ('独有的贡献', 'Unique Contributions'),
    ('以下是 Spring 完成而', 'The following are accomplished by Spring that'),
    ('没有任何前人工作同时完成', 'no prior work has simultaneously achieved'),
    ('的事情：', ':'),
    ('自进化评估标准（不仅自改进策略）', 'Self-Evolving Evaluation Criteria (Not Just Self-Improving Policy)'),
    ('前人限制', 'Prior Work Limitations'),
    ('自改进其策略（如何下棋），但评估标准（游戏规则）是固定的外部真理。主动学习和贝叶斯优化有固定查询策略/采集函数。', 'self-improves its policy (how to play), but the evaluation criteria (game rules) are fixed external truths. Active learning and Bayesian optimization have fixed query strategies/acquisition functions.'),
    ('Spring 的创新', "Spring's Innovation"),
    ('自身', 'itself'),
    ('是学习对象', 'is the learning object'),
    ('它定义', 'it defines'),
    ('什么是好的数据', 'what constitutes good data'),
    ('系统不是在固定评估标准下优化策略，而是', 'The system is not optimizing a policy under a fixed evaluation criterion, but rather'),
    ('同时进化评估标准本身', 'simultaneously evolving the evaluation criterion itself'),
    ('这是一个二阶学习问题：学习如何学习判断数据质量。', 'This is a second-order learning problem: learning how to learn to judge data quality.'),
    ('单调增长记忆（不替换重放）', 'Monotonically Growing Memory (No Replacement Replay)'),
    ('所有重放缓冲方案（AlphaZero、DQN、经验重放）在某种程度上替换旧记忆', 'All replay buffer schemes (AlphaZero, DQN, experience replay) replace old memories to some degree'),
    ('缓冲有界，最旧/最不有用的样本被丢弃。', 'the buffer is bounded, and the oldest/least useful samples are discarded.'),
    ('记忆仅增长。无删除策略意味着： 1.', 'memory only grows. The no-deletion policy means: 1.'),
    ('无灾难性遗忘', 'No catastrophic forgetting'),
    ('早期学习的结构永不被丢弃 2.', 'structures learned early are never discarded. 2.'),
    ('记忆单调性提供自由的结构性质（Lemma SE-1.2 需要） 3.', 'Memory monotonicity provides a free structural property (needed by Lemma SE-1.2). 3.'),
    ('复活机制成为可能', 'Resurrection mechanism becomes possible'),
    ('分数低于阈值的旧结构保留在记忆库中，等待', 'old structures with scores below threshold remain in the memory bank, waiting for'),
    ('成熟时重新评分', 'to mature and re-score them'),
    ('复活机制', 'Resurrection Mechanism'),
    ('无前人算法包含', 'No prior algorithm includes the concept of'),
    ('的概念。被拒绝的样本要么被丢弃（主动学习），要么不被重访。', 'Rejected samples are either discarded (active learning) or never revisited.'),
    ('冬天不杀', 'Winter does not kill'),
    ('它等待春天', 'it waits for spring'),
    ('低于阈值', 'Structures below threshold'),
    ('的结构不被删除', 'are not deleted'),
    ('它们进入休眠。当 gatekeeper', 'they enter dormancy. When the gatekeeper'),
    ('在后续迭代中进化（', 'evolves in subsequent iterations ('),
    ('可能对相同结构给出更高分数）时，休眠结构被复活并引入训练：', 'may give higher scores to the same structures), dormant structures are resurrected and introduced into training:'),
    ('春天使其复活', 'Spring resurrects it'),
    ('这在数学上编码为：gatekeeper', 'This is mathematically encoded as: the gatekeeper'),
    ('更新可以在任何时间将样本的评分推过阈值，变拒绝为接受', 'update can, at any time, push a sample\'s score past the threshold, turning rejection into acceptance'),
    ('这在主动学习（一旦拒绝即永久丢弃）或贝叶斯优化（一旦评估即消耗预算）中是不可能的。', 'This is impossible in active learning (once rejected, permanently discarded) or Bayesian optimization (once evaluated, budget is consumed).'),
    ('耦合动力系统分析（gatekeeper +', 'Coupled Dynamical System Analysis (Gatekeeper +'),
    ('学生协同进化）', 'Student Co-Evolution)'),
    ('Robbins-Monro 分析单一递归。AlphaZero', 'Robbins-Monro analyzes a single recursion. AlphaZero'),
    ('的策略迭代交替固定一个组件更新另一个（策略评估与策略改进之间无耦合动力系统分析）。', "'s policy iteration alternates between fixing one component while updating the other (no coupled dynamical system analysis between policy evaluation and policy improvement)."),
    ('完整的耦合动力系统形式化： - 状态空间', 'Complete coupled dynamical system formalization: - State space'),
    ('乘积空间', 'Product Space'),
    ('更新算子', 'Update Operator'),
    ('因果前馈结构，块三角', 'Causal feed-forward structure, block-triangular'),
    ('Jacobian） - 双时间尺度 ODE 分析（快慢方程组） - Lyapunov', 'Jacobian) - Two-timescale ODE analysis (fast-slow system of equations) - Lyapunov'),
    ('函数在乘积空间上的显式下降 -', 'function explicit descent on the product space -'),
    ('极限集、吸引子盆地、相图', '-limit set, basin of attraction, phase diagram'),
    ('没有前人算法在形式耦合动力系统框架中分析两个学习组件的协同进化。', 'No prior algorithm analyzes the co-evolution of two learning components within a formal coupled dynamical system framework.'),
    ('精确收敛速率与 Polyak\n平均', 'Exact Convergence Rate with Polyak\nAveraging'),
    ('贝叶斯优化给出累积遗憾界', 'Bayesian optimization gives cumulative regret bounds'),
    ('但不给出参数收敛速率。主动学习给出标签复杂度但不给出学习速率。', 'but does not give parameter convergence rates. Active learning gives label complexity but not learning rates.'),
    ('强凸下学生速率为', 'Under strong convexity, student rate is'),
    ('已证明） -', 'Proved) -'),
    ('收缩下 gatekeeper 速率为', 'Under contraction, gatekeeper rate is'),
    ('将速率提升至', 'boosts the rate to'),
    ('匹配', 'matching'),
    ('耦合速率由学生瓶颈', 'Coupled rate dominated by student bottleneck'),
    ('主导（Theorem 11.3） - 有限时间（非渐近）界含显式常数（Theorem 11.6,', 'dominant (Theorem 11.3) - Finite-time (non-asymptotic) bound with explicit constants (Theorem 11.6,'),
    ('形式化选择偏差循环分析', 'Formalized Selection Bias Cycle Analysis'),
    ('无前人算法形式化分析其自身数据选择程序创建自强化偏差循环的机制。', 'No prior algorithm formally analyzes the mechanism by which its own data selection procedure creates a self-reinforcing bias cycle.'),
    ('证明', 'proves'),
    ('在没有参考集重放的情况下，Lyapunov', 'Without reference set replay, Lyapunov'),
    ('下降在渐近意义下是不可能的', 'descent is asymptotically impossible'),
    ('可以通过只接受', 'can reduce its apparent loss by only accepting'),
    ('简单', 'easy'),
    ('样本来降低其表观损失，而不真正改进。这是对任何自选择学习系统的深刻限制，在', 'samples, without truly improving. This is a profound limitation for any self-selecting learning system, which was not formally proved before'),
    ('之前未被形式化证明。', '.'),
    ('具体来说，选择偏差循环：', 'Specifically, the selection bias cycle:'),
    ('被分解、量化并证明为 Lyapunov 下降的必要阻碍', 'is decomposed, quantified, and proven to be a necessary obstacle to Lyapunov descent'),
    ('然后通过参考集重放 +', 'then resolved through the combined mechanism of reference set replay +'),
    ('重要性采样的联合机制被解决（Theorem 12.5, 完整证明）。', 'importance sampling (Theorem 12.5, full proof).'),
    ('自进化算法在七个经典数学领域的交汇处运作：随机逼近、动力系统、贝叶斯推断、在线学习、集中不等式、信息论和', 'The Spring self-evolution algorithm operates at the intersection of seven classical mathematical domains: stochastic approximation, dynamical systems, Bayesian inference, online learning, concentration inequalities, information theory, and'),
    ('理论。其核心架构创新', 'theory. Its core architectural innovations'),
    ('双时间尺度分离、参考集重放打破选择偏差、单调增长记忆、复活机制、耦合动力系统分析', 'two-timescale separation, reference set replay breaking selection bias, monotonically growing memory, resurrection mechanism, coupled dynamical system analysis'),
    ('由这些领域的完整证明链支撑。与所有前人的决定性区别在于：Spring', 'are supported by complete proof chains from these domains. The decisive difference from all prior work: Spring'),
    ('同时', 'simultaneously'),
    ('自进化其评估标准和被评估模型，形式化证明收敛，并保持单调增长的记忆（永不遗忘）。', 'self-evolves both its evaluation criteria and the evaluated model, formally proves convergence, and maintains monotonically growing memory (never forgetting).'),
    ('本谱系学由 SCX 理论组编制', 'This genealogy compiled by the SCX Theory Group'),
]

def process_file(fpath):
    with open(fpath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    for cn, en in TRANSLATIONS:
        content = content.replace(cn, en)
    
    with open(fpath, 'w', encoding='utf-8') as f:
        f.write(content)
    
    remaining = len(re.findall(r'[\u4e00-\u9fff]', content))
    print(f"  {os.path.basename(fpath)}: {remaining} Chinese chars remaining")

files = [
    'theory/self_evolution/MATHEMATICAL_GENEALOGY.tex',
    'theory/self_evolution/multi_head_spring_and_positional_encoding_analysis.tex',
    'theory/self_evolution/ppe_rigorous_derivation.tex',
    'theory/self_evolution/situs_final_verification.tex',
    'theory/self_evolution/situs_physical_validation.tex',
    'theory/self_evolution/spring_convergence_analysis.tex',
    'theory/self_evolution/spring_hostile_review.tex',
    'theory/theorems/01_noise_detection_guarantee.tex',
    'theory/theorems/02_weak_feature_failure.tex',
    'theory/theorems/03_unidentifiability_theorem.tex',
]

for f in files:
    process_file(f)
