import re, os

files = [
    'paper/archive/scx_llm/main.tex',
    'theory/self_evolution/spring_convergence_analysis.tex',
    'theory/self_evolution/spring_hostile_review.tex',
    'theory/theorems/01_noise_detection_guarantee.tex',
    'theory/theorems/02_weak_feature_failure.tex',
    'theory/theorems/03_unidentifiability_theorem.tex'
]

pattern = re.compile(r'[\u4e00-\u9fff]+')

# Comprehensive translation dictionary built from file context
# Format: Chinese fragment -> English translation
TRANSLATIONS = {
    # === Single characters (context-dependent) ===
    '立': 'holds',
    '此': 'thus',
    '签': 'label',
    '变': 'varies', 
    '世': 'world',
    '间': 'between',
    '价': 'equivalent',
    '弱': 'weak',
    '区': 'distinguish',
    '匀': 'uniform',
    '凸': 'convex',
    '真': 'true',
    '退': 'degenerate',
    '致': 'consistent',
    '轮': 'round',
    '排': 'permutation',
    '质': 'property',
    '设': 'setup',
    '较': 'compare',
    '知': 'known',
    '矩': 'matrix',
    '反': 'counter',
    '效': 'effective',
    '果': 'if',
    '交': 'disjoint',
    '取': 'take',
    '内': 'within',
    '档': 'document',
    '该': 'the',
    '形': 'case',
    '决': 'determine',
    '占': 'proportion',
    '注': 'note',
    '际': 'actual',
    '头': 'head',
    '维': 'dimension',
    '义': 'meaning',
    '聚': 'cluster',
    '更': 'more',
    '靠': 'reliable',
    '随': 'random',
    '额': 'extra',
    '正': 'positive',
    '强': 'strong',
    '难': 'hard',
    '混': 'mixed',
    '商': 'quotient',
    '解': 'solve',
    '梯': 'gradient',
    '总': 'total',
    '评': 'evaluate',
    '联': 'joint',
    '存': 'exists',
    '况': 'case',
    '似': 'similar',
    '误': 'error',
    '端': 'extreme',
    '降': 'descent',
    '差': 'variance',
    '引': 'induce',
    '偏': 'bias',
    '特': 'specific',
    '概': 'probability',
    '改': 'improve',
    '拟': 'fit',
    '错': 'wrong',
    '项': 'term',
    '导': 'dominate',
    '臂': 'arm',
    '适': 'suitable',
    '身': 'itself',
    '增': 'add',
    '表': 'surface',
    '倍': 'times',
    '放': 'relax',
    '求': 'require',
    '测': 'measure',
    '零': 'zero',
    '步': 'step',
    '达': 'reach',
    '操': 'operation',
    '低': 'low',
    '负': 'negative',
    '处': 'at',
    '够': 'sufficient',
    '紧': 'tight',
    '全': 'full',
    '指': 'assign',
    '前': 'previous',
    '验': 'empirical',
    '见': 'observed',
    '符': 'symbol',
    '令': 'let',
    '越': 'more',
    '号': 'number',
    '驻': 'stationary',
    '素': 'factor',
    '程': 'process',
    '带': 'with',
    '盆': 'basin',
    '优': 'optimal',
    '阶': 'order',
    '归': 'normalize',
    '重': 'weight',
    '阈': 'threshold',
    '通': 'through',
    '证': 'proof',
    '边': 'boundary',
    '歧': 'ambiguous',
    '输': 'output',
    '添': 'add',
    '者': 'one',
    '诚': 'honest',
    '足': 'sufficient',
    '某': 'some',
    '逆': 'inverse',
    '各': 'each',
    '涉': 'involve',
    '献': 'contribution',
    '何': 'what',
    '受': 'subject',
    '毒': 'poison',
    '并': 'and',
    '充': 'sufficient',
    '功': 'success',
    '必': 'must',
    '沿': 'along',
    '入': 'enter',
    '慢': 'slow',
    '浅': 'shallow',
    '鞍': 'saddle',
    '网': 'network',
    '约': 'approximately',
    '逐': 'iteratively',
    '复': 'complex',
    '张': 'tension',
    '速': 'speed',
    '少': 'few',
    '找': 'find',
    '原': 'original',
    '造': 'create',
    '写': 'write',
    '疑': 'doubt',
    '族': 'family',
    '事': 'event',
    '管': 'manage',
    '字': 'digit',
    '哪': 'which',
    '划': 'partition',
    '称': 'called',
    '别': 'other',
    '散': 'diverge',
    '角': 'angle',
    '般': 'general',
    '尾': 'tail',
    '恰': 'exactly',
    '单': 'single',
    '积': 'accumulate',
    '施': 'apply',
    '住': 'stuck',
    '系': 'system',
    '潜': 'latent',
    '综': 'overall',
    '恒': 'constant',
    '伪': 'pseudo',
    '隐': 'hidden',
    '除': 'remove',
    '良': 'good',
    '扰': 'perturb',
    '距': 'distance',
    '纯': 'pure',
    '规': 'rule',
    '样': 'sample',
    '游': 'walk',
    '预': 'predict',
    '离': 'separate',
    '空': 'empty',
    '巨': 'huge',
    '劣': 'worse',
    '象': 'phenomenon',
    '卡': 'stuck',
    '松': 'loose',
    '长': 'long',
    '异': 'abnormal',
    '减': 'reduce',
    '版': 'version',
    '确': 'indeed',
    '述': 'described',
    '算': 'compute',
    '么': 'why',
    '元': 'element',
    '神': 'magic',
    '肯': 'affirm',
    '条': 'condition',
    '转': 'turn',
    '幻': 'phantom',
    '完': 'complete',
    '隔': 'gap',
    '侧': 'side',
    '整': 'entire',
    '律': 'law',
    '假': 'false',
    '抗': 'resist',
    '格': 'lattice',
    '手': 'hand',
    '远': 'far',
    '估': 'estimate',
    '超': 'exceed',
    '运': 'run',
    '接': 'connect',
    '故': 'deliberately',
    '稀': 'sparse',
    '示': 'indicate',
    '趋': 'tend',
    '失': 'lose',
    '景': 'landscape',
    '泛': 'vacuous',
    '采': 'adopt',
    '驱': 'drive',
    '洁': 'clean',
    '虽': 'although',
    '含': 'contain',
    '锚': 'anchor',
    '构': 'structure',
    '升': 'increase',
    '硬': 'hard',
    '附': 'appendix',
    '域': 'domain',
    '违': 'violate',
    '衡': 'balanced',
    '视': 'view',
    '医': 'medical',
    '像': 'image',

    # === Two-character fragments ===
    '严格': 'rigorous',
    '观测': 'observed',
    '边际': 'marginal',
    '损失': 'loss',
    '攻击': 'attack',
    '注者': 'note',
    '保守': 'conservative',
    '打破': 'break',
    '声称': 'claim',
    '梯范': 'gradient norm',
    '步长': 'step size',
    '模拟': 'simulate',
    '歧义': 'ambiguity',
    '伪代': 'pseudo-code',
    '歧概': 'error probability',
    '联系': 'connection',
    '论证': 'argument',
    '致命': 'fatal',
    '松弛': 'relaxation',
    '手选': 'hand-picked',
    '传播': 'propagation',
    '表达': 'expression',
    '思路': 'approach',
    '投票': 'vote',
    '陈述': 'statement',
    '协差': 'covariance',
    '接近': 'approaches',
    '污染': 'corruption',
    '反映': 'reflect',
    '前形': 'current form',
    '凸优': 'convex optimization',
    '称驻': 'symmetric stationary',
    '单位': 'unit',
    '凸形': 'convex case',
    '适配': 'adaptation',
    '考虑': 'consider',
    '误删': 'incorrectly pruned',
    '假阴': 'false negative',
    '忽略': 'ignore',
    '盆边': 'basin boundary',
    '判决': 'verdict',
    '约简': 'reduction',
    '果链': 'causal chain',
    '敏感': 'sensitive',
    '解读': 'interpretation',
    '表明': 'indicate',
    '某驻': 'some stationary',
    '诚注': 'honest note',
    '价驻': 'equivalent stationary',
    '位移': 'displacement',
    '传递': 'transfer',
    '网节': 'network node',
    '真正': 'true',
    '质询': 'interrogation',
    '盆间': 'between basins',
    '知道': 'know',
    '承认': 'admit',
    '景观': 'landscape',
    '避免': 'avoid',
    '缩放': 'scaling',
    '特异': 'specific',
    '流形': 'manifold',
    '悬浮': 'floating',
    '证毕': 'QED',
    '变异': 'variation',
    '召回': 'recall',
    '翻转': 'flip',
    '语义': 'semantic',
    '梯差': 'gradient difference',
    '选取': 'select',
    '轨道': 'orbit',
    '项导': 'term dominates',
    '软概': 'soft probability',
    '遗忘': 'forgetting',
    '果存': 'if exists',
    '头注': 'attention head',
    '输概': 'output probability',
    '逼近': 'approximate',
    '间存': 'there exists',
    '某形': 'some form',
    '此退': 'this degeneracy',
    '桥接': 'bridge',
    '权平': 'weighted average',
    '凸组': 'convex combination',
    '爆炸': 'explosion',
    '单独': 'alone',
    '鸿沟': 'gap',
    '误导': 'misleading',
    '建模': 'model',
    '重建': 'reconstruct',
    '重言': 'tautology',
    '直觉': 'intuition',
    '切换': 'switch',
    '仍然': 'still',
    '楼阁': 'castle in air',
    '前提': 'premise',
    '猜测': 'guess',
    '名字': 'name',
    '支撑': 'support',
    '交叉': 'cross',
    '蕴含': 'imply',
    '参见': 'see',
    '原版': 'original version',
    '代入': 'substitute',
    '消失': 'vanish',
    '详见': 'see details',
    '回顾': 'review',
    '号立': 'number holds',
    '改幅': 'improvement magnitude',
    '流程': 'pipeline',
    '取决': 'depend',
    '辅助': 'auxiliary',
    '联概': 'joint probability',
    '差距': 'discrepancy',
    '变松': 'becomes loose',
    '际义': 'practical meaning',
    '签恒': 'label constant',
    '犯错': 'make mistakes',
    '区世': 'distinguish worlds',
    '揭示': 'reveal',
    '限混': 'finite mixture',
    '谱系': 'spectral system',
    '雅洁': 'Yajie',
    '严密': 'rigorous',
    '随程': 'stochastic process',
    '元组': 'tuple',
    '全批': 'full batch',
    '诱导': 'induced',
    '该鞍': 'that saddle',
    '扰梯': 'perturbed gradient',
    '此处': 'here',
    '陷入': 'trapped in',
    '早期': 'early',
    '拉扯': 'pull',
    '阶优': 'first-order optimization',
    '模排': 'modulo permutation',
    '般形': 'general case',
    '预算': 'budget',
    '涵盖': 'cover',
    '风格': 'style',
    '增长': 'grow',
    '逐轮': 'per round',
    '某轮': 'some round',
    '原先': 'originally',
    '混入': 'mixed in',
    '歧程': 'degree of ambiguity',
    '越散': 'more dispersed',
    '差越': 'variance larger',
    '寻找': 'search',
    '某适': 'some suitable',
    '少样': 'few samples',
    '般况': 'general condition',
    '著名': 'famous',
    '摇摆': 'oscillation',
    '总变': 'total variation',
    '损害': 'damage',
    '倾斜': 'skew',
    '提纯': 'purify',
    '回放': 'replay',
    '存疑': 'doubtful',
    '警示': 'warning',
    '谱并': 'spectral and',
    '者注': 'note',
    '回避': 'avoid',
    '审稿': 'review',
    '礼貌': 'polite',
    '漏洞': 'hole',
    '打穿': 'punch through',
    '欺骗': 'deceptive',
    '解剖': 'dissection',
    '仔细': 'careful',
    '随梯': 'stochastic gradient',
    '么档': 'either the document',
    '么故': 'or deliberately',
    '看更': 'look more',
    '称盆': 'symmetric basin',
    '处散': 'diverge at',
    '处异': 'abnormal at',
    '重排': 're-permute',
    '注明': 'note',
    '希望': 'hope',
    '该写': 'should write',
    '遮盖': 'cover up',
    '平根': 'square root',
    '此该': 'this should',
    '匀格': 'uniform lattice',
    '操际': 'actual operation',
    '取者': 'take the',
    '注具': 'note has',
    '裂痕': 'crack',
    '添原': 'add original',
    '档隐': 'document implicitly',
    '活跃': 'active',
    '增臂': 'add arm',
    '并入': 'merge into',
    '挤占': 'crowd out',
    '确适': 'indeed suitable',
    '前轮': 'previous round',
    '回路': 'feedback loop',
    '历史': 'history',
    '身随': 'itself with',
    '暗示': 'imply',
    '事先': 'in advance',
    '见明': 'even explicitly',
    '轨迹': 'trajectory',
    '该臂': 'that arm',
    '断言': 'assertion',
    '果异': 'if different',
    '预先': 'in advance',
    '注入': 'inject',
    '支持': 'support',
    '字附': 'digit attached',
    '叙事': 'narrative',
    '碰巧': 'coincidentally',
    '全题': 'entire problem',
    '何处': 'where',
    '评元': 'evaluation unit',
    '维变': 'dimension change',
    '跳跃': 'jump',
    '读者': 'reader',
    '脑补': 'fill in mentally',
    '怎么': 'how',
    '左边': 'left side',
    '右边': 'right side',
    '随排': 'random permutation',
    '何重': 'what weight',
    '层空': 'layer space',
    '估约': 'estimate approximately',
    '误传': 'misreport',
    '档摘': 'document excerpt',
    '缺失': 'missing',
    '递推': 'recurrence',
    '省略': 'omit',
    '闭解': 'closed-form solution',
    '规范': 'specification',
    '拼写': 'spelling',
    '者名': 'name',
    '评语': 'review comment',
    '野心': 'ambition',
    '者改': 'author revise',
    '签降': 'label degradation',
    '变臂': 'changing arm',
    '清单': 'checklist',
    '签字': 'sign',
    '处诚': 'honest at',
    '严谨': 'rigorous',
    '局限': 'limitation',
    '共享': 'shared',
    '留置': 'hold-out',
    '详细': 'detailed',
    '划充': 'partition adequacy',
    '想况': 'ideal case',
    '求解': 'solve',
    '代替': 'replace',
    '纳入': 'incorporate',
    '取平': 'take average',
    '并注': 'and note',
    '步简': 'further simplify',
    '致低': 'uniformly low',
    '完美': 'perfect',
    '验规': 'empirical rule',
    '累积': 'cumulative',
    '知边': 'known boundary',
    '远低': 'far lower',
    '低质': 'low quality',
    '教训': 'lesson',
    '见正': 'seen positive',
    '逆决': 'inverse decision',
    '求各': 'require each',
    '语境': 'context',
    '受导': 'subject to',
    '支配': 'dominate',
    '验概': 'empirical probability',
    '划退': 'partition degeneracy',
    '任务': 'task',
    '刻画': 'characterize',
    '差约': 'variance approximately',
    '随变': 'random variable',
    '谱聚': 'spectral clustering',
    '密项': 'density term',
    '致项': 'consistency term',
    '球形': 'spherical',
    '评排': 'evaluation ranking',
    '超越': 'exceed',
    '切断': 'cut off',
    '散正': 'dispersion positive',
    '正运': 'correct operation',
    '趋近': 'approaches',
    '更充': 'more sufficient',
    '宽松': 'relaxed',
    '看似': 'seemingly',
    '交互': 'interaction',
    '指南': 'guide',
    '键长': 'key length',
    '补救': 'remedy',
    '放弃': 'abandon',
    '互补': 'complementary',
    '正反': 'positive/negative',
    '超基': 'exceed baseline',
    '渡区': 'transition region',
    '整义': 'entire meaning',
    '共指': 'co-reference',
    '区差': 'discrimination',
    '驱聚': 'drive clustering',
    '建构': 'construction',
    '遗漏': 'omission',
    '论述': 'discussion',
    '程决': 'process determines',
    '偏离': 'deviate',
    '解恒': 'solution constant',
    '附额': 'additional',
    '互斥': 'mutually exclusive',
    '易懂': 'easy',
    '较低': 'lower',
    '难驱': 'difficulty-driven',
    '含难': 'contains hard',
    '表良': 'appears good',
    '习决': 'learning determines',
    '解立': 'decomposition holds',
    '复核': 'verify',
    '身更': 'itself more',
    '区者': 'distinguish them',
    '价认': 'equivalent to',
    '交叠': 'overlap',
    '低位': 'lower bits',
    '抵抗': 'resist',
    '域确': 'domain confirmed',
    '际表': 'actual expression',
    '优随': 'optimal random',
    '难耦': 'hard to decouple',
    '异质': 'heterogeneous',
    '更细': 'more refined',
    '假阳': 'false positive',
    '何隐': 'what hidden',
    '簇内': 'within cluster',
    '典测': 'canonical test',
    '具变': 'possess variation',
    '换言': 'in other words',
    '哪位': 'which',
    '视角': 'perspective',
    '箭头': 'arrow',
    '马尔': 'Markov',
    '施额': 'apply additional',
    '么隐': 'what implicit',
    '么存': 'what exists',
    '减弱': 'weaken',
    '竞争': 'competition',
    '批判': 'critique',
    '评价': 'evaluation',
    '该解': 'this solution',
    '稍弱': 'slightly weaker',
    '降少': 'reduce',
    '际操': 'actual operation',
    '乘积': 'product',
    '恒立': 'always holds',
    '论真': 'argument true',
    '此者': 'this one',
    '狭窄': 'narrow',
    '通具': 'through',
    '某特': 'some specific',
    '附温': 'appendix temperature',
    '支柱': 'pillar',

    # === Three-character fragments ===
    '损失基': 'loss-based',
    '较基准': 'comparison baseline',
    '混淆矩': 'confusion matrix',
    '互信息': 'mutual information',
    '诚暴击': 'honest critique',
    '离间隙': 'separation gap',
    '指示变': 'indicator variable',
    '严格鞍': 'strict saddle',
    '期望义': 'expected meaning',
    '严格立': 'strictly holds',
    '观测联': 'observed joint',
    '解递归': 'solve recurrence',
    '臂老虎': 'bandit',
    '内散布': 'within scatter',
    '步长调': 'step size schedule',
    '档声称': 'document claims',
    '贝叶斯': 'Bayesian',
    '估计退': 'estimator degeneracy',
    '总变差': 'total variation',
    '仍然立': 'still holds',
    '转移矩': 'transition matrix',
    '更仔细': 'more careful',
    '梯信号': 'gradient signal',
    '渐近阶': 'asymptotic order',
    '边际退': 'marginal degeneracy',
    '签信息': 'label information',
    '档承认': 'document admits',
    '诚赤字': 'honest deficit',
    '严格优': 'strictly optimal',
    '变异系': 'coefficient of variation',
    '凭观测': 'from observed',
    '初版完': 'first version complete',
    '完美区': 'perfectly distinguish',
    '匀翻转': 'uniform flip',
    '考虑带': 'consider with',
    '孤立驻': 'isolated stationary',
    '头坍塌': 'head collapse',
    '头特异': 'head-specific',
    '代表元': 'representative',
    '立取决': 'holds depending',
    '丰富程': 'richness degree',
    '并重排': 'and rearrange',
    '彼此距': 'mutual distance',
    '入特驻': 'enter specific stationary',
    '邻近节': 'neighboring section',
    '更细致': 'more detailed',
    '轮损失': 'per-round loss',
    '剩余轮': 'remaining rounds',
    '差距随': 'gap follows',
    '游任务': 'game task',
    '误删价': 'incorrectly pruned value',
    '逐轮变': 'per-round change',
    '寻找退': 'search degeneracy',
    '际读完': 'actual reading',
    '全攻击': 'full attack',
    '考虑位': 'consider position',
    '求步长': 'require step size',
    '承认商': 'admit quotient',
    '确严格': 'indeed rigorous',
    '令费解': 'puzzling',
    '驱位移': 'drive displacement',
    '代表维': 'represent dimension',
    '维景观': 'high-dimensional landscape',
    '细微处': 'subtlety',
    '更微妙': 'more subtle',
    '心重建': 'core reconstruction',
    '梯传播': 'gradient propagation',
    '处流形': 'at manifold',
    '构误导': 'structurally misleading',
    '组手选': 'group hand-picked',
    '程编号': 'process numbering',
    '评语义': 'evaluation semantics',
    '声称商': 'claim quotient',
    '蕴含梯': 'implies gradient',
    '处梯差': 'at gradient difference',
    '更精细': 'more refined',
    '累积效': 'cumulative effect',
    '通缩写': 'through abbreviation',
    '审稿程': 'review process',
    '天然约': 'naturally approximately',
    '差距决': 'gap determines',
    '何松弛': 'what relaxation',
    '较松弛': 'comparatively relaxed',
    '权投票': 'weighted vote',
    '签随变': 'label random variable',
    '知局限': 'known limitation',
    '表明存': 'indicates existence',
    '簇形状': 'cluster shape',
    '述流程': 'described pipeline',
    '越宽松': 'more relaxed',
    '直观事': 'intuitive fact',
    '限宽松': 'finite relaxed',
    '随翻转': 'random flip',
    '际解读': 'practical interpretation',
    '步阻止': 'step prevents',
    '际指南': 'practical guide',
    '辅助改': 'auxiliary improvement',
    '损失阈': 'loss threshold',
    '任务重': 'task importance',
    '联刻画': 'joint characterization',
    '程优先': 'process priority',
    '犯错并': 'makes mistakes and',
    '签身具': 'label itself has',
    '注此处': 'note here',
    '较观测': 'compare observed',
    '者知道': 'one knows',
    '域重叠': 'domain overlap',
    '额观测': 'additional observation',
    '角占优': 'angle dominant',
    '签翻转': 'label flip',
    '仍然存': 'still exists',
    '程妥协': 'process compromise',
    '际遵循': 'actually follows',
    '纯随故': 'purely random',
    '签歧义': 'label ambiguity',
    '边际概': 'marginal probability',

    # === Four-character fragments ===
    '期望单调': 'expected monotonic',
    '重构损失': 'reconstruction loss',
    '雅洁审计': 'Yajie audit',
    '损失景观': 'loss landscape',
    '致命缺陷': 'fatal defect',
    '冷启协议': 'cold start protocol',
    '保守剪枝': 'conservative pruning',
    '剪枝移除': 'pruning removal',
    '层描述符': 'layer descriptor',
    '压缩保真': 'compression fidelity',
    '取决历史': 'depends on history',
    '期望损失': 'expected loss',
    '共享表示': 'shared representation',
    '信息增益': 'information gain',
    '宏观单调': 'macroscopic monotonic',
    '衰减步长': 'decaying step size',
    '优损失基': 'outperform loss-based',
    '约束更少': 'fewer constraints',
    '接近随基': 'approaches random baseline',
    '统计检验': 'statistical test',
    '审计报告': 'audit report',
    '先备知识': 'prerequisite knowledge',
    '头索引按': 'head index by',
    '边际估计': 'marginal estimate',
    '逃离该鞍': 'escape that saddle',
    '广泛观察': 'widely observed',
    '早期阶段': 'early phase',
    '吸引盆前': 'before attraction basin',
    '快速衰减': 'rapid decay',
    '期望梯范': 'expected gradient norm',
    '信号累积': 'signal accumulation',
    '间随游走': 'random walk between',
    '事先知道': 'known in advance',
    '维护权重': 'maintain weights',
    '观测奖励': 'observed reward',
    '奖励估计': 'reward estimate',
    '严格推导': 'rigorous derivation',
    '设剪枝规': 'set pruning rule',
    '累积损失': 'cumulative loss',
    '逐轮单调': 'per-round monotonic',
    '表示越散': 'representation more dispersed',
    '越容易歧': 'easier to be ambiguous',
    '信息损失': 'information loss',
    '预测置信': 'prediction confidence',
    '表示包含': 'representation contains',
    '任务间存': 'exists between tasks',
    '信息单调': 'information monotonic',
    '导致权重': 'leads to weights',
    '揭示修剪': 'reveals pruning',
    '监控梯范': 'monitor gradient norm',
    '谱并检查': 'spectral and check',
    '推导某形': 'derive some form',
    '严苛审稿': 'rigorous review',
    '篇档声称': 'this document claims',
    '逻辑跳跃': 'logical leap',
    '严重遗漏': 'serious omission',
    '吹毛求疵': 'nitpicking',
    '档己承认': 'document itself admits',
    '盆间逃逸': 'escape between basins',
    '维景观间': 'between high-dim landscapes',
    '隐藏裂痕': 'hidden crack',
    '权重初始': 'weight initialization',
    '该臂永远': 'that arm forever',
    '避免误删': 'avoid incorrect pruning',
    '导致松弛': 'causes relaxation',
    '奖励信号': 'reward signal',
    '带噪估计': 'noisy estimate',
    '奖励观测': 'reward observation',
    '表示距离': 'representation distance',
    '打印语句': 'print statement',
    '声明初始': 'claim initialization',
    '声明手选': 'claim hand-picked',
    '低密区域': 'low-density region',
    '表示污染': 'representation corruption',
    '期望怎么': 'expected how',
    '观测带噪': 'observed noisy',
    '声称遗憾': 'claim regret',
    '期望递推': 'expectation recurrence',
    '前沿交叉': 'cutting-edge intersection',
    '雄心勃勃': 'ambitious',
    '循环伪代': 'loop pseudo-code',
    '修正建议': 'revision suggestion',
    '重写伪代': 'rewrite pseudo-code',
    '审稿签字': 'reviewer signature',
    '签翻转事': 'label flip event',
    '间隙收窄': 'gap narrows',
    '原始命题': 'original proposition',
    '渐近完美': 'asymptotically perfect',
    '借助交叉': 'via cross',
    '权投票完': 'weighted voting complete',
    '风险估计': 'risk estimate',
    '价混淆矩': 'equivalent confusion matrix',
    '天然离者': 'natural outlier',
    '权重命题': 'weight proposition',
    '回归任务': 'regression task',
    '此离间隙': 'this separation gap',
    '输入随变': 'input random variable',
    '包含足够': 'contains sufficient',
    '效互信息': 'effective mutual information',
    '极限接近': 'limit approaches',
    '似然估计': 'likelihood estimate',
    '判断平衡': 'judge balance',
    '放总变差': 'relax total variation',
    '详见附录': 'see appendix',
    '信息支撑': 'information support',
    '少超随基': 'slightly exceed random baseline',
    '携带极少': 'carry extremely little',
    '幅超越基': 'substantially exceed baseline',
    '何诊断弱': 'how to diagnose weak',
    '诊断检查': 'diagnostic check',
    '超越此基': 'exceed this baseline',
    '诊断表明': 'diagnosis indicates',
    '低互信息': 'low mutual information',
    '携带足够': 'carry sufficient',
    '声明移除': 'claim removal',
    '描述输入': 'describe input',
    '观测映射': 'observed mapping',
    '确切知道': 'know exactly',
    '打破什么': 'break what',
    '技术基础': 'technical foundation',
    '细微差别': 'nuance',
    '明确检验': 'explicit test',
    '求审查少': 'require review few',
    '签决观测': 'label-determined observation',
    '该解失效': 'this solution fails',
    '提交审查': 'submit for review',
    '虽然极端': 'although extreme',
    '预测某特': 'predict some specific',
    '原版附录': 'original appendix',

    # === Longer fragments ===
    '求初始阶段审查少': 'requiring fewer initial-phase reviews',
    '确讨论保守剪枝': 'indeed discusses conservative pruning',
    '雅洁审计统计': 'Yajie audit statistics',
    '循环改善雅洁': 'iterative Yajie improvement',
    '信任衰减硬阈': 'trust decay hard threshold',
    '必须穿越盆间': 'must cross between basins',
    '必须翻越势垒': 'must surmount potential barrier',
    '雅洁审计估计': 'Yajie audit estimate',
    '论证混淆概念': 'argument confuses concepts',
    '致命缺陷汇总': 'fatal defect summary',
    '衰减步长导致': 'decaying step size causes',
    '共享归纳偏置': 'shared inductive bias',
    '偏离纯损失排': 'deviates from pure loss ranking',
    '共构逻辑闭环': 'co-construct logical closure',
    '损失景观具': 'loss landscape has',
    '果初始权重': 'if initial weight',
    '半致命缺陷': 'semi-fatal defect',
    '总变差距离': 'total variation distance',
    '互信息估计': 'mutual information estimate',
    '选取代表元': 'select representative',
    '迭代沿负曲': 'iterate along negative curvature',
    '凸损失景观': 'convex loss landscape',
    '损失景观族': 'loss landscape family',
    '轮期望奖励': 'per-round expected reward',
    '避免误删质': 'avoid incorrect pruning quality',
    '重构程捕获': 'reconstruction process captures',
    '价声称重构': 'equivalence claim reconstruction',
    '互信息单调': 'mutual information monotonic',
    '重构确捕捉': 'reconstruction indeed captures',
    '模拟维景观': 'simulate high-dim landscape',
    '周期盆几何': 'periodic basin geometry',
    '项惩罚误删': 'term penalizes incorrect pruning',
    '论证逻辑际': 'argument logic actually',
    '果处密区域': 'if in dense region',
    '真正推导概': 'truly derive probability',
    '接近随猜测': 'approaches random guess',
    '态期望损失': 'state expected loss',
    '详细推导见': 'detailed derivation see',
    '超越随猜测': 'exceed random guess',
    '任务身很难': 'task itself is hard',
    '调整兰德指': 'adjusted Rand index',
    '维手描述符': 'high-dim hand-crafted descriptor',
    '更强描述符': 'stronger descriptor',
    '超越损失基': 'exceed loss-based',
    '阶段明确配': 'phase explicit allocation',
}

def translate_file(input_path, output_path):
    with open(input_path, 'r', encoding='utf-8') as fh:
        content = fh.read()
    
    # Sort by length (longest first) to avoid partial matches
    sorted_frags = sorted(TRANSLATIONS.keys(), key=len, reverse=True)
    
    for frag in sorted_frags:
        if frag in content:
            content = content.replace(frag, TRANSLATIONS[frag])
    
    with open(output_path, 'w', encoding='utf-8') as fh:
        fh.write(content)
    
    # Count remaining Chinese
    remaining = pattern.findall(content)
    print(f'{input_path}: {len(remaining)} Chinese fragments remaining')

for f in files:
    translate_file(f, f)
