#!/usr/bin/env python3
"""Batch Chinese->English translation for SCX LaTeX files."""
import re, os, sys

FILES = [
    "theory/self_evolution/multi_head_spring_and_positional_encoding_analysis.tex",
    "theory/self_evolution/ppe_rigorous_derivation.tex",
    "theory/self_evolution/README.tex",
    "theory/self_evolution/situs_final_verification.tex",
    "theory/self_evolution/situs_physical_validation.tex",
    "theory/self_evolution/spring_convergence_analysis.tex",
    "theory/self_evolution/spring_hostile_review.tex",
    "theory/theorems/01_noise_detection_guarantee.tex",
    "theory/theorems/02_weak_feature_failure.tex",
    "theory/theorems/03_unidentifiability_theorem.tex",
    "theory/theorems/README.tex",
]

# Comprehensive replacement dictionary: Chinese -> English
REPLACEMENTS = [
    # --- Common mixed-language fragments ---
    # Mathematical terms
    ("不等式", " inequality"),
    ("定理", "theorem"),
    ("引理", "lemma"),
    ("推论", "corollary"),
    ("命题", "proposition"),
    ("证明", "proof"),
    ("定义", "definition"),
    ("假设", "assumption"),
    ("条件", "condition"),
    ("结论", "conclusion"),
    ("附录", "appendix"),
    ("参考文献", "references"),
    ("摘要", "abstract"),
    ("符号", "notation"),
    ("约定", "convention"),
    ("推导", "derivation"),
    ("分析", "analysis"),
    ("验证", "verification"),
    ("评估", "assessment"),
    ("修正", "correction"),
    ("修改", "modification"),
    ("修正版", "corrected version"),
    ("修正后", "corrected"),
    ("修正项", "correction term"),
    ("修复", "fix"),
    ("修复吗", "be fixed"),
    ("检查", "check"),
    ("报告", "report"),
    ("最终", "final"),
    ("严格", "rigorous"),
    ("严密", "rigorous"),
    ("严谨", "rigorous"),
    ("诚实", "honest"),
    ("审查", "audit"),
    ("审计", "audit"),
    ("评价", "assessment"),
    ("断言", "claim"),
    ("声称", "claim"),
    ("声明", "statement"),
    ("陈述", "statement"),
    ("描述", "description"),
    ("解释", "explanation"),
    ("注释", "note"),
    ("备注", "remark"),
    ("警告", "warning"),
    ("注意", "note"),
    ("局限", "limitation"),
    ("缺陷", "defect"),
    ("错误", "error"),
    ("变量", "variable"),
    ("随机变量", "random variable"),
    ("常数", "constant"),
    ("函数", "function"),
    ("映射", "mapping"),
    ("空间", "space"),
    ("分布", "distribution"),
    ("概率", "probability"),
    ("期望", "expectation"),
    ("方差", "variance"),
    ("协方差", "covariance"),
    ("信息", "information"),
    ("互信息", "mutual information"),
    ("熵", "entropy"),
    ("散度", "divergence"),
    ("损失", "loss"),
    ("误差", "error"),
    ("残差", "residual"),
    ("梯度", "gradient"),
    ("噪声", "noise"),
    ("信号", "signal"),
    ("样本", "sample"),
    ("数据", "data"),
    ("特征", "feature"),
    ("标签", "label"),
    ("分类", "classification"),
    ("检测", "detection"),
    ("估计", "estimate"),
    ("预测", "prediction"),
    ("收敛", "convergence"),
    ("发散", "divergence"),
    ("衰减", "decay"),
    ("增长", "growth"),
    ("降低", "decrease"),
    ("增加", "increase"),
    ("减少", "reduce"),
    ("改进", "improve"),
    ("退化", "degenerate"),
    ("崩溃", "collapse"),
    ("稳定", "stable"),
    ("不稳定", "unstable"),
    ("最优", "optimal"),
    ("次优", "suboptimal"),
    ("充分", "sufficient"),
    ("必要", "necessary"),
    ("独立", "independent"),
    ("依赖", "dependent"),
    ("一致", "consistent"),
    ("不一致", "inconsistent"),
    ("精确", "precise"),
    ("近似", "approximate"),
    ("启发式", "heuristic"),
    ("猜想", "conjecture"),
    ("假设", "assumption"),
    ("猜测", "guess"),
    ("观察", "observation"),
    ("实验", "experiment"),
    ("理论", "theory"),
    ("实践", "practice"),
    ("应用", "application"),
    ("场景", "scenario"),
    ("情况", "situation"),
    ("案例", "case"),
    ("实例", "example"),
    ("反例", "counterexample"),
    ("边界", "boundary"),
    ("界", "bound"),
    ("上界", "upper bound"),
    ("下界", "lower bound"),
    ("边界", "bound"),
    ("临界", "critical"),
    ("阈值", "threshold"),
    ("参数", "parameter"),
    ("超参数", "hyperparameter"),
    ("维度", "dimension"),
    ("大小", "size"),
    ("尺度", "scale"),
    ("数量", "quantity"),
    ("质量", "quality"),
    ("速率", "rate"),
    ("指数", "exponential"),
    ("线性", "linear"),
    ("非线性", "nonlinear"),
    ("多项式", "polynomial"),
    ("对数", "logarithm"),
    ("权重", "weight"),
    ("偏置", "bias"),
    ("激活", "activation"),
    ("归一化", "normalization"),
    ("正则化", "regularization"),
    ("惩罚", "penalty"),
    ("优化", "optimization"),
    ("目标", "objective"),
    ("约束", "constraint"),
    ("可行", "feasible"),
    ("不可行", "infeasible"),
    ("紧的", "tight"),
    ("松的", "loose"),
    ("空的", "vacuous"),
    ("平凡的", "trivial"),
    ("非平凡的", "non-trivial"),
    ("有界", "bounded"),
    ("无界", "unbounded"),
    ("可微", "differentiable"),
    ("不可微", "non-differentiable"),
    ("凸", "convex"),
    ("非凸", "non-convex"),
    ("光滑", "smooth"),
    ("连续", "continuous"),
    ("不连续", "discontinuous"),
    ("可逆", "invertible"),
    ("不可逆", "non-invertible"),
    ("对称", "symmetric"),
    ("非对称", "asymmetric"),
    ("可交换", "commutative"),
    ("可区分", "distinguishable"),
    ("不可区分", "indistinguishable"),
    ("可识别", "identifiable"),
    ("不可识别", "unidentifiable"),
    ("可观测", "observable"),
    ("不可观测", "unobservable"),
    ("可解释", "interpretable"),
    ("可计算", "computable"),
    ("不可计算", "uncomputable"),
    ("确定", "determine"),
    ("确定性的", "deterministic"),
    ("随机的", "stochastic"),
    ("有限的", "finite"),
    ("无限的", "infinite"),
    ("离散的", "discrete"),
    ("连续的", "continuous"),
    ("局部的", "local"),
    ("全局的", "global"),
    ("显式的", "explicit"),
    ("隐式的", "implicit"),
    ("直接的", "direct"),
    ("间接的", "indirect"),
    ("正向的", "positive"),
    ("负向的", "negative"),
    ("主要的", "primary"),
    ("次要的", "secondary"),

    # --- Common multi-word phrases ---
    ("在...下", "under"),
    ("在...中", "in"),
    ("在...上", "on"),
    ("在...内", "within"),
    ("在...之间", "between"),
    ("对...的影响", "impact on"),
    ("与...的关系", "relationship with"),
    ("与...的联系", "connection to"),
    ("与...的比较", "comparison with"),
    ("关于...的", "regarding"),
    ("基于...的", "based on"),
    ("取决于", "depends on"),
    ("不取决于", "does not depend on"),
    ("等价于", "is equivalent to"),
    ("对应于", "corresponds to"),
    ("定义为", "is defined as"),
    ("称为", "is called"),
    ("记作", "denoted as"),
    ("表示为", "denoted by"),
    ("由...给出", "given by"),
    ("由...决定", "determined by"),
    ("由...控制", "controlled by"),
    ("受限于", "subject to"),
    ("满足", "satisfies"),
    ("成立", "holds"),
    ("不成立", "does not hold"),
    ("存在", "there exists"),
    ("不存在", "there does not exist"),
    ("唯一", "unique"),
    ("所有", "all"),
    ("任意", "any"),
    ("某个", "some"),
    ("每个", "each"),
    ("至少", "at least"),
    ("至多", "at most"),
    ("恰好", "exactly"),
    ("大约", "approximately"),
    ("几乎", "almost"),
    ("可能", "possible"),
    ("不可能", "impossible"),
    ("必然", "necessarily"),
    ("通常", "usually"),
    ("总是", "always"),
    ("从不", "never"),
    ("有时", "sometimes"),
    ("经常", "often"),
    ("罕见", "rarely"),
    ("因此", "therefore"),
    ("所以", "hence"),
    ("因为", "because"),
    ("由于", "due to"),
    ("然而", "however"),
    ("但是", "but"),
    ("而且", "moreover"),
    ("此外", "furthermore"),
    ("另一方面", "on the other hand"),
    ("同时", "simultaneously"),
    ("此外", "in addition"),
    ("特别地", "in particular"),
    ("具体地", "specifically"),
    ("更一般地", "more generally"),
    ("换句话说", "in other words"),
    ("即", "i.e."),
    ("也就是说", "that is"),
    ("例如", "e.g."),
    ("等等", "etc."),
    ("第一", "first"),
    ("第二", "second"),
    ("第三", "third"),
    ("第四", "fourth"),
    ("第五", "fifth"),
    ("首先", "first of all"),
    ("其次", "secondly"),
    ("然后", "then"),
    ("最后", "finally"),
    ("步骤", "step"),
    ("阶段", "stage"),
    ("部分", "part"),
    ("章节", "section"),
    ("组件", "component"),
    ("模块", "module"),
    ("框架", "framework"),
    ("系统", "system"),
    ("模型", "model"),
    ("方法", "method"),
    ("算法", "algorithm"),
    ("技术", "technique"),
    ("策略", "strategy"),
    ("方案", "scheme"),
    ("设计", "design"),
    ("实现", "implementation"),
    ("结构", "structure"),
    ("机制", "mechanism"),
    ("过程", "process"),
    ("效应", "effect"),
    ("影响", "impact"),
    ("结果", "result"),
    ("性能", "performance"),
    ("精度", "accuracy"),
    ("效率", "efficiency"),
    ("复杂度", "complexity"),
    ("鲁棒性", "robustness"),
    ("泛化", "generalization"),
    ("过拟合", "overfitting"),
    ("欠拟合", "underfitting"),
    ("容量", "capacity"),
    ("表达力", "expressiveness"),
    ("计算", "computation"),
    ("训练", "training"),
    ("测试", "testing"),
    ("验证", "validation"),
    ("推理", "inference"),
    ("预测", "prediction"),
    ("评估", "evaluation"),
    ("测量", "measurement"),
    ("采样", "sampling"),
    ("初始化", "initialization"),
    ("更新", "update"),
    ("迭代", "iteration"),
    ("循环", "loop"),
    ("递归", "recursion"),
    ("调度", "schedule"),
    ("学习率", "learning rate"),
    ("步长", "step size"),
    ("动量", "momentum"),
    ("批大小", "batch size"),
    ("轮次", "epoch"),
    ("周期", "period"),
    ("频率", "frequency"),
    ("波长", "wavelength"),
    ("幅度", "amplitude"),
    ("相位", "phase"),
    ("能量", "energy"),
    ("力", "force"),
    ("温度", "temperature"),
    ("压力", "pressure"),
    ("密度", "density"),
    ("电荷", "charge"),
    ("电场", "electric field"),
    ("磁场", "magnetic field"),
    ("势", "potential"),
    ("轨道", "orbital"),
    ("原子", "atom"),
    ("分子", "molecule"),
    ("晶体", "crystal"),
    ("晶格", "lattice"),
    ("表面", "surface"),
    ("界面", "interface"),
    ("边界", "boundary"),
    ("缺陷", "defect"),
    ("空位", "vacancy"),
    ("间隙", "interstitial"),
    ("位错", "dislocation"),
    ("晶界", "grain boundary"),
    ("体相", "bulk"),
    ("掺杂", "doping"),
    ("吸附", "adsorption"),
    ("催化", "catalysis"),
    ("反应", "reaction"),
    ("扩散", "diffusion"),
    ("迁移", "migration"),
    ("相变", "phase transition"),
    ("熔化", "melting"),
    ("凝固", "solidification"),
    ("弹性", "elastic"),
    ("塑性", "plastic"),
    ("断裂", "fracture"),
    ("疲劳", "fatigue"),
    ("蠕变", "creep"),
    ("硬度", "hardness"),
    ("强度", "strength"),
    ("韧性", "toughness"),
    ("脆性", "brittleness"),
    ("导电", "conductivity"),
    ("电阻", "resistivity"),
    ("介电", "dielectric"),
    ("光学", "optical"),
    ("磁性", "magnetic"),
    ("热学", "thermal"),
    ("力学", "mechanical"),
    ("化学", "chemical"),
    ("物理", "physical"),
    ("生物", "biological"),
    ("材料", "material"),
    ("蛋白质", "protein"),
    ("氨基酸", "amino acid"),
    ("残基", "residue"),
    ("序列", "sequence"),
    ("结构", "structure"),
    ("折叠", "folding"),
    ("螺旋", "helix"),
    ("折叠", "sheet"),
    ("环", "loop"),
    ("位点", "site"),
    ("活性", "activity"),
    ("功能", "function"),
    ("相互作用", "interaction"),
    ("结合", "binding"),
    ("识别", "recognition"),
    ("催化", "catalysis"),
    ("抑制", "inhibition"),
    ("激活", "activation"),
    ("信号传导", "signaling"),
    ("表达", "expression"),
    ("调控", "regulation"),
    ("修饰", "modification"),
    ("突变", "mutation"),
    ("进化", "evolution"),
    ("保守", "conservation"),
    ("同源", "homology"),
    ("相似性", "similarity"),
    ("差异性", "difference"),

    # --- Abstract terms ---
    ("状态", "state"),
    ("状况", "status"),
    ("环境", "environment"),
    ("上下文", "context"),
    ("背景", "background"),
    ("动机", "motivation"),
    ("贡献", "contribution"),
    ("创新", "innovation"),
    ("新颖性", "novelty"),
    ("意义", "significance"),
    ("重要性", "importance"),
    ("难度", "difficulty"),
    ("挑战", "challenge"),
    ("问题", "problem"),
    ("开放问题", "open problem"),
    ("解决方案", "solution"),
    ("见解", "insight"),
    ("思路", "idea"),
    ("观点", "viewpoint"),
    ("视角", "perspective"),
    ("角度", "angle"),
    ("方面", "aspect"),
    ("层次", "level"),
    ("类型", "type"),
    ("类别", "category"),
    ("种类", "kind"),
    ("形式", "form"),
    ("格式", "format"),
    ("模式", "pattern"),
    ("样式", "style"),
    ("趋势", "trend"),
    ("行为", "behavior"),
    ("属性", "property"),
    ("特性", "characteristic"),
    ("能力", "capability"),
    ("可能性", "possibility"),
    ("必然性", "necessity"),
    ("合理性", "reasonableness"),
    ("有效性", "effectiveness"),
    ("正确性", "correctness"),
    ("完整性", "completeness"),
    ("一致性", "consistency"),
    ("可靠性", "reliability"),
    ("可用性", "usability"),
    ("可扩展性", "scalability"),
    ("可维护性", "maintainability"),
    ("可重复性", "reproducibility"),
    ("可解释性", "interpretability"),
    ("公平性", "fairness"),
    ("安全性", "safety"),
    ("隐私性", "privacy"),

    # --- Common action verbs ---
    ("使用", "use"),
    ("采用", "adopt"),
    ("应用", "apply"),
    ("利用", "utilize"),
    ("需要", "require"),
    ("必须", "must"),
    ("应该", "should"),
    ("可以", "can"),
    ("可能", "may"),
    ("能够", "be able to"),
    ("不能", "cannot"),
    ("允许", "allow"),
    ("禁止", "prohibit"),
    ("推荐", "recommend"),
    ("建议", "suggest"),
    ("要求", "require"),
    ("期望", "expect"),
    ("希望", "hope"),
    ("试图", "attempt"),
    ("尝试", "try"),
    ("努力", "strive"),
    ("确保", "ensure"),
    ("保证", "guarantee"),
    ("验证", "verify"),
    ("确认", "confirm"),
    ("检查", "check"),
    ("测试", "test"),
    ("测量", "measure"),
    ("计算", "compute"),
    ("估计", "estimate"),
    ("推断", "infer"),
    ("推导", "derive"),
    ("证明", "prove"),
    ("展示", "demonstrate"),
    ("表明", "indicate"),
    ("显示", "show"),
    ("揭示", "reveal"),
    ("发现", "discover"),
    ("观察", "observe"),
    ("记录", "record"),
    ("报告", "report"),
    ("描述", "describe"),
    ("定义", "define"),
    ("形式化", "formalize"),
    ("构建", "construct"),
    ("建立", "establish"),
    ("创造", "create"),
    ("生成", "generate"),
    ("产生", "produce"),
    ("导致", "lead to"),
    ("引起", "cause"),
    ("引发", "trigger"),
    ("促进", "promote"),
    ("抑制", "suppress"),
    ("阻止", "prevent"),
    ("避免", "avoid"),
    ("消除", "eliminate"),
    ("降低", "reduce"),
    ("增加", "increase"),
    ("提高", "improve"),
    ("优化", "optimize"),
    ("调整", "adjust"),
    ("修改", "modify"),
    ("替换", "replace"),
    ("移除", "remove"),
    ("添加", "add"),
    ("插入", "insert"),
    ("删除", "delete"),
    ("合并", "merge"),
    ("拆分", "split"),
    ("组合", "combine"),
    ("分解", "decompose"),
    ("扩展", "extend"),
    ("收缩", "shrink"),
    ("放大", "amplify"),
    ("缩小", "narrow"),
    ("开始", "start"),
    ("结束", "end"),
    ("继续", "continue"),
    ("停止", "stop"),
    ("暂停", "pause"),
    ("恢复", "resume"),
    ("完成", "complete"),
    ("失败", "fail"),
    ("成功", "succeed"),

    # --- Common noun phrases ---
    ("专家模型", "expert model"),
    ("评分函数", "scoring function"),
    ("检测器", "detector"),
    ("分类器", "classifier"),
    ("回归器", "regressor"),
    ("估计器", "estimator"),
    ("预测器", "predictor"),
    ("编码器", "encoder"),
    ("解码器", "decoder"),
    ("生成器", "generator"),
    ("判别器", "discriminator"),
    ("优化器", "optimizer"),
    ("调度器", "scheduler"),
    ("正则化器", "regularizer"),
    ("初始化器", "initializer"),
    ("激活函数", "activation function"),
    ("损失函数", "loss function"),
    ("目标函数", "objective function"),
    ("代价函数", "cost function"),
    ("奖励函数", "reward function"),
    ("值函数", "value function"),
    ("核函数", "kernel function"),
    ("基函数", "basis function"),
    ("特征映射", "feature mapping"),
    ("特征向量", "feature vector"),
    ("特征空间", "feature space"),
    ("输入空间", "input space"),
    ("输出空间", "output space"),
    ("标签空间", "label space"),
    ("参数空间", "parameter space"),
    ("状态空间", "state space"),
    ("动作空间", "action space"),
    ("搜索空间", "search space"),
    ("解空间", "solution space"),
    ("假设空间", "hypothesis space"),
    ("模型空间", "model space"),
    ("数据分布", "data distribution"),
    ("先验分布", "prior distribution"),
    ("后验分布", "posterior distribution"),
    ("联合分布", "joint distribution"),
    ("条件分布", "conditional distribution"),
    ("边缘分布", "marginal distribution"),
    ("经验分布", "empirical distribution"),
    ("真实分布", "true distribution"),
    ("估计分布", "estimated distribution"),
    ("概率密度", "probability density"),
    ("概率质量", "probability mass"),
    ("累积分布", "cumulative distribution"),
    ("分位数", "quantile"),
    ("中位数", "median"),
    ("均值", "mean"),
    ("方差", "variance"),
    ("标准差", "standard deviation"),
    ("协方差矩阵", "covariance matrix"),
    ("相关系数", "correlation coefficient"),
    ("偏度", "skewness"),
    ("峰度", "kurtosis"),
    ("矩", "moment"),
    ("中心矩", "central moment"),
    ("原点矩", "raw moment"),
    ("信息熵", "information entropy"),
    ("交叉熵", "cross entropy"),
    ("条件熵", "conditional entropy"),
    ("联合熵", "joint entropy"),
    ("相对熵", "relative entropy"),
    ("KL 散度", "KL divergence"),
    ("JS 散度", "JS divergence"),
    ("总变差", "total variation"),
    ("Wasserstein 距离", "Wasserstein distance"),
    ("Hellinger 距离", "Hellinger distance"),
    ("核密度估计", "kernel density estimation"),
    ("最大似然", "maximum likelihood"),
    ("最大后验", "maximum a posteriori"),
    ("贝叶斯估计", "Bayesian estimation"),
    ("蒙特卡洛", "Monte Carlo"),
    ("马尔可夫链", "Markov chain"),
    ("隐马尔可夫", "hidden Markov"),
    ("卡尔曼滤波", "Kalman filter"),
    ("粒子滤波", "particle filter"),
    ("变分推断", "variational inference"),
    ("期望最大化", "expectation maximization"),
    ("梯度下降", "gradient descent"),
    ("随机梯度", "stochastic gradient"),
    ("批量梯度", "batch gradient"),
    ("小批量", "mini-batch"),
    ("动量法", "momentum method"),
    ("自适应", "adaptive"),
    ("反向传播", "backpropagation"),
    ("前向传播", "forward propagation"),
    ("链式法则", "chain rule"),
    ("自动微分", "automatic differentiation"),
    ("数值微分", "numerical differentiation"),
    ("符号微分", "symbolic differentiation"),

    # --- Compound phrases (longer patterns) ---
    ("在...条件下", "under the condition that"),
    ("在...假设下", "under the assumption that"),
    ("在...情况下", "in the case of"),
    ("在...意义上", "in the sense that"),
    ("当...时", "when"),
    ("当且仅当", "if and only if"),
    ("如果...那么", "if ... then"),
    ("不仅...而且", "not only ... but also"),
    ("要么...要么", "either ... or"),
    ("既不...也不", "neither ... nor"),
    ("虽然...但是", "although ..."),
    ("因为...所以", "because ... therefore"),
    ("由于...因此", "since ... hence"),
    ("为了...而", "in order to"),
    ("以便", "so that"),
    ("以免", "lest"),
    ("除非", "unless"),
    ("除了", "except"),
    ("包括", "including"),
    ("排除", "excluding"),
    ("根据", "according to"),
    ("按照", "following"),
    ("依照", "in accordance with"),
    ("通过", "through"),
    ("借助", "by means of"),
    ("依靠", "relying on"),
    ("鉴于", "in view of"),
    ("考虑到", "considering"),
    ("关于", "regarding"),
    ("对于", "for"),
    ("针对", "targeting"),
    ("面向", "towards"),
    ("围绕", "around"),
    ("涉及", "involving"),
    ("包含", "containing"),
    ("涵盖", "covering"),
    ("跨越", "spanning"),
    ("超越", "beyond"),
    ("处于", "in"),
    ("位于", "located at"),
    ("属于", "belonging to"),
    ("来自", "from"),
    ("前往", "to"),
    ("达到", "reach"),
    ("超过", "exceed"),
    ("低于", "below"),
    ("高于", "above"),
    ("等于", "equals"),
    ("不等于", "does not equal"),
    ("大于", "is greater than"),
    ("小于", "is less than"),
    ("远大于", "is much greater than"),
    ("远小于", "is much less than"),
    ("接近于", "approaches"),
    ("趋向于", "tends to"),
    ("收敛到", "converges to"),
    ("发散到", "diverges to"),
    ("趋于", "tends toward"),
]

def apply_replacements(text):
    """Apply all Chinese->English replacements."""
    for cn, en in REPLACEMENTS:
        text = text.replace(cn, en)
    return text

def main():
    base = "F:/scx"
    for filepath in FILES:
        full_path = os.path.join(base, filepath)
        if not os.path.exists(full_path):
            print(f"SKIP (not found): {full_path}")
            continue
        with open(full_path, "r", encoding="utf-8") as f:
            content = f.read()
        
        original_len = len(content)
        content = apply_replacements(content)
        new_len = len(content)
        
        # Count Chinese characters remaining
        chinese_chars = sum(1 for c in content if '\u4e00' <= c <= '\u9fff')
        
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(content)
        
        print(f"DONE: {filepath} ({original_len}->{new_len} bytes, {chinese_chars} Chinese chars remaining)")

if __name__ == "__main__":
    main()
