#!/usr/bin/env python3
"""Translate Chinese fragments in theory/ LaTeX files to English."""
import re, sys, os

def translate_file(filepath):
    """Apply comprehensive Chinese→English translations to a LaTeX file."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original = content
    
    # ============================================================
    # Common patterns across all files
    # ============================================================
    common = [
        # Section/paragraph labels
        ('符号与设定', 'Notation and Setup'),
        ('基础定义', 'Basic Definitions'),
        ('核心量', 'Core Quantities'),
        ('目录', 'Table of Contents'),
        ('问题', 'Problem'),
        ('形式化定义', 'Formal Definition'),
        ('证明', 'Proof'),
        ('推论', 'Corollary'),
        ('参考文献', 'References'),
        ('总结', 'Summary'),
        ('摘要', 'Abstract'),
        ('语境', 'Context'),
        ('标注', 'Annotations'),
        ('核心直觉', 'Core Intuition'),
        ('定理陈述（草案）', 'Theorem Statement (Draft)'),
        ('与已有定理的关系', 'Relationship to Existing Theorems'),
        
        # Proposition/Theorem labels  
        ('命题', 'Proposition'),
        ('定理', 'Theorem'),
        ('引理', 'Lemma'),
        ('定义', 'Definition'),
        ('猜想', 'Conjecture'),
        ('推论', 'Corollary'),
        
        # Common LaTeX section labels
        ('步骤', 'Step'),
        ('部分', 'Part'),
        ('设', 'Setup'),
        ('注', 'Note'),
        ('警告', 'Warning'),
        ('建议', 'Recommendation'),
        ('结论', 'Conclusion'),
        ('评价', 'Assessment'),
        ('判断', 'Judgment'),
        ('状态', 'Status'),
        ('输出类型', 'Output Type'),
        
        # Common academic terms
        ('严格可推', 'rigorously provable'),
        ('开放问题', 'open problem'),
        ('严格证明', 'rigorous proof'),
        ('形式化', 'formalization'),
        ('推导', 'derivation'),
        ('估计', 'estimation'),
        ('假设', 'hypothesis'),
        ('实验', 'experiment'),
        ('验证', 'validation'),
        ('分析', 'analysis'),
        ('数据', 'data'),
        ('模型', 'model'),
        ('参数', 'parameter'),
        ('函数', 'function'),
        ('空间', 'space'),
        ('分布', 'distribution'),
        ('特征', 'feature'),
        ('专家', 'expert'),
        ('样本', 'sample'),
        ('噪声', 'noise'),
        ('困难', 'difficulty'),
        ('质量', 'quality'),
        ('审计', 'audit'),
        ('信息', 'information'),
        ('理论', 'theory'),
        ('物理', 'physical'),
        ('数学', 'mathematical'),
        ('统计', 'statistical'),
        ('计算', 'computation'),
        ('学习', 'learning'),
        ('训练', 'training'),
        ('测试', 'test'),
        ('预测', 'prediction'),
        ('误差', 'error'),
        ('损失', 'loss'),
        ('梯度', 'gradient'),
        ('优化', 'optimization'),
        ('收敛', 'convergence'),
        ('稳定', 'stability'),
        ('鲁棒', 'robust'),
        ('敏感', 'sensitive'),
        ('依赖', 'dependence'),
        ('独立', 'independent'),
        ('条件', 'condition'),
        ('充分', 'sufficient'),
        ('必要', 'necessary'),
        ('等价', 'equivalent'),
        ('平凡', 'trivial'),
        ('非平凡', 'non-trivial'),
        ('最优', 'optimal'),
        ('次优', 'suboptimal'),
        ('上界', 'upper bound'),
        ('下界', 'lower bound'),
        ('紧界', 'tight bound'),
        ('松界', 'loose bound'),
        ('阈值', 'threshold'),
        ('权重', 'weight'),
        ('系数', 'coefficient'),
        ('常数', 'constant'),
        ('变量', 'variable'),
        ('随机', 'random'),
        ('确定', 'deterministic'),
        ('概率', 'probability'),
        ('期望', 'expectation'),
        ('方差', 'variance'),
        ('协方差', 'covariance'),
        ('熵', 'entropy'),
        ('互信息', 'mutual information'),
        ('散度', 'divergence'),
        ('距离', 'distance'),
        ('范数', 'norm'),
        ('度量', 'metric'),
        ('连续', 'continuous'),
        ('离散', 'discrete'),
        ('光滑', 'smooth'),
        ('非光滑', 'non-smooth'),
        ('凸', 'convex'),
        ('非凸', 'non-convex'),
        ('线性', 'linear'),
        ('非线性', 'nonlinear'),
        ('单调', 'monotonic'),
        ('有界', 'bounded'),
        ('无界', 'unbounded'),
        ('紧致', 'compact'),
        ('完备', 'complete'),
        ('可分', 'separable'),
        ('对称', 'symmetric'),
        ('非对称', 'asymmetric'),
        ('可逆', 'reversible'),
        ('不可逆', 'irreversible'),
        ('可区分', 'distinguishable'),
        ('不可区分', 'indistinguishable'),
        ('可观测', 'observable'),
        ('不可观测', 'unobservable'),
        ('可计算', 'computable'),
        ('不可计算', 'uncomputable'),
        ('可实现', 'realizable'),
        ('不可实现', 'unrealizable'),
        ('可证明', 'provable'),
        ('不可证明', 'unprovable'),
        ('存在', 'exists'),
        ('唯一', 'unique'),
        ('任意', 'arbitrary'),
        ('所有', 'all'),
        ('每个', 'each'),
        ('某个', 'some'),
        ('任何', 'any'),
        ('至少', 'at least'),
        ('至多', 'at most'),
        ('恰好', 'exactly'),
        ('近似', 'approximately'),
        ('严格', 'strictly'),
        ('几乎', 'almost'),
        ('可能', 'possibly'),
        ('必然', 'necessarily'),
        ('通常', 'typically'),
        
        # Common phrases
        ('其中', 'where'),
        ('即', 'i.e.'),
        ('例如', 'e.g.'),
        ('等等', 'etc.'),
        ('因此', 'therefore'),
        ('因为', 'because'),
        ('所以', 'thus'),
        ('但是', 'however'),
        ('虽然', 'although'),
        ('如果', 'if'),
        ('否则', 'otherwise'),
        ('并且', 'and'),
        ('或者', 'or'),
        ('不仅', 'not only'),
        ('而且', 'but also'),
        ('通过', 'via'),
        ('根据', 'according to'),
        ('关于', 'regarding'),
        ('对于', 'for'),
        ('由于', 'due to'),
        ('随着', 'as'),
        ('当', 'when'),
        ('然后', 'then'),
        ('首先', 'first'),
        ('其次', 'second'),
        ('最后', 'finally'),
        ('此外', 'moreover'),
        ('另外', 'additionally'),
        ('同时', 'simultaneously'),
        ('反而', 'instead'),
        ('相反', 'conversely'),
        ('类似', 'similarly'),
        ('不同', 'differently'),
        ('特别', 'especially'),
        ('尤其', 'particularly'),
        ('主要', 'mainly'),
        ('完全', 'completely'),
        ('部分', 'partially'),
        ('直接', 'directly'),
        ('间接', 'indirectly'),
        ('显式', 'explicitly'),
        ('隐式', 'implicitly'),
        ('足够', 'sufficiently'),
        ('不足', 'insufficiently'),
        ('极大', 'greatly'),
        ('极小', 'minimally'),
        ('显著', 'significantly'),
        ('略微', 'slightly'),
        ('明确', 'clearly'),
        ('隐含', 'implicitly'),
        ('潜在', 'potentially'),
        ('实际', 'actually'),
        ('理论', 'theoretically'),
        ('经验', 'empirically'),
        ('数值', 'numerically'),
        ('解析', 'analytically'),
        ('定性', 'qualitatively'),
        ('定量', 'quantitatively'),
        ('局部', 'locally'),
        ('全局', 'globally'),
        ('内部', 'internally'),
        ('外部', 'externally'),
        
        # Remaining common terms
        ('输入', 'input'),
        ('输出', 'output'),
        ('结果', 'result'),
        ('方法', 'method'),
        ('算法', 'algorithm'),
        ('策略', 'strategy'),
        ('机制', 'mechanism'),
        ('结构', 'structure'),
        ('框架', 'framework'),
        ('系统', 'system'),
        ('过程', 'process'),
        ('现象', 'phenomenon'),
        ('性质', 'property'),
        ('特征', 'characteristic'),
        ('关系', 'relationship'),
        ('关联', 'correlation'),
        ('影响', 'influence'),
        ('效果', 'effect'),
        ('性能', 'performance'),
        ('精度', 'accuracy'),
        ('效率', 'efficiency'),
        ('复杂度', 'complexity'),
        ('规模', 'scale'),
        ('范围', 'range'),
        ('边界', 'boundary'),
        ('极限', 'limit'),
        ('约束', 'constraint'),
        ('限制', 'restriction'),
        ('假设', 'assumption'),
        ('前提', 'premise'),
        ('结论', 'conclusion'),
        ('观察', 'observation'),
        ('发现', 'finding'),
        ('贡献', 'contribution'),
        ('创新', 'innovation'),
        ('改进', 'improvement'),
        ('扩展', 'extension'),
        ('推广', 'generalization'),
        ('应用', 'application'),
        ('实现', 'implementation'),
        ('设计', 'design'),
        ('构建', 'construction'),
        ('选择', 'selection'),
        ('决策', 'decision'),
        ('检测', 'detection'),
        ('识别', 'identification'),
        ('分类', 'classification'),
        ('回归', 'regression'),
        ('聚类', 'clustering'),
        ('降维', 'dimensionality reduction'),
        ('编码', 'encoding'),
        ('解码', 'decoding'),
        ('表示', 'representation'),
        ('嵌入', 'embedding'),
        ('映射', 'mapping'),
        ('投影', 'projection'),
        ('变换', 'transformation'),
        ('分解', 'decomposition'),
        ('组合', 'combination'),
        ('聚合', 'aggregation'),
        ('融合', 'fusion'),
        ('对齐', 'alignment'),
        ('校准', 'calibration'),
        ('正则化', 'regularization'),
        ('归一化', 'normalization'),
        ('标准化', 'standardization'),
        ('初始化', 'initialization'),
        ('更新', 'update'),
        ('迭代', 'iteration'),
        ('递归', 'recursion'),
        ('演化', 'evolution'),
        ('自适应', 'adaptive'),
        ('动态', 'dynamic'),
        ('静态', 'static'),
        ('离线', 'offline'),
        ('在线', 'online'),
        ('批量', 'batch'),
        ('实时', 'real-time'),
        ('分布式', 'distributed'),
        ('集中式', 'centralized'),
        ('联邦', 'federated'),
        ('协同', 'collaborative'),
        ('对抗', 'adversarial'),
        ('博弈', 'game'),
        ('均衡', 'equilibrium'),
        ('帕累托', 'Pareto'),
        ('纳什', 'Nash'),
        ('量子', 'quantum'),
        ('经典', 'classical'),
        ('热力学', 'thermodynamic'),
        ('熵增', 'entropy increase'),
        ('熵减', 'entropy decrease'),
        ('相变', 'phase transition'),
        ('临界', 'critical'),
        ('涌现', 'emergence'),
        ('自组织', 'self-organization'),
        ('自指', 'self-reference'),
        ('元', 'meta'),
        
        # File-specific: 05_expert_governance_protocol.tex
        ('SCX/EGP 蒸馏前专家规范化协议', 'SCX/EGP Pre-Distillation Expert Standardization Protocol'),
        ('Protocol 整体结构', 'Protocol Overall Structure'),
        ('是从原始专家系统到蒸馏授权决策的', 'is a linear decision pipeline from raw expert system to distillation authorization decision'),
        ('输入', 'Input'),
        ('输出', 'Output'),
        ('authorized', 'authorized'),
        ('conditional', 'conditional'),
        ('denied', 'denied'),
        ('所有检查通过，可直接蒸馏', 'all checks passed, direct distillation allowed'),
        ('部分条件不满足但可补救（如补锚点测试）', 'partial conditions unmet but remediable (e.g., additional anchor tests)'),
        ('不可蒸馏，需专家重新训练或更换专家', 'cannot distill, requires expert retraining or replacement'),
        ('Gauge Check (量规检查)', 'Gauge Check'),
        ('不同 MLIP 的总能量预测存在系统性能量偏移（gauge freedom）。Step 1 检测并消除这些偏移，使所有专家的能量预测在统一的参考标度上可比。', 'Different MLIP total energy predictions exhibit systematic energy offsets (gauge freedom). Step 1 detects and eliminates these offsets, making all expert energy predictions comparable on a unified reference scale.'),
        ('选择能量已知的简单状态，如体相晶格', 'simple states with known energies, e.g., bulk lattice'),
        ('参考能量', 'reference energy'),
        ('容忍度', 'tolerance'),
        ('物理部分', 'physical component'),
        ('gauge offset', 'gauge offset'),
        ('残差', 'residual'),
        ('依赖于专家的系统偏差（gauge shift）', 'expert-dependent systematic bias (gauge shift)'),
        ('总能量基准', 'total energy baseline'),
        ('Gauge Check 算法', 'Gauge Check Algorithm'),
        ('Gauge Fixing（失败时执行）', 'Gauge Fixing (executed on failure)'),
        ('低方差意味着偏移在各参考状态间一致，是纯 gauge 偏移', 'low variance means the offset is consistent across reference states, i.e., a pure gauge offset'),
        ('即将专家', 'i.e., the expert'),
        ('的能量预测减去其对参考状态的平均系统偏差', 'energy prediction minus its average systematic bias across reference states'),
        ('校准后重新运行 Check', 're-run Check after calibration'),
        ('与已有工作的关系', 'Relationship to Existing Work'),
        ('文献中', 'In the literature'),
        ('指出不同 DFT 泛函间存在类似问题，但未处理跨 MLIP 架构的 gauge 对齐', 'notes similar issues between different DFT functionals, but does not address gauge alignment across MLIP architectures'),
        ('本步骤是 SCX/EGP 的原创贡献——在蒸馏前强制多专家能量标度统一', 'This step is an original contribution of SCX/EGP — enforcing multi-expert energy scale unification before distillation'),
        ('Domain Certificate (域认证)', 'Domain Certificate (Domain Certification)'),
        ('对目标状态', 'For the target state'),
        ('评估每个专家在该状态上的可靠性。不可靠专家不应参与蒸馏。', 'evaluate each expert\'s reliability on that state. Unreliable experts should not participate in distillation.'),
        ('低可靠性阈值', 'low reliability threshold'),
        ('高可靠性阈值', 'high reliability threshold'),
        ('损失阈值', 'loss threshold'),
        ('最小样本数', 'minimum sample count'),
        ('可靠性估计', 'Reliability Estimation'),
        ('小样本时使用 James-Stein 收缩估计', 'For small samples, use James-Stein shrinkage estimation'),
        ('全局平均可靠性', 'global average reliability'),
        ('判定逻辑', 'Adjudication Logic'),
        ('专家在目标状态上高度可靠，可参与蒸馏', 'expert is highly reliable on target state, may participate in distillation'),
        ('可靠性不足以独立贡献，但可参与多专家集成', 'reliability insufficient for independent contribution, but may participate in multi-expert ensemble'),
        ('专家在该状态不可信，排除出蒸馏', 'expert is untrustworthy on this state, excluded from distillation'),
        ('与 SCX 代码的对应', 'Correspondence with SCX Code'),
        ('直接调用', 'directly calls'),
        ('Conflict Resolution (冲突解决)', 'Conflict Resolution (Conflict Resolution)'),
        ('检查通过 Step 2 认证的专家之间是否存在显著预测冲突。冲突区域需要仲裁。', 'check whether significant prediction conflicts exist among experts certified by Step 2. Conflict regions require arbitration.'),
        ('已认证专家子集', 'subset of certified experts'),
        ('状态内未标注构型', 'unlabeled configurations within the state'),
        ('冲突阈值', 'conflict threshold'),
        ('冲突度量', 'Conflict Metric'),
        ('冲突判定', 'Conflict Determination'),
        ('无冲突需要解决', 'no conflict to resolve'),
        ('冲突类型诊断', 'Conflict Type Diagnosis'),
        ('Step 1 未完全消除的 gauge 残差', 'gauge residuals not fully eliminated by Step 1'),
        ('专家对局部结构类型的选择性失效', 'selective failure of experts on local structure types'),
        ('至少一个专家在', 'at least one expert in'),
        ('中完全不可靠', 'is completely unreliable'),
        ('冲突经仲裁后可解决（见下方）', 'conflict is resolvable after arbitration (see below)'),
        ('需要 DFT anchor 仲裁', 'requires DFT anchor arbitration'),
        ('仲裁方法', 'Arbitration Method'),
        ('返回 Step 1 重新校准', 'return to Step 1 for recalibration'),
        ('将冲突子区域', 'mark the conflict sub-region'),
        ('标记为需要 DFT anchor（Step 4）并排除它', 'as needing DFT anchor (Step 4) and exclude it'),
        ('退化为仅使用 Step 2 认证的', 'fall back to using only Step 2 certified'),
        ('专家做简单平均，不加权', 'experts with simple averaging, unweighted'),
        ('使用', 'uses'),
        ('Anchor Verification (锚点验证)', 'Anchor Verification (Anchor Verification)'),
        ('用 DFT 计算锚点（anchor frames）作为 ground truth 仲裁', 'use DFT-computed anchor frames as ground truth for arbitration'),
        ('冲突状态列表', 'list of conflicting states'),
        ('锚点预算', 'anchor budget'),
        ('允许的总 DFT 计算数', 'total allowed DFT calculations'),
        ('锚点精度阈值', 'anchor precision threshold'),
        ('锚点选择策略', 'anchor selection strategy'),
        ('锚点选择', 'Anchor Selection'),
        ('分配锚点数', 'allocate anchor count'),
        ('状态概率', 'state probability'),
        ('冲突度的归一化度量', 'normalized measure of conflict degree'),
        ('最大分歧采样', 'Maximum disagreement sampling'),
        ('最远点采样', 'Farthest point sampling'),
        ('选择专家预测方差最大的构型，这些构型最能区分不同专家的表现。', 'select configurations with maximum expert prediction variance; these best distinguish different expert behaviors.'),
        ('锚点验证', 'Anchor Verification'),
        ('计算 DFT 标签', 'compute DFT label'),
        ('验证其在锚点上的误差', 'verify its error on anchors'),
        ('全局锚点验证', 'Global Anchor Verification'),
        ('识别出表现最差的专家', 'identify the worst-performing expert'),
        ('将其排除出蒸馏', 'exclude it from distillation'),
        ('校正后的仲裁规则', 'Corrected Arbitration Rule'),
        ('在锚点约束下，对专家权重进行校准', 'under anchor constraints, calibrate expert weights'),
        ('这确保了锚点附近的预测以 DFT 为基准加权。', 'this ensures predictions near anchors are weighted based on DFT ground truth.'),
        ('Distillation Authorization (蒸馏授权)', 'Distillation Authorization (Distillation Authorization)'),
        ('聚合前 4 步输出，做出最终的蒸馏授权决策。', 'aggregate outputs from the previous 4 steps to make the final distillation authorization decision.'),
        ('授权判定', 'Authorization Decision'),
        ('首先定义 Step 2 的聚合域认证', 'first define the aggregated domain certification from Step 2'),
        ('即至少有一个专家在', 'i.e., at least one expert in'),
        ('上被认证为可靠或用条件参与', 'is certified as reliable or conditionally participating'),
        ('所有专家 gauge 已对齐', 'all experts gauge-aligned'),
        ('目标状态有可靠专家', 'target state has reliable experts'),
        ('冲突已解决或用锚点可解决', 'conflict resolved or anchor-resolvable'),
        ('锚点验证通过', 'anchor verification passed'),
        ('特殊情况', 'Special Cases'),
        ('若所有专家', 'If all experts'),
        ('必须先执行 gauge fixing', 'must first execute gauge fixing'),
        ('但锚点预算不足：返回 conditional with 锚点建议', 'but anchor budget insufficient: return conditional with anchor recommendations'),
        ('但排除失败专家后重新通过所有检查：返回 authorized with 排除列表', 'but re-passes all checks after excluding failed experts: return authorized with exclusion list'),
        ('蒸馏授权证书', 'Distillation Authorization Certificate'),
        ('Protocol 的标准输出', 'standard output of the Protocol'),
        ('参与蒸馏的专家 ID', 'expert IDs participating in distillation'),
        ('被排除的专家及原因', 'excluded experts and reasons'),
        ('使用的锚点帧数', 'number of anchor frames used'),
        ('应用的 gauge 校正量', 'applied gauge correction amounts'),
        ('保证的界', 'guaranteed bound'),
        ('置信度', 'confidence'),
        ('阈值选择指引', 'Threshold Selection Guide'),
        ('阈值汇总', 'Threshold Summary'),
        ('推荐值', 'Recommended Value'),
        ('选择依据', 'Selection Rationale'),
        ('物理上有意义的精度边界', 'physically meaningful precision boundary'),
        ('本身的数值精度约', 'own numerical precision approx.'),
        ('低于此值的专家在目标状态上误差概率 >30\\%，不适合独立参与蒸馏', 'experts below this value have error probability >30% on target state, unsuitable for independent distillation participation'),
        ('高于此值的专家可独立贡献预测', 'experts above this value can contribute predictions independently'),
        ('两倍于典型 MLIP 的 MAE，冲突超过此值意味着专家间存在实质性分歧', 'twice the typical MLIP MAE; conflict exceeding this means substantive disagreement between experts'),
        ('锚点验证时允许的最大专家-DFT 偏差，此值应略低于', 'maximum allowed expert-DFT deviation during anchor verification; should be slightly below'),
        ('Gauge 方差阈值', 'Gauge variance threshold'),
        ('参考状态间 gauge 偏移的方差上限，过大的方差意味着非一致偏移（非纯 gauge）', 'upper bound on gauge offset variance across reference states; excessive variance indicates non-uniform offset (not pure gauge)'),
        ('状态内样本数低于此值需使用贝叶斯收缩估计', 'state sample count below this value requires Bayesian shrinkage estimation'),
        ('阈值选择的物理依据', 'Physical Basis for Threshold Selection'),
        ('在 MLIP 场景中，能量和力的精度阈值应基于以下考量', 'In MLIP scenarios, energy and force precision thresholds should be based on the following considerations'),
        ('DFT 数值精度', 'DFT Numerical Precision'),
        ('典型 DFT 计算的数值收敛精度约为', 'typical DFT calculation numerical convergence precision is approximately'),
        ('能量', 'energy'),
        ('力', 'force'),
        ('应设于此值以上以避免检测到虚假的专家错误', 'should be set above this value to avoid detecting spurious expert errors'),
        ('MLIP 典型精度范围', 'MLIP Typical Precision Range'),
        ('当前 MLIP 对能量的 MAE 通常在', 'current MLIP energy MAE typically ranges'),
        ('范围。', 'range.'),
        ('设为此范围的中值可合理区分正常分歧和异常冲突', 'setting to the median of this range reasonably distinguishes normal disagreement from anomalous conflict'),
        ('力与能量的权衡', 'Force-Energy Tradeoff'),
        ('力的阈值通常应比能量的阈值宽松，因为力的数值噪声通常更大。建议', 'force thresholds should generally be looser than energy thresholds, since force numerical noise is typically larger. Recommended:'),
        ('自适应阈值', 'Adaptive Thresholds'),
        ('在实际操作中，可以基于验证集上的专家性能分布自适应设定阈值', 'In practice, thresholds can be set adaptively based on expert performance distribution on the validation set'),
        ('其中 MAD 为中位数绝对偏差。', 'where MAD is median absolute deviation.'),
        ('失败回退策略', 'Failure Fallback Strategy'),
        ('失败模式', 'Failure Mode'),
        ('回退策略', 'Fallback Strategy'),
        ('执行 gauge fixing', 'execute gauge fixing'),
        ('重检', 're-check'),
        ('参考状态', 'reference state'),
        ('无数据', 'has no data'),
        ('从任意状态采样', 'sample from any state'),
        ('个构型，用 DFT 计算参考能量', 'configurations, compute reference energies via DFT'),
        ('对所有', 'for all'),
        ('扩大状态范围（合并相邻状态以增加样本），或降低', 'expand state range (merge adjacent states to increase samples), or lower'),
        ('若仍失败：需为新状态补充 DFT 标签', 'if still fails: need to supplement DFT labels for new states'),
        ('全新状态', 'completely new state'),
        ('使用 Bayesian shrinkage 到全局均值；标记为', 'use Bayesian shrinkage to global mean; mark as'),
        ('不可解决', 'unresolvable'),
        ('排除最小可靠专家后重检。若仍冲突：标记为', 're-check after excluding least reliable expert. If still conflicting: mark as'),
        ('无锚点预算', 'no anchor budget'),
        ('退化为仅使用 Step 2 认证的', 'fall back to only Step 2 certified'),
        ('专家做简单平均，不加权', 'experts with simple averaging, unweighted'),
        ('排除锚点验证失败的最差专家，回退到 Step 3 重检（排除后可能解决冲突）', 'exclude worst expert failing anchor verification, fall back to Step 3 re-check (conflict may resolve after exclusion)'),
        ('返回 conditional with 详细的失败原因和补救行动清单', 'return conditional with detailed failure reasons and remedial action checklist'),
        ('所有专家均被排除', 'all experts excluded'),
        ('在目标状态', 'on target state'),
        ('上无法进行多专家蒸馏；建议使用单专家微调或构造新专家', 'cannot perform multi-expert distillation; recommend single-expert fine-tuning or constructing new experts'),
        ('Certification Theorem', 'Certification Theorem'),
        ('问题设定', 'Problem Setup'),
        ('设蒸馏后得到学生模型', 'Let the distilled student model be'),
        ('蒸馏过程从通过 Governance Protocol 认证的专家子集中学习', 'the distillation process learns from the expert subset certified by the Governance Protocol'),
        ('定义学生', 'Define student'),
        ('的风险', 'risk'),
        ('最佳专家在状态', 'Best expert on state'),
        ('上的风险', 'risk'),
        ('主定理', 'Main Theorem'),
        ('定理 5.1 (Governance Certification Bound)', 'Theorem 5.1 (Governance Certification Bound)'),
        ('对状态', 'For state'),
        ('返回', 'returns'),
        ('且锚点帧数为', 'and anchor frame count is'),
        ('则对任意', 'then for any'),
        ('以概率至少', 'with probability at least'),
        ('锚点抽样误差', 'Anchor sampling error'),
        ('锚点验证保证', 'Anchor verification guarantee'),
        ('蒸馏误差', 'Distillation error'),
        ('是与专家复杂度相关的常数', 'is a constant related to expert complexity'),
        ('是蒸馏收敛率', 'is the distillation convergence rate'),
        ('证明策略', 'Proof Strategy'),
        ('分解为三项可分别界定的误差之和', 'decomposed into sum of three separately boundable error terms'),
        ('分解', 'Decomposition'),
        ('选择与锚点最近的专家预测作为桥接量。对任意', 'Select the expert prediction closest to the anchor as bridging quantity. For any'),
        ('是', 'is'),
        ('在锚点集中的最近邻（在输入空间距离', 'nearest neighbor in the anchor set (under input space distance'),
        ('下）', ')'),
        ('误差分解', 'Error Decomposition'),
        ('然而，这一分解涉及', 'However, this decomposition involves'),
        ('的 Lipschitz 性质且不易处理。', 'Lipschitz properties and is not easily tractable.'),
        ('更简洁的证明策略', 'A Cleaner Proof Strategy'),
        ('引理 5.1 (Anchor Approximation)', 'Lemma 5.1 (Anchor Approximation)'),
        ('则对所有通过认证的专家', 'then for all certified experts'),
        ('在状态', 'on state'),
        ('上以高概率有', 'with high probability'),
        ('是专家', 'is expert'),
        ('的 Lipschitz 常数', 'Lipschitz constant'),
        ('是零均值随机噪声', 'is zero-mean random noise'),
        ('证明（引理 5.1）', 'Proof (Lemma 5.1)'),
        ('为', 'be'),
        ('中最近邻点。由三角不等式：', 'nearest neighbor point. By triangle inequality:'),
        ('其中第二个不等式使用了锚点验证保证', 'where the second inequality uses the anchor verification guarantee'),
        ('由', 'by'),
        ('保证）', 'guaranteed)'),
        ('主定理证明', 'Proof of Main Theorem'),
        ('由引理 5.1，对最佳专家', 'By Lemma 5.1, for the best expert'),
        ('和学生', 'and student'),
        ('分别有', 'respectively'),
        ('定义', 'definition'),
        ('由引理，假设 MSE 损失', 'by lemma, assuming MSE loss'),
        ('是全局 Lipschitz 常数（假设所有函数 Lipschitz 连续）', 'is the global Lipschitz constant (assuming all functions are Lipschitz continuous)'),
        ('由', 'By'),
        ('学生', 'student'),
        ('是从', 'is distilled from'),
        ('蒸馏得到的。蒸馏保证（假设蒸馏算法在锚点处最小化', 'The distillation guarantee (assuming the distillation algorithm minimizes'),
        ('给出', 'gives'),
        ('锚点验证保证', 'Anchor verification guarantee'),
        ('覆盖误差', 'Coverage error'),
        ('现在界定期望覆盖误差。锚点集', 'Now bound the expected coverage error. The anchor set'),
        ('的', 'of'),
        ('个点独立采自', 'points independently sampled from'),
        ('在状态', 'in state'),
        ('内条件化）', 'conditioned)'),
        ('的期望值由经典的最远点距离 bound 控制。对', 'expectation is controlled by classical farthest-point distance bound. For'),
        ('维空间中的概率度量', 'dimensional space with a probability measure'),
        ('但这指数较慢。更好的方法是利用样本的集中性质。对于有界度量空间，由 VC 维论证可得更紧的界', 'But this rate is slow. A better approach uses sample concentration. For bounded metric spaces, tighter bounds come from VC-dimension arguments'),
        ('以概率至少', 'with probability at least'),
        ('但更直接的界来自 Hoeffding 不等式——将', 'But a more direct bound comes from Hoeffding\'s inequality — treating'),
        ('视为', 'as'),
        ('上的有界随机变量。其期望的蒙特卡洛估计误差为', 'a bounded random variable on [0, D_max^2]. The Monte Carlo estimation error of its expectation is'),
        ('设右边等于', 'Set RHS equal to'),
        ('解得', 'solve for'),
        ('因此，以概率至少', 'Therefore, with probability at least'),
        ('令', 'Let'),
        ('并记', 'and denote'),
        ('对', 'for'),
        ('对低维，收敛更快）', 'for low dimensions, convergence is faster'),
        ('可得', 'we obtain'),
        ('当', 'When'),
        ('时，平方根项占主导；当', 'the square root term dominates; when'),
        ('时，多项式项占主导。取最坏情况', 'the polynomial term dominates. Taking worst case'),
        ('给出', 'gives'),
        ('bound 更紧', 'bound is tighter'),
        ('为与定理陈述一致，记', 'For consistency with the theorem statement, denote'),
        ('推论 5.1（锚点预算规划）', 'Corollary 5.1 (Anchor Budget Planning)'),
        ('要达到', 'To achieve'),
        ('所需锚点帧数满足', 'required anchor frame count satisfies'),
        ('推论 5.2（无标签 bound）', 'Corollary 5.2 (No-Label Bound)'),
        ('在没有锚点（', 'Without anchors ('),
        ('）的情况下', '),'),
        ('Protocol 在无 ground truth 时不能提供认证保证。这与直觉一致：没有 DFT 参考就无法验证专家质量。', 'the Protocol cannot provide certification guarantees without ground truth. This matches intuition: without DFT reference, expert quality cannot be verified.'),
        ('Bound 的规模估计', 'Bound Scale Estimation'),
        ('在典型 MLIP 情境下（能量 MSE，', 'In typical MLIP scenarios (energy MSE,'),
        ('均值，meV/atom', 'mean, meV/atom'),
        ('未定义（无法估计）', 'undefined (cannot estimate)'),
        ('极差，仅来自平方根项', 'very poor, from square root term only'),
        ('要达到有实际意义的 bound（', 'To achieve a practically meaningful bound ('),
        ('），需要约', '), approximately'),
        ('锚点帧。这在 AlN v3 的规模（425 train + 103 test）下是可行的——将从 train 集中分配锚点。', 'anchor frames are needed. This is feasible at AlN v3 scale (425 train + 103 test) — anchors will be allocated from the train set.'),
        ('AlN v3 回顾性验证方案', 'AlN v3 Retrospective Validation Protocol'),
        ('数据描述', 'Data Description'),
        ('AlN v3 数据集：', 'AlN v3 Dataset:'),
        ('Train', 'Train'),
        ('个构型，含 DFT 能量/力标签', 'configurations with DFT energy/force labels'),
        ('Test', 'Test'),
        ('专家', 'Experts'),
        ('个异构 MLIP（MACE, NEP, SevenNet 等，待实际确定）', 'heterogeneous MLIPs (MACE, NEP, SevenNet, etc., to be determined)'),
        ('状态', 'States'),
        ('根据化学环境划分（如 sp², sp³, 表面, 缺陷, 高应变）', 'partitioned by chemical environment (e.g., sp², sp³, surface, defect, high strain)'),
        ('实验设计', 'Experimental Design'),
        ('数据分组', 'Data Grouping'),
        ('将 528 个构型按以下比例拆分：', 'Split the 528 configurations according to the following proportions:'),
        ('Step 1 Gauge Check 参考状态', 'Step 1 Gauge Check reference state'),
        ('Step 2 Domain Certificate 可靠性估计', 'Step 2 Domain Certificate reliability estimation'),
        ('蒸馏训练集（假设 authorized）', 'distillation training set (assuming authorized)'),
        ('Step 4 Anchor Verification', 'Step 4 Anchor Verification'),
        ('最终评估', 'final evaluation'),
        ('实际执行时可以使用', 'In practice, one may use'),
        ('折交叉验证（', '-fold cross-validation ('),
        ('）以充分利用有限数据。', ') to fully utilize limited data.'),
        ('状态划分', 'State Division'),
        ('中的构型进行状态聚类。对 AlN 系统，建议的状态划分维度：', 'configurations for state clustering. For AlN systems, recommended state partition dimensions:'),
        ('配位数', 'Coordination number'),
        ('缺陷/线状', 'defect/linear'),
        ('原子间距离', 'Interatomic distance'),
        ('平衡键长 vs. 拉伸/压缩键', 'equilibrium bond length vs. stretched/compressed bonds'),
        ('中心原子类型', 'Central atom type'),
        ('二元体系的基本区分', 'basic distinction for binary systems'),
        ('对称性', 'Symmetry'),
        ('类纤锌矿、类岩盐矿、非晶/界面', 'wurtzite-like, rocksalt-like, amorphous/interface'),
        ('产生', 'producing'),
        ('个状态。', 'states.'),
        ('Protocol 运行', 'Protocol Execution'),
        ('对每个状态', 'For each state'),
        ('上计算每个专家的', 'compute each expert\'s'),
        ('上估计', 'estimate on'),
        ('标注每个', 'annotate each'),
        ('对每个状态', 'for each state'),
        ('用认证专家的预测计算冲突矩阵', 'compute conflict matrix using certified expert predictions'),
        ('在冲突状态上从', 'on conflicting states from'),
        ('选点验证', 'select points for verification'),
        ('汇总得到', 'aggregate to obtain'),
        ('蒸馏与评估', 'Distillation and Evaluation'),
        ('按 Protocol 划分为 authorized states 和 unauthorized states', 'partition by Protocol into authorized states and unauthorized states'),
        ('仅在 authorized states 上蒸馏学生', 'distill student only on authorized states'),
        ('上评估', 'evaluate on'),
        ('度量', 'Metric'),
        ('公式', 'Formula'),
        ('含义', 'Meaning'),
        ('学生 vs. 最佳专家', 'student vs. best expert'),
        ('是否满足 bound', 'whether bound is satisfied'),
        ('整体准确率', 'overall accuracy'),
        ('验证假设与判定标准', 'Validation Hypotheses and Criteria'),
        ('假设', 'Hypothesis'),
        ('判定标准', 'Judgment Criterion'),
        ('期望结果', 'Expected Result'),
        ('authorized states 上学生误差', 'student error on authorized states'),
        ('最佳专家误差 + bound', 'best expert error + bound'),
        ('对', 'for'),
        ('在 authorized states 上满足', 'satisfied on authorized states'),
        ('unauthorized states 上学生表现更差', 'student performs worse on unauthorized states'),
        ('在不满足条件的 states 上显著更差', 'significantly worse on non-compliant states'),
        ('的授权决策与', 'authorization decision and'),
        ('正相关', 'positively correlated'),
        ('显著', 'significant'),
        ('授权状态 vs. 学生相对表现的排序一致', 'authorization status vs. student relative performance ordering is consistent'),
        ('是保守上界', 'is a conservative upper bound'),
        ('实际', 'actual'),
        ('以', 'with'),
        ('频率成立', 'frequency holds'),
        ('是保守的但不 vacuous', 'is conservative but not vacuous'),
        ('消融实验', 'Ablation Experiments'),
        ('为验证 Protocol 中每个步骤的必要性：', 'To verify the necessity of each step in the Protocol:'),
        ('消融', 'Ablation'),
        ('操作', 'Operation'),
        ('预期效果', 'Expected Effect'),
        ('去除 Step 1', 'Remove Step 1'),
        ('跳过 gauge check', 'skip gauge check'),
        ('能量偏移导致学生误差增大，尤其对混合架构蒸馏', 'energy offsets increase student error, especially for mixed-architecture distillation'),
        ('去除 Step 2', 'Remove Step 2'),
        ('包含所有专家而不做域认证', 'include all experts without domain certification'),
        ('不可靠专家污染蒸馏结果', 'unreliable experts contaminate distillation results'),
        ('去除 Step 3', 'Remove Step 3'),
        ('不做冲突检测', 'skip conflict detection'),
        ('冲突专家的平均预测产生无物理意义的中间值', 'averaging conflicting expert predictions produces physically meaningless intermediate values'),
        ('去除 Step 4', 'Remove Step 4'),
        ('不验证锚点', 'skip anchor verification'),
        ('蒸馏失去 ground truth 约束，误差无法保证', 'distillation loses ground truth constraint, error cannot be guaranteed'),
        ('结果报告模板', 'Result Report Template'),
        ('Protocol 输出表格', 'Protocol Output Table'),
        ('消融结果', 'Ablation Results'),
        ('Authorized states 合格率', 'Authorized states pass rate'),
        ('Unauthorized states 检测率', 'Unauthorized states detection rate'),
        ('与 SCX 代码的实现映射', 'Implementation Mapping to SCX Code'),
        ('Protocol 步骤', 'Protocol Step'),
        ('SCX 模块', 'SCX Module'),
        ('核心类/方法', 'Core Class/Method'),
        ('新建或扩展', 'new or extend'),
        ('新建', 'new'),
        ('聚合层，整合 Step 1-4 输出', 'aggregation layer, integrating Step 1-4 outputs'),
        ('阈值管理', 'Threshold Management'),
        ('所有', 'all'),
        ('的集中配置', 'centralized configuration'),
        ('蒸馏授权证书', 'Distillation Authorization Certificate'),
        ('输出结构', 'output structure'),
        ('参考文献', 'References'),
        ('SCX Framework Definitions', 'SCX Framework Definitions'),
        ('SCX 核心定义', 'SCX Core Definitions'),
        ('Expert Reliability Estimation', 'Expert Reliability Estimation'),
        ('Expert Conflict Detection', 'Expert Conflict Detection'),
        ('Expert Routing', 'Expert Routing'),
        ('Gauge Dependence of Total Energies', 'Gauge Dependence of Total Energies'),
        ('Constructing MLIP with Minimum DFT Data', 'Constructing MLIP with Minimum DFT Data'),
        ('Teacher-Student Training for MLIPs', 'Teacher-Student Training for MLIPs'),
        ('Ensemble Knowledge Distillation for MLIP', 'Ensemble Knowledge Distillation for MLIP'),
        ('DeepMD MoE: Scaling MLIP with Mixtures of Experts', 'DeepMD MoE: Scaling MLIP with Mixtures of Experts'),
    ]
    
    for old, new in common:
        content = content.replace(old, new)
    
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return len(original) - len(content)
    return 0

if __name__ == '__main__':
    files = [
        'theory/propositions/05_expert_governance_protocol.tex',
        'theory/SCX_Undiscovered_Theorems.tex',
        'theory/self_evolution/MATHEMATICAL_GENEALOGY.tex',
        'theory/self_evolution/multi_head_spring_and_positional_encoding_analysis.tex',
        'theory/self_evolution/ppe_rigorous_derivation.tex',
        'theory/self_evolution/situs_final_verification.tex',
        'theory/self_evolution/situs_physical_validation.tex',
    ]
    total = 0
    for f in files:
        if os.path.exists(f):
            changed = translate_file(f)
            print(f'{f}: {changed} bytes changed')
            total += changed
        else:
            print(f'{f}: NOT FOUND')
    print(f'Total: {total} bytes changed across all files')
