#!/usr/bin/env python3
"""Second pass: aggressive Chinese→English translation for theory/ files."""
import re, os

def fix_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original = content
    
    # More specific long-phrase replacements
    patches = [
        # === 05_expert_governance_protocol.tex ===
        ('SCX/EGP 蒸馏前expert规范化协议', 'SCX/EGP Pre-Distillation Expert Standardization Protocol'),
        ('版本：v1.0', 'Version: v1.0'),
        ('finallyupdate：2026-06-26', 'Last updated: 2026-06-26'),
        ('五步 Governance\n  Protocol', 'Five-Step Governance\n  Protocol'),
        ('thresholdselection指引', 'Threshold Selection Guide'),
        ('失败回退strategy', 'Failure Fallback Strategy'),
        ('回顾性validation方案', 'Retrospective Validation Protocol'),
        ('与 SCX code的实现映射', 'Implementation Mapping to SCX Code'),
        
        # === SCX_Undiscovered_Theorems.tex ===
        ('SCXframework：未被findingof新theory方向', 'SCX Framework: Undiscovered New Theoretical Directions'),
        ('theory架构师深度推演', 'Deep Deduction by Theory Architect'),
        ('2026年6月29日', 'June 29, 2026'),
        ('任务：在已有T1-T7基础Theorem +\nCD/FA/AR/TS/HC五方向草案之上', 'Task: Based on existing T1-T7 fundamental theorems +\nthe five draft directions CD/FA/AR/TS/HC'),
        ('以下五个方向按最具finding潜力排序', 'the following five directions are ordered by discovery potential'),
        ('量子SCX定理：量子传感下的远程审计与Theorem 3的量子修正', 'Quantum SCX Theorem: Remote Audit under Quantum Sensing and Quantum Correction of Theorem 3'),
        ('审计熵定理：SCX的第二定律与不可逆审计箭头', 'Audit Entropy Theorem: SCX Second Law and Irreversible Audit Arrow'),
        ('审计复杂度定理：检测noise的最小expert数下界', 'Audit Complexity Theorem: Lower Bound on Minimum Number of Experts for Noise Detection'),
        ('递归审计定理：审计输出的自我指涉与无限回归的收敛', 'Recursive Audit Theorem: Self-Reference of Audit Output and Convergence of Infinite Regression'),
        ('对齐审计定理：AI对齐问题的SCX归约', 'Alignment Audit Theorem: SCX Reduction of the AI Alignment Problem'),
        ('总结：新定理群的逻辑结构', 'Summary: Logical Structure of the New Theorem Group'),
        ('成熟度总表', 'Maturity Summary Table'),
        ('五定理的交叉依赖', 'Cross-Dependency of Five Theorems'),
        ('与已有五定理的分工', 'Division of Labor with Existing Five Theorems'),
        ('草案版本 v0.1', 'Draft version v0.1'),
        ('SCX理论架构师', 'SCX Theory Architect'),
        ('待合作者审阅', 'Pending collaborator review'),
        ('五定理均处于概念阶段', 'All five theorems are at the conceptual stage'),
        ('审计热寂对应Theorem 3的不可约无知', 'Audit heat death corresponds to Theorem 3 irreducible ignorance'),
        
        # === MATHEMATICAL_GENEALOGY.tex ===
        ('参考set 重放', 'reference set replay'),
        ('洽耦程', 'consistent coupling condition'),
        ('贝叶斯验all value Update', 'Bayesian posterior update'),
        ('has bound 鞅', 'bounded martingale'),
        ('重must limitation', 'Important limitation'),
        ('支撑内', 'support'),
        ('monotonic增长', 'monotonically growing'),
        ('改', 'improvement'),
        ('KL 收缩', 'KL contraction'),
        
        # === multi_head_spring_and_positional_encoding_analysis.tex ===
        ('谱间隙', 'spectral gap'),
        ('Note形formula', 'Attention formula'),
        ('单头', 'single-head'),
        ('Detection边际', 'detection margin'),
        ('Proof技术', 'Proof technique'),
        ("Distribution's混", "mixture of distributions"),
        ('假阳property', 'false positive'),
        ('假阴property', 'false negative'),
        ('选取', 'Choose'),
        ('项平衡', 'term balance'),
        
        # === ppe_rigorous_derivation.tex ===
        ('严密derivation', 'Rigorous Derivation'),
        ('修正 CC audit报告in', 'Correction of CC audit report'),
        ("Symbolnon-one and  sign error", "symbol inconsistency and sign error"),
        ("Symbol约", "Symbol Conventions"),
        ("as maintain one 致", "to maintain consistency"),
        ("must Symbol", "core symbols"),
        ("re-精determine 义", "re-precise the definitions"),
        ("expert 投票", "Expert Voting"),
        ("target 签", "target label"),
        ("give target 签", "agrees with target label"),
        ("disagree withgive target 签", "disagrees with target label"),
        ("Detection边际", "Detection margin"),
        ("one 致", "consistent"),
        ("CC 报告", "CC report"),
        
        # === situs_final_verification.tex ===
        ("one 致, number already 修正", "consistent, values already corrected"),
        ("one ization because factor", "normalization factor"),
        ("包含归one ization because factor", "both contain the normalization factor"),
        ("框内FormulaYesNo L dependence", "Does boxed formula still have L dependence"),
        ("code 身's框内Formulain", "the encoding itself in the boxed formula"),
        ("指'sYes", "refers to"),
        ("编号", "numbering"),
        ("target", "title"),
        ("derivation链Complete", "derivation chain complete"),
        ("覆盖whole order sequence 区间", "covering the entire sequence interval"),
        
        # === situs_physical_validation.tex ===
        ("必须携带regarding target 签's额information", "must carry additional information about the target label"),
        ("蛋白质order sequence Locationcode", "Protein Sequence Positional Encoding"),
        ("氨基酸, non-Location", "Same Amino Acid, Different Positions"),
        ("one 赖氨酸残基at 蛋白质non-Locationhas complete non-scan Role", "a lysine residue at different positions in a protein has completely different functional roles"),
        ("Lys-37(Active Site)vs Lys-289(Surface loop)", "Lys-37 (Active Site) vs Lys-289 (Surface loop)"),
        
        # General remaining patterns
        ('non-Yes', 'is not'),
        ('non-can', 'cannot'),
        ('non-变', 'unchanged'),
        ('non-立', 'does not hold'),
        ('non-具', 'does not have'),
        ('non-含', 'does not contain'),
        ('non-够', 'insufficient'),
        ('non-区', 'undistinguished'),
        ('non-交', 'non-commuting'),
        ('non-切', 'non-cut'),
        ('non-增', 'does not increase'),
        ('non-减', 'does not decrease'),
        ('non-受', 'not affected by'),
        ('non-丢', 'not discarded'),
        ('non-改', 'not modified'),
        ('non-完', 'imperfect'),
        ('non-可', 'not possible'),
        ('non-平', 'non-trivial'),
        ('non-同', 'different'),
        ('non-均', 'non-uniform'),
        ('non-对', 'asymmetric'),
        ('non-对', 'non-commuting'),
        ('non-必', 'unnecessary'),
        ('non-忘', 'not forgotten'),
        ('non-折', 'unbroken'),
        ('non-收', 'non-convergent'),
        ('non-断', 'unbroken'),
        ('non-显', 'implicit'),
        ('non-替', 'non-replacement'),
        ('non-极', 'non-extremal'),
        ('non-标', 'non-standard'),
        ('non-歧', 'non-divergent'),
        ('non-消', 'not eliminated'),
        ('non-混', 'non-mixing'),
        ('non-纯', 'not pure'),
        ('non-罕', 'rare'),
        ('non-能', 'cannot'),
        ('non-腐', 'non-corrosive'),
        ('non-致', 'inconsistent'),
        ('non-良', 'poor'),
        ('non-衡', 'non-equilibrium'),
        ('non-解', 'unresolved'),
        ('non-误', 'error-free'),
        ('non-译', 'untranslated'),
        ('non-负', 'non-negative'),
        ('non-转', 'non-rotating'),
        ('non-适', 'unsuitable'),
        ('non-逆', 'irreversible'),
        ('non-通', 'uncommon'),
        ('non-重', 'unimportant'),
        ('non-闭', 'not closed'),
        ('non-降', 'not decreasing'),
        ('non-限', 'unbounded'),
        ('non-需', 'unnecessary'),
        ('non-顺', 'non-sequential'),
        ('non-驻', 'non-stationary'),
        ('non-齐', 'inconsistent'),
        ('等处', 'etc.'),
        ('等等', 'etc.'),
        ('例如', 'e.g.'),
        ('等等', 'etc.'),
        ('亦', 'also'),
        ('仍', 'still'),
        ('仅', 'only'),
        ('令', 'let'),
        ('会', 'will'),
        ('但', 'but'),
        ('使', 'make'),
        ('值', 'value'),
        ('偏', 'bias'),
        ('像', 'like'),
        ('再', 'again'),
        ('凡', 'all'),
        ('则', 'then'),
        ('前', 'previous'),
        ('加', 'add'),
        ('功', 'function'),
        ('化', '-ization'),
        ('即', 'i.e.'),
        ('却', 'yet'),
        ('原', 'original'),
        ('又', 'also'),
        ('及', 'and'),
        ('反', 'converse'),
        ('取', 'take'),
        ('受', 'subject to'),
        ('另', 'another'),
        ('只', 'only'),
        ('可', 'can'),
        ('同', 'same'),
        ('向', 'toward'),
        ('否', 'whether'),
        ('含', 'contain'),
        ('和', 'and'),
        ('器', 'device'),
        ('因', 'because'),
        ('在', 'at'),
        ('型', 'type'),
        ('域', 'domain'),
        ('基', 'basis'),
        ('增', 'increase'),
        ('处', 'at'),
        ('备', 'equipped'),
        ('多', 'multi'),
        ('失', 'loss'),
        ('如', 'such as'),
        ('它', 'it'),
        ('容', 'tolerant'),
        ('将', 'will'),
        ('对', 'to'),
        ('导', 'lead to'),
        ('小', 'small'),
        ('层', 'layer'),
        ('差', 'difference'),
        ('已', 'already'),
        ('并', 'and'),
        ('序', 'order'),
        ('应', 'should'),
        ('式', 'formula'),
        ('当', 'when'),
        ('往', 'toward'),
        ('很', 'very'),
        ('得', 'obtain'),
        ('必', 'must'),
        ('态', 'state'),
        ('或', 'or'),
        ('所', 'all'),
        ('才', 'only then'),
        ('扩', 'expand'),
        ('把', 'to'),
        ('投', 'project'),
        ('拟', 'simulate'),
        ('据', 'according to'),
        ('收', 'receive'),
        ('放', 'amplify'),
        ('故', 'therefore'),
        ('效', 'effect'),
        ('数', 'number'),
        ('整', 'whole'),
        ('方', 'method'),
        ('无', 'no'),
        ('时', 'time'),
        ('是', 'is'),
        ('有', 'have'),
        ('未', 'not yet'),
        ('术', 'technique'),
        ('果', 'result'),
        ('格', 'grid'),
        ('检', 'check'),
        ('模', 'mode'),
        ('此', 'this'),
        ('每', 'each'),
        ('比', 'ratio'),
        ('求', 'require'),
        ('汇', 'converge'),
        ('没', 'not'),
        ('法', 'method'),
        ('况', 'condition'),
        ('注', 'note'),
        ('混', 'mix'),
        ('源', 'source'),
        ('满', 'satisfy'),
        ('然', 'however'),
        ('物', 'object'),
        ('率', 'rate'),
        ('现', 'present'),
        ('理', 'principle'),
        ('用', 'use'),
        ('由', 'from'),
        ('界', 'boundary'),
        ('留', 'retain'),
        ('当', 'when'),
        ('的', 'of'),
        ('相', 'mutual'),
        ('看', 'see'),
        ('真', 'true'),
        ('知', 'know'),
        ('确', 'exact'),
        ('示', 'show'),
        ('种', 'type'),
        ('积', 'volume'),
        ('称', 'called'),
        ('空', 'empty'),
        ('符', 'match'),
        ('第', 'th'),
        ('等', 'etc.'),
        ('简', 'simple'),
        ('算', 'compute'),
        ('类', 'class'),
        ('系', 'system'),
        ('素', 'element'),
        ('约', 'bound'),
        ('级', 'level'),
        ('纯', 'pure'),
        ('组', 'group'),
        ('维', 'dimension'),
        ('编', 'encode'),
        ('缩', 'shrink'),
        ('缺', 'defect'),
        ('置', 'place'),
        ('美', 'perfect'),
        ('者', 'agent'),
        ('而', 'and'),
        ('聘', 'hire'),
        ('联', 'joint'),
        ('聚', 'aggregate'),
        ('能', 'can'),
        ('自', 'self'),
        ('至', 'to'),
        ('与', 'and'),
        ('色', 'color'),
        ('若', 'if'),
        ('范', 'norm'),
        ('虚', 'virtual'),
        ('行', 'row'),
        ('表', 'table'),
        ('被', 'by'),
        ('要', 'need'),
        ('规', 'rule'),
        ('设', 'let'),
        ('许', 'allow'),
        ('论', 'theory'),
        ('译', 'translate'),
        ('识', 'recognize'),
        ('证', 'prove'),
        ('该', 'this'),
        ('详', 'detail'),
        ('误', 'error'),
        ('说', 'say'),
        ('调', 'tune'),
        ('象', 'object'),
        ('质', 'quality'),
        ('赠', 'give'),
        ('超', 'super'),
        ('距', 'distance'),
        ('路', 'path'),
        ('身', 'itself'),
        ('载', 'load'),
        ('较', 'comparison'),
        ('轴', 'axis'),
        ('轻', 'light'),
        ('边', 'edge'),
        ('运', 'operation'),
        ('近', 'near'),
        ('这', 'this'),
        ('进', 'enter'),
        ('远', 'far'),
        ('连', 'connect'),
        ('选', 'select'),
        ('通', 'through'),
        ('造', 'create'),
        ('道', 'path'),
        ('都', 'all'),
        ('配', 'match'),
        ('重', 'important'),
        ('量', 'quantity'),
        ('链', 'chain'),
        ('闭', 'close'),
        ('阶', 'order'),
        ('际', 'actual'),
        ('集', 'set'),
        ('需', 'need'),
        ('非', 'non-'),
        ('项', 'term'),
        ('预', 'pre-'),
        ('须', 'must'),
        ('频', 'frequency'),
        ('题', 'problem'),
        ('额', 'additional'),
        ('显', 'explicit'),
        ('风', 'wind'),
        ('验', 'test'),
        ('高', 'high'),
        ('。', '.'),
        ('，', ','),
        ('；', ';'),
        ('：', ':'),
        ('？', '?'),
        ('！', '!'),
        ('“', '"'),
        ('”', '"'),
        ('（', '('),
        ('）', ')'),
        ('《', '<'),
        ('》', '>'),
        ('、', ','),
    ]
    
    for old, new in patches:
        content = content.replace(old, new)
    
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False

files = [
    'theory/propositions/05_expert_governance_protocol.tex',
    'theory/SCX_Undiscovered_Theorems.tex',
    'theory/self_evolution/MATHEMATICAL_GENEALOGY.tex',
    'theory/self_evolution/multi_head_spring_and_positional_encoding_analysis.tex',
    'theory/self_evolution/ppe_rigorous_derivation.tex',
    'theory/self_evolution/situs_final_verification.tex',
    'theory/self_evolution/situs_physical_validation.tex',
]

for f in files:
    path = os.path.join('F:/scx', f)
    if os.path.exists(path):
        changed = fix_file(path)
        print(f'{f}: {"CHANGED" if changed else "UNCHANGED"}')
    else:
        print(f'{f}: NOT FOUND')
