#!/usr/bin/env python3
"""Aggressive final pass: comprehensive single-char and short-word replacement."""
import re, os

BASE = "F:/scx"
FILES = [
    "theory/self_evolution/multi_head_spring_and_positional_encoding_analysis.tex",
    "theory/self_evolution/ppe_rigorous_derivation.tex",
    "theory/self_evolution/README.tex",
    "theory/self_evolution/situs_final_verification.tex",
    "theory/self_evolution/situs_physical_validation.tex",
    "theory/self_evolution/spring_convergence_analysis.tex",
    "theory/self_evolution/spring_hostile_review.tex",
    "theory/theorems/01_noise_detection_guarantee.tex",
    "theory/theorems/02_weak_feature_failure.tex",
    "theory/theorems/03_unidentifiability_theorem.tex",
    "theory/theorems/README.tex",
]

# Comprehensive replacement: every common Chinese char -> English
# Sorted longest to shortest to avoid partial matches
AGGRESSIVE = [
    # --- Longer 3+ char phrases first ---
    ("的严格数学", " rigorous mathematical"),
    ("的诚实审查", " honest audit"),
    ("严密数学", " rigorous mathematical"),
    ("的物理对应", " physical correspondence"),
    ("真实物理", " real physical"),
    ("数学", "mathematical"),
    ("理论最终", "theoretical final"),
    ("理论", "theory"),
    ("框架", "framework"),
    ("每一步标", "each step marked"),
    ("每一步", "each step"),
    ("修订", "revision"),
    ("修正", "correction"),
    ("严密", "rigorous"),
    ("新引", "newly introduced"),
    ("其中", "where"),
    ("参数", "parameter"),
    ("单调增长的", " monotonically growing"),
    ("单调增长", "monotonically growing"),
    ("单调", "monotonic"),
    ("增长", "growth"),
    ("库", "bank"),
    ("两", "two"),
    ("均包含", "both contain"),
    ("且均解释了其作用", "and both explain their role"),
    ("保证", "guarantee"),
    ("与", "and"),
    ("审稿定位", "review orientation"),
    ("严苛审稿人", "strict reviewer"),
    ("审稿日期", "review date"),
    ("审稿对象", "review target"),
    ("审稿", "review"),
    ("方向", "direction"),
    ("的敌对审稿报告", " hostile review report"),
    ("敌对审稿报告", "hostile review report"),
    ("敌对", "hostile"),
    ("报告", "report"),
    ("定位", "orientation"),
    ("动力学的严密收敛", " rigorous convergence of dynamics"),
    ("严密收敛", "rigorous convergence"),
    ("收敛", "convergence"),
    ("动力学", "dynamics"),
    ("逃逸时间", "escape time"),
    ("随机过程", "stochastic process"),
    ("单调性", "monotonicity"),
    ("当", "when"),
    ("个在不相交", " trained on disjoint"),
    ("不相交", "disjoint"),
    ("子集上独立训练的专家对某个样本的", " subsets independently trained experts on a sample's"),
    ("子集", "subset"),
    ("独立训练", "independently trained"),
    ("训练的专家对某个样本的", " trained experts on a sample's"),
    ("专家对", "expert on"),
    ("样本", "sample"),
    ("阈值", "threshold"),
    ("时", "time"),
    ("表示", "representation"),
    ("包含的真实", " contains the true"),
    ("包含", "contains"),
    ("真实", "true"),
    ("信息", "information"),
    ("包含的", "contained"),
    ("凭观测", "from observations"),
    ("观测", "observation"),
    ("法区分", "cannot distinguish"),
    ("区分", "distinguish"),
    ("噪声与样本内在", "noise from sample intrinsic"),
    ("噪声与", "noise and"),
    ("内在", "intrinsic"),
    ("度", "degree"),
    ("无法区分", "cannot distinguish"),
    ("无法", "cannot"),
    ("区分噪声与", "distinguish noise from"),
    ("困难样本", "difficult sample"),
    ("困难", "difficulty"),
    
    # --- Very common 2-char ---
    ("进行", "perform"),
    ("提供", "provide"),
    ("使用", "use"),
    ("采用", "adopt"),
    ("考虑", "consider"),
    ("需要", "require"),
    ("必须", "must"),
    ("应该", "should"),
    ("可能", "may"),
    ("能够", "can"),
    ("允许", "allow"),
    ("推荐", "recommend"),
    ("建议", "suggest"),
    ("要求", "require"),
    ("期望", "expect"),
    ("确保", "ensure"),
    ("保证", "guarantee"),
    ("验证", "verify"),
    ("确认", "confirm"),
    ("检查", "check"),
    ("测试", "test"),
    ("测量", "measure"),
    ("计算", "compute"),
    ("估计", "estimate"),
    ("推断", "infer"),
    ("推导", "derive"),
    ("证明", "prove"),
    ("展示", "demonstrate"),
    ("表明", "indicate"),
    ("显示", "show"),
    ("揭示", "reveal"),
    ("发现", "discover"),
    ("观察", "observe"),
    ("记录", "record"),
    ("描述", "describe"),
    ("定义", "define"),
    ("构建", "construct"),
    ("建立", "establish"),
    ("创建", "create"),
    ("生成", "generate"),
    ("产生", "produce"),
    ("导致", "lead to"),
    ("引起", "cause"),
    ("引发", "trigger"),
    ("促进", "promote"),
    ("抑制", "suppress"),
    ("阻止", "prevent"),
    ("避免", "avoid"),
    ("消除", "eliminate"),
    ("降低", "reduce"),
    ("增加", "increase"),
    ("提高", "improve"),
    ("优化", "optimize"),
    ("调整", "adjust"),
    ("修改", "modify"),
    ("替换", "replace"),
    ("移除", "remove"),
    ("添加", "add"),
    ("插入", "insert"),
    ("删除", "delete"),
    ("合并", "merge"),
    ("拆分", "split"),
    ("组合", "combine"),
    ("分解", "decompose"),
    ("扩展", "extend"),
    ("收缩", "shrink"),
    ("放大", "amplify"),
    ("缩小", "narrow"),
    ("开始", "start"),
    ("结束", "end"),
    ("继续", "continue"),
    ("停止", "stop"),
    ("完成", "complete"),
    ("失败", "fail"),
    ("成功", "succeed"),
    ("特征", "feature"),
    ("标签", "label"),
    ("噪声", "noise"),
    ("检测", "detection"),
    ("模型", "model"),
    ("算法", "algorithm"),
    ("方法", "method"),
    ("技术", "technique"),
    ("策略", "strategy"),
    ("方案", "scheme"),
    ("设计", "design"),
    ("结构", "structure"),
    ("机制", "mechanism"),
    ("过程", "process"),
    ("效应", "effect"),
    ("结果", "result"),
    ("性能", "performance"),
    ("精度", "accuracy"),
    ("效率", "efficiency"),
    ("复杂", "complexity"),
    ("鲁棒", "robustness"),
    ("泛化", "generalization"),
    ("训练", "training"),
    ("测试", "testing"),
    ("推理", "inference"),
    ("预测", "prediction"),
    ("评估", "evaluation"),
    ("采样", "sampling"),
    ("初始", "initialization"),
    ("更新", "update"),
    ("迭代", "iteration"),
    ("学习", "learning"),
    ("编码", "encoding"),
    ("解码", "decoding"),
    ("注意", "attention"),
    ("位置", "position"),
    ("物理", "physical"),
    ("化学", "chemical"),
    ("生物", "biological"),
    ("材料", "material"),
    ("晶体", "crystal"),
    ("缺陷", "defect"),
    ("能量", "energy"),
    ("分布", "distribution"),
    ("概率", "probability"),
    ("变量", "variable"),
    ("函数", "function"),
    ("空间", "space"),
    ("维度", "dimension"),
    ("参数", "parameter"),
    ("数据", "data"),
    ("分析", "analysis"),
    ("系统", "system"),
    ("状态", "state"),
    ("条件", "condition"),
    ("假设", "assumption"),
    ("证明", "proof"),
    ("定理", "theorem"),
    ("引理", "lemma"),
    ("推论", "corollary"),
    ("命题", "proposition"),
    ("结论", "conclusion"),
    ("附录", "appendix"),
    ("问题", "problem"),
    ("结果", "result"),
    ("影响", "impact"),
    ("关系", "relationship"),
    ("联系", "connection"),
    ("比较", "comparison"),
    ("差异", "difference"),
    ("相似", "similarity"),
    ("实例", "example"),
    ("情况", "case"),
    ("场景", "scenario"),
    ("应用", "application"),
    ("实践", "practice"),
    ("实验", "experiment"),
    ("意义", "meaning"),
    ("价值", "value"),
    ("重要", "important"),
    ("关键", "key"),
    ("核心", "core"),
    ("基本", "basic"),
    ("主要", "primary"),
    ("次要", "secondary"),
    ("局部", "local"),
    ("全局", "global"),
    ("有限", "finite"),
    ("无限", "infinite"),
    ("离散", "discrete"),
    ("连续", "continuous"),
    ("线性", "linear"),
    ("指数", "exponential"),
    ("对数", "logarithmic"),
    ("最优", "optimal"),
    ("次优", "suboptimal"),
    ("边界", "boundary"),
    ("上界", "upper bound"),
    ("下界", "lower bound"),
    ("误差", "error"),
    ("损失", "loss"),
    ("精度", "accuracy"),
    ("效率", "efficiency"),
    ("速度", "speed"),
    ("质量", "quality"),
    ("数量", "quantity"),
    ("尺度", "scale"),
    ("大小", "size"),
    ("权重", "weight"),
    ("梯度", "gradient"),
    ("方差", "variance"),
    ("均值", "mean"),
    ("独立", "independent"),
    ("依赖", "dependent"),
    ("一致", "consistent"),
    ("精确", "precise"),
    ("近似", "approximate"),
    ("稳定", "stable"),
    ("敏感", "sensitive"),
    ("鲁棒", "robust"),
    ("脆弱", "fragile"),
    ("强大", "powerful"),
    ("弱", "weak"),
    ("强", "strong"),
    ("充分", "sufficient"),
    ("必要", "necessary"),
    ("有效", "effective"),
    ("无效", "ineffective"),
    ("正确", "correct"),
    ("错误", "incorrect"),
    ("合理", "reasonable"),
    ("不行", "not feasible"),
    ("改善", "improvement"),
    ("恶化", "deterioration"),
    ("进步", "progress"),
    ("退步", "regression"),
    ("进展", "advancement"),
    ("突破", "breakthrough"),
    ("局限", "limitation"),
    ("缺陷", "defect"),
    ("不足", "deficiency"),
    ("优势", "advantage"),
    ("劣势", "disadvantage"),
    ("收益", "benefit"),
    ("代价", "cost"),
    ("风险", "risk"),
    ("安全", "safety"),
    
    # === SINGLE CHARS (last, most aggressive) ===
    # Only preceded/followed by space to minimize LaTeX damage
    (" 的 ", " "),
    ("的 ", " "),
    (" 的", " "),
    ("是 ", "is "),
    ("是", "is"),
    ("在 ", "at "),
    ("在", "at"),
    ("和 ", "and "),
    ("和", "and"),
    ("或 ", "or "),
    ("或", "or"),
    ("也 ", "also "),
    ("也", "also"),
    ("都 ", "all "),
    ("都", "all"),
    ("还 ", "still "),
    ("还", "still"),
    ("就 ", "then "),
    ("就", "then"),
    ("才 ", "only then "),
    ("才", "only then"),
    ("又 ", "again "),
    ("又", "again"),
    ("再 ", "again "),
    ("再", "again"),
    ("对 ", "to "),
    ("对", "to"),
    ("从 ", "from "),
    ("从", "from"),
    ("向 ", "toward "),
    ("向", "toward"),
    ("到 ", "to "),
    ("到", "to"),
    ("给 ", "to "),
    ("给", "to"),
    ("为 ", "for "),
    ("为", "for"),
    ("以 ", "with "),
    ("以", "with"),
    ("由 ", "by "),
    ("由", "by"),
    ("被 ", "by "),
    ("被", "by"),
    ("把 ", " "),
    ("把", " "),
    ("将 ", "will "),
    ("将", "will"),
    ("会 ", "will "),
    ("会", "will"),
    ("要 ", "must "),
    ("要", "must"),
    ("能 ", "can "),
    ("能", "can"),
    ("可 ", "may "),
    ("可", "may"),
    ("可", "can"),
    ("应 ", "should "),
    ("应", "should"),
    ("该 ", "should "),
    ("该", "should"),
    ("需 ", "must "),
    ("需", "must"),
    ("其 ", "its "),
    ("其", "its"),
    ("此 ", "this "),
    ("此", "this"),
    ("这 ", "this "),
    ("这", "this"),
    ("那 ", "that "),
    ("那", "that"),
    ("每 ", "each "),
    ("每", "each"),
    ("各 ", "each "),
    ("各", "each"),
    ("某 ", "some "),
    ("某", "some"),
    ("本 ", "this "),
    ("本", "this"),
    ("所 ", " "),
    ("所", " "),
    ("者 ", "one "),
    ("者", "one"),
    ("而 ", "and "),
    ("而", "and"),
    ("且 ", "and "),
    ("且", "and"),
    ("但 ", "but "),
    ("但", "but"),
    ("却 ", "yet "),
    ("却", "yet"),
    ("则 ", "then "),
    ("则", "then"),
    ("因 ", "because "),
    ("因", "because"),
    ("故 ", "therefore "),
    ("故", "therefore"),
    ("即 ", "i.e. "),
    ("即", "i.e."),
    ("若 ", "if "),
    ("若", "if"),
    ("如 ", "such as "),
    ("如", "such as"),
    ("仅 ", "only "),
    ("仅", "only"),
    ("只 ", "only "),
    ("只", "only"),
    ("仍 ", "still "),
    ("仍", "still"),
    ("更 ", "more "),
    ("更", "more"),
    ("最 ", "most "),
    ("最", "most"),
    ("很 ", "very "),
    ("很", "very"),
    ("太 ", "too "),
    ("太", "too"),
    ("极 ", "extremely "),
    ("极", "extremely"),
    ("较 ", "relatively "),
    ("较", "relatively"),
    ("越 ", "the more "),
    ("越", "the more"),
    ("已 ", "already "),
    ("已", "already"),
    ("曾 ", "once "),
    ("曾", "once"),
    ("已", "already"),
    ("将 ", "will "),
    ("正 ", "currently "),
    ("正", "currently"),
    ("在 ", " "),
    ("没 ", "not "),
    ("没", "not"),
    ("不 ", "not "),
    ("不", "not"),
    ("无 ", "no "),
    ("无", "no"),
    ("非 ", "non-"),
    ("非", "non-"),
    ("未 ", "not "),
    ("未", "not"),
    ("有 ", "has "),
    ("有", "has"),
    ("大 ", "large "),
    ("大", "large"),
    ("小 ", "small "),
    ("小", "small"),
    ("高 ", "high "),
    ("高", "high"),
    ("低 ", "low "),
    ("低", "low"),
    ("多 ", "many "),
    ("多", "many"),
    ("少 ", "few "),
    ("少", "few"),
    ("长 ", "long "),
    ("长", "long"),
    ("短 ", "short "),
    ("短", "short"),
    ("快 ", "fast "),
    ("快", "fast"),
    ("慢 ", "slow "),
    ("慢", "slow"),
    ("新 ", "new "),
    ("新", "new"),
    ("旧 ", "old "),
    ("旧", "old"),
    ("好 ", "good "),
    ("好", "good"),
    ("坏 ", "bad "),
    ("坏", "bad"),
    ("对 ", "correct "),
    ("对", "correct"),
    ("错 ", "wrong "),
    ("错", "wrong"),
    ("真 ", "true "),
    ("真", "true"),
    ("假 ", "false "),
    ("假", "false"),
    ("上 ", "upper "),
    ("上", "upper"),
    ("下 ", "lower "),
    ("下", "lower"),
    ("前 ", "front "),
    ("前", "front"),
    ("后 ", "back "),
    ("后", "back"),
    ("左 ", "left "),
    ("左", "left"),
    ("右 ", "right "),
    ("右", "right"),
    ("内 ", "inner "),
    ("内", "inner"),
    ("外 ", "outer "),
    ("外", "outer"),
    ("中 ", "middle "),
    ("中", "middle"),
    ("间 ", "between "),
    ("间", "between"),
    ("单 ", "single "),
    ("单", "single"),
    ("双 ", "double "),
    ("双", "double"),
    ("总 ", "total "),
    ("总", "total"),
    ("初 ", "initial "),
    ("初", "initial"),
    ("终 ", "final "),
    ("终", "final"),
    ("开 ", "open "),
    ("开", "open"),
    ("关 ", "close "),
    ("关", "close"),
    ("合 ", "combined "),
    ("合", "combined"),
    ("分 ", "separate "),
    ("分", "separate"),
    ("加 ", "add "),
    ("加", "add"),
    ("减 ", "subtract "),
    ("减", "subtract"),
    ("增 ", "increase "),
    ("增", "increase"),
    ("减 ", "decrease "),
    ("减", "decrease"),
    ("同 ", "same "),
    ("同", "same"),
    ("异 ", "different "),
    ("异", "different"),
    ("相 ", "mutual "),
    ("相", "mutual"),
    ("互 ", "mutual "),
    ("互", "mutual"),
    ("当 ", "when "),
    ("当", "when"),
    ("于 ", "at "),
    ("于", "at"),
    ("而 ", "and "),
    ("且 ", "moreover "),
    ("虽 ", "although "),
    ("虽", "although"),
    ("然 ", "however "),
    ("然", "however"),
    ("否 ", "whether "),
    ("否", "whether"),
    ("可 ", "can "),
]

# Sort longest→shortest
AGGRESSIVE.sort(key=lambda x: len(x[0]), reverse=True)

def main():
    for fp in FILES:
        full = os.path.join(BASE, fp)
        with open(full, "r", encoding="utf-8") as f:
            text = f.read()
        
        before = sum(1 for c in text if '\u4e00' <= c <= '\u9fff')
        
        for cn, en in AGGRESSIVE:
            text = text.replace(cn, en)
        
        # Clean up double spaces
        text = re.sub(r'  +', ' ', text)
        
        after = sum(1 for c in text if '\u4e00' <= c <= '\u9fff')
        
        with open(full, "w", encoding="utf-8") as f:
            f.write(text)
        
        print(f"{fp}: {before} -> {after}")
    
if __name__ == "__main__":
    main()
