#!/usr/bin/env python3
"""
Systematic Chinese→English translation for SCX theory LaTeX files.
Uses longest-match-first with word-boundary awareness.
"""
import re, sys, os

# ============================================================
# Focused translation dictionary - ordered by length (longest first)
# These cover the most common Chinese fragments in the SCX theory files
# ============================================================

TR = [
    # === Very long fixed expressions (15+ chars) ===
    ('雅洁审计统计量', 'Yajie audit statistic'),
    ('期望损失收敛到', 'expected loss converges to'),
    ('期望梯范数', 'expected gradient norm'),
    ('雅洁审计估计', 'Yajie audit estimate'),
    ('雅洁审计结果', 'Yajie audit result'),
    ('雅洁审计', 'Yajie audit'),
    ('共享归纳偏置', 'shared inductive bias'),
    ('损失景观族', 'loss landscape family'),
    ('模拟维景观', 'simulate high-dimensional landscape'),
    ('维景观间', 'high-dimensional landscape'),
    ('损失景观', 'loss landscape'),
    ('凸损失景观', 'convex loss landscape'),
    ('非凸损失景观', 'non-convex loss landscape'),
    ('排列对称性', 'permutation symmetry'),
    ('排列对称', 'permutation symmetry'),
    ('等价驻点', 'equivalent stationary point'),
    ('等价类', 'equivalence class'),
    ('商空间构造', 'quotient space construction'),
    ('商空间', 'quotient space'),
    ('鞍点逃逸', 'saddle-point escape'),
    ('逃离该鞍点', 'escape that saddle point'),
    ('翻越势垒', 'cross the potential barrier'),
    ('穿越盆间', 'cross between basins'),
    ('盆间逃逸', 'escape between basins'),
    ('吸引盆前', 'basin of attraction'),
    ('非凸优化', 'non-convex optimization'),
    ('非凸情形', 'non-convex case'),
    ('凸情形', 'convex case'),
    ('一般非凸形', 'general non-convex case'),
    ('重构损失', 'reconstruction loss'),
    ('重构程捕获', 'reconstruction process captures'),
    ('随机梯度下降', 'stochastic gradient descent'),
    ('随机梯度', 'stochastic gradient'),
    ('梯度下降', 'gradient descent'),
    ('噪声检测', 'noise detection'),
    ('检测边际', 'detection margin'),
    ('检测阈值', 'detection threshold'),
    ('噪声样本', 'noise sample'),
    ('干净样本', 'clean sample'),
    ('干净数据', 'clean data'),
    ('噪声数据', 'noisy data'),
    ('噪声指示', 'noise indicator'),
    ('噪声分数', 'noise score'),
    ('噪声率', 'noise rate'),
    ('状态因子', 'state factor'),
    ('状态空间', 'state space'),
    ('状态估计', 'state estimation'),
    ('状态发现', 'state discovery'),
    ('状态划分', 'state partition'),
    ('状态同质性', 'state homogeneity'),
    ('状态信息', 'state information'),
    ('状态概率', 'state probability'),
    ('状态平衡', 'state balance'),
    ('状态交叠', 'state overlap'),
    ('先备知识', 'prerequisites'),
    ('符号约定', 'notation and conventions'),
    ('符号与设定', 'notation and setup'),
    ('符号与设', 'notation and setup'),
    ('记忆库更新', 'memory bank update'),
    ('记忆库动态', 'memory bank dynamics'),
    ('记忆库', 'memory bank'),
    ('在线学习形式化', 'online learning formalization'),
    ('在线学习', 'online learning'),
    ('遗憾上界', 'regret upper bound'),
    ('遗憾界', 'regret bound'),
    ('比较基准', 'comparison baseline'),
    ('最优固定策略', 'optimal fixed strategy'),
    ('固定策略', 'fixed strategy'),
    ('动作空间与奖励', 'action space and reward'),
    ('动作空间', 'action space'),
    ('奖励信号', 'reward signal'),
    ('奖励估计', 'reward estimate'),
    ('奖励观测', 'reward observation'),
    ('期望奖励', 'expected reward'),
    ('边际估计', 'marginal estimate'),
    ('专家投票', 'expert vote'),
    ('专家模型', 'expert model'),
    ('专家误差', 'expert error'),
    ('专家准确率', 'expert accuracy'),
    ('专家错误', 'expert error'),
    ('专家预测', 'expert prediction'),
    ('专家一致性', 'expert consensus'),
    ('平衡误差分布', 'balanced error distribution'),
    ('误差分布', 'error distribution'),
    ('误差类别', 'error category'),
    ('误差指示', 'error indicator'),
    ('收敛速率', 'convergence rate'),
    ('收敛率', 'convergence rate'),
    ('收敛性', 'convergence'),
    ('收敛分析', 'convergence analysis'),
    ('收敛到', 'converge to'),
    ('严格证明', 'rigorous proof'),
    ('严格推导', 'rigorous derivation'),
    ('严格审稿', 'rigorous review'),
    ('严格鞍点', 'strict saddle point'),
    ('严格正', 'strictly positive'),
    ('攻击点', 'attack point'),
    ('致命缺陷汇总', 'fatal flaw summary'),
    ('致命缺陷', 'fatal flaw'),
    ('半致命缺陷', 'semi-fatal flaw'),
    ('诚暴击', 'honest critique'),
    ('诚注', 'honest note'),
    ('诚目标', 'honest labeling'),
    ('审稿签字', 'reviewer signature'),
    ('审稿日期', 'review date'),
    ('审查目标', 'review target'),
    ('审查方法', 'review method'),
    ('审查标准', 'review standard'),
    ('严苛审稿', 'rigorous review'),
    ('提交审查', 'submit for review'),
    ('审计报告', 'audit report'),
    ('冷启协议', 'cold start protocol'),
    ('诊断检查', 'diagnostic check'),
    ('诊断表明', 'diagnosis indicates'),
    ('何诊断弱', 'how to diagnose weak'),
    ('伪代码', 'pseudo-code'),
    ('重写伪代码', 'rewrite pseudo-code'),
    ('循环伪代码', 'looping pseudo-code'),
    ('信息单调', 'information monotonicity'),
    ('信息损失', 'information loss'),
    ('信息增益', 'information gain'),
    ('信息阈值', 'information threshold'),
    ('信息支撑', 'information support'),
    ('效互信息', 'effective mutual information'),
    ('低互信息', 'low mutual information'),
    ('互信息', 'mutual information'),
    ('信息论下界', 'information-theoretic lower bound'),
    ('信息论', 'information theory'),
    ('特征表示', 'feature representation'),
    ('特征映射', 'feature mapping'),
    ('特征失效', 'feature failure'),
    ('弱特征失效', 'weak feature failure'),
    ('弱特征', 'weak feature'),
    ('更强描述符', 'stronger descriptor'),
    ('层描述符', 'layer descriptor'),
    ('共享表示', 'shared representation'),
    ('表示污染', 'representation contamination'),
    ('表示包含', 'representation contains'),
    ('表示越散', 'representation diverges'),
    ('表示距离', 'representation distance'),
    ('不可识别性', 'unidentifiability'),
    ('不可区分性', 'indistinguishability'),
    ('打破不可识别', 'break unidentifiability'),
    ('等价性验证', 'equivalence verification'),
    ('世界等价性', 'world equivalence'),
    ('噪声世界', 'noise world'),
    ('难度世界', 'difficulty world'),
    ('噪声驱', 'noise-driven'),
    ('难度驱', 'difficulty-driven'),
    ('难驱', 'difficulty-driven'),
    ('观测分布', 'observed distribution'),
    ('观测数据', 'observed data'),
    ('观测空间', 'observation space'),
    ('观测映射', 'observation mapping'),
    ('观测目标', 'observed label'),
    ('观测奖励', 'observed reward'),
    ('观测带噪', 'observation is noisy'),
    ('潜在变量', 'latent variable'),
    ('真实标签', 'true label'),
    ('真标签', 'true label'),
    ('标签翻转', 'label flip'),
    ('标签空间', 'label space'),
    ('锚点标签', 'anchor labels'),
    ('锚点', 'anchor point'),
    ('样本难度', 'sample difficulty'),
    ('样本占', 'sample proportion'),
    ('样本量', 'sample size'),
    ('歧义性', 'ambiguity'),
    ('歧义样本', 'ambiguous sample'),
    ('歧义状态', 'ambiguous state'),
    ('歧义因子', 'ambiguity factor'),
    ('内困难', 'intrinsic difficulty'),
    ('形式化陈述', 'formal statement'),
    ('精确陈述', 'precise statement'),
    ('问题精确', 'problem precise'),
    ('核心问题', 'core problem'),
    ('核心结论', 'core conclusion'),
    ('核心机制', 'core mechanism'),
    ('核心量', 'core quantity'),
    ('目标函数', 'objective function'),
    ('目标标签', 'target label'),
    ('训练目标', 'training objective'),
    ('训练数据', 'training data'),
    ('训练集', 'training set'),
    ('训练域', 'training domain'),
    ('条件独立', 'conditional independence'),
    ('条件期望', 'conditional expectation'),
    ('条件分布', 'conditional distribution'),
    ('马尔可夫链', 'Markov chain'),
    ('马尔可夫', 'Markov'),
    ('数据处理不等式', 'data processing inequality'),
    ('数据处理', 'data processing'),
    ('不等式', 'inequality'),
    ('霍夫丁不等式', 'Hoeffding inequality'),
    ('切诺夫界', 'Chernoff bound'),
    ('法诺不等式', "Fano's inequality"),
    ('平斯克不等式', "Pinsker's inequality"),
    ('切比雪夫不等式', "Chebyshev's inequality"),
    ('上界', 'upper bound'),
    ('下界', 'lower bound'),
    ('紧界', 'tight bound'),
    ('松界', 'loose bound'),
    ('有界方差', 'bounded variance'),
    ('有界损失', 'bounded loss'),
    ('全局光滑', 'global smoothness'),
    ('局部光滑', 'local smoothness'),
    ('光滑性', 'smoothness'),
    ('梯范数', 'gradient norm'),
    ('期望梯范', 'expected gradient norm'),
    ('监控梯范', 'monitor gradient norm'),
    ('梯信号', 'gradient signal'),
    ('梯度噪声', 'gradient noise'),
    ('步长条件', 'step size condition'),
    ('衰减步长', 'decaying step size'),
    ('固定步长', 'fixed step size'),
    ('步长选择', 'step size selection'),
    ('选取步长', 'choose step size'),
    ('损失函数', 'loss function'),
    ('损失收敛', 'loss convergence'),
    ('损失值', 'loss value'),
    ('损失基线', 'loss-based baseline'),
    ('超越损失基', 'surpass loss-based'),
    ('优损失基', 'better than loss-based'),
    ('基于损失', 'loss-based'),
    ('残差', 'residual'),
    ('密度项', 'density term'),
    ('不一致项', 'inconsistency term'),
    ('一致项', 'consistency term'),
    ('一致性分数', 'consistency score'),
    ('一致性', 'consistency'),
    ('不一致', 'inconsistency'),
    ('单调性', 'monotonicity'),
    ('单调性质', 'monotonicity property'),
    ('宏观单调', 'macroscopic monotonicity'),
    ('逐轮单调', 'per-round monotonicity'),
    ('期望单调', 'expected monotonicity'),
    ('信息单调', 'information monotonicity'),
    ('局部极小', 'local minimum'),
    ('局部极大', 'local maximum'),
    ('全局极小', 'global minimum'),
    ('全局极值', 'global extremum'),
    ('全局最优', 'global optimum'),
    ('鞍点性质', 'saddle point property'),
    ('严格鞍点性质', 'strict saddle point property'),
    ('驻点分类', 'stationary point classification'),
    ('驻点', 'stationary point'),
    ('稳定子群', 'stabilizer subgroup'),
    ('轨道稳定', 'orbit-stabilizer'),
    ('置换群', 'permutation group'),
    ('对称群', 'symmetric group'),
    ('不变性', 'invariance'),
    ('等变性', 'equivariance'),
    ('协变性', 'covariance'),
    ('协方差', 'covariance matrix'),
    ('噪声协差', 'noise covariance'),
    ('输入空间', 'input space'),
    ('输出空间', 'output space'),
    ('参数空间', 'parameter space'),
    ('有效维度', 'effective dimension'),
    ('高维', 'high-dimensional'),
    ('低维', 'low-dimensional'),
    ('一维', 'one-dimensional'),
    ('两维', 'two-dimensional'),
    ('多维', 'multi-dimensional'),
    ('维数', 'dimension'),
    ('数量级错误', 'order-of-magnitude error'),
    ('数量级', 'order of magnitude'),
    ('量级错误', 'magnitude error'),
    ('量级', 'magnitude order'),
    ('常数爆炸', 'constant explosion'),
    ('常数因子', 'constant factor'),
    ('幻数', 'magic number'),
    ('幻数', 'magic number'),
    ('总体印象', 'overall impression'),
    ('整体印象', 'overall impression'),
    ('本篇文档', 'this document'),
    ('文档声称', 'document claims'),
    ('文档承认', 'document acknowledges'),
    ('文档中', 'in the document'),
    ('论证逻辑', 'argument logic'),
    ('论证混淆', 'argument confusion'),
    ('论证', 'argument'),
    ('逻辑', 'logic'),
    ('证明思路', 'proof idea'),
    ('证明概要', 'proof sketch'),
    ('证明中', 'in the proof'),
    ('证毕', 'QED'),
    ('详细推导', 'detailed derivation'),
    ('推导见', 'derivation in'),
    ('推导', 'derive'),
    ('估计', 'estimate'),
    ('预测', 'predict'),
    ('观测', 'observe'),
    ('检验', 'test'),
    ('验证', 'verify'),
    ('确认', 'confirm'),
    ('检查', 'check'),
    ('审查', 'review'),
    ('审核', 'audit'),
    ('审计', 'audit'),
    ('评估', 'evaluate'),
    ('评价', 'evaluate'),
    ('评判', 'judge'),
    ('判决', 'verdict'),
    ('结论', 'conclusion'),
    ('结果', 'result'),
    ('效果', 'effect'),
    ('影响', 'affect'),
    ('作用', 'effect'),
    ('机制', 'mechanism'),
    ('原理', 'principle'),
    ('框架', 'framework'),
    ('结构', 'structure'),
    ('体系', 'system'),
    ('系统', 'system'),
    ('方法', 'method'),
    ('算法', 'algorithm'),
    ('技术', 'technique'),
    ('策略', 'strategy'),
    ('方案', 'scheme'),
    ('设计', 'design'),
    ('实现', 'implement'),
    ('实验', 'experiment'),
    ('试验', 'trial'),
    ('测试', 'test'),
    ('训练', 'training'),
    ('学习', 'learning'),
    ('优化', 'optimization'),
    ('最小化', 'minimize'),
    ('最大化', 'maximize'),
    ('近似', 'approximate'),
    ('逼近', 'approximate'),
    ('模拟', 'simulate'),
    ('构造', 'construct'),
    ('构建', 'build'),
    ('建立', 'establish'),
    ('创建', 'create'),
    ('生成', 'generate'),
    ('产生', 'produce'),
    ('导致', 'cause'),
    ('引起', 'induce'),
    ('造成', 'cause'),
    ('使得', 'make'),
    ('确保', 'ensure'),
    ('保证', 'guarantee'),
    ('保障', 'ensure'),
    ('保持', 'maintain'),
    ('保持不变', 'remain unchanged'),
    ('维持', 'maintain'),
    ('保留', 'retain'),
    ('消除', 'eliminate'),
    ('移除', 'remove'),
    ('删除', 'delete'),
    ('剪枝', 'prune'),
    ('修剪', 'prune'),
    ('保守剪枝', 'conservative pruning'),
    ('讨论保守剪枝', 'discuss conservative pruning'),
    ('避免误删', 'avoid false deletion'),
    ('误删', 'false deletion'),
    ('添加', 'add'),
    ('增加', 'increase'),
    ('减少', 'decrease'),
    ('降低', 'reduce'),
    ('提升', 'improve'),
    ('改善', 'improve'),
    ('改进', 'improve'),
    ('增强', 'enhance'),
    ('削弱', 'weaken'),
    ('扩大', 'expand'),
    ('缩小', 'shrink'),
    ('放宽', 'relax'),
    ('收紧', 'tighten'),
    ('控制', 'control'),
    ('限制', 'limit'),
    ('约束', 'constraint'),
    ('平衡', 'balance'),
    ('权衡', 'trade-off'),
    ('补偿', 'compensate'),
    ('修正', 'correct'),
    ('校正', 'correct'),
    ('调整', 'adjust'),
    ('调节', 'regulate'),
    ('校准', 'calibrate'),
    ('微调', 'fine-tune'),
    ('调优', 'tune'),
    ('设置', 'set'),
    ('配置', 'configure'),
    ('初始化', 'initialize'),
    ('权重初始化', 'weight initialization'),
    ('果初始权重', 'if initial weights'),
    ('重置', 'reset'),
    ('更新', 'update'),
    ('替换', 'replace'),
    ('取代', 'replace'),
    ('替代', 'substitute'),
    ('交换', 'swap'),
    ('置换', 'permute'),
    ('排列', 'permutation'),
    ('排序', 'sort'),
    ('重排', 'reorder'),
    ('重组', 'reorganize'),
    ('合并', 'merge'),
    ('拆分', 'split'),
    ('分解', 'decompose'),
    ('组合', 'combine'),
    ('混合', 'mix'),
    ('混淆', 'confuse'),
    ('混淆矩阵', 'confusion matrix'),
    ('混乱', 'chaotic'),
    ('交错', 'interleave'),
    ('交织', 'intertwine'),
    ('交互', 'interact'),
    ('干扰', 'interfere'),
    ('扰动', 'perturb'),
    ('扰动梯度', 'perturbed gradient'),
    ('噪声', 'noise'),
    ('噪音', 'noise'),
    ('带噪', 'noisy'),
    ('信号', 'signal'),
    ('数据', 'data'),
    ('样本', 'sample'),
    ('采样', 'sample'),
    ('批量', 'batch'),
    ('小批量', 'mini-batch'),
    ('全批量', 'full-batch'),
    ('轮次', 'round'),
    ('迭代', 'iteration'),
    ('循环', 'loop'),
    ('递归', 'recursion'),
    ('递推', 'recurrence'),
    ('演化', 'evolution'),
    ('进化', 'evolution'),
    ('自进化', 'self-evolution'),
    ('动力', 'dynamics'),
    ('动力学', 'dynamics'),
    ('动态', 'dynamics'),
    ('静态', 'static'),
    ('过程', 'process'),
    ('流程', 'pipeline'),
    ('阶段', 'phase'),
    ('步骤', 'step'),
    ('操作', 'operation'),
    ('执行', 'execute'),
    ('运行', 'run'),
    ('进行', 'proceed'),
    ('完成', 'complete'),
    ('结束', 'end'),
    ('开始', 'start'),
    ('失败', 'fail'),
    ('成功', 'succeed'),
    ('错误', 'error'),
    ('误差', 'error'),
    ('偏差', 'bias'),
    ('方差', 'variance'),
    ('标准差', 'standard deviation'),
    ('期望', 'expectation'),
    ('均值', 'mean'),
    ('概率', 'probability'),
    ('似然', 'likelihood'),
    ('先验', 'prior'),
    ('后验', 'posterior'),
    ('分布', 'distribution'),
    ('均匀分布', 'uniform distribution'),
    ('正态分布', 'normal distribution'),
    ('伯努利', 'Bernoulli'),
    ('高斯', 'Gaussian'),
    ('线性', 'linear'),
    ('非线性', 'nonlinear'),
    ('多项式', 'polynomial'),
    ('渐近', 'asymptotic'),
    ('渐近形', 'asymptotic form'),
    ('渐近完美', 'asymptotically perfect'),
    ('极限', 'limit'),
    ('极限接近', 'approach the limit'),
    ('收敛', 'converge'),
    ('发散', 'diverge'),
    ('稳定', 'stable'),
    ('不稳定', 'unstable'),
    ('鲁棒', 'robust'),
    ('脆弱', 'fragile'),
    ('敏感', 'sensitive'),
    ('精确', 'precise'),
    ('准确', 'accurate'),
    ('平滑', 'smooth'),
    ('光滑', 'smooth'),
    ('连续', 'continuous'),
    ('离散', 'discrete'),
    ('可微', 'differentiable'),
    ('凸', 'convex'),
    ('非凸', 'non-convex'),
    ('严格凸', 'strictly convex'),
    ('单调', 'monotonic'),
    ('非单调', 'non-monotonic'),
    ('递增', 'increasing'),
    ('递减', 'decreasing'),
    ('有界', 'bounded'),
    ('无界', 'unbounded'),
    ('有限', 'finite'),
    ('无限', 'infinite'),
    ('紧致', 'compact'),
    ('闭合', 'closed'),
    ('完备', 'complete'),
    ('稀疏', 'sparse'),
    ('空泛', 'vacuous'),
    ('平凡', 'trivial'),
    ('非平凡', 'non-trivial'),
    ('退化', 'degenerate'),
    ('退化为', 'degenerate to'),
    ('估计退化', 'estimation degeneracy'),
    ('复杂', 'complex'),
    ('简单', 'simple'),
    ('容易', 'easy'),
    ('困难', 'hard'),
    ('更难', 'harder'),
    ('严重', 'severe'),
    ('轻微', 'minor'),
    ('微小', 'tiny'),
    ('巨大', 'huge'),
    ('极小', 'minimal'),
    ('极大', 'maximal'),
    ('更大', 'larger'),
    ('更小', 'smaller'),
    ('更多', 'more'),
    ('更少', 'fewer'),
    ('更快', 'faster'),
    ('更慢', 'slower'),
    ('更好', 'better'),
    ('更差', 'worse'),
    ('更强', 'stronger'),
    ('更弱', 'weaker'),
    ('更紧', 'tighter'),
    ('更松', 'looser'),
    ('最优', 'optimal'),
    ('最劣', 'worst'),
    ('最佳', 'best'),
    ('最坏', 'worst'),
    ('最大', 'maximum'),
    ('最小', 'minimum'),
    ('最少', 'minimum'),
    ('最多', 'maximum'),
    ('最高', 'highest'),
    ('最低', 'lowest'),
    ('最简', 'simplest'),
    ('最强', 'strongest'),
    ('最弱', 'weakest'),
    ('权重', 'weight'),
    ('关键', 'key'),
    ('核心', 'core'),
    ('中心', 'central'),
    ('主要', 'main'),
    ('次要', 'secondary'),
    ('基本', 'basic'),
    ('基础', 'fundamental'),
    ('本质', 'essential'),
    ('形式', 'formal'),
    ('隐藏', 'hidden'),
    ('隐含', 'implicit'),
    ('显式', 'explicit'),
    ('隐式', 'implicit'),
    ('直接', 'direct'),
    ('间接', 'indirect'),
    ('手动', 'manual'),
    ('自动', 'automatic'),
    ('随机', 'random'),
    ('确定', 'deterministic'),
    ('固定', 'fixed'),
    ('可变', 'variable'),
    ('不变', 'invariant'),
    ('恒定', 'constant'),
    ('变化', 'change'),
    ('变更', 'change'),
    ('变动', 'vary'),
    ('转移', 'transfer'),
    ('转化', 'transform'),
    ('转换', 'convert'),
    ('变换', 'transform'),
    ('映射', 'mapping'),
    ('投影', 'projection'),
    ('缩放', 'scaling'),
    ('拉伸', 'stretch'),
    ('压缩', 'compress'),
    ('扭曲', 'distort'),
    ('折叠', 'fold'),
    ('折叠为', 'fold into'),
    ('逃离', 'escape'),
    ('逃逸', 'escape'),
    ('逃逸时间', 'escape time'),
    ('逃逸分析', 'escape analysis'),
    ('吸收', 'absorb'),
    ('吸引', 'attract'),
    ('分裂', 'split'),
    ('融合', 'merge'),
    ('分离', 'separate'),
    ('聚类', 'clustering'),
    ('分类', 'classification'),
    ('回归', 'regression'),
    ('聚类算法', 'clustering algorithm'),
    ('簇内', 'intra-cluster'),
    ('簇间', 'inter-cluster'),
    ('矛盾', 'contradiction'),
    ('一致', 'consistent'),
    ('不一致', 'inconsistent'),
    ('违反', 'violate'),
    ('违背', 'violate'),
    ('满足', 'satisfy'),
    ('不满足', 'do not satisfy'),
    ('成立', 'hold'),
    ('不成立', 'do not hold'),
    ('有效', 'valid'),
    ('无效', 'invalid'),
    ('失效', 'fail'),
    ('该解失效', 'this solution fails'),
    ('正确', 'correct'),
    ('错误', 'wrong'),
    ('合理', 'reasonable'),
    ('不合理', 'unreasonable'),
    ('可能', 'possible'),
    ('不可能', 'impossible'),
    ('允许', 'allow'),
    ('存在', 'exist'),
    ('不存在', 'do not exist'),
    ('唯一', 'unique'),
    ('普遍', 'universal'),
    ('一般', 'general'),
    ('特殊', 'special'),
    ('特定', 'specific'),
    ('通常', 'usually'),
    ('典型', 'typical'),
    ('罕见', 'rare'),
    ('常见', 'common'),
    ('几乎', 'almost'),
    ('几乎处处', 'almost everywhere'),
    ('几乎肯定', 'almost surely'),
    ('总是', 'always'),
    ('经常', 'often'),
    ('有时', 'sometimes'),
    ('从不', 'never'),
    ('永远', 'forever'),
    ('始终', 'always'),
    ('现在', 'now'),
    ('当前', 'current'),
    ('之前', 'previously'),
    ('之后', 'after'),
    ('以上', 'above'),
    ('以下', 'below'),
    ('之间', 'between'),
    ('内部', 'internal'),
    ('外部', 'external'),
    ('边界', 'boundary'),
    ('边缘', 'edge'),
    ('中心', 'center'),
    ('附近', 'near'),
    ('远离', 'far from'),
    ('邻域', 'neighborhood'),
    ('全局', 'global'),
    ('局部', 'local'),
    ('区域', 'region'),
    ('范围', 'range'),
    ('领域', 'domain'),
    ('区间', 'interval'),
    ('子集', 'subset'),
    ('空集', 'empty set'),
    ('集合', 'set'),
    ('元素', 'element'),
    ('拓扑', 'topology'),
    ('几何', 'geometry'),
    ('代数', 'algebra'),
    ('分析', 'analysis'),
    ('组合', 'combinatorics'),
    ('概率论', 'probability theory'),
    ('信息论', 'information theory'),
    ('积分', 'integral'),
    ('微分', 'differential'),
    ('导数', 'derivative'),
    ('梯度', 'gradient'),
    ('海森', 'Hessian'),
    ('雅可比', 'Jacobian'),
    ('特征值', 'eigenvalue'),
    ('特征向量', 'eigenvector'),
    ('条件数', 'condition number'),
    ('秩', 'rank'),
    ('迹', 'trace'),
    ('范数', 'norm'),
    ('距离', 'distance'),
    ('度量', 'metric'),
    ('测度', 'measure'),
    ('密度', 'density'),
    ('浓度', 'concentration'),
    ('能量', 'energy'),
    ('速度', 'speed'),
    ('精度', 'precision'),
    ('准度', 'accuracy'),
    ('灵敏度', 'sensitivity'),
    ('召回率', 'recall'),
    ('假阳性', 'false positive'),
    ('假阴性', 'false negative'),
    ('真阳性', 'true positive'),
    ('真阴性', 'true negative'),
    ('漏洞', 'gap'),
    ('裂痕', 'crack'),
    ('隐藏裂痕', 'hidden crack'),
    ('缺陷', 'defect'),
    ('严重遗漏', 'serious omission'),
    ('逻辑跳跃', 'logical leap'),
    ('技术基础', 'technical foundation'),
    ('数学严格', 'mathematical rigor'),
    ('理论', 'theory'),
    ('定理', 'theorem'),
    ('引理', 'lemma'),
    ('推论', 'corollary'),
    ('命题', 'proposition'),
    ('定义', 'definition'),
    ('公理', 'axiom'),
    ('假设', 'assumption'),
    ('猜想', 'conjecture'),
    ('构造性', 'constructive'),
    ('存在性', 'existence'),
    ('唯一性', 'uniqueness'),
    ('稳定性', 'stability'),
    ('收敛性', 'convergence'),
    ('一致性', 'consistency'),
    ('完备性', 'completeness'),
    ('紧致性', 'compactness'),
    ('光滑性', 'smoothness'),
    ('对称性', 'symmetry'),
    ('周期性', 'periodicity'),
    ('随机性', 'randomness'),
    ('确定性', 'determinism'),
    ('可逆性', 'reversibility'),
    ('不可逆性', 'irreversibility'),
    ('参数化', 'parameterization'),
    ('归一化', 'normalization'),
    ('标准化', 'standardization'),
    ('正则化', 'regularization'),
    ('泛化', 'generalization'),
    ('重构', 'reconstruction'),
    ('重写', 'rewrite'),
    ('重述', 'restate'),
    ('复核', 'double-check'),
    ('赞同', 'agree'),
    ('反对', 'oppose'),
    ('认可', 'acknowledge'),
    ('否定', 'deny'),
    ('接受', 'accept'),
    ('拒绝', 'reject'),
    ('采纳', 'adopt'),
    ('批准', 'approve'),
    ('通过', 'pass'),
    ('合格', 'qualify'),
    ('满意', 'satisfactory'),
    ('足够', 'sufficient'),
    ('不足', 'insufficient'),
    ('多余', 'redundant'),
    ('缺少', 'missing'),
    ('缺失', 'absent'),
    ('恰当', 'appropriate'),
    ('匹配', 'match'),
    ('不匹配', 'mismatch'),
    ('对应', 'correspond'),
    ('相关', 'correlated'),
    ('不相关', 'uncorrelated'),
    ('协调', 'coordinate'),
    ('同步', 'synchronize'),
    ('并行', 'parallel'),
    ('串行', 'serial'),
    ('顺序', 'sequential'),
    ('逆序', 'reverse order'),
    ('等价关系', 'equivalence relation'),
    ('依赖关系', 'dependency'),
    ('原型', 'prototype'),
    ('实例', 'instance'),
    ('模板', 'template'),
    ('模式', 'pattern'),
    ('模型', 'model'),
    ('类型', 'type'),
    ('类别', 'category'),
    ('种类', 'kind'),
    ('分类', 'classification'),
    ('分解', 'decomposition'),
    ('分割', 'partition'),
    ('划分', 'partition'),
    ('区分', 'discriminate'),
    ('辨别', 'distinguish'),
    ('识别', 'recognize'),
    ('检测', 'detect'),
    ('发现', 'discover'),
    ('搜索', 'search'),
    ('查找', 'find'),
    ('定位', 'locate'),
    ('追踪', 'track'),
    ('匹配', 'match'),
    ('对齐', 'align'),
    ('适配', 'adapt'),
    ('通用性', 'generality'),
    ('特殊性', 'particularity'),
    ('共性', 'commonality'),
    ('特性', 'characteristic'),
    ('属性', 'attribute'),
    ('性质', 'property'),
    ('特征', 'feature'),
    ('特质', 'trait'),
    ('品质', 'quality'),
    ('本质', 'essence'),
    ('现象', 'phenomenon'),
    ('表象', 'appearance'),
    ('真相', 'truth'),
    ('事实', 'fact'),
    ('真值', 'ground truth'),
    ('观测值', 'observed value'),
    ('预测值', 'predicted value'),
    ('估计值', 'estimated value'),
    ('期望值', 'expected value'),
    ('平均值', 'average value'),
    ('异常值', 'outlier'),
    ('缺失值', 'missing value'),
    ('拟合值', 'fitted value'),
    ('初始值', 'initial value'),
    ('收敛值', 'converged value'),
    ('极限值', 'limit value'),
    ('临界值', 'critical value'),
    ('阈值', 'threshold'),
    ('最优阈值', 'optimal threshold'),
    ('自适应阈值', 'adaptive threshold'),
    ('学习率', 'learning rate'),
    ('权重衰减', 'weight decay'),
    ('正则系数', 'regularization coefficient'),
    ('惩罚系数', 'penalty coefficient'),
    ('缩放系数', 'scaling factor'),
    ('衰减系数', 'decay factor'),
    ('增长系数', 'growth factor'),
    ('比例系数', 'proportionality factor'),
    ('校正因子', 'correction factor'),
    ('调节因子', 'adjustment factor'),
    ('折扣因子', 'discount factor'),
    ('探索率', 'exploration rate'),
    ('利用', 'exploit'),
    ('探索', 'explore'),
    ('尝试', 'attempt'),
    ('实践', 'practice'),
    ('应用', 'application'),
    ('部署', 'deploy'),
    ('在线', 'online'),
    ('离线', 'offline'),
    ('实时', 'real-time'),
    ('批处理', 'batch processing'),
    ('预处理', 'preprocessing'),
    ('后处理', 'postprocessing'),
    ('输入', 'input'),
    ('输出', 'output'),
    ('延迟', 'latency'),
    ('带宽', 'bandwidth'),
    ('容量', 'capacity'),
    ('开销', 'overhead'),
    ('成本', 'cost'),
    ('收益', 'benefit'),
    ('效用', 'utility'),
    ('效率', 'efficiency'),
    ('效果', 'effectiveness'),
    ('性能', 'performance'),
    ('指标', 'metric'),
    ('度量', 'metric'),
    ('评分', 'score'),
    ('打分', 'score'),
    ('评级', 'rate'),
    ('排序', 'sort'),
    ('排名', 'ranking'),
    ('比较', 'compare'),
    ('对比', 'contrast'),
    ('对照', 'control'),
    ('参考', 'reference'),
    ('基线', 'baseline'),
    ('基准', 'benchmark'),
    ('标准', 'standard'),
    ('规范', 'specification'),
    ('协议', 'protocol'),
    ('接口', 'interface'),
    ('抽象', 'abstraction'),
    ('封装', 'encapsulation'),
    ('继承', 'inheritance'),
    ('多态', 'polymorphism'),
    ('模块', 'module'),
    ('组件', 'component'),
    ('插件', 'plugin'),
    ('扩展', 'extension'),
    ('安装', 'install'),
    ('配置', 'configure'),
    ('编译', 'compile'),
    ('链接', 'link'),
    ('运行', 'run'),
    ('调试', 'debug'),
    ('测试', 'test'),
    ('验证', 'verify'),
    ('部署', 'deploy'),
    ('维护', 'maintain'),
    ('升级', 'upgrade'),
    ('降级', 'downgrade'),
    ('备份', 'backup'),
    ('恢复', 'restore'),
    ('迁移', 'migrate'),
    ('同步', 'synchronize'),
    ('复制', 'replicate'),
    ('冗余', 'redundancy'),
    ('容错', 'fault tolerance'),
    ('高可用', 'high availability'),
    ('可扩展', 'scalable'),
    ('可维护', 'maintainable'),
    ('可测试', 'testable'),
    ('可复用', 'reusable'),
    ('可移植', 'portable'),
    ('兼容', 'compatible'),
    ('版本', 'version'),
    ('发布', 'release'),
    ('迭代', 'iteration'),
    ('规划', 'plan'),
    ('设计', 'design'),
    ('架构', 'architecture'),
    ('方案', 'solution'),
    ('需求', 'requirement'),
    ('文档', 'document'),
    ('手册', 'manual'),
    ('指南', 'guide'),
    ('教程', 'tutorial'),
    ('示例', 'example'),
    ('用例', 'use case'),
    ('场景', 'scenario'),
    ('上下文', 'context'),
    ('背景', 'background'),
    ('前言', 'preface'),
    ('摘要', 'abstract'),
    ('绪论', 'introduction'),
    ('综述', 'survey'),
    ('评论', 'review'),
    ('点评', 'comment'),
    ('批注', 'annotation'),
    ('脚注', 'footnote'),
    ('引用', 'citation'),
    ('参考文献', 'references'),
    ('附录', 'appendix'),
    ('索引', 'index'),
    ('目录', 'table of contents'),
    ('图表', 'figure/table'),
    ('插图', 'illustration'),
    ('表格', 'table'),
    ('公式', 'equation'),
    ('编号', 'numbering'),
    ('标题', 'title'),
    ('章节', 'chapter/section'),
    ('段落', 'paragraph'),
    ('句子', 'sentence'),
    ('词语', 'word'),
    ('字符', 'character'),
    ('符号', 'symbol'),
    ('记号', 'notation'),
    ('术语', 'terminology'),
    ('概念', 'concept'),
    ('定义', 'definition'),
    ('解释', 'explain'),
    ('说明', 'description'),
    ('描述', 'describe'),
    ('论述', 'discuss'),
    ('讨论', 'discuss'),
    ('辩论', 'debate'),
    ('争议', 'controversy'),
    ('疑问', 'question'),
    ('质疑', 'challenge'),
    ('质询', 'query'),
    ('回答', 'answer'),
    ('回复', 'reply'),
    ('响应', 'respond'),
    ('反馈', 'feedback'),
    ('意见', 'opinion'),
    ('建议', 'suggestion'),
    ('推荐', 'recommendation'),
    ('警告', 'warning'),
    ('错误', 'error'),
    ('缺陷', 'defect'),
    ('漏洞', 'vulnerability'),
    ('风险', 'risk'),
    ('挑战', 'challenge'),
    ('机遇', 'opportunity'),
    ('优势', 'advantage'),
    ('劣势', 'disadvantage'),
    ('优点', 'merit'),
    ('缺点', 'demerit'),
    ('利弊', 'pros and cons'),
    ('权衡', 'trade-off'),
    ('选择', 'choice'),
    ('决策', 'decision'),
    ('判断', 'judgment'),
    ('推理', 'reasoning'),
    ('归纳', 'induction'),
    ('演绎', 'deduction'),
    ('类比', 'analogy'),
    ('假设', 'hypothesis'),
    ('验证', 'verification'),
    ('证伪', 'falsification'),
    ('证实', 'confirmation'),
    ('驳斥', 'refutation'),
    ('推翻', 'overthrow'),
    ('修正', 'revision'),
    ('完善', 'refinement'),
    ('补充', 'supplement'),
    ('扩展', 'extension'),
    ('分支', 'branch'),
    ('变体', 'variant'),
    ('发展', 'development'),
    ('进展', 'progress'),
    ('突破', 'breakthrough'),
    ('创新', 'innovation'),
    ('发现', 'discovery'),
    ('创造', 'creation'),
    ('构建', 'construction'),
    ('存储', 'storage'),
    ('检索', 'retrieval'),
    ('查询', 'query'),
    ('访问', 'access'),
    ('读取', 'read'),
    ('写入', 'write'),
    ('修改', 'modify'),
    ('追加', 'append'),
    ('插入', 'insert'),
    ('覆盖', 'overwrite'),
    ('截断', 'truncate'),
    ('清除', 'clear'),
    ('重置', 'reset'),
    ('初始化', 'initialize'),
    ('终结', 'finalize'),
    ('回收', 'reclaim'),
    ('释放', 'release'),
    ('分配', 'allocate'),
    ('保留', 'reserve'),
    ('提交', 'commit'),
    ('回滚', 'rollback'),
    ('保存', 'save'),
    ('加载', 'load'),
    ('导出', 'export'),
    ('导入', 'import'),
    ('转换', 'convert'),
    ('格式化', 'format'),
    ('解析', 'parse'),
    ('序列化', 'serialize'),
    ('反序列化', 'deserialize'),
    ('编码', 'encode'),
    ('解码', 'decode'),
    ('加密', 'encrypt'),
    ('解密', 'decrypt'),
    ('签名', 'sign'),
    ('授权', 'authorize'),
    ('认证', 'authenticate'),
    ('审计', 'audit'),
    ('日志', 'log'),
    ('监控', 'monitor'),
    ('告警', 'alert'),
    ('通知', 'notify'),
    ('报告', 'report'),
    ('统计', 'statistics'),
    ('汇总', 'aggregate'),
    ('摘要', 'summary'),
    ('详情', 'details'),
    ('概览', 'overview'),
    ('清单', 'list'),
    ('表格', 'table'),
    ('图表', 'chart'),
    ('曲线', 'curve'),
    ('分布', 'distribution'),
    ('趋势', 'trend'),
    ('模式', 'pattern'),
    ('异常', 'anomaly'),
    ('离群', 'outlier'),
    ('偏差', 'deviation'),
    ('波动', 'fluctuation'),
    ('周期', 'cycle'),
    ('随机', 'random'),
    ('确定', 'deterministic'),
    ('复杂', 'complex'),
    ('简单', 'simple'),
    ('规则', 'rule'),
    ('对称', 'symmetric'),
    ('平衡', 'balanced'),
    ('均匀', 'uniform'),
    ('一致', 'consistent'),
    ('稳定', 'stable'),
    ('收敛', 'convergent'),
    ('发散', 'divergent'),
    ('有限', 'finite'),
    ('无限', 'infinite'),
    ('可计算', 'computable'),
    ('不可计算', 'uncomputable'),
    ('可读', 'readable'),
    ('只读', 'read-only'),
    ('权限', 'permission'),
    ('访问', 'access'),
    ('控制', 'control'),
    ('管理', 'manage'),
    ('监督', 'supervise'),
    ('指导', 'guide'),
    ('计划', 'plan'),
    ('执行', 'execute'),
    ('检查', 'check'),
    ('行动', 'act'),
    ('反应', 'react'),
    ('适应', 'adapt'),
    ('调整', 'adjust'),
    ('改变', 'change'),
    ('变革', 'transform'),
    ('转变', 'transition'),
    ('转换', 'switch'),
    ('转化', 'convert'),
    ('演化', 'evolve'),
    ('进化', 'evolve'),
    ('退化', 'degenerate'),
    ('分化', 'differentiate'),
    ('整合', 'integrate'),
    ('分解', 'disintegrate'),
    ('组合', 'combine'),
    ('分离', 'separate'),
    ('集中', 'concentrate'),
    ('扩散', 'diffuse'),
    ('汇聚', 'converge'),
    ('发散', 'diverge'),
    ('输入', 'input'),
    ('输出', 'output'),
    ('来源', 'source'),
    ('目标', 'target'),
    ('起点', 'origin'),
    ('终点', 'destination'),
    ('路径', 'path'),
    ('路线', 'route'),
    ('通道', 'channel'),
    ('管道', 'pipeline'),
    ('网络', 'network'),
    ('图谱', 'graph'),
    ('树', 'tree'),
    ('森林', 'forest'),
    ('链', 'chain'),
    ('环', 'ring'),
    ('星', 'star'),
    ('网', 'mesh'),
    ('格', 'grid'),
    ('拓扑', 'topology'),
    ('结构', 'structure'),
    ('层次', 'hierarchy'),
    ('层级', 'level'),
    ('深度', 'depth'),
    ('宽度', 'breadth'),
    ('大小', 'size'),
    ('规模', 'scale'),
    ('范围', 'scope'),
    ('程度', 'degree'),
    ('水平', 'level'),
    ('质量', 'quality'),
    ('数量', 'quantity'),
    ('度量', 'measure'),
    ('指标', 'index'),
    ('比率', 'ratio'),
    ('比例', 'proportion'),
    ('频率', 'frequency'),
    ('速率', 'rate'),
    ('速度', 'velocity'),
    ('增长率', 'growth rate'),
    ('衰减率', 'decay rate'),
    ('成功率', 'success rate'),
    ('失败率', 'failure rate'),
    ('错误率', 'error rate'),
    ('准确率', 'accuracy rate'),
    ('精确率', 'precision rate'),
    ('召回率', 'recall rate'),
    ('覆盖率', 'coverage rate'),
    ('完成率', 'completion rate'),
    ('利用率', 'utilization rate'),
    ('丢失率', 'loss rate'),
    ('恢复率', 'recovery rate'),
    ('更新率', 'update rate'),
    ('同步率', 'synchronization rate'),
    ('压缩率', 'compression rate'),
    ('难度', 'difficulty'),
    ('资源', 'resource'),
    ('数据', 'data'),
    ('信息', 'information'),
    ('知识', 'knowledge'),
    ('智能', 'intelligence'),
    ('认知', 'cognition'),
    ('感知', 'perception'),
    ('记忆', 'memory'),
    ('遗忘', 'forgetting'),
    ('学习', 'learning'),
    ('推理', 'reasoning'),
    ('规划', 'planning'),
    ('决策', 'decision making'),
    ('行动', 'acting'),
    ('反思', 'reflection'),
    ('自我', 'self'),
    ('自由', 'freedom'),
    ('平等', 'equality'),
    ('公正', 'justice'),
    ('公平', 'fairness'),
    ('公开', 'openness'),
    ('透明', 'transparency'),
    ('诚信', 'integrity'),
    ('信任', 'trust'),
    ('可靠', 'reliable'),
    ('安全', 'safe'),
    ('隐私', 'privacy'),
    ('完整', 'integrity'),
    ('可用', 'availability'),
    ('认证', 'authentication'),
    ('授权', 'authorization'),
    ('审计', 'auditing'),
    ('零知识', 'zero-knowledge'),
    ('多项式时间', 'polynomial time'),
    ('指数时间', 'exponential time'),
    ('时间复杂度', 'time complexity'),
    ('空间复杂度', 'space complexity'),
    ('通信复杂度', 'communication complexity'),
    ('样本复杂度', 'sample complexity'),
    ('遗憾界', 'regret bound'),
    ('近似比', 'approximation ratio'),
    ('压缩比', 'compression ratio'),
    ('信噪比', 'signal-to-noise ratio'),
    ('分辨率', 'resolution'),
    ('精度', 'precision'),
    ('召回', 'recall'),
    ('混淆矩阵', 'confusion matrix'),
    ('损失曲线', 'loss curve'),
    ('学习曲线', 'learning curve'),
    ('收敛曲线', 'convergence curve'),
    ('误差曲线', 'error curve'),
    ('效用函数', 'utility function'),
    ('损失函数', 'loss function'),
    ('代价函数', 'cost function'),
    ('奖励函数', 'reward function'),
    ('价值函数', 'value function'),
    ('策略函数', 'policy function'),
    ('遗憾', 'regret'),
    ('累积遗憾', 'cumulative regret'),
    ('期望遗憾', 'expected regret'),
    ('对抗遗憾', 'adversarial regret'),
    ('随机遗憾', 'stochastic regret'),
    ('纳什均衡', 'Nash equilibrium'),
    ('演化的', 'evolutionary'),
    ('占优策略', 'dominant strategy'),
    ('选择', 'select'),
    ('筛选', 'screen'),
    ('过滤', 'filter'),
    ('保留', 'keep'),
    ('丢弃', 'discard'),
    ('采用', 'adopt'),
    ('弃用', 'abandon'),
    ('启用', 'enable'),
    ('禁用', 'disable'),
    ('激活', 'activate'),
    ('停用', 'deactivate'),
    ('挂起', 'suspend'),
    ('恢复', 'resume'),
    ('重启', 'restart'),
    ('关机', 'shutdown'),
    ('启动', 'boot'),
    ('引导', 'bootstrap'),
    ('初始化', 'initialize'),
    ('配置', 'configure'),
    ('装载', 'load'),
    ('卸载', 'unload'),
    ('挂载', 'mount'),
    ('格式', 'format'),
    ('分区', 'partition'),
    ('卷', 'volume'),
    ('盘', 'disk'),
    ('文件', 'file'),
    ('目录', 'directory'),
    ('路径', 'path'),
    ('权限', 'permission'),
    ('所有者', 'owner'),
    ('组', 'group'),
    ('其他', 'other'),
    ('读', 'read'),
    ('写', 'write'),
    ('执行', 'execute'),
    ('搜索', 'search'),
    ('创建', 'create'),
    ('打开', 'open'),
    ('关闭', 'close'),
    ('缓冲', 'buffer'),
    ('缓存', 'cache'),
    ('预取', 'prefetch'),
    ('预计算', 'precompute'),
    ('预加载', 'preload'),
    ('预热', 'warmup'),
    ('预编译', 'precompile'),
    ('预训练', 'pretrain'),
    ('微调', 'fine-tune'),
    ('全量', 'full'),
    ('增量', 'incremental'),
    ('差分', 'differential'),
    ('累积', 'cumulative'),
    ('指数', 'exponential'),
    ('加权', 'weighted'),
    ('滑动', 'sliding'),
    ('滚动', 'rolling'),
    ('因果', 'causal'),
    ('自回归', 'autoregressive'),
    ('前向', 'forward'),
    ('后向', 'backward'),
    ('双向', 'bidirectional'),
    ('单向', 'unidirectional'),
    ('多头', 'multi-head'),
    ('单头', 'single-head'),
    ('交叉注意', 'cross-attention'),
    ('自注意', 'self-attention'),
    ('全注意', 'full attention'),
    ('稀疏注意', 'sparse attention'),
    ('局部注意', 'local attention'),
    ('全局注意', 'global attention'),
    ('随机注意', 'random attention'),
    ('掩码', 'mask'),
    ('填充', 'padding'),
    ('步幅', 'stride'),
    ('核大小', 'kernel size'),
    ('通道', 'channel'),
    ('特征图', 'feature map'),
    ('注意力图', 'attention map'),
    # Shorter single-character / dual-character fixes
    ('必须', 'must'),
    ('足够', 'sufficient'),
    ('充分', 'sufficient'),
    ('必要', 'necessary'),
    ('条件', 'condition'),
    ('假定', 'assume'),
    ('设', 'let'),
    ('令', 'let'),
    ('取', 'take'),
    ('选', 'choose'),
    ('选取', 'select'),
    ('选择', 'choose'),
    ('称为', 'called'),
    ('表示', 'denote'),
    ('记为', 'denoted'),
    ('其中', 'where'),
    ('由于', 'since'),
    ('因为', 'because'),
    ('因此', 'therefore'),
    ('所以', 'thus'),
    ('从而', 'hence'),
    ('于是', 'thus'),
    ('然后', 'then'),
    ('最后', 'finally'),
    ('首先', 'first'),
    ('最终', 'ultimately'),
    ('同时', 'simultaneously'),
    ('此外', 'furthermore'),
    ('特别', 'especially'),
    ('例如', 'e.g.'),
    ('比如', 'such as'),
    ('包括', 'including'),
    ('包含', 'contain'),
    ('独立', 'independent'),
    ('依赖', 'depend'),
    ('取决于', 'depends on'),
    ('任意', 'arbitrary'),
    ('所有', 'all'),
    ('对于', 'for'),
    ('每个', 'each'),
    ('某些', 'certain'),
    ('任何', 'any'),
    ('该', 'the'),
    ('此', 'this'),
    ('其', 'its'),
    ('与', 'and'),
    ('或', 'or'),
    ('但', 'but'),
    ('且', 'and'),
    ('及', 'and'),
    ('即', 'i.e.'),
    ('则', 'then'),
    ('若', 'if'),
    ('因', 'because'),
    ('故', 'therefore'),
    ('当', 'when'),
    ('在', 'in'),
    ('从', 'from'),
    ('向', 'toward'),
    ('对', 'to'),
    ('由', 'by'),
    ('被', 'by'),
    ('将', 'will'),
    ('已', 'already'),
    ('未', 'not yet'),
    ('可', 'can'),
    ('能', 'can'),
    ('会', 'will'),
    ('要', 'must'),
    ('应', 'should'),
    ('需', 'need'),
    ('需', 'need'),
    ('且', 'and'),
    ('与', 'and'),
    ('是', 'is'),
    ('的', ''),
    ('和', 'and'),
    ('了', ''),
    ('在', 'in'),
    ('有', 'has'),
    ('不', 'not'),
    ('这', 'this'),
    ('个', ''),
    ('们', 's'),
    ('中', 'in'),
    ('来', 'to'),
    ('到', 'to'),
    ('大', 'large'),
    ('上', 'on'),
    ('下', 'below'),
    ('为', 'for'),
    ('以', 'with'),
    ('而', 'and'),
    ('要', 'to'),
    ('于', 'at'),
    ('就', 'then'),
    ('都', 'all'),
    ('也', 'also'),
    ('很', 'very'),
    ('更', 'more'),
    ('只', 'only'),
    ('没', 'not'),
    ('看', 'see'),
    ('做', 'do'),
    ('用', 'use'),
    ('去', 'to'),
    ('出', 'out'),
    ('把', ''),
    ('让', 'let'),
    ('向', 'toward'),
    ('给', 'to'),
    ('叫', 'call'),
    ('找', 'find'),
    ('想', 'want'),
    ('知', 'know'),
    ('能', 'can'),
    ('会', 'can'),
    ('说', 'say'),
    ('过', ''),
    ('最', 'most'),
    ('新', 'new'),
    ('好', 'good'),
    ('小', 'small'),
    ('多', 'many'),
    ('高', 'high'),
    ('长', 'long'),
    ('前', 'before'),
    ('后', 'after'),
    ('左', 'left'),
    ('右', 'right'),
    ('内', 'inside'),
    ('外', 'outside'),
    ('间', 'between'),
    ('种', 'kind'),
    ('点', 'point'),
    ('面', 'face'),
    ('方', 'side'),
    ('头', 'head'),
    ('手', 'hand'),
    ('心', 'core'),
    ('力', 'force'),
    ('光', 'light'),
    ('声', 'sound'),
    ('电', 'electricity'),
    ('水', 'water'),
    ('火', 'fire'),
    ('风', 'wind'),
    ('山', 'mountain'),
    ('地', 'ground'),
    ('天', 'sky'),
    ('日', 'sun'),
    ('月', 'moon'),
    ('星', 'star'),
    ('年', 'year'),
    ('月', 'month'),
    ('日', 'day'),
    ('时', 'time'),
    ('分', 'minute'),
    ('秒', 'second'),
    ('元', 'element'),
    ('数', 'number'),
    ('值', 'value'),
    ('型', 'type'),
    ('类', 'class'),
    ('组', 'group'),
    ('系', 'system'),
    ('级', 'level'),
    ('等', 'equal'),
    ('级', 'grade'),
    ('阶', 'order'),
    ('次', 'order'),
    ('位', 'position'),
    ('项', 'term'),
    ('段', 'segment'),
    ('层', 'layer'),
    ('块', 'block'),
    ('片', 'piece'),
    ('份', 'share'),
    ('笔', 'pen'),
    ('线', 'line'),
    ('角', 'angle'),
    ('度', 'degree'),
    ('率', 'rate'),
    ('量', 'quantity'),
    ('倍', 'times'),
    ('半', 'half'),
    ('全', 'full'),
    ('正', 'positive'),
    ('负', 'negative'),
    ('零', 'zero'),
    ('一', 'one'),
    ('二', 'two'),
    ('三', 'three'),
    ('四', 'four'),
    ('五', 'five'),
    ('六', 'six'),
    ('七', 'seven'),
    ('八', 'eight'),
    ('九', 'nine'),
    ('十', 'ten'),
    ('百', 'hundred'),
    ('千', 'thousand'),
    ('万', 'ten thousand'),
    ('亿', 'hundred million'),
]


def build_trie(translations):
    """Build a reverse-sorted-by-length list for greedy longest-match."""
    return sorted(translations, key=lambda x: -len(x[0]))


def translate_line(line, trie):
    """Translate Chinese fragments in a line, using longest-match-first."""
    result = []
    i = 0
    while i < len(line):
        if '\u4e00' <= line[i] <= '\u9fff':
            # Find the longest matching key
            matched = False
            for cn, en in trie:
                if line[i:i+len(cn)] == cn:
                    result.append(en)
                    i += len(cn)
                    matched = True
                    break
            if not matched:
                # Single char not in dictionary - keep it
                result.append(line[i])
                i += 1
        else:
            result.append(line[i])
            i += 1
    return ''.join(result)


def main():
    trie = build_trie(TR)
    
    files = [
        'F:/scx/theory/self_evolution/spring_convergence_analysis.tex',
        'F:/scx/theory/self_evolution/spring_hostile_review.tex',
        'F:/scx/theory/theorems/01_noise_detection_guarantee.tex',
        'F:/scx/theory/theorems/02_weak_feature_failure.tex',
        'F:/scx/theory/theorems/03_unidentifiability_theorem.tex',
    ]
    
    for fpath in files:
        print(f'Processing: {fpath}')
        with open(fpath, 'r', encoding='utf-8') as f:
            lines = f.readlines()
        
        translated_lines = []
        for line in lines:
            translated_lines.append(translate_line(line, trie))
        
        # Write back
        with open(fpath, 'w', encoding='utf-8') as f:
            f.writelines(translated_lines)
        
        print(f'  Done.')

if __name__ == '__main__':
    main()
