#!/usr/bin/env python3
import re, os

base = "F:/scx"
files = [
    "theory/self_evolution/multi_head_spring_and_positional_encoding_analysis.tex",
    "theory/self_evolution/ppe_rigorous_derivation.tex",
    "theory/self_evolution/README.tex",
    "theory/self_evolution/situs_final_verification.tex",
    "theory/self_evolution/situs_physical_validation.tex",
    "theory/self_evolution/spring_convergence_analysis.tex",
    "theory/self_evolution/spring_hostile_review.tex",
    "theory/theorems/01_noise_detection_guarantee.tex",
    "theory/theorems/02_weak_feature_failure.tex",
    "theory/theorems/03_unidentifiability_theorem.tex",
    "theory/theorems/README.tex",
]

# Round 2 replacements - more specific multi-word patterns
R2 = [
    # --- Remaining mixed Chinese/English fragments (common patterns) ---
    ("的 ", " "),
    ("是 ", " is "),
    ("为 ", " is "),
    ("在 ", " in "),
    ("和 ", " and "),
    ("或 ", " or "),
    ("与 ", " and "),
    ("对 ", " to "),
    ("从 ", " from "),
    ("向 ", " to "),
    ("用 ", " using "),
    ("被 ", " is "),
    ("将 ", " will "),
    ("把 ", " "),
    ("使 ", " makes "),
    ("让 ", " lets "),
    ("给 ", " gives "),
    ("以 ", " with "),
    ("由 ", " by "),
    ("因 ", " because "),
    ("所 ", " "),
    ("而 ", " and "),
    ("但 ", " but "),
    ("却 ", " yet "),
    ("则 ", " then "),
    ("也 ", " also "),
    ("都 ", " all "),
    ("会 ", " will "),
    ("能 ", " can "),
    ("可 ", " can "),
    ("要 ", " must "),
    ("需 ", " need "),
    ("应 ", " should "),
    ("该 ", " should "),
    ("其 ", " its "),
    ("此 ", " this "),
    ("这 ", " this "),
    ("那 ", " that "),
    ("哪 ", " which "),
    ("每 ", " each "),
    ("各 ", " each "),
    ("某 ", " some "),
    ("多 ", " many "),
    ("少 ", " few "),
    ("更 ", " more "),
    ("最 ", " most "),
    ("较 ", " relatively "),
    ("很 ", " very "),
    ("太 ", " too "),
    ("极 ", " extremely "),
    ("非常", " very "),
    ("十分", " very "),
    ("相当", " quite "),
    ("几乎", " almost "),
    ("已经", " already "),
    ("曾经", " once "),
    ("正在", " currently "),
    ("将要", " about to "),
    ("即将", " soon "),
    ("立刻", " immediately "),
    ("马上", " immediately "),
    ("始终", " always "),
    ("一直", " always "),
    ("仍然", " still "),
    ("还是", " still "),
    ("依旧", " still "),
    ("不再", " no longer "),
    ("尚未", " not yet "),
    ("从未", " never "),
    ("如何", " how "),
    ("为何", " why "),
    ("什么", " what "),
    ("是否", " whether "),
    ("多少", " how many "),
    ("多久", " how long "),
    ("哪里", " where "),
    ("谁", " who "),
    ("这里", " here "),
    ("那里", " there "),
    ("这些", " these "),
    ("那些", " those "),
    ("这样", " this way "),
    ("那样", " that way "),
    ("如此", " thus "),
    ("同样", " similarly "),
    ("相同", " same "),
    ("不同", " different "),
    ("类似", " similar "),
    ("一样", " the same "),
    ("其他", " other "),
    ("其余", " the rest "),
    ("另外", " additionally "),
    ("此外", " furthermore "),
    ("而且", " moreover "),
    ("然而", " however "),
    ("虽然", " although "),
    ("即使", " even if "),
    ("如果", " if "),
    ("假如", " suppose "),
    ("假设", " assuming "),
    ("除非", " unless "),
    ("否则", " otherwise "),
    ("不然", " otherwise "),
    ("因此", " therefore "),
    ("所以", " hence "),
    ("于是", " thus "),
    ("之后", " after "),
    ("之前", " before "),
    ("之内", " within "),
    ("之外", " outside "),
    ("之间", " between "),
    ("之中", " among "),
    ("之上", " above "),
    ("之下", " below "),
    ("之前", " before "),
    ("之后", " after "),
    ("以内", " within "),
    ("以外", " beyond "),
    ("以后", " afterwards "),
    ("以前", " previously "),
    ("以上", " above "),
    ("以下", " below "),
    ("左边", " left "),
    ("右边", " right "),
    ("上面", " above "),
    ("下面", " below "),
    ("前面", " front "),
    ("后面", " behind "),
    
    # Common compound words with Chinese that survived round 1
    ("不能", "cannot"),
    ("不会", "will not"),
    ("不是", "is not"),
    ("不必", "need not"),
    ("不一定", "not necessarily"),
    ("不一定", "not necessarily"),
    ("不正确", "incorrect"),
    ("不成立", "does not hold"),
    ("不存在", "does not exist"),
    ("不可能", "impossible"),
    ("不充分", "insufficient"),
    ("不必要", "unnecessary"),
    ("不完整", "incomplete"),
    ("不精确", "imprecise"),
    ("不一致", "inconsistent"),
    ("不相关", "irrelevant"),
    ("不依赖", "independent of"),
    ("不影响", "does not affect"),
    ("不改变", "unchanged"),
    ("不变化", "unchanged"),
    ("不增加", "does not increase"),
    ("不减少", "does not decrease"),
    ("不改进", "does not improve"),
    ("不收敛", "does not converge"),
    ("不满足", "does not satisfy"),
    ("不符合", "does not match"),
    ("不具有", "does not have"),
    ("不携带", "does not carry"),
    ("不提供", "does not provide"),
    ("不包含", "does not contain"),
    ("不涉及", "does not involve"),
    ("不需要", "does not require"),
    ("不保证", "does not guarantee"),
    ("不确定", "uncertain"),
    ("不变", "invariant"),
    ("不可行", "infeasible"),
    ("不可区分", "indistinguishable"),
    ("不可识别", "unidentifiable"),
    ("不可观测", "unobservable"),
    ("不可计算", "uncomputable"),
    ("不可逆", "irreversible"),
    ("无限大", "infinity"),
    ("无穷大", "infinity"),
    ("无穷小", "infinitesimal"),
    ("非常大", "very large"),
    ("非常小", "very small"),
    ("非常大", "very large"),
    ("极其小", "extremely small"),
    ("足够大", "sufficiently large"),
    ("足够小", "sufficiently small"),
    ("相对大", "relatively large"),
    ("相对小", "relatively small"),
    
    # Mixed words
    ("好", "good"),
    ("坏", "bad"),
    ("优", "excellent"),
    ("差", "poor"),
    ("高", "high"),
    ("低", "low"),
    ("大", "large"),
    ("小", "small"),
    ("长", "long"),
    ("短", "short"),
    ("宽", "wide"),
    ("窄", "narrow"),
    ("厚", "thick"),
    ("薄", "thin"),
    ("深", "deep"),
    ("浅", "shallow"),
    ("快", "fast"),
    ("慢", "slow"),
    ("强", "strong"),
    ("弱", "weak"),
    ("硬", "hard"),
    ("软", "soft"),
    ("轻", "light"),
    ("重", "heavy"),
    ("新", "new"),
    ("旧", "old"),
    ("正", "positive"),
    ("负", "negative"),
    ("真", "true"),
    ("假", "false"),
    ("对", "correct"),
    ("错", "wrong"),
    ("是", "yes"),
    ("否", "no"),
    ("有", "has"),
    ("无", "without"),
    ("非", "non-"),
    ("半", "semi-"),
    ("准", "quasi-"),
    ("超", "super-"),
    ("次", "sub-"),
    ("伪", "pseudo-"),
    ("反", "anti-"),
    ("前", "pre-"),
    ("后", "post-"),
    ("上", "upper"),
    ("下", "lower"),
    ("左", "left"),
    ("右", "right"),
    ("内", "inner"),
    ("外", "outer"),
    ("中", "middle"),
    ("间", "intermediate"),
    ("单", "single"),
    ("双", "double"),
    ("多", "multi-"),
    ("全", "full"),
    ("半", "half"),
    ("总", "total"),
    ("分", "partial"),
    ("初", "initial"),
    ("末", "final"),
    ("始", "begin"),
    ("终", "end"),
    ("起", "start"),
    ("止", "stop"),
    ("进", "forward"),
    ("出", "output"),
    ("入", "input"),
    ("开", "open"),
    ("关", "close"),
    ("合", "combine"),
    ("分", "separate"),
    ("加", "add"),
    ("减", "subtract"),
    ("乘", "multiply"),
    ("除", "divide"),
    ("增", "increase"),
    ("减", "decrease"),
    ("升", "rise"),
    ("降", "fall"),
    ("涨", "rise"),
    ("落", "fall"),
    ("存", "exist"),
    ("亡", "perish"),
    ("生", "generate"),
    ("灭", "destroy"),
    ("兴", "prosper"),
    ("衰", "decay"),
    
    # More specific common Chinese words in the mixed text
    ("时候", "time"),
    ("地方", "place"),
    ("东西", "thing"),
    ("事情", "matter"),
    ("方法", "method"),
    ("方式", "way"),
    ("办法", "approach"),
    ("手段", "means"),
    ("工具", "tool"),
    ("结果", "result"),
    ("效果", "effect"),
    ("后果", "consequence"),
    ("原因", "reason"),
    ("目的", "purpose"),
    ("目标", "goal"),
    ("任务", "task"),
    ("工作", "work"),
    ("作业", "operation"),
    ("项目", "project"),
    ("计划", "plan"),
    ("方案", "scheme"),
    ("设计", "design"),
    ("实现", "implementation"),
    ("执行", "execution"),
    ("完成", "completion"),
    ("成功", "success"),
    ("失败", "failure"),
    ("错误", "error"),
    ("问题", "problem"),
    ("困难", "difficulty"),
    ("容易", "easy"),
    ("简单", "simple"),
    ("复杂", "complex"),
    ("重要", "important"),
    ("主要", "primary"),
    ("次要", "secondary"),
    ("基本", "basic"),
    ("根本", "fundamental"),
    ("核心", "core"),
    ("关键", "key"),
    ("本质", "essential"),
    ("表面", "surface"),
    ("内部", "internal"),
    ("外部", "external"),
    ("中心", "center"),
    ("边缘", "edge"),
    ("范围", "range"),
    ("领域", "domain"),
    ("区域", "region"),
    ("部分", "part"),
    ("整体", "whole"),
    ("个体", "individual"),
    ("群体", "group"),
    ("集合", "set"),
    ("元素", "element"),
    ("成员", "member"),
    ("单位", "unit"),
    ("数量", "quantity"),
    ("数值", "value"),
    ("数字", "number"),
    ("数据", "data"),
    ("信息", "information"),
    ("知识", "knowledge"),
    ("智慧", "wisdom"),
    ("经验", "experience"),
    ("历史", "history"),
    ("传统", "tradition"),
    ("文化", "culture"),
    ("科学", "science"),
    ("技术", "technology"),
    ("工程", "engineering"),
    ("数学", "mathematics"),
    ("物理", "physics"),
    ("化学", "chemistry"),
    ("生物", "biology"),
    ("医学", "medicine"),
    ("经济", "economics"),
    ("社会", "society"),
    ("政治", "politics"),
    ("法律", "law"),
    ("教育", "education"),
    ("艺术", "art"),
    ("音乐", "music"),
    ("语言", "language"),
    ("文学", "literature"),
    ("哲学", "philosophy"),
    ("历史", "history"),
    ("地理", "geography"),
    ("天文", "astronomy"),
    ("气象", "meteorology"),
    ("环境", "environment"),
    ("生态", "ecology"),
    ("能源", "energy"),
    ("资源", "resource"),
    ("材料", "material"),
    ("设备", "equipment"),
    ("仪器", "instrument"),
    ("机器", "machine"),
    ("计算机", "computer"),
    ("软件", "software"),
    ("硬件", "hardware"),
    ("网络", "network"),
    ("系统", "system"),
    ("平台", "platform"),
    ("应用", "application"),
    ("服务", "service"),
    ("产品", "product"),
    ("商品", "commodity"),
    ("市场", "market"),
    ("价格", "price"),
    ("价值", "value"),
    ("成本", "cost"),
    ("收益", "benefit"),
    ("利润", "profit"),
    ("风险", "risk"),
    ("机会", "opportunity"),
    ("挑战", "challenge"),
    ("竞争", "competition"),
    ("合作", "cooperation"),
    ("冲突", "conflict"),
    ("和平", "peace"),
    ("战争", "war"),
    ("安全", "security"),
    ("危险", "danger"),
    ("健康", "health"),
    ("疾病", "disease"),
    ("生命", "life"),
    ("死亡", "death"),
    
    # --- Number words ---
    ("零", "zero"),
    ("一", "one"),
    ("二", "two"),
    ("三", "three"),
    ("四", "four"),
    ("五", "five"),
    ("六", "six"),
    ("七", "seven"),
    ("八", "eight"),
    ("九", "nine"),
    ("十", "ten"),
    ("百", "hundred"),
    ("千", "thousand"),
    ("万", "ten thousand"),
    ("亿", "hundred million"),
    
    # --- Units and measures ---
    ("个", " items"),
    ("位", " position"),
    ("次", " times"),
    ("回", " round"),
    ("倍", " times"),
    ("度", " degree"),
    ("米", " meter"),
    ("克", " gram"),
    ("秒", " second"),
    ("分", " minute"),
    ("时", " hour"),
    ("天", " day"),
    ("月", " month"),
    ("年", " year"),
    ("元", " dollar"),
    ("角", " dime"),
    ("分", " cent"),
    ("点", " point"),
    ("线", " line"),
    ("面", " surface"),
    ("体", " volume"),
    ("角", " angle"),
    ("边", " side"),
    
    # --- Single characters that are particles / grammatical ---
    ("的", ""),
    ("了", ""),
    ("着", ""),
    ("过", ""),
    ("得", ""),
    ("地", ""),
    ("吗", "?"),
    ("呢", "?"),
    ("吧", ""),
    ("啊", ""),
    ("呀", ""),
    ("哦", ""),
    ("嗯", ""),
    ("嘛", ""),
    ("呗", ""),
    ("啦", ""),
    ("喽", ""),
    ("嘛", ""),
    ("哈", ""),
    ("嘿", ""),
    ("喂", ""),
    ("哎", ""),
    ("唉", ""),
    ("哟", ""),
    ("哇", ""),
]

def apply_r2(text):
    for cn, en in R2:
        text = text.replace(cn, en)
    return text

total_remaining = 0
for fp in files:
    full = os.path.join(base, fp)
    with open(full, "r", encoding="utf-8") as f:
        content = f.read()
    content = apply_r2(content)
    with open(full, "w", encoding="utf-8") as f:
        f.write(content)
    cnt = sum(1 for c in content if '\u4e00' <= c <= '\u9fff')
    total_remaining += cnt
    print(f"R2: {fp} -> {cnt} Chinese chars remaining")

print(f"Total remaining: {total_remaining}")
